### ISSUE TITLE
Please allow CoverInitializedNames in non-Pattern ObjectLiterals

### ISSUE THREAD

**Issue by caitp** [tc39/ecma262#100]
It's a lot of effort to track where the CoverInitializedName occurs, and then later determine if it's allowed to be present there.

Why not just allow it everywhere? property name = LHS, value = evaluation of RHS.

```js
var x;
var foo = { x = 10 }; // equivalent of `var foo = { x: x = 10 }`
console.log(x) // 10
console.log(foo) // { x: 10 }
```

It would at simplify implementation a bit.

Maybe, if it was really necessary, it could have consistency with the behaviour of destructuring, such that

```js
var x;
var foo = { x = 10 }; // equivalent of `var foo = { x: x === void 0 ? 10 : x }`
console.log(x) // undefined
console.log(foo) // { x: 10 }
```

**Comment by bterlson** [comment]
Making new syntax for `{ x: x = 10 }` doesn't seem good - it does an assignment to x (or is an error in strict mode if an x binding doesn't exist). The destructuring-like version is interesting but questionably useful as well. Not sure it's worth adding these forms for helping parsers.

**Comment by allenwb** [comment]
If we'd wanted to extend object literals with that syntax we would have specified it. 

In practice, you don't need to defer the check.  That's why they are explicitly called out  as early errors. The covered initializer syntax is only valid within patterns and patterns are only valid in a few specific syntactic contexts. An implementation is perfectly free to internally use different grammars for pattern context and for object literal contexts.

**Comment by caitp** [comment]
the problems can be worked around, but it just doesn't seem particularly worth it

**Comment by caitp** [comment]
You do need to defer the check, because you don't know if you're parsing a pattern or not, until after you've parsed it.

**Comment by allenwb** [comment]
True for LHS contexts, but not true for declaration contexts.   And that are various ways you can approach implementing this that dopes not have too high an overhead.

TC39 was well aware of these issues when we decided to add syntax that requires a cover grammar and we decided that implementors could deal with them (it's not like nobody on TC39 had ever written a compiler before...).

We certainly don't ignore implementor convenience, but it is secondary concern.

**Comment by caitp** [comment]
I know you're aware of all this, which is why it's curious what the point is in making the grammars so different for no particularly useful reason? The difference between the cover grammar and the ObjectLiteral grammar doesn't serve any compelling purpose

**Comment by bterlson** [comment]
I believe that throwing errors for easy mistakes like `let point = { x = 1, y = 2 };` serves a compelling purpose.

**Comment by allenwb** [comment]
and we've have had to invent a meaning for such assignments within actual object literals, which would have precluded a possible future extension point,
