### ISSUE TITLE
Say what the draft represents

### ISSUE THREAD

**Issue by tjcrowder** [tc39/ecma262#1007]
I understand from Domenic Denicola that the live copy at https://tc39.github.io/ecma262/ contains only previously-specified features and Stage 4 proposals (e.g., finished ones). Let's say that clearly up front.

**Comment by ljharb** [comment]
What else would you expect it to contain?

**Comment by tjcrowder** [comment]
@ljharb Miscellaneous in-progress work which may or may not reach a final stage. "Draft" has that connotation. But Stage 4 proposals won't change in a material way prior to the next snapshot.

**Comment by allenwb** [comment]
Note there are also IPR differences (both copyright and RF patent) between GA approved Ecma standard and TG drafts!

**Comment by tjcrowder** [comment]
@allenwb Ah! Very good point. Then we should call those out as well. (Concisely, if possible -- perhaps just with what you've said there?)

**Comment by ljharb** [comment]
Calling out the differences is useful, but I don't think "draft" implies "includes proposals".

Generally speaking the snapshots are only useful for historical value; the spec that matters is what's on github.

**Comment by domenic** [comment]
I wonder if "Current Work" would be less confusing than "Draft"

**Comment by ljharb** [comment]
I agree that "draft" seems to be a problematic term.

**Comment by tjcrowder** [comment]
Regardless of what we call it, we'll still want to say what it represents. To me, "draft" is fine as long as we do that. Naming things is famously one of the two hard computer science problems (along with cache invalidation). The WHAT-WG went with "[living standard](https://html.spec.whatwg.org/multipage/)." I don't think that'd fly (see [AWB's comment here](https://github.com/tc39/ecma262/pull/1010#issuecomment-331554667)), but if people don't like "draft," perhaps "living specification."

AWB's was one of several useful comments over on [the PR](https://github.com/tc39/ecma262/pull/1010), which I'll update later this week folding in feedback.

**Comment by jmdyck** [comment]
We could say "About this Specification" or "About this Document".
