### ISSUE TITLE
Normative reference to ISO/IEC 10646 should be undated.

### ISSUE THREAD

**Issue by allenwb** [tc39/ecma262#1011]
Clause 3 contains a normative reference to ISO/IEC 10646:2003  (The ISO version of Unicode).  In ECMAEcript 2017 we switch to reference the "latest version" of Unicode but did not update that reference.

The Clause 3 reference should just be:ISO/IEC 10646 without a date.

**Comment by annevk** [comment]
See also #726.

**Comment by bterlson** [comment]
Yeah I should fix both of these. Ok, when I'm back from TC39.
