### ISSUE TITLE
Expose initial JSON.parse as %JSONParse%

### ISSUE THREAD

**Issue by annevk** [tc39/ecma262#1012]
That way Fetch and XMLHttpRequest can use it more directly (and other web platform entry points that need JSON parsing). Alternative is an abstract operation, which might be a little clearer usage wise.

Any preference?

**Comment by annevk** [comment]
I missed that %JSON% already exists. Could I write something like

> Return ? Invoke(%JSON%, "parse", « _jsonSource_ »).

then?

**Comment by michaelficarra** [comment]
I'd prefer we just name the intrinsic so you can call it directly.

**Comment by ljharb** [comment]
With the Invoke, you'd be calling whatever I happened to install on the JSON object under "parse"; it definitely would need a direct name.

**Comment by annevk** [comment]
Thanks, I'll work on a PR. How would I end up using it in prose afterwards? Just

> Return ? %JSONParse%( _jsonSource_ )

or something more involved?

**Comment by ljharb** [comment]
That seems right to me!

**Comment by domenic** [comment]
> Return ? %JSONParse%( jsonSource )

No, that's not correct. That's only correct if it's an abstract operation ("JSONParse", no %s), which indeed is neater.

If we expose it as a named intrinsic, we'd need

> Return ? Call(%JSONParse%, undefined, « jsonSource »).

I think an abstract operation would be nicer if we can get away with it.

If we do that we can also make it encompass only steps 2-6 of the JSON.parse function.

**Comment by annevk** [comment]
Okay, I think we can just add an abstraction in Infra to make the difficulty go away for everyone else in the web platform. (And maybe also require UTF-8 there at the same time when the input is bytes.)
