### ISSUE TITLE
Default values for realm and prototype in CreateBuiltinFunction (9.3.3)

### ISSUE THREAD

**Issue by brabalan** [tc39/ecma262#1030]
The abstract operation [CreateBuiltinFunction](https://tc39.github.io/ecma262/#sec-createbuiltinfunction) does not specify default values for `realm` and `prototype`. Since it may be called implicitely
> Each built-in function defined in this specification is created as if by calling the CreateBuiltinFunction abstract operation, unless otherwise specified.

what should one use if none is given?

Concrete application: the `revoker` created in step 2 of [Proxy.revocable](https://tc39.github.io/ecma262/#sec-proxy.revocable).

Editorial nitpick: step 3 of CreateBuiltinFunction could be interpreted as recursively calling CreateBuiltinFunction.

**Comment by jmdyck** [comment]
PR #1044 was merged, so this issue can be closed?

**Comment by ljharb** [comment]
Indeed, thanks - closed in #1044.
