### ISSUE TITLE
Disallow ArrayBuffers bigger than 2**53

### ISSUE THREAD

**Issue by littledan** [tc39/ecma262#1032]
As [pointed out](https://github.com/tc39/proposal-bigint/issues/58#issuecomment-345215753) by @verwaest, weird things happen on gigantic ArrayBuffers, where you can't actually address each byte because Numbers can't point to things bigger than 2**53. @verwaest points out a case in interactions with BigInt, but I think there are more mundane cases as well (e.g., running any of the array-derived methods, which assume that you can increment a Number up to the length of the TypedArray).

This is probably not reachable in real implementations because [CreateByteDataBlock](https://tc39.github.io/ecma262/#sec-createbytedatablock) will throw a RangeError on too-big arguments. I think we should change the specification to throw if you're above 2**53 to prevent the theoretical case where you get outside exact integer territory. Some callsites of CreateByteDataBlock call ToIndex (which will always be in that range) but some don't (e.g., TypedArray constructors called on iterables, though that would take *forever*). Maybe this could be fixed by inserting more calls to ToIndex.

**Comment by rossberg** [comment]
Note that once WebAssembly supports 64-bit address spaces, one of its linear memories might (just as theoretically) be larger than 2^53. So it would no longer be possible to materialise every memory as an ArrayBuffer in JavaScript under that restriction.

**Comment by littledan** [comment]
I think we're pretty far in the future to get beyond 2^53 bits of memory. We won't be able to use a Number to store things anyway. (Seems like I misunderstood the idea of the other post, [clarification](https://github.com/tc39/proposal-bigint/issues/58#issuecomment-345269291))

**Comment by rossberg** [comment]
Well, we talked about things like supporting mmap and other virtual memory games, so I'm not so sure.

**Comment by littledan** [comment]
My understanding was that virtual memory in 64-bit systems was commonly a 48-bit address space.

**Comment by allenwb** [comment]
>  virtual memory in 64-bit systems was commonly a 48-bit address space.

In which decade?

**Comment by jfbastien** [comment]
> >  virtual memory in 64-bit systems was commonly a 48-bit address space.
>
> In which decade?

The current decade.

**Comment by apaprocki** [comment]
... to clarify the above, AMD64 architecture defines a 64-bit virtual address format, of which the low-order 48 bits are used in current implementations.

Don't take it *too* seriously, but both POWER (Node.js ships for POWER) and SPARC actually use the 64-bit address space and I will admit to having to force memory allocated for SpiderMonkey to fit under the 48-bit limit to not break invariants in the engine. Intel domination creeping into software design... :)

**Comment by allenwb** [comment]
@jfbastien 
I hope my irony was obvious.  Never write standards for the current decade.

**Comment by littledan** [comment]
@apaprocki Thanks for that context. I wasn't aware of POWER and SPARC. Still, everything with using ArrayBuffers is currently tied to Number, so until we upgrade them to BigInt, I still think we should do this sort of change.

**Comment by littledan** [comment]
Sounds like we should go ahead with making this restriction as a PR, with a test262 PR to check for the RangeError, and proposing it to TC39 for consensus. This could be a one-line addition to CreateByteDataBlock. Rather than fix it myself right now, I'd rather leave it as a "good first patch" to any contributor who wants to make a normative change to the JS spec. I'm happy to mentor anyone interested through the process here.

(Thanks for the private ping on this issue, @ljharb !)

**Comment by mster** [comment]
@littledan Hi there! Is this issue still looking for a contributor? I'd love to work on it :)

**Comment by Josh-Cena** [comment]
Fixed by #3052
