### ISSUE TITLE
JSON.stringify is ambiguous with respect to upper and lowercase

### ISSUE THREAD

**Issue by cyberphone** [tc39/ecma262#1033]
It is possible that I failed interpreting the rather massive document, but AFAICT JSON.stringify may generate "\u000f" or "\u000F" for the control character 0x000F.  This collides with specifications like https://cyberphone.github.io/doc/security/jcs.html which rely on a fixed notation.  Implementations appear to use the lowercase notation though.

**Comment by jmdyck** [comment]
In `QuoteJSONString `, step 2.c.iii says:
```
Let hex be the string result of converting the numeric value of C to a String of four lowercase hexadecimal digits.
```
So it isn't ambiguous with respect to upper/lowercase.

**Comment by cyberphone** [comment]
That's great.  Thanx!
