### ISSUE TITLE
How to find and define a Internal Method?

### ISSUE THREAD

**Issue by wangyi7099** [tc39/ecma262#1039]
At [Object Internal Methods and Internal Slots](http://www.ecma-international.org/ecma-262/6.0/#sec-object-internal-methods-and-internal-slots)  , 
I see the Internal Method, and the essential  internal methods listed by table 5  such as [[GetPrototypeOf]] and so on . But I can't find them ...  Can you tell me where I can find them?

**Comment by claudepache** [comment]
They are described in Chapter 9 [Ordinary and Exotic Objects Behaviours](https://tc39.github.io/ecma262/#sec-ordinary-and-exotic-objects-behaviours).

**Comment by wangyi7099** [comment]
@claudepache  
Thank you.I see.. But I can't find Internal Methods such as [[GetPrototypeOf]]   in Chrome Dev Tool ,  If they can't see by users, but I see the Internal Slots  '[[PromiseStatus]]
' in the Promise instance.. So , Can you  explain me the reason? Thank you !

**Comment by ljharb** [comment]
@wangyi7099 internal slots are generally not directly accessible in the language, although some of them, like [[Prototype]], are exposed indirectly. In the repl/developer tools, engines can show you information that you can’t get any other way, including the internal status of a promise. In your actual code, you can’t synchronously see the state of a promise.

**Comment by wangyi7099** [comment]
@ljharb 
Thank you! I know !!

**Comment by ljharb** [comment]
This seems answered; closing.
