### ISSUE TITLE
Where I can to study the JIT (Just-In-Time) of the ECMAScript?

### ISSUE THREAD

**Issue by renanbastos93** [tc39/ecma262#1042]
Hello,

I want to learn as it works, because I want share knowledge with the community and write one article about the JIT.

Thanks,
See Ya

**Comment by jaydson** [comment]
Lin Clark's "A crash course in just-in-time (JIT) compilers" article is a great start, it's really really well written with fun cartoons and examples.
https://hacks.mozilla.org/2017/02/a-crash-course-in-just-in-time-jit-compilers/

**Comment by renanbastos93** [comment]
Thanks @jaydson I will read this article.

**Comment by ljharb** [comment]
JIT is a feature of specific implementations; it’s not part of the language nor the spec.

**Comment by ljharb** [comment]
@jaydson btw, thanks for the very helpful link :-) and @renanbastos93, please feel free to update here when you've written your article! I look forward to reading it.
