### ISSUE TITLE
Early errors for invalid regular expressions

### ISSUE THREAD

**Issue by TimothyGu** [tc39/ecma262#1050]
As it currently stands, the spec categorizes most invalid regular expression literals that don't interfere with parsing (e.g. `/(/`) as runtime errors. (See grammar productions for *[RegularExpressionLiteral](https://tc39.github.io/ecma262/#prod-RegularExpressionLiteral)*; regular expression parsing errors only occur during [Evaluation](https://tc39.github.io/ecma262/#sec-regular-expression-literals-runtime-semantics-evaluation) of such literals, through [RegExpCreate](https://tc39.github.io/ecma262/#sec-regexpcreate) and [RegExpInitialize](https://tc39.github.io/ecma262/#sec-regexpinitialize) steps 7 and 8.) However, it seems that many implementations treat them as early errors, as discovered in https://github.com/ternjs/acorn/issues/640.

Specifically, the following script parses in V8, but not in SpiderMonkey or JavaScriptCore. I am not sure how it performs on ChakraCore.

```js
if (false) (/(/);
```

Alternatively, this could be used as a test:

```js
new Function('return /(/');
```

**Comment by RReverser** [comment]
> Alternatively, this could be used as a test:

Or `() => /(/`

**Comment by RReverser** [comment]
Tested with Chakra on MacOS, it also treats this as an early parsing error. So it's only V8 that delays it to runtime.

**Comment by mathiasbynens** [comment]
https://bugs.chromium.org/p/v8/issues/detail?id=896

**Comment by mathiasbynens** [comment]
@TimothyGu 

> Specifically, the following script parses in V8, but not in SpiderMonkey or JavaScriptCore. I am not sure how it performs on ChakraCore.

```
$ eshost -e '(() => { if (false) /(/ })()'
#### Chakra
SyntaxError: Expected ')' in regular expression

#### JavaScriptCore
SyntaxError: Invalid regular expression: missing )

#### SpiderMonkey
SyntaxError: unterminated parenthetical:

#### V8 --harmony
undefined

#### V8
undefined
```

As a side comment, [eshost-cli](https://github.com/bterlson/eshost-cli) + [jsvu](https://github.com/GoogleChromeLabs/jsvu) make it really easy to test across all engines.

**Comment by jmdyck** [comment]
> As it currently stands, the spec categorizes most invalid regular expression literals that don't interfere with parsing (e.g. /(/) as runtime errors ...
> regular expression parsing errors only occur during Evaluation of such literals

What about the following [early error](https://tc39.github.io/ecma262/#sec-primary-expression-regular-expression-literals-static-semantics-early-errors)?
```
It is a Syntax Error if BodyText of RegularExpressionLiteral
cannot be recognized using the goal symbol Pattern
of the ECMAScript RegExp grammar specified in 21.2.1. 
```

**Comment by littledan** [comment]
Agreed with @jmdyck , this is already specified an early error. V8 has a [bug](https://bugs.chromium.org/p/v8/issues/detail?id=896) open for this spec violation.

**Comment by TimothyGu** [comment]
@jmdyck Oops, I overlooked that one.

@littledan Thanks for confirming.
