### ISSUE TITLE
Should %TypedArray%.prototype.slice throw an error if Set throws?

### ISSUE THREAD

**Issue by JakeChampion** [tc39/ecma262#1055]
[Section 22.2.3.24, step 14.b.iii](https://tc39.github.io/ecma262/#sec-%typedarray%.prototype.slice) performs a [`Set`](https://tc39.github.io/ecma262/#sec-set-o-p-v-throw) whilst omitting the fourth argument, which is used to indicate whether `Set` should ignore any errors that may have been thrown whilst performing the set.

This is the only place in the specification that calls `Set` without the fourth argument, which I think is incorrect as the fourth argument is not marked as an optional argument. This is also the only call to `Set` from Section 18 and onwards that is not passing `true` as the fourth argument to `Set`.

I would like to finish this issue off by saying that it is fantastic to have the specification and issue tracker on GitHub, thank you for making it simple for the community to get involved.

**Comment by ljharb** [comment]
This sounds like a clear spec bug; step 3 in https://tc39.github.io/ecma262/#sec-set-o-p-v-throw is an assertion that the fourth argument is a boolean.

As to whether it should be true or false, because of the `!`, it theoretically *can't* throw - which would either mean 1) that its value doesn't matter, and it probably should be "true", or 2) it shouldn't throw even if it otherwise would, meaning it should be "false".

In this case, since `A` is created by [TypedArraySpeciesCreate](https://tc39.github.io/ecma262/#typedarray-species-create), and the species constructor could do anything it likes, including installing throwing setters, step 14.b.iii could, indeed, throw (when "Throw" is set to "true").

What do existing engines do in this scenario?

**Comment by littledan** [comment]
@JakeChampion Thank you so much for your first bug report! I agree with you that `true` would be the right parameter ot pass. The next step from here would be to make a PR to the spec to correct the bug. Do you have enough information to do this? If not, feel free to ask on this issue or in the `#tc39` IRC channel on Freenode.

@ljharb I don't see how Set can throw here. TypedArraySpeciesCreate can only output a TypedArray--see step 2 of TypedArrayCreate which validates that it is a TypedArray. No casts between TypedArray element types can throw, and writing to an integer-indexed element of a TypedArray will never hit setters, so I think you're safe.

**Comment by jmdyck** [comment]
See PR #553 in which @leobalter asserts that this call to Set() cannot throw. The commit changed '?' to '!' (which seems correct), but also removed the fourth argument (which is incorrect).

**Comment by ljharb** [comment]
@littledan if i make a subclass of a typed array that has a setter (own or prototype) on an index that throws?

If indeed it’s not possible, then it should probably pass “false”.

**Comment by littledan** [comment]
@jmdyck Thanks for the context! This seems pretty straightforward then.

@ljharb A subclass of an integer indexed exotic object can't make accesses to integer indexes start throwing.

**Comment by JakeChampion** [comment]
In conclusion, it doesn't matter what the argument value actually is, because it cannot throw due to `Perform !`?

**Comment by ljharb** [comment]
Sounds right to me - `false` matches what te behavior will be; `true` would help ensure the `!` assertion is tested. I have a mild preference for the latter.

**Comment by littledan** [comment]
@JakeChampion `Perform !` doesn't suppress exceptions--instead, it's an spec-level assertion that no expression is being thrown. If an expression is thrown, then it's an error in the specification itself.

**Comment by JakeChampion** [comment]
@littledan I have learnt even more about the specification today, I was not aware `Perform !` was at the spec-level and not at the implementation level. This means that the argument _has_ to be `false` then. Is there any automated testing that verifies these spec-level assertions are valid?

**Comment by littledan** [comment]
@JakeChampion The argument doesn't have to be false--the argument can be true and this just makes the assertion stronger--for reasons that have to do with the bigger context, this particular callsite will never throw.

**Comment by jmdyck** [comment]
>  Is there any automated testing that verifies these spec-level assertions are valid?

I suspect it's either impossible or difficult to automatically verify all spec-level assertions. *Some* are amenable to static verification, particularly those that assert the type of value bound to a metavariable.

**Comment by ljharb** [comment]
@JakeChampion one common thing i've seen in some browser implementations is to actually encode the asserts - that way they *are* being exercised whenever the feature is tested (not in production, obv).

**Comment by ljharb** [comment]
@jmdyck @littledan https://github.com/tc39/ecma262/issues/1055#issuecomment-354131885 implies that the next step here is to reinstate the fourth argument - can you confirm?

**Comment by jmdyck** [comment]
It looks like I re-discovered + fixed this bug 6 months later, forgetting about the issue here.
See 9ce8b389 from PR #1266.

If that still looks good, you can close issue this with no further action.

**Comment by ljharb** [comment]
In that case, fixed by #1266 :-)
