### ISSUE TITLE
Should yield* preserve iteration result identity?

### ISSUE THREAD

**Issue by littledan** [tc39/ecma262#1058]
The [runtime semantics for `yield*`](https://tc39.github.io/ecma262/#sec-generator-function-definitions-runtime-semantics-evaluation) seem to forward out the exact iteration result that was provided in the inner iterator. See step 6.a.iv. At the bottom of this post is a quick test I wrote to expose the semantics; the spec's semantics are implemented by 3/4 of the engines I tested.

In [this V8 bug](https://bugs.chromium.org/p/v8/issues/detail?id=7236), some optimizations to generators are discussed. It seems that, if generators *always* output a new iteration result, it would be possible to move the iteration result allocation to the caller side, enabling unboxing even if the generator can't be inlined. @caitp prototyped this optimization and got a significant speedup. However, current `yield*` semantics don't permit this optimization, and @bmeurer judges it to be infeasible to make this work otherwise.

Alternate semantics are implemented by JSC (cc @kmiller68 @msaboff), where `yield*` always creates a new iteration result. For a naive implementation, the current specification may be slightly faster by avoiding the allocation in the `yield*` case, but in a more advanced implementation, JSC's semantics could enable a much greater level of avoiding allocations.

Does anyone have information about how the current `yield*` semantics were chosen?

cc @dherman @allenwb

----
```
Quick and ugly test differentiating the semantic options:

$ eshost -e "(function() { function* copy(iterable) { yield* iterable } let obj = { [Symbol.iterator]() { return { next() { return { value: 1, done: false, other: 123 } } } } }; let myCopy = copy(obj); return myCopy.next().other })()"
#### jsc
undefined

#### d8
123

#### chakracore
123

#### spidermonkey
123
```

**Comment by gskachkov** [comment]
In JSC we have a bug to fix this behaviour. cc @conselation

**Comment by littledan** [comment]
@gskachkov Link to the issue?

**Comment by gskachkov** [comment]
Should be that one https://bugs.webkit.org/show_bug.cgi?id=174756

**Comment by caitp** [comment]
I’m not sure we should fix it unless there’s a good reason to with real code depending on the identity preserving behaviour.

**Comment by littledan** [comment]
I think there's value in all implementations being on the same page about which value is returned where.

**Comment by ljharb** [comment]
cc @dherman @allenwb for historical context

**Comment by ljharb** [comment]
Is someone planning to make a needs consensus PR, or should this be closed?

**Comment by littledan** [comment]
Thanks for pinging the thread, @ljharb.

I'd like to hear from JS implementers about whether this sort of change might still enable/preserve optimizations. Any thoughts? @syg @caitp @ystartsev @kmiller68 @phoddie @devsnek etc

I'd also like to hear if people have any reservations about this change from a PL intuition/correctness perspective. In my opinion, creating a new IterationResult would make the behavior of generators more regular and so would be a desirable change. If these semantics are still shipping in JSC, it's likely to be a web-compatible change.

If people are positive/unconcerned from those perspectives, then I'd like to pursue a needs-consensus PR for this change.

**Comment by devsnek** [comment]
The result should absolutely be passed through without modification. For that proposed V8 optimization, it should still be possible as long as the caller doesn't try to observe the identity of the object right?

**Comment by littledan** [comment]
@devsnek Do you have a reason to provide, for why the result should be passed through without modification?

I don't know whether it's realistic to implement this optimization with the current semantics; at least in the past, it seems to have been judged impractical.

**Comment by devsnek** [comment]
Because the entire point of `yield*` is to give control to another iterator. The `yield*` itself shouldn't be doing anything to the iterator except passing it through.

**Comment by littledan** [comment]
I disagree; I think of `yield*` as passing through the iteration at more of a control level, so the important thing was more the values than the iteration results. But I don't plan to carry this argument forward amid these kinds of strong objections, so I'm going to close this issue. Someone else can reopen it if they want to carry on the discussion.
