### ISSUE TITLE
PRs policy

### ISSUE THREAD

**Issue by raulsebastianmihaila** [tc39/ecma262#1061]
Should TC39 have a policy w.r.t the time frame in which a PR should be merged? There's currently an open [PR](https://github.com/tc39/ecma262/pull/666), which has consensus, for a confirmed bug that was reported one year and a half ago.

**Comment by ljharb** [comment]
No. https://github.com/tc39/ecma262/pull/666 says that it's blocked on test262 tests.

**Comment by raulsebastianmihaila** [comment]
@ljharb Does that mean that it can take 20 years for a PR that achieved consensus to be merged?

**Comment by littledan** [comment]
@raulsebastianmihaila That PR is pretty tricky; if we merge it without good test262 tests, I'm worried implementations might not get everything right. Test262 has been very useful in the implementation of Proxies across engines so far. If you want to push this feature forward, contributing the tests could help get it landed in less than 20 years :)

**Comment by raulsebastianmihaila** [comment]
@littledan Unfortunatelly I don't have enough time, working full time as a JS dev, having to write tests for my own JS framework, taking bachata and salsa lessons etc. :) Joking aside, is TC39 in general lacking resources for testing? Also, being a tricky PR it would probably be a good idea for an experienced Test262 person to take care of this one.

**Comment by ljharb** [comment]
@raulsebastianmihaila I don't think a policy would serve much value here; we're all volunteers and not employees, so it's really a combination of the availability of editors, delegates, and community members that can help drive changes forward.

Any objections to this being closed? #666 still needs someone to have the time to write the test262 tests for it, but artificially applying a deadline isn't likely to create that time for anyone, unfortunately.

**Comment by raulsebastianmihaila** [comment]
OK, I'm closing this.
