### ISSUE TITLE
建议消除内置全局对象

### ISSUE THREAD

**Issue by wollld** [tc39/ecma262#1072]
如nodejs,分模块，然后导入，减少全局对象污染，如top，parent，self，居然是全局对象window的一个属性，容易出bug，也不合理。

**Comment by littledan** [comment]
The title translates as "It is recommended to eliminate the built-in global object".

I don't see how this could be done without breaking web compatibility. In any case, this sounds like a new proposal. Please see [CONTRIBUTING.md](https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md) for how to create such a new proposal.
