### ISSUE TITLE
Missing definitions for "<thing> equivalent to a function that <action>"

### ISSUE THREAD

**Issue by anba** [tc39/ecma262#1077]
Added in #1073

**Comment by ljharb** [comment]
This phrase was actually added in ES2015: http://ecma-international.org/ecma-262/6.0/#sec-promisereaction-records

I copied that phrasing in the "finally" spec, but afterwards, I filed #584, which refactored the existing (definitionless) usage to be strings, instead of callbacks, stored in internal slots.

I think it'd be fine to add a definition, but ES2015 didn't seem to need one - what definition would you suggest and where would it go?

**Comment by ljharb** [comment]
Fair enough :-) What definition would you suggest and where would it go?

**Comment by anba** [comment]
The easiest fix is to create normal built-in functions à la:

Add:

---
25.6.5.3.1.1 Return Completion Functions

A Return Completion function is an anonymous built-in function that has a [[Completion]] internal slot.

When a Return Completion function F is called, the following steps are taken:

    1. Return Completion(F.[[Completion]]). 

The length property of a Return Completion function is 0.

---

And then replace:

---

7. Let valueThunk be equivalent to a function that returns value.

---

With:

---

7. Let stepsReturnCompletion be the algorithm steps defined in Return Completion Functions.
8. Let valueThunk be CreateBuiltinFunction(stepsReturnCompletion, « [[Completion]] »).
9. Set valueThunk.[[Completion]] to NormalCompletion(value).

---

And replace:

---

7. Let thrower be equivalent to a function that throws reason.

---

With:

---

7. Let stepsReturnCompletion be the algorithm steps defined in Return Completion Functions.
8. Let thrower be CreateBuiltinFunction(stepsReturnCompletion, « [[Completion]] »).
9. Set thrower.[[Completion]] to ThrowCompletion(reason).

---


And if we don't want to repeat the three steps to create this new function, it's also possible to add a helper like:

----

25.6.5.3.1.2 MakeReturnCompletionFunction(completionRecord)

The abstract operation MakeReturnCompletionFunction with argument completionRecord performs the following steps:

1. Let stepsReturnCompletion be the algorithm steps defined in Return Completion Functions.
2. Let F be CreateBuiltinFunction(stepsReturnCompletion, « [[Completion]] »).
3. Set F.[[Completion]] to completionRecord.
4. Return F.

----

And then use it like:

---

7. Let valueThunk be MakeReturnCompletionFunction(NormalCompletion(value)).

---

7. Let thrower be MakeReturnCompletionFunction(ThrowCompletion(reason)).

---

**Comment by domenic** [comment]
A more ambitious fix would be to tackle https://github.com/tc39/ecma262/issues/933.

**Comment by arai-a** [comment]
Related to https://github.com/tc39/ecma262/issues/2222
if the function is passed to `Promise.prototype.then` ("Then Finally Function"'s case), the function's [[Realm]] slot affects embedding behavior,
so it should be explicit about [[Realm]] slot.
