### ISSUE TITLE
Make 21.2.7 and 21.2.8 subclauses of 21.2.1/2?

### ISSUE THREAD

**Issue by anba** [tc39/ecma262#1080]
Having them as extra clauses after 21.2.6 doesn't look correct to me.

**Comment by jmdyck** [comment]
Didn't look correct to me either.
See 57e09db and 2e2e5b2

**Comment by ljharb** [comment]
Both of these changes appear to be moved; I'm closing this.

Happy to reopen if something still needs to be done here.
