### ISSUE TITLE
Missing [?U] for ClassEscape :: CharacterClassEscape 

### ISSUE THREAD

**Issue by anba** [tc39/ecma262#1082]
CharacterClassEscape now also has `[U]`, so it needs to be passed from ClassEscape.

**Comment by jmdyck** [comment]
And from AtomEscape.
See ee6c6b6

**Comment by bterlson** [comment]
Also the Annex B definitions of AtomEscape and ClassEscape, presumably.

**Comment by jmdyck** [comment]
Yup, ee6c6b6 has got those too.

**Comment by bterlson** [comment]
Ahh I missed that in the midst of @jmdyck's editorial PR. I guess I'll splice out my duplicate commit there.

**Comment by anba** [comment]
Looks like it's fixed now. Thanks @jmdyck !
