### ISSUE TITLE
Proposal to add "nowait"

### ISSUE THREAD

**Issue by MrEfrem** [tc39/ecma262#1098]
Sometimes when create the `async` functions forget to add `await` and later such mistake difficult to find.
Maybe would be better always demand to add keyword `nowait` to calls returning promises which we don't plan to wait. But if this keyword and `await` keyword no exists then throw the error?

**Comment by CrocoDillon** [comment]
You can use [ESLint's `require-await`](https://eslint.org/docs/rules/require-await) for this.

**Comment by MrEfrem** [comment]
Thanks.
