### ISSUE TITLE
Editorial: Missing sentence period

### ISSUE THREAD

**Issue by js-choi** [tc39/ecma262#1106]
A period is missing from the final sentence of the second paragraph of [Clause 8.1 Lexical Environments](https://tc39.github.io/ecma262/#sec-lexical-environments).

> …and a new Lexical Environment is created each time such code is evaluated.

> An Environment Record records the identifier bindings that are created within the scope of its associated Lexical Environment. It is referred to as the Lexical Environment's _EnvironmentRecord_

> The outer environment reference is used to model the logical nesting of Lexical Environment values. The outer reference of a (inner) Lexical Environment is a reference…

**Comment by littledan** [comment]
@js-choi Good catch. PRs welcome!
