### ISSUE TITLE
Question: Where is ES2018 (ES9) spec published?

### ISSUE THREAD

**Issue by styfle** [tc39/ecma262#1115]
Any idea where the official ES2018 (ES9) is published?
I tried https://www.ecma-international.org/ecma-262/9.0/ but its not up yet.
I tried https://tc39.github.io/ecma262/ but it says "ECMAScript® 2019 Language Specification".

So where is the 2018 spec?

**Comment by caridy** [comment]
https://tc39.github.io/ecma262/2018/

FYI, It is not official just yet! It is expected to become official later this year.
