### ISSUE TITLE
Missing IsFunctionDefinition for anonymous FunctionExpression

### ISSUE THREAD

**Issue by jorendorff** [tc39/ecma262#1139]
See [14.1.12](https://tc39.github.io/ecma262/#sec-function-definitions-static-semantics-isfunctiondefinition). It only seems to be specified for the production where the BindingIdentifier is present. Likewise, GeneratorExpression ([14.4.8](https://tc39.github.io/ecma262/#sec-generator-function-definitions-static-semantics-isfunctiondefinition)) and AsyncGeneratorExpression (14.5.8) only specify IsFunctionDefinition for the production with BindingIdentifier.

The corresponding spec for async functions, [14.7.8](https://tc39.github.io/ecma262/#sec-async-function-definitions-static-semantics-IsFunctionDefinition), lists both productions.

I think either the other three sections should be changed to list both productions, like 14.7.8; or else all four should be changed to use `_opt`.

**Comment by bakkot** [comment]
The `?` which should render as "\_opt" is actually present in the source, I think (line 18841, which I can't link to since it's too big).

Pretty sure this is a [bug](https://github.com/bterlson/ecmarkup/issues/108) in ecmarkup. cc @bterlson.

**Comment by anba** [comment]
See #536
