### ISSUE TITLE
14.4.2 and 14.5.2 have the same section id

### ISSUE THREAD

**Issue by jorendorff** [tc39/ecma262#1140]
Here's a link to 14.4.2: https://tc39.github.io/ecma262/#sec-generator-function-definitions-static-semantics-boundnames

Clicking on 14.5.2 in the table of contents takes me to the same section (that is, it's a link to 14.4.2). Some subsequent sections are also affected.

**Comment by littledan** [comment]
Thanks for the fix, @ljharb

**Comment by ljharb** [comment]
Issues should remain open until the fix is merged.

**Comment by littledan** [comment]
Oops, I missed that it was your branch.
