### ISSUE TITLE
[Question] Where is the ECMAScript 2018 spec link?

### ISSUE THREAD

**Issue by rajaraodv** [tc39/ecma262#1151]
I see 2017 spec link here: https://www.ecma-international.org/ecma-262/8.0/ but I can't find the 2018's link. 

PS: https://tc39.github.io/ecma262/ says its 2019.

**Comment by michaelficarra** [comment]
https://tc39.github.io/ecma262/2018/

**Comment by rajaraodv** [comment]
@michaelficarra Thanks!

**Comment by leobalter** [comment]
Keep in mind the 2018 edition is in it's final draft / release candidate going to the Ecma's General Assembly for final vote and publishing, this should occur in June or July.

The link posted by @michaelficarra reflects this accurate candidate.

In any case, I suggest following the latest draft as any fixes are applied there. https://tc39.github.io/ecma262/
