### ISSUE TITLE
%TypedArray%.of does not use @@species

### ISSUE THREAD

**Issue by TimothyGu** [tc39/ecma262#1157]
[%TypedArray%.of](https://tc39.github.io/ecma262/#sec-%typedarray%.of) uses the **this** value as the constructor, not `this[Symbol.species]`. This seems inconsistent with the methods on %TypedArrayPrototype% like subarray and slice.

**Comment by allenwb** [comment]
No, it's correct as written and handled exactly the same as in [%Array%.of](https://tc39.github.io/ecma262/#sec-array.of)

`of` is a factory method of the constructor so the actual class constructor to be instantiated is the thisValue passed to the factory.  What the algorithm is doing is approximately this: 

```js
class %TypedArray% {
   of(...args) {
      let ta = new this(args.length
      for (let i=0; ++1; i<args.length) ta[i]=args[i];
      return ta;
  }
}
```
When used in an expression referencing a subclass such as `Int32Array.of(1,2,3)` the value of `this` within the inherited method will be  %Int32Array%.  Essentially the expression is explicitly naming the kind of typed array it wants to instantiate.

@@species is primarily for use in instance methods that create derived collections whose class isn't explicit stated at the usage site.
