### ISSUE TITLE
Why does FunctionDeclaration allow the name to be omitted?

### ISSUE THREAD

**Issue by erights** [tc39/ecma262#1159]
See the second clause at
http://www.ecma-international.org/ecma-262/8.0/#prod-FunctionDeclaration

**Comment by ljharb** [comment]
Is it for `export default function () {}`?

**Comment by allenwb** [comment]
yes

**Comment by allenwb** [comment]
see https://www.ecma-international.org/ecma-262/8.0/#sec-function-definitions-static-semantics-boundnames

**Comment by ljharb** [comment]
The editors decided no note is warranted here.
