### ISSUE TITLE
Addition of "Immutable mode"

### ISSUE THREAD

**Issue by jperasmus** [tc39/ecma262#1165]
Similar to how strict mode can be enabled by setting `'use strict';`, it will be extremely useful to have a `'use immutable';` mode setting. When this mode is enabled, all methods within the global or function scope should perform in an immutable fashion instead of mutating data.

An example could be all of the [array methods](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/prototype#Mutator_methods) that mutate the underlying data, like `push()`, `pop()`, etc. I am aware that you can use `concat()` instead of `push()` if you don't want to mutate the array, but this mode can reach far beyond this method and arrays.

As an example for objects, doing something like `Object.assign(obj1, obj2)` would produce a new object without mutating `obj1` and also work for deeply nested structures and not just one level deep.

It should be fairly easy to polyfill a lot of these methods by using something similar to [Immutable.js](https://facebook.github.io/immutable-js/).

**Comment by bterlson** [comment]
This repository is not for making proposals. See [here](https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#new-feature-proposals) for more information.
