### ISSUE TITLE
Suggestion: add Issue/PR templates to this repo

### ISSUE THREAD

**Issue by getify** [tc39/ecma262#1166]
In an effort to maybe cut down on people submitting feature suggestions to this repo -- which it clearly is not for but a lot of people assume it is -- may I suggest: in addition to the CONTRIBUTING.md that you've already got, add Issue & PR templates to this repo, each including a notice linking to the CONTRIBUTING.md. Ostensibly, the submitter then has to read and remove this notice from the text of their issue before they submit. This may make it more likely that someone reads the guidelines before submitting.

**Comment by ljharb** [comment]
This has been done in #1449 and #1445.
