### ISSUE TITLE
Move AsyncFunction section next to AsyncGenerator section?

### ISSUE THREAD

**Issue by anba** [tc39/ecma262#1170]
- 25.1 Iteration
- 25.2 GeneratorFunction Objects
- 25.3 AsyncGeneratorFunction Objects
- 25.4 Generator Objects
- 25.5 AsyncGenerator Objects
- 25.6 Promise Objects
- 25.7 AsyncFunction Objects

Maybe "25.6 Promise Objects" and "25.7 AsyncFunction Objects" should switch places, so that async functions are placed next to async generator (objects)?

**Comment by ljharb** [comment]
Alternatively, maybe Promise objects should go higher since async generators depend on them?

**Comment by ryzokuken** [comment]
@ljharb where exactly should `Promise Objects` land up in your opinion? Right above `AsyncGeneratorFunction Objects`?

**Comment by ljharb** [comment]
After iteration, perhaps?

**Comment by ryzokuken** [comment]
Sure, will do.
