### ISSUE TITLE
Section 27 (Memory Model) in the wrong place?

### ISSUE THREAD

**Issue by michaelficarra** [tc39/ecma262#1189]
Section [4.4](https://tc39.github.io/ecma262/#sec-organization-of-this-specification) (Organization of This Specification) lists sections 5 through 26 and generally categorises them. Section 27, the final numbered section, is missing from here. It doesn't clearly fit into the 17-26 (ECMAScript standard library) group. Should it be moved to be adjacent to a more appropriate group? Either way, 4.4 should mention the Memory Model section in some way.

**Comment by syg** [comment]
A definite yes to 4.4 mentioning the memory model. I put it at the last numbered section as it doesn't fit with any existing group. I recommend 4.4 saying 27 is the memory model.
