### ISSUE TITLE
Should remove unnecessary [[Extensible]] assignments

### ISSUE THREAD

**Issue by bmeck** [tc39/ecma262#1201]
Default behavior is for it to be `true` per https://tc39.github.io/ecma262/#sec-ecmascript-standard-built-in-objects , but lots of builtins specify it to be true. This can lead to some confusion and thinking that `true` is not the default.

**Comment by rkirsling** [comment]
@bmeck: I was looking for a `good first patch` to tackle, but noticed that you've also self-assigned here. Do you mind if I submit a PR for this?

**Comment by bmeck** [comment]
@rkirsling feel free to make the PR, I accidentally set myself to this wehn making it and then changed it to be good first patch XD.
