### ISSUE TITLE
What is difference between VarDeclaredNames and VarScopedDeclarations?

### ISSUE THREAD

**Issue by dSalieri** [tc39/ecma262#1203]
Yeah, if look at title you can understand: first (VarDeclaredNames) contains names, second (VarScopedDeclarations) contains declarations. Hence the question is what is the sense of VarDeclaredNames if VarScopeDeclarations contains names (at least you can extract)?

**Comment by bergus** [comment]
Same conclusion on StackOverflow: [What's the difference between VarDeclaredNames and VarScopedDeclarations?](https://stackoverflow.com/q/40609675/1048572)

**Comment by ljharb** [comment]
This was answered on SO: https://stackoverflow.com/a/40623284/632724

> they do return different data - different types of lists. While VarDeclaredNames returns a list of names (strings), VarScopedDeclarations does return a list of declarations (i.e. AST nodes).
