### ISSUE TITLE
Idea: Required property accessor

### ISSUE THREAD

**Issue by adrianhelvik** [tc39/ecma262#1221]
It would be nice to have foo!.bar alongside foo?.bar.

foo!.bar could then throw if foo.bar === undefined.

Useful when using process.env in Node and for debugging. Its primary use case would be for when undefined is unacceptable:

    sendEmailToUsers({
      from: process.env!.customerSupport
    })

The reason I think allowing nulls is a good idea is that they are generally explicitly specified, whereas undefined is usually not what you want.

**Comment by ljharb** [comment]
Please see the proposal repo for [optional chaining](https://github.com/tc39/proposal-optional-chaining/), as well as https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md for how to best suggest new ideas.

Separately, `foo?.bar` tells you something about `foo`, not `bar` - as such, `foo!.bar` would have to have behavior based on `foo` - not `foo.bar` - for consistency.
