### ISSUE TITLE
New syntax for lazy getters

### ISSUE THREAD

**Issue by aaditmshah** [tc39/ecma262#1223]
[Lazy getters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get#Smart_self-overwriting_lazy_getters) are really useful in functional programming. They are used to [prevent stackoverflows](https://stackoverflow.com/a/50311377/783743) (via [tail recursion modulo cons](https://en.wikipedia.org/wiki/Tail_call#Tail_recursion_modulo_cons)), and they can be used to create infinite data structures. However, they are very verbose. Consider the following lazy `take` function:

```javascript
const take = (n, xs) => n === 0 ? null : xs && {
    head: xs.head,
    get tail() {
        delete this.tail;
        return this.tail = take(n - 1, xs.tail);
    }
};
```

It would be nice to have syntactic sugar to create the lazy getter:

```javascript
const tail = (n, xs) => n === 0 ? xs && {
    head: xs.head,
    lazy tail: take(n - 1, xs.tail)
};
```

This syntax could also be used to *succinctly* [tie the knot](https://wiki.haskell.org/Tying_the_Knot) to create cyclic data structures:

```javascript
const xs = { head: 0, lazy tail: ys },
      ys = { head: 1, lazy tail: xs };

const zeros = { head: 0, lazy tail: zeros };
```

This enables a limited form of `letrec` without actually changing the semantics of `let`, `const` or `var`.

**Comment by ljharb** [comment]
Please see https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md for how to best suggest new ideas.
