### ISSUE TITLE
Markup: update `es6num` comments in Section 25

### ISSUE THREAD

**Issue by ryzokuken** [tc39/ecma262#1235]
The different sub-sections inside Section 25 are annotated using `es6num` markup comments like `<!-- es6num="25.2" -->`. However, these comments weren't updated (and added to new sub-sections) when the `Async` variants of existing entries were added.

Should these comments be updated/added wherever necessary?

**Comment by jmdyck** [comment]
> they’re set in stone to preserve ES6-era links

I'm pretty sure that's not the case: they could be removed without breaking links from any era.

If the editors would prefer them gone (to avoid such questions in the future), I can submit a PR.

**Comment by ryzokuken** [comment]
> No, these should never be updated or added - they’re set in stone to preserve ES6-era links.

Making appropriate changes in https://github.com/tc39/ecma262/pull/1234

**Comment by ljharb** [comment]
No, links from es6 must work for all eternity. Cool urls never change.

**Comment by ryzokuken** [comment]
@ljharb thanks for the clarification. Closing this in that case, made appropriate changes in #1234.

**Comment by jmdyck** [comment]
> No, links from es6 must work for all eternity.

Sure, but why do you think that has *anything* to do with these comments?

Do you think the `ecmarkup` process looks at them and turns them into anchors? (It doesn't.)

**Comment by ljharb** [comment]
I did think that, yes. If it doesn’t, then I’m not sure why we bother keeping the comments at all.

**Comment by ryzokuken** [comment]
I understand why you'd want to remove the comments altogether, they need to be updated and added and add extra layers without doing anything meaningful, but for one, they help people navigate. When you're neck deep in markup, an indicator telling which section you're currently on helps.

**Comment by ljharb** [comment]
The clause ID does a better job of that though.

**Comment by ryzokuken** [comment]
Just noticed, you're right. It does. So, should I just remove all the comments?

**Comment by ljharb** [comment]
The editors discussed this; and decided to get rid of them (see #1237)
