### ISSUE TITLE
Cross-platforms method to enumerate all globals?

### ISSUE THREAD

**Issue by gardhr** [tc39/ecma262#1240]
I'm currently working on a project to allow sandboxed loading of scripts. The basic approach is to selectively declare "shadow" variables for defined globals and native types. The problem is I'm not sure how to do this in the most generic way across all platforms. My current naive attempt is essentially:

`

        var namespaces = [this];

        if (typeof global != "undefined") namespaces.push(global);

        if (typeof window != "undefined") namespaces.push(window);

        var globals = [

          "Array",

          "RegExp",

          "Symbol",

          "Object",

          "Number",

          "Boolean",

          "String",

          "Function",

          "Date",

          "Error",

          "Iterator",

          "JSON",

          "Math",

          "eval"

        ];

        for (var index = 0; index < namespaces.length; ++index)

          globals = globals.concat(Object.keys(namespaces[index]));

`
That seems to work okay so far, but it's just too easy for things to fall through the cracks. Is there a more generic method to do this that is guaranteed to catch all possible definitions?

**Comment by ljharb** [comment]
The globals are `Object.getOwnPropertyNames(global)` where `global` is `Function(‘return this’)()` or the equivalent. I’m not sure what you’re asking for.

Separately, if you’re looking into sandboxing, you may want to look into prior art: Caja and SES.

**Comment by gardhr** [comment]
@ljharb Thank you so much, precisely what I was looking for! And yes, somewhat familiar with Caja and SES but this is more of a "safe eval" type of project. Hadn't found anything yet along those lines so I decided to take a stab at it myself. Anyhow, thanks again for the prompt, helpful response. Cheers!

**Comment by loganfsmyth** [comment]
`Object.getOwnPropertyNames(global)` is as close as you'll get I think, but it will only enumerate all _var_-scoped globals like `var` and `function` declarations, it will not enumerate lexical globals, so it won't catch `let`/`const`/`class` declarations in the global scope.

Whether or not that matters probably depends on the details of what you're doing, but it is worth mentioning at least.

**Comment by gardhr** [comment]
@loganfsmyth True, but as far as this project goes I really just want to provide a mechanism to prevent scripts from accessing/modifying properties of native types and platform-specific globals. Thank you for pointing that out though, definitely worth noting and I'll be sure to mention that in the documentation nonetheless.

**Comment by ljharb** [comment]
Closing; but we can continue discussing as needed.

**Comment by robpalme** [comment]
I don't think this safety is possible without a frozen realm because the
caller can always get to certain globals.

[].__proto__.smoosh = ...

**Comment by IgnoredAmbience** [comment]
The source code for Caja/SES is [here](https://github.com/google/caja/tree/master/src/com/google/caja/ses), it is well worth reading to get an understanding for many of the JS edge cases that permit sandbox escapes, the `startSES.js` file is an appropriate place to begin reading. The codebase is well-commented.

**Comment by gardhr** [comment]
@robpalme Hmm, I can't seem to produce anything meaningful from that. Would you mind providing a working example?

**Comment by gardhr** [comment]
@IgnoredAmbience Thanks, I'll have a look at that!
