### ISSUE TITLE
[Feature Request] Support for 'self' keyword in classes which is more specific than 'this' keyword

### ISSUE THREAD

**Issue by devssh** [tc39/ecma262#1251]
**Is your feature request related to a problem? Please describe.**
Using 'this' is confusing in classes as it could refer to the class or the current function in the class.
I have spent a lot of time writing code where there is an error and it turns out to be an oversight of the scope for 'this' when refactoring code to a function.

**Describe the solution you'd like**
The same solution provided by Scala which is to add a keyword called 'self'
So 'self.function1' refers to the class.function1 while 'this.function1' refers to the local scope of the function.

**Describe alternatives you've considered**
a simple hack for this is to create a variable 'self' in every class and assign it to 'this' in the beginning, another solution would be to use 'class1.function1' instead of 'this.function1' but working in a team means that other people end up writing 'this.function1' leaving me to figure out the scope and this restricts readability

**Teachability, Documentation, Adoption, Migration Strategy**
Users will understand this if they have worked in languages like scala or if they do a quick search for the keyword

**Comment by nicolo-ribaudo** [comment]
https://github.com/rbuckton/proposal-class-access-expressions

Does this proposal do what you want?

**Comment by devssh** [comment]
No it does not. That is a different use case

**Comment by nicolo-ribaudo** [comment]
Ok, I initially misunderstood your request.

`self` as a keyword will never be added, because it would be a breaking change:
```js
var self = 2;
class A {
  foo() {
    return function () {
      console.log(self); // 2
    }
  }
}
```

If you don't want to loose the this context, just use arrow functions "by default".

Anyway, the correct place to discuss a new ECMAScript feature is the https://esdiscuss.org mailing list 😉

**Comment by devssh** [comment]
Haha I see, just a suggestion since it seems handy to have and nobody seems to have reported this yet. 

ES does have breaking changes from time to time as long as the benefits outweigh the downside.
Yes, I usually use arrow functions but unfortunately I work in React, and when it is not possible to have stateless functions I have to work on functions in React Components.
Plus there are a lot of blog posts about using the 'self' keyword in ES which shows how much people want it

https://stackoverflow.com/questions/34483888/difference-between-bind-and-var-self-this
https://groups.google.com/forum/#!topic/nodejs/1cTO_cJVxUg
https://medium.com/@vijay.j.shekhawat/javascript-why-var-self-this-bbbaf98ab9d9
http://blog.iangilman.com/2015/02/self-this.html

Thanks for the reference to esdiscuss

**Comment by ljharb** [comment]
@devssh in react, the pattern you want is a normal instance method `foo`, with `this.foo = this.foo.bind(this)` in the constructor.

Since every function invocation can redefine `this`, there's no way to achieve what you want for the instance short of autobinding every method, which would break a lot of legitimate use cases - and the linked proposal above covers the static use case, for which you would currently hardcode the class name.

See https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md for how to suggest new features.

**Comment by devssh** [comment]
I already know about `this.foo = this.foo.bind(this)`
I meant this issue https://github.com/facebook/react/issues/2899 which is closed for the same reason, `breaking changes`

**Comment by ljharb** [comment]
You may find https://github.com/tc39/proposal-class-access-expressions relevant.

**Comment by devssh** [comment]
It is not

**Comment by ljharb** [comment]
@devssh there's really just no way for this to work; given that a method is usually on the prototype, shared across potentially millions of instances, how would the engine know which instance the keyword refers to? Binding as an own property, or making an auto-binding getter, are really the only possible ways to achieve what you want.

See also https://esdiscuss.org/topic/proposal-for-a-new-alternative-keyword-to-this-for-classes

**Comment by devssh** [comment]
Yes, I understand that self is not a reserved keyword, therefore it will be a change that is potentially breaking if someone is using self, thus the issue is closed. The engine could just bind self as a property to every class automatically as you stated, that way only classes have 'self', and functions are 'this'. But ES proposal you shared is going with a different approach. Really love the thread and arguments for 'self' like keyword in  https://esdiscuss.org/topic/proposal-for-a-new-alternative-keyword-to-this-for-classes, but like they confirm, it makes static analysis easier and the code more readable and less context dependent on 'this' but they chose not to proceed with this approach.
