### ISSUE TITLE
Editorial: Clarification on auto semicolon insertion

### ISSUE THREAD

**Issue by crlf0710** [tc39/ecma262#1254]
Hello, I think the spec text should mention that the ";" rule of `ClassElement` can not use an auto inserted semicolon. While this conclusion can be actually deduced from the current syntax rules(e.g. adding semicolon there will not change an offending token into an accepted one so syntax error still will happen), it's not very obvious at first sight.

**Comment by ljharb** [comment]
I'm going to assume that #1062 resolved this; if not, happy to reopen with more specifics.
