### ISSUE TITLE
Request: Shortcut for declaring an ES6 fat arrow function that doesn't take parameters.

### ISSUE THREAD

**Issue by ozzie1998** [tc39/ecma262#1265]
Declaring an ES6 Fat arrow function is like so: 

```js
let example = () => {/*Blah*/}
```

It would be handy to be able to declare an ES6 Fat Arrow Function that doesn't take any parameters like so: 

```js 
let example => {/*blah*/}
```

The main problem with this would be that this isn't immediately obvious as a function. 

#### Advantages of a shorter Fat Arrow function declaration for a function that doesn't take any arguments:

1) Less to type 
2) Makes writing callbacks easier

**Comment by devsnek** [comment]
seems more confusing than useful. adding too much syntax has a strain on people writing the language.

**Comment by ljharb** [comment]
Please see [Contributing to ECMAScript](https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md) for the most up-to-date information on contributing proposals to this standard.
