### ISSUE TITLE
Rationale behind early ReferenceError and early SyntaxError

### ISSUE THREAD

**Issue by Constellation** [tc39/ecma262#1267]
I'm attempting to update JSC's parser to accept early `ReferenceError` concept.
But I don't get the point of the rationale behind early ReferenceError and SyntaxError yet.

According to the spec[1,2],

```js
function test() {
    "use strict";
    arguments = 42;
}
```

should raise early ReferenceError. On the other hand,

```js
function test() {
    "use strict";
    ({ arguments } = object);
}
```

```js
function test() {
    "use strict";
    ({ a: arguments = 20 } = object);
}
```

should raise early SyntaxError[3].

What makes this differences? Why are IdentifierReference in Object/ArrayPatterns handled differently from usual AssignmentExpression LHS's IdentifierReference?
This is a bit confusing and it seems that even test262 does not test it correctly (see `test/language/expressions/assignment/id-arguments-strict.js` for example).

1: https://tc39.github.io/ecma262/#sec-assignment-operators-static-semantics-early-errors
2: https://tc39.github.io/ecma262/#sec-identifiers-static-semantics-isvalidsimpleassignmenttarget
3: https://tc39.github.io/ecma262/#sec-destructuring-assignment-static-semantics-early-errors

**Comment by IgnoredAmbience** [comment]
It looks like this was previously raised as a bug in the ES6 spec period and got deferred to ES7, but never resolved?
https://tc39.github.io/archives/bugzilla/4375/

**Comment by IgnoredAmbience** [comment]
PR #1132 is open already to fix this as well.
