### ISSUE TITLE
Site loading is too slow

### ISSUE THREAD

**Issue by sshmyg** [tc39/ecma262#1270]
Hi, can you split https://tc39.github.io/ecma262/ this site on separate pages?
Because right now, performance is awful. I can't open it even on desktop, not mention about mobile devices. 
Thank you.

**Comment by jonpalmer41** [comment]
i think i have now let me know if not sry

jon

**Comment by devsnek** [comment]
i've definitely felt the sluggishness of the site on my devices...

something similar to what whatwg does would be ideal: https://html.spec.whatwg.org/multipage/

**Comment by sshmyg** [comment]
Yep `whatwg` is what I mean.

**Comment by nicolo-ribaudo** [comment]
Also, even when loaded the site is almost unusable on mid-range smartphones (Xiaomi Mi A1) because it is too big and it crashes Chrome.

**Comment by cup** [comment]
https://github.com/bterlson/ecmarkup/issues/151
https://github.com/tc39/ecma262/issues/1270
https://github.com/tc39/ecma262/issues/1434

**Comment by michaelficarra** [comment]
@nicolo-ribaudo As a temporary workaround, I've found that Firefox loads the page many times (:exclamation:) faster than Chrome. You could try using that to browse it instead.



:fire:
