### ISSUE TITLE
Array.sort() sorted order invariant does not distinguish undefined and missing values

### ISSUE THREAD

**Issue by lukq** [tc39/ecma262#1271]
The Array.sort() method specification gives steps that should be taken

> The following steps are taken:
> Perform an implementation-dependent sequence of calls to the [[Get]] and [[Set]] internal methods of obj, to the DeletePropertyOrThrow and HasOwnProperty abstract operation with obj as the first argument, and to SortCompare (described below), such that:
> ...
> 

The calls performed are implementation-dependent. Therefore, the next paragraph states what is the correctly sorted order.

> There must be some mathematical permutation π of the nonnegative integers less than len, such that 
> 
> - for every nonnegative integer j less than len, if property old[j] existed, then new[π(j)] is exactly the same value as old[j]. But if property old[j] did not exist, then new[π(j)] does not exist. 
> - Then for all nonnegative integers j and k, each less than len, if SortCompare(old[j], old[k]) < 0 (see SortCompare below), then new[π(j)] < new[π(k)].
> 
> 

Here, the second point does not distinguish values that are undefined and values that are missing from the array.

But the text phrasing in the part about the steps to be taken, and Note 1 in _Runtime Semantics: SortCompare_ suggest that undefined values should be sorted before missing values. I suggest the sorted array invariant be rewritten to reflect this implicit requirement.

**Comment by ljharb** [comment]
#1585 might be relevant.
