### ISSUE TITLE
const is too verbose! Make it default when assignment is done by :=

### ISSUE THREAD

**Issue by Kimilhee** [tc39/ecma262#1276]
## Feature Request

I think good language has a good default syntax.

In es6 and above, more than 95% of the variables is declared as const.
Then, let's make it default!

**My Feature request**
Instead of this 
```
const id = 123;
```

This is far better! concise and shorter!
```
id := 123;
```

I know that this one declaration seems not so much difference.

But, you con easily find the following case!
```
const id = 123;
const str = 'ABC'
const time = new Date();
const reg = /abc/;
const ....
```

Let's do it just like this.
```
id := 123;
str := 'ABC'
time := new Date();
reg := /abc/;
....
```

Done.

**Comment by annevk** [comment]
This is not the right place to propose changes to ECMAScript. I recommend reading through https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md.
