### ISSUE TITLE
The [[ExportName]] field of ExportEntry Record can also be null

### ISSUE THREAD

**Issue by aruku7230** [tc39/ecma262#1290]
In [Table 42: ExportEntry Record Fields](https://tc39.github.io/ecma262/#table-41), it states that  [[ExportName]] filed's value type is String. 

But look at the [example](https://tc39.github.io/ecma262/#table-42),  [[ExportName]]  can also be null, when Export Statement Form is the following:

> export * from "mod";

The [[ExportName]] field of ExportEntry Record should be "String | null", 
or the [[ExportName]] of `export * from "mod";`  should not be null.

**Comment by jmdyck** [comment]
It appears that when an ExportEntry Record has `[[ImportName]] = "*"`, its `[[ExportName]]` and `[[LocalName]]` are completely ignored. (`ParseModule` puts the record in `_starExportEntries_`, which goes to `[[StarExportEntries]]`, which is then processed in `GetExportedNames` and `ResolveExport`.)

So on the one hand, it doesn't matter what `[[ExportName]]` is set to there. But on the other hand, I agree that the use of the field should conform to its 'type declaration'. The easiest thing would be to change the latter to "String | null". (Personally, I think replacing `null` with (say) `"*ignored*"` would be somewhat more informative. Another alternative would be to have 3 'sub-types' of ExportEntry Record, none of which have any `null` fields.)

**Comment by seminaoki** [comment]
I agree that 

> The easiest thing would be to change the latter to "String | null"

Since other fields of ExportEntry also use "String | null" value type.

**Comment by devsnek** [comment]
wouldn't we use the term unset here?

**Comment by jmdyck** [comment]
> wouldn't we say not present or unset here?

The spec doesn't use the word "unset" at all, so that seems unlikely. As for "not present", did you mean like this?

    ExportEntry Record { ..., [[ExportName]]: not present, ... }

That would amount to treating `not present` as a (spec) value, which we don't really do.

**Comment by ljharb** [comment]
It could be `~empty~`

**Comment by jmdyck** [comment]
It could, but:
- `null` is clearly the convention for ExportEntry records, and
- you'd still have to change [[ExportEntry]]'s field type.

**Comment by ljharb** [comment]
Would you? Empty means there’s nothing there, so the type is still string, it’s just optional.

**Comment by jmdyck** [comment]
I don't think there's a precedent in the spec where something with a declared type of T actually allows T or `~empty~`. E.g., the `[[Target]]` field of completion records is explicitly declared as `any ECMAScript string or ~empty~`.

(In several programming languages, "optional string" is quite distinct from "string". E.g. Rust, Swift, Kotlin, Scala, C#, F#.)

**Comment by bakkot** [comment]
Fixed by https://github.com/tc39/ecma262/pull/1379.
