### ISSUE TITLE
Stray &lt in spec

### ISSUE THREAD

**Issue by DanielRosenwasser** [tc39/ecma262#1304]
At the bottom of https://tc39.github.io/ecma262/#sec-static-semantics-tv-and-trv

> The TRV of *LineTerminatorSequence* :: `<CR>`*&lt* is the sequence consisting of the code unit 0x000A (LINE FEED).

I believe this should be

> The TRV of *LineTerminatorSequence* :: `<CR>` `<LF>` is the sequence consisting of the code unit 0x000A (LINE FEED).

**Comment by allenwb** [comment]
The corresponding line in the ES6 spec is:

> The TRV of LineTerminatorSequence :: \<CR>\<LF> is the sequence consisting of the code unit value 0x000A.

**Comment by jmdyck** [comment]
The source is fine, so I've labelled this a rendering bug.

**Comment by bterlson** [comment]
Filed here: https://github.com/rbuckton/grammarkdown/issues/30.
