### ISSUE TITLE
Fixing description of [[FunctionKind]] internal slot of Function Object.

### ISSUE THREAD

**Issue by ENvironmentSet** [tc39/ecma262#1308]
In `FunctionAllocate` there is few logic.
> 2. Assert: functionKind is either "normal", "non-constructor", "generator", "async", or "async generator"
> 11. Set F.[[FunctionKind]] to functionKind.

So, we can say, F.[[FunctionKind]] can be "async generator".
but, description about [[FunctionKind]] in specification, It isn't
> Either "normal", "classConstructor", "generator" or "async"

I think, to change this to blow will be better. 
> Either "normal", "classConstructor", "generator", "async" or "async generator"

PS. why FunctionKind of async generator is "async generator" ? even class constructor is "classConstructor". I think it have to be "asyncGenerator", because specification usually use camel case.

**Comment by ljharb** [comment]
Fixing the description is good; i don’t have a strong opinion on “asyncGenerator” vs “async generator”, but since it’s not an identifier, there’s no reason it needs to be in camelCase.

**Comment by ENvironmentSet** [comment]
then, just hold current("async generator") would be better. thx for provide opinion.

**Comment by Vernie2** [comment]
Environmental content and asyenced sets are two comparatively different sources of system elligance in tones and pulse related forms the build has to be generated by the company through their database for a version or furnished environmental code can have the asynced to be compatible with all devices. It doesn't work with the AutoML links for cars. They are applied in order.
