### ISSUE TITLE
Problem with the supplemental syntax in section 12.3

### ISSUE THREAD

**Issue by kwesibrunee** [tc39/ecma262#1315]
The supplemental Syntax listed in 12.3 for CallMemberExpression is actually the same as CoverCallExpressionAndAsyncArrowHead.  What is the purpose of a supplemental syntax if it is the same as the original syntax.

CallMemberExpression[Yield, Await]:
 &nbsp;&nbsp;  MemberExpression[?Yield, ?Await]&nbsp;&nbsp; Arguments[?Yield, ?Await]

CoverCallExpressionAndAsyncArrowHead[Yield, Await]:
&nbsp;&nbsp; MemberExpression[?Yield, ?Await]&nbsp;&nbsp; Arguments[?Yield, ?Await]

I believe that CallMemberExpression should actually be:

CallMemberExpression[Yield, Await]:
&nbsp;&nbsp; MemberExpression[?Yield, ?Await] 

with the mandatory Arguments there it does not match `new a()` and only matches `new a()()` if the mandatory Arguments is removed, it matches both `new a()` and `new a()()` appropriately

**Comment by jmdyck** [comment]
`new a()` is a `NewExpression`, specifically a `MemberExpression`. There's no reason that `CallMemberExpression` should match it. And if you change the grammar so that `CallMemberExpression` *does* match it, then you've just made the grammar ambiguous. (`LeftHandSideExpression` would match any `MemberExpression` in two different ways.)

**Comment by kwesibrunee** [comment]
per the ES2019 grammar, 
new&nbsp;&nbsp;MemberExpression[?Yield, ?Await]&nbsp;&nbsp;Arguments[?Yield, ?Await] is part of Member Expression, which in turn is part of NewExpression. There is nothing that I see in the spec that precludes CallMemberExpression from matching `new a()`  CallMemberExpression directly calls MemberExpression as its first non-terminal. If CallMemberExpression should not match MemberExpression, I don't see any reference to it in the spec. 

for reference:

MemberExpression[Yield, Await]:
&nbsp;&nbsp;PrimaryExpression[?Yield, ?Await]
&nbsp;&nbsp;MemberExpression[?Yield, ?Await]&nbsp;&nbsp;[Expression[+In, ?Yield, ?Await]]
&nbsp;&nbsp;MemberExpression[?Yield, ?Await]&nbsp;&nbsp;.&nbsp;&nbsp;IdentifierName
&nbsp;&nbsp;MemberExpression[?Yield, ?Await]&nbsp;&nbsp;TemplateLiteral[?Yield, ?Await, +Tagged]
&nbsp;&nbsp;SuperProperty[?Yield, ?Await]
&nbsp;&nbsp;MetaProperty
&nbsp;&nbsp;new&nbsp;&nbsp;MemberExpression[?Yield, ?Await]&nbsp;&nbsp;Arguments[?Yield, ?Await]

NewExpression[Yield, Await]:
&nbsp;&nbsp;MemberExpression[?Yield, ?Await]
&nbsp;&nbsp;new&nbsp;&nbsp;NewExpression[?Yield, ?Await]

**Comment by jmdyck** [comment]
>  There is nothing that I see in the spec that precludes `CallMemberExpression` from matching `new a()`.

(You said yourself in the original post that `CallMemberExpression` does not match `new a()`, so I'm not clear on what you're saying.)

Anyhow, the grammar precludes it. Ignoring grammatical parameters (which are not pertinent to this discussion), we have
```
 CallMemberExpression: MemberExpression Arguments
```

If you try to make `CallMemberExpression` match `new a()`, it's clear that `()` would match `Arguments`, so then you would have to make `new a` match `MemberExpression`, but this can't be done.

**Comment by kwesibrunee** [comment]
I found my issue, sorry for the confusion, I had accidentally shortened the following production

NewExpression[Yield, Await]:
  MemberExpression[?Yield, ?Await]
  new  NewExpression[?Yield, ?Await]

to

NewExpression[Yield, Await]:
  new opt  MemberExpression[?Yield, ?Await]

which caused the strange behavior, thanks for helping me find my issue, you were very helpful.
