### ISSUE TITLE
ES7 "do expression" proposal is not listed in README

### ISSUE THREAD

**Issue by simevidas** [tc39/ecma262#132]
Chromium (V8) has implemented "do expression" parsing: https://chromium.googlesource.com/v8/v8/+/b6596aa73b069aaa6e52291c3756b0e0f0e483b6

I would like to read about this ES7 proposal, but I can’t find anything on the Web (ecmascript.org seems to be down). Is there a GitHub repo for this feature? If so, could you add it to the “Current proposals” table?

**Comment by zloirock** [comment]
@simevidas it's [stage 0 proposal](https://github.com/tc39/ecma262/blob/master/stage0.md).

**Comment by simevidas** [comment]
@zloirock Thanks! It links to ecmascript.org which is currently down. I’ll wait.

**Comment by ljharb** [comment]
@rossberg-chromium perhaps you could put the proposal up on a github repo and PR it into the stage 0 proposals list?

**Comment by rossberg-chromium** [comment]
Can do.

**Comment by forivall** [comment]
I'm finding more and more that I have to invoke web.archive.org for ecmascript.org: http://web.archive.org/http://wiki.ecmascript.org/doku.php?id=strawman:do_expressions

**Comment by jkrems** [comment]
For other people stumbling over this issue (it's doing well on Google): Looks like the latest version is the [stage 1 proposal](https://gist.github.com/dherman/1c97dfb25179fa34a41b5fff040f9879) that's also properly linked in the proposals repo.

**Comment by simevidas** [comment]
@jkrems The official repo is https://github.com/tc39/proposal-do-expressions

**Comment by ljharb** [comment]
Updated the proposals list.

**Comment by littledan** [comment]
I don't remember getting a chance to cover @dherman's proposal in committee yet; IIRC the last time it was discussed in committee was before ES6 was released. I'm not sure how much it makes sense to have it in the proposals repository in this form (since many other things which haven't been presented to the committee are left off).

**Comment by ljharb** [comment]
@littledan it was brought to stage 1 in January of this year: https://github.com/rwaldron/tc39-notes/blob/3eb7d06f12559c95bf674f75d955d2bd14380b28/es7/2017-01/jan-26.md

**Comment by littledan** [comment]
Oh that's right, sorry for my bad memory here.
