### ISSUE TITLE
Proposal: add Array.prototype.remove

### ISSUE THREAD

**Issue by jolleekin** [tc39/ecma262#1322]
Surprisingly, `Array` has always lacked a method to remove an item. To remove an item, one has to use `indexOf` (or `lastIndexOf`) and `splice`, which is very inconvenient. It would be nice if the following method (written in TypeScript here) could be added to `Array`.
``` ts
class Array<E> {
    /**
     * Removes the first occurrence of [item] from this array.
     * 
     * Returns `true` if [item] was in this array and `false` otherwise.
     */
    remove(item: E): boolean {
        const i = this.indexOf(item);
        if (i >= 0) {
            this.splice(i, 1);
            return true;
        }
        return false;
    }
}
```

**Comment by ljharb** [comment]
Please see https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#new-feature-proposals for how best to suggest new features.

(As an aside, `.filter` seems like a much better non-mutating approach here than two O(n) operations)
