### ISSUE TITLE
Normative: Array.prototype.pluck

### ISSUE THREAD

**Issue by tm2josep** [tc39/ecma262#1324]
Note: I only have about a 1.5 years of professional dev experience, and am not well versed in how this sort of thing goes. Please be patient with me.

Assume we have an array of objects that are of the same schema (for lack of a better term), and wish to quickly fetch values on certain keys, pluck would allow us to do so. 

Example data:

``` javascript
let arrOfObjs = [
    {
        firstName: 'John',
        lastName: 'Smith',
        cellNum: '(441)-1**-****'
    },
    {
        firstName: 'Foo',
        lastName: 'Bar',
        cellNum: '(144)-1**-****'
    },
    {
        firstName: 'Sarah',
        lastName: 'Smith',
        cellNum: '(251)-1**-****'
    },
] ;
```

Previous solution:

``` javascript
let firstNames = arrOfObjs.map( function (obj) { return obj.firstName} )

console.log(firstNames); // ['John', 'Foo', 'Sarah']
```

New solution (with Array.prototype.pluck):

``` javascript
let firstNames = arrOfObjs.pluck('firstName');

console.log(firstNames); // ['John', 'Foo', 'Sarah']
```

We could also make this variadic, plucking only the values we need. Although this could be done with destructing in Array.prototype.map, I think it would be convenient to have pluck instead. 

``` javascript
let justNames = arrOfObjs.pluck('firstName', 'lastName');

console.log(justNames);
/*
[
    {
        firstName: 'John',
        lastName: 'Smith',
    },
    {
        firstName: 'Foo',
        lastName: 'Bar',
    },
    {
        firstName: 'Sarah',
        lastName: 'Smith',
    },
] 
*/
```

Also, php supports this in the form of array_column, but it's not variadic.

**Comment by annevk** [comment]
This isn't the place to propose features, see https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#new-feature-proposals.

**Comment by tm2josep** [comment]
Ah okay, thanks! Also, at the risk of sounding like a total noob, do you think this is worth going through the process?

**Comment by annevk** [comment]
Given that you can also write your example as `arr.map(obj => obj.firstName)` if I'm not mistaken, I somewhat doubt it folks will be convinced it's worth adding another method for, but who knows. Asking on the mailing list or IRC will give you an idea.

**Comment by littledan** [comment]
In addition to CONTRIBUTING.md, I'd recommend starting with making a library which does this, and gathering broad developer feedback, before proposing for standardization.

**Comment by mathiasbynens** [comment]
Note that Lodash used to have `_.pluck`, but later [removed](https://github.com/lodash/lodash/wiki/Changelog#v400) in favor of `_.map` with iteratee shorthand analogous to @annevk's counter-example.
