### ISSUE TITLE
Productions involving character abbreviations are rendered incorrectly

### ISSUE THREAD

**Issue by gibson042** [tc39/ecma262#1334]
Sometime after the 2017 edition was released, ecmarkup of alternative right-hand sides involving `<…>` abbreviations (e.g., `<NBSP>`) was broken in such a way that the resulting productions are incorrect when interpreted as documented ("_One or more alternative right-hand sides for the nonterminal then follow on succeeding lines_").

ES2017:
> <emu-nt><a href="http://ecma-international.org/ecma-262/8.0/#prod-LineTerminatorSequence">LineTerminatorSequence</a></emu-nt><emu-geq>::</emu-geq>
    <emu-rhs a="7b39d525"><emu-gprose>&lt;LF&gt;</emu-gprose></emu-rhs>
    <emu-rhs a="1e22ed49"><emu-gprose>&lt;CR&gt;</emu-gprose><emu-gann>[lookahead ≠ <emu-gprose>&lt;LF&gt;</emu-gprose>]</emu-gann></emu-rhs>
    <emu-rhs a="10022ab3"><emu-gprose>&lt;LS&gt;</emu-gprose></emu-rhs>
    <emu-rhs a="cfc875d1"><emu-gprose>&lt;PS&gt;</emu-gprose></emu-rhs>
    <emu-rhs a="2da252ec"><emu-gprose>&lt;CR&gt;</emu-gprose><emu-gprose>&lt;LF&gt;</emu-gprose></emu-rhs>

ES2018:
> <emu-nt><a href="http://ecma-international.org/ecma-262/9.0/#prod-LineTerminatorSequence">LineTerminatorSequence</a></emu-nt><emu-geq>::</emu-geq>
    <emu-rhs a="fd2fb3b0"><emu-gprose>&lt;LF&gt; </emu-gprose><emu-gprose>&lt;CR&gt; </emu-gprose><emu-gann>[lookahead ≠ <emu-gprose>&lt;LF&gt; </emu-gprose>]</emu-gann></emu-rhs>
    <emu-rhs a="735c7d95"><emu-gprose>&lt;LS&gt; </emu-gprose><emu-gprose>&lt;PS&gt; </emu-gprose><emu-gprose>&lt;CR&gt; </emu-gprose><emu-gprose>&lt;LF&gt;</emu-gprose></emu-rhs>

git master:
> <emu-nt><a href="https://tc39.github.io/ecma262/#prod-LineTerminatorSequence">LineTerminatorSequence</a></emu-nt><emu-geq>::</emu-geq>
    <emu-rhs a="fd2fb3b0"><emu-gprose>&lt;LF&gt; </emu-gprose><emu-gprose>&lt;CR&gt; </emu-gprose><emu-gann>[lookahead ≠ <emu-gprose>&lt;LF&gt; </emu-gprose>]</emu-gann></emu-rhs>
    <emu-rhs a="735c7d95"><emu-gprose>&lt;LS&gt; </emu-gprose><emu-gprose>&lt;PS&gt; </emu-gprose><emu-gprose>&lt;CR&gt; </emu-gprose><emu-gprose>&lt;LF&gt;</emu-gprose></emu-rhs>

**Comment by NilSet** [comment]
This is now fixed.
