### ISSUE TITLE
Permits importing "module-name" which doesn't start with `/` or `.`

### ISSUE THREAD

**Issue by CarterLi** [tc39/ecma262#1338]
More and more packages are using es2015 module, but few of them write `import module from '/node_modules/package/index.js'.

[Node module resolution](https://nodejs.org/api/modules.html#modules_all_together) is supported for long time and AFAIK all popular [bundle](https://webpack.js.org/) [tools](https://rollupjs.org/guide/en) support it. Third-party packages are assuming that they are used in an environment supporting NMR, which generally prevents those packages being used in browser easily.

Permiting importing "module-name" which doesn't start with `/` or `.` has following advantages:

1. get rid of the ugly `/node_modules`
1. be compatible with existing third-party libraries ( MOST IMPORTANT )
1. be compatible with existing tools. Notice that `/node_modules` doesn't refer to the root path of your project, but the root path of your file system.
1. enable path alias. No one likes `../../../../abc` instead of `@/abc`

Existing behavior does have a solution that rewrites all imports using NMR into relative paths. I don't know if such tool exists but with suggested behavior, a simple `require.resolve(request.path)` at server side can handle most cases.

I know the motivation of existing behavior is for future builtin native modules. But it can have [other solutions](https://github.com/tc39/ecma262/issues/395)

Sorry for my bad English. Any comments are welcome.

**Comment by devsnek** [comment]
ecma262 doesn't specify how runtimes resolve imports. your issue would be better suited for https://github.com/nodejs/node/

**Comment by CarterLi** [comment]
> ecma262 doesn't specify how runtimes resolve imports. your issue would be better suited for https://github.com/nodejs/node/

Really? I got `Uncaught TypeError: Failed to resolve module specifier "@angular/core". Relative references must start with either "/", "./", or "../".`

**Comment by devsnek** [comment]
@CarterLi whatever tool you're using, you should report that with them, not here. That error isn't part of ecma262.

**Comment by CarterLi** [comment]
> @CarterLi whatever tool you're using, you should report that with them, not here. That error isn't part of ecma262.

But I got such errors in all major browsers (Chrome, Firefox and Safari)

![image](https://user-images.githubusercontent.com/6134068/47611261-c1719580-da9c-11e8-8ff1-b3332725ec60.png)

Do you mean that it's implementation forbids such usage, not ecma262 standard?

**Comment by devsnek** [comment]
@CarterLi 

> Do you mean that it's browser implementation that forbids such usage, not ecma262 standard? But why?

Yes. browsers don't have npm. they can just import other modules by url.

**Comment by CarterLi** [comment]
That's sad. Thanks for your explanation.

**Comment by robpalme** [comment]
@CarterLi the consistent browser behaviour you are describing is defined in the Html spec.

https://html.spec.whatwg.org/#integration-with-the-javascript-module-system

A proposed solution to this problem is Package Name Maps which is being worked on here:

https://github.com/domenic/package-name-maps
