### ISSUE TITLE
Editorial: statically enforcing regex grammar for literals

### ISSUE THREAD

**Issue by bakkot** [tc39/ecma262#1343]
The grammar for regular expressions is pretty weird, in that there is a [very liberal grammar](https://tc39.github.io/ecma262/#sec-literals-regular-expression-literals) which is later [refined](https://tc39.github.io/ecma262/#sec-patterns). The intent of this, at least as I understand, test262 tests, and engines implement, is that the more conservative grammar is enforced statically.

As far as I can tell, that's done in [12.2.8.1](https://tc39.github.io/ecma262/#sec-primary-expression-regular-expression-literals-static-semantics-early-errors):

> It is a Syntax Error if BodyText of RegularExpressionLiteral cannot be recognized using the goal symbol Pattern of the ECMAScript RegExp grammar specified in [21.2.1](https://tc39.github.io/ecma262/#sec-patterns).

But this has a couple of problems: in particular, "the goal symbol Pattern" does not refer to a particular thing, because the Pattern goal symbol has parameters. And nothing in this rule refers to the regex's flags, which means that I don't think it would forbid `/\a/u` statically, though all engines ([except V8](https://bugs.chromium.org/p/v8/issues/detail?id=896)) reject it.

This is even more complicated because of the behavior of the named groups `\k`, which is responsible for the `N` flag on the Pattern grammar. The [runtime semantics](https://tc39.github.io/ecma262/#sec-regexpinitialize) which make for example `/\k<>(?<a>)/` an error live in RegExpInitialize, and are pretty complicated:

> Parse P using the grammars in [21.2.1](https://tc39.github.io/ecma262/#sec-patterns) and interpreting each of its 16-bit elements as a Unicode BMP code point. UTF-16 decoding is not applied to the elements. The goal symbol for the parse is Pattern[~U, ~N]. If the result of parsing contains a GroupName, reparse with the goal symbol Pattern[~U, +N] and use this result instead. Throw a SyntaxError exception if P did not conform to the grammar, if any elements of P were not matched by the parse, or if any Early Error conditions exist.

I think the rules in the runtime semantics (specifically, steps 6, 7/a, and 8/a) need to be essentially copied to the static semantics. That solves all three problems above:

- The ambiguous reference to "the goal symbol Pattern" is removed, because the flags are always explicitly specified.
- The unicode flag is properly taken into consideration.
- The reparse-if-named-group behavior is enforced.

On IRC, @jmdyck points out that the problematic static semantics text predates the addition of parameters to the Pattern grammar, so this is probably just an editorial oversight as the grammar became more complicated.

See also #1050.

**Comment by waldemarhorwat** [comment]
> The intent of this, at least as I understand, test262 tests, and engines implement, is that the more conservative grammar is enforced statically.

Correct. I wrote it this way in ES3 because the interpretation of the regexp pattern depended on the flags, but you couldn't get to the flags until you skipped past the pattern.

> But this has a couple of problems: in particular, "the goal symbol Pattern" does not refer to a particular thing, because the Pattern goal symbol has parameters.

That's a bug that was introduced at the point when the parameter was added. It should choose the Unicode mode depending on the flags.

**Comment by jmdyck** [comment]
>On IRC,  @jmdyck points out that the problematic static semantics text predates the addition of parameters to the Pattern grammar

Not "predates", but "coincides with", as Waldemar indicates above.

**Comment by ljharb** [comment]
It seems like some of the action items here are:
 - fix the [bug](https://github.com/tc39/ecma262/issues/1343#issuecomment-436412530) :choose the Unicode mode depending on the flags."
 - possibly change the grammar? but the thread above implies not.

@bakkot, thoughts?

**Comment by bakkot** [comment]
@ljharb It's no longer sufficient to just choose the `U` flag on the parse goal appropriately, because you also have to get the `N` flag right so that `/\k<>(?<a>)/` is an Early Error. And that involves some logic, because the process for determining the `N` flag involves a "if that didn't work, reparse" step.

I think my preferred solution would be to introduce a new Abstract Operation, `IsValidRegularExpressionLiteral`, along the lines of

```
Static Semantics: IsValidRegularExpressionLiteral ( literal )

1. Assert: _literal_ is a RegularExpressionLiteral.
1. If FlagText of _literal_ contains any code points other than "g", "i",  "m", "s", "u", or "y", or if it contains the same code point more than once, return false.
1. Let _P_ be BodyText of _literal_.
1. If FlagText of _literal_ contains "u",
  1. If _P_ cannot be recognized using the goal symbol Pattern[+U, +N] of the ECMAScript RegExp grammar specified in 21.2.1, return false.
  1. Otherwise, return true.
1. Parse _P_ using the grammars in 21.2.1. The goal symbol for the parse is Pattern[~U, ~N]. If the result of parsing contains a GroupName, reparse with the goal symbol Pattern[~U, +N] and use this result instead. If _P_ did not conform to the grammar, if any elements of _P_ were not matched by the parse, or if any Early Error conditions exist, return false. Otherwise, return true.
```

and then replace the Early Error conditions for `PrimaryExpression : RegularExpressionLiteral` with `It is a Syntax Error if IsValidRegularExpressionLiteral ( RegularExpressionLiteral ) is false.`

This is heavily duplicated with the runtime semantics for RegExpInitialize, but that looks somewhat tricky to avoid.

**Comment by ljharb** [comment]
That seems reasonable to me; @waldemarhorwat, do you think a PR making that change is a tenable path forward?

**Comment by waldemarhorwat** [comment]
Yes, this seems like a reasonable way forward. It would be nice to share the algorithm between the static assertion and 21.2.3.2.2, but the latter also has some side effects such as patternCharacters which may make this too awkward.
