### ISSUE TITLE
Incorrect JSON.stringify description

### ISSUE THREAD

**Issue by ahungry** [tc39/ecma262#1344]
https://tc39.github.io/ecma262/#sec-json.stringify

    The stringify function returns a String in UTF-16 encoded JSON format representing an ECMAScript value. 

This needs to read as: "The stringify function *may* return a String in UTF-16 encoded JSON format representing an ECMAScript value. "

If you call it as such:

JSON.stringify(undefined)

The resultant value is *NOT* of type string, and therefore cannot be a string representation of a JSON object.

The simple test case is that: JSON.parse(JSON.stringify(undefined)) should throw an exception on unencodable data eagerly (at the stringify step), not at the later parse step - otherwise, every call to JSON.stringify has to type check the resultant value when the input is non deterministic at run time.

**Comment by ljharb** [comment]
I'd probably say "The stringify function returns a String in UTF-16 encoded JSON format representing an ECMAScript value, or `undefined`."

Either way, want to make a PR?

**Comment by ahungry** [comment]
Sure!  I'll put one in this evening.
