### ISSUE TITLE
Wonky evaluation order for SuperCall

### ISSUE THREAD

**Issue by bakkot** [tc39/ecma262#1351]
```js
console.log(0);
new null(console.log(1))
```
prints both 0 and 1 before throwing, but

```js
class A extends (class {}) {
  constructor() {
    console.log(0);
    super(console.log(1));
  }
}
Object.setPrototypeOf(A, null);

new A;
```
prints only 0 (because the semantics of `SuperCall` are to perform [`GetSuperConstructor`](https://tc39.github.io/ecma262/#sec-getsuperconstructor) before `ArgumentListEvaluation`, and `GetSuperConstructor` throws if it results in a non-constructor). That's kinda weird.

See also #1175 (cc @jridgewell).

**Comment by jridgewell** [comment]
I think the more pertinent example is:

```js
null(console.log(0))
```

which logs 0 then throws.

**Comment by ljharb** [comment]
What are the next steps here? Should a Needs Consensus PR be pursued?

**Comment by jridgewell** [comment]
Yah, just a needs consensus is all that's needed. The super property evaluation order one took ~5min in committee to agree on.

**Comment by ljharb** [comment]
Any volunteers? :-)
