### ISSUE TITLE
Add new Symbol for async/await

### ISSUE THREAD

**Issue by clitetailor** [tc39/ecma262#1359]
Async/await helps a lot in solving callback hell. But it does not solve every problem with callback hell but problems that deal with concurrency or Promise only. So the ideal is to provide a new async/await Symbol that accept other typeclasses than Promise.

Example with Array:

```js
class Array {
  [Symbol.await](callback) {
    return this.map(callback)
  }
}

async function increaseEachItemByOne(arr)
  const item = await arr
  return item + 1
}

const newArr = increaseEachItemByOne([1, 2, 3, 4])
```

Example with RxJS:

```js
class Observable {
  [Symbol.await](callback) {
    return this.pipe(
      rxjs.operators.map(callback)
    )
  }
}

async function reactive(state$, action$, api) {
  const state = await switchMap(state$)
  const action = await mergeMap(click$)
  const response = await postData(api, state + action)
  return reponse.data
}

const state$ = new BehaviorSubject(1)
const click$ = Observable.from(button, 'click')

const data$ = reactive(state$, click$, '/api')
```

**Comment by ljharb** [comment]
Hi! Please see https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal for how to suggest new features to the language; rather than filing them on this repo. Thanks!
