### ISSUE TITLE
Suggestion: Multiple arity bitwise operator 

### ISSUE THREAD

**Issue by alineDiesel** [tc39/ecma262#1364]
This suggestion was elaborated with @naomijub

Due to heavy bitwise operations in our code we would like some solution as LISPs like Clojure implements to bitwise operators. This would reduce boilerplate code and increase legibility. An example of this proposal is:

```javascript
const myConst = 10;

return (myConst !== 3 &&  myConst === 10) || (typeof(myConst) !== 'number' && myConst === 'word') 
```
Suggestions:

1.
```javascript
const myConst = 10;

return myConst (&& (!==3, ===10)) || (&& (=== 'word', typeof() !=== 'number')) 
```

2. 
```javascript
const myConst = 10;

return myConst.or(and(!3, 10), and('word', typeof !'number')))
```

=P

**Comment by ljharb** [comment]
Thanks for the suggestion! Please see https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal which describes the process of making new proposals.
