### ISSUE TITLE
Proposal idea (hoping for feedback)

### ISSUE THREAD

**Issue by harrysolovay** [tc39/ecma262#1371]
If this isn't the right forum for proposal idea discussion, please let me know where I should repost this.

It would be great to be able to simplify turning function calls into uncalled form.

This:

```js
() => console.log('Hello TC39')
```

... could become this:

```js
~console.log('Hello TC39')
```

... or could use another character if anyone thinks of something more suitable :)

It's a simple change, but one that I think reduces complexity; it doesn't make much sense that––in order to "uncall" a function, that you need to place it within a new function. Plus, something like this reduces code-size 👍

**Comment by ljharb** [comment]
Thanks for your thoughts! Please see https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#new-feature-proposals for the best places to discuss proposal ideas.

**Comment by harrysolovay** [comment]
@ljharb thank you!
