### ISSUE TITLE
Add method on Function.prototype that allows `this` to be bound later

### ISSUE THREAD

**Issue by ORESoftware** [tc39/ecma262#1385]
Right now when we use `Function.prototype.bind`, we have to choose the value for `this` at the time this call is made.

I always have been looking for a way to omit the `this` parameter, for example here we have a fictitious `Function.prototype.create`:

```js

const foo = function () {
  const args = Array.from(arguments);
  const lastArg = args.pop();
  return lastArg.apply(this, args);
};

Function.prototype.create = function () {     //  NEW METHOD on Function.prototype
  const fn = this;
  const values = Array.from(arguments);
  return function () {
    return fn.call(this, ...values, ...arguments);
  };
};

const created = foo.create(1, 2, 3);

created.call('B', 4, function () {
  console.log('this is:', this);
  console.log(arguments);
});
```

The function that gets created using the create method, can be called with a different value for `this`, which makes it more versatile. If user does want to bind `this` they can obviously use the already existing `Function.prototype.bind` instead.

**Comment by zloirock** [comment]
I love this way of partial application, by it's not a correct place for proposals. See [CONTRIBUTING.md](https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#new-feature-proposals).

**Comment by ORESoftware** [comment]
@zloirock not trying to be snarky but I looked at that and the link to contribute was to this issue tracker isn't it?

**Comment by devsnek** [comment]
@ORESoftware issues/prs are for editorial changes or normative bug fixes. adding features to the language should follow this: https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#new-feature-proposals

**Comment by ORESoftware** [comment]
@zloirock @devsnek  sorry I don't understand, that document here says:

https://tc39.github.io/process-document/

> Input into the process
> Ideas for evolving the ECMAScript language are accepted in any form. Any discussion, idea or proposal for a change or addition which has not been submitted as a formal proposal is considered to be a “strawman” (stage 0) and has no acceptance requirements. Such submissions must either come from members of TC39 or from non-members who have registered via Ecma International.

so what should I do instead of filing an issue here? I don't know

**Comment by devsnek** [comment]
@ORESoftware https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal

**Comment by ORESoftware** [comment]
@devsnek thanks alright, I sent an email out on the email list, and I linked this issue in the email, hope that's ok, thx

**Comment by ljharb** [comment]
Closing; per the contributing document.
