### ISSUE TITLE
Annex B.3.5: Should we stop making for-of a special case?

### ISSUE THREAD

**Issue by rkirsling** [tc39/ecma262#1392]
[Annex B.3.5](https://tc39.github.io/ecma262/#sec-variablestatements-in-catch-blocks), **VariableStatements in Catch Blocks**, says:
> It is a Syntax Error if any element of the BoundNames of CatchParameter also occurs in the VarDeclaredNames of Block unless CatchParameter is CatchParameter : BindingIdentifier and that element is only bound by a VariableStatement, the VariableDeclarationList of a for statement, the ForBinding of a for-in statement, or the BindingIdentifier of a for-in statement.

That is, we allow var-redeclaration of a non-destructured catch parameter...
```js
try {} catch (e) { var e; }
```
...except in the particular case where the var declaration is a for-of initializer.
```js
try {} catch (e) { for (var e of whatever) {} }
```
(_Note that this behavior applies equally to sloppy and strict modes._)

Based on some earlier discussion I see in #150, it seems like the motivation here was to prohibit as much as possible without jeopardizing web compatibility. Still, if the for-of case is neither easy to remember nor trivial to implement, I wonder whether it provides concrete benefit to anyone. Should we simplify it away?

-----

Current status in the major engines:
- [V8](https://github.com/v8/v8/blob/64c85cf403fe19a38c452b07b080368756bb079c/src/parsing/parser.cc#L1914-L1920) and [SpiderMonkey](https://hg.mozilla.org/mozilla-central/file/aac6849c6ff0/js/src/frontend/ParseContext.cpp#l461) fully implement Annex B.3.5 and have special codepaths for the for-of case
- [JSC](https://github.com/WebKit/webkit/blob/8b7a022d2061c6b306b9ed3204df37b8f1ede31c/Source/JavaScriptCore/parser/Parser.h#L1232-L1233) implements everything but the for-of case, for which it has a `FIXME` (and a [bug](https://bugs.webkit.org/show_bug.cgi?id=192830))
- ChakraCore allows any var-redeclaration of a catch parameter, destructured or otherwise

**Comment by ljharb** [comment]
It seems exceedingly odd to me that:
```js
function f(e) { for (var e of whatever) { } }
```
works but
```js
try {} catch (e) { for (var e of whatever) {} }
```
errors.

**Comment by rkirsling** [comment]
Made a concrete proposal in #1393. 

(_Note: There's no test for the existing behavior, but we'd surely want to add one [here](https://github.com/tc39/test262/tree/master/test//annexB/language/statements/try)._)

**Comment by littledan** [comment]
This was pretty complicated to implement in V8, and came later than other parts of lexical scoping. Does anyone know the motivation? cc @allenwb @waldemarhorwat

**Comment by anba** [comment]
The relevant [bug report](https://tc39.github.io/archives/bugzilla/2608/) and [meeting notes](https://github.com/rwaldron/tc39-notes/blob/master/es6/2014-04/apr-8.md#var-hoisting-and-catch-parameters) also don't mention why `for-of` was excluded. (Maybe only the web-compatibility necessary exclusion was considered to be necessary at the point in time?)

**Comment by allenwb** [comment]
@syg Yes! That is correct.  During ES6 development there was general consensus within TC39 that "undesirable" Annex B behaviors would not be added to new features.
