### ISSUE TITLE
Add reflection support for all accessible enumerable keys

### ISSUE THREAD

**Issue by rdking** [tc39/ecma262#1400]
ES has a long standing history of having reflection functions on Object that do not take into account the prototype chain of the target object. Due to the increasing reliance on inheritance mechanisms, it would be beneficial if Object gained a new set of reflection functions that take the prototype chain to account.

Currently, the need for something like this is partially filled by libraries like lodash. I am requesting that such functions be added directly to the language. I have created [this proposal](https://github.com/rdking/proposal-known-keys) for use as a potential starting point.

**Comment by ljharb** [comment]
Per [CONTRIBUTING.md](https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal) this repo isn’t the right place to make feature suggestions.
