### ISSUE TITLE
In algorithms, change confusing ”Else foo” into ”Else, Assert: foo”

### ISSUE THREAD

**Issue by claudepache** [tc39/ecma262#1419]
In the spec, there’s a bunch of instances of:

> 1. Else _x_ is "bar",
>     1. ...

This is confusing, because ”_x_ is "bar"” is an assertion without the word ”assert”, and it can be confused with an assignment without the word ”let”, as it did happen in https://github.com/tc39/proposal-regexp-lookbehind/pull/7#discussion_r151567046.

I suggest to replace it systematically with:

> 1. Else,
>     1. Assert: _x_ is "bar".
>     1. ...

**Comment by jmdyck** [comment]
(See [this commit](https://github.com/tc39/ecma262/pull/1413/commits/a02031813c9e80903c8d3f2beb68f1b1852eff3c) in PR 1413 for some discussion about these else-assertions.)

**Comment by ljharb** [comment]
Does #1413 close this?

**Comment by jmdyck** [comment]
No, #1413 eliminates a particular subset of these.
