### ISSUE TITLE
Why aren't `Math.ceil` and `Math.floor` specified in terms of the spec's mathematical operations

### ISSUE THREAD

**Issue by isiahmeadows** [tc39/ecma262#1422]
In the [mathematical operations part of the spec](https://tc39.github.io/ecma262/#sec-mathematical-operations), there's a reference to a `floor` function, specified in terms of subtraction and `modulo` in its note. There is no corresponding `ceil` function, but it could be similarly specified as `ceil(x) = -floor(-x)`.

Is there a reason these aren't used for `Math.ceil` and `Math.floor`? Similarly, is there a reason why `max` and `min` aren't used for `Math.max` or `Math.min`, respectively?

**Comment by ljharb** [comment]
`floor` is used in a number of places; where would we use this operation if defined?

**Comment by isiahmeadows** [comment]
I forgot to re-add a couple key details when I filed the bug. Fixed.

**Comment by isiahmeadows** [comment]
I think the `Math.*` algorithms could all use a little bit of cleanup because most non-implementation-defined algorithms are defined in prose, but they could be better and more clearly and precisely defined using algorithms.

- Ones with algorithm-based definitions:
	- `Math.clz32`
	- `Math.fround`
	- `Math.imul`
	- `Math.pow`, in terms of the implementation-defined `**` operator

- Ones that *should* have algorithm-based definitions:
	- `Math.abs`, in terms of the `abs` function specified in the spec
	- `Math.ceil`, in terms of the `ceil` function specified the initial comment
	- `Math.floor`, in terms of the `floor` function specified in the spec
	- `Math.max`, in terms of the `max` function specified in the spec
	- `Math.min`, in terms of the `min` function specified in the spec
	- `Math.round`, through explicit comparisons
	- `Math.sign`, through explicit comparisons
	- `Math.trunc`, through explicit comparisons

**Comment by isiahmeadows** [comment]
I'm not touching things like `Math.sin` or `Math.log1p`, though: that's obviously implementation-defined stuff, and it's just easier to specify in prose with a few constraints.

**Comment by ljharb** [comment]
These seem like reasonable editorial PRs to me.

**Comment by bakkot** [comment]
The Math operations are specified using algorithms as of https://github.com/tc39/ecma262/pull/2122, as suggested above. `ceil` and `floor` still bottom out in prose rather than the `ceil` and `floor` operations, but I don't think it would be an improvement to convert them, since as @waldemarhorwat says above they operate on different domains: using them would require converting to reals and back, which I think is unnecessary overhead.

As such I'm closing this, but feel free to reopen if you think there's still something to be done here.
