### ISSUE TITLE
Missing coverage in static semantics definition

### ISSUE THREAD

**Issue by adrianheine** [tc39/ecma262#1424]
[The conventions for Static Semantics](https://tc39.github.io/ecma262/#sec-static-semantic-rules) state that
> a production that has multiple alternative definitions will typically have for each alternative a distinct algorithm for each applicable named static semantic rule

What does »typically« mean? What are the semantics of missing static semantics?

I noticed that [the `AssignmentTargetType` definition for `PrimaryExpression`](https://tc39.github.io/ecma262/#sec-semantics-static-semantics-assignmenttargettype) does not cover ` PrimaryExpression: IdentifierReference`. Is that a simple (if old) oversight?

**Comment by jmdyck** [comment]
"Typically" means that it's good as a first approximation to the truth, but you shouldn't expect that it will always be true.

Re your particular example, `PrimaryExpression: IdentifierReference` is (what the spec calls) a "chain production" (see [Context-Free Grammars](https://tc39.github.io/ecma262/#sec-context-free-grammars)), and so is subject to the [rule](https://tc39.github.io/ecma262/#sec-algorithm-conventions-syntax-directed-operations) about implicit definitions for syntax-directed operations for chain productions. In this case, the implicit rule chains to the [explicit rules](https://tc39.github.io/ecma262/#sec-identifiers-static-semantics-assignmenttargettype) for `AssignmentTargetType` for `IdentifierReference`.

**Comment by adrianheine** [comment]
Thanks!
