### ISSUE TITLE
Proposal: synchronous response from web workers

### ISSUE THREAD

**Issue by dawidgarus** [tc39/ecma262#1428]
Right now communication with web workers is purely asynchronous and this makes them unsuitable to use in sync function. In order to move part of you code to another thread one must convert the function that uses it to be async, then function that uses that function and so on. Often it impossible without breaking compatibility with existing APIs or lots of refactoring.
I propose a way to synchronously wait for a message from worker:
```javascript
const worker = new Worker('worker.js')
const future = worker.futureMessage(); // returns an placeholder for message sent by worker
const message = future.get(); // blocks thread until worker sends a message and return it
```
What's the point of executing a code in a worker if we are going to block a thread until it sends response? Until `get` method is called both main thread and worker are working simultaneously.
Example usage:
```javascript
class Template {
  constructor(templateStr) {
    const worker = new Worker('template-compiler.js');
    this.future = worker.futureMessage();
    worker.postMessage(templateStr);
  }
  render(data) {
   const compiledTemplate = this.future.get();
   return doRender(compiledTemplate, data);
  }
}
```
In example above, template would be compiled when Template instance is created. By the time `render` method would be called in the future, the compilation might be over, the main thread wouldn't be blocked and we can use it even if API expects synchronous response.

**Comment by ljharb** [comment]
Sounds like an interesting idea!

Web Workers aren't part of the language spec (they're part of the web), so this repo wouldn't be the place to propose it.

For language features, please see https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal for how to best suggest new features.
