### ISSUE TITLE
Javascript bug ? indexOf(void 0) return -1?

### ISSUE THREAD

**Issue by djmisterjon** [tc39/ecma262#1432]
Am building a editor with a sprites register.
And i get strange result with indexOF

So example
```javascript

var LIST = []; // array list
LIST[4] = {}; // register data to id 4, OK
LIST[3] = {}; // register data to id 3, OK

// now check
LIST[2] === undefined; // return true , OK
LIST.length; // return 5 OK

LIST.indexOf(undefined); // return -1 WAIT WHAT ??? WHY?

// but 
LIST[2] = undefined;
LIST.indexOf(undefined); // return 2 OK
```

Existe a way to get index of the first array undefined if we not set undefined. ?
if i assign `undefined` it work, but not work if i just leave empty.
It a good idea to fix this issue or it the correct behavior?

**Comment by ljharb** [comment]
Because in your example, there’s not any actual `undefined` values in the array until the last assignment. You can test that your LIST array is sparse with `2 in LIST`, which will return false, and `Object.keys(LIST)`, which will only contain 4 and 5.

**Comment by ljharb** [comment]
Happy to keep elaborating, but I’m going to close this as answered.
