### ISSUE TITLE
Updates to Ternary Operator

### ISSUE THREAD

**Issue by The-Code-Monkey** [tc39/ecma262#1436]
Hi i think a good update to the ternary operators could be an even shorted version of what we have now as for example

`variable_a.item ? variable_a.item : variable_b.item`

could be shortened to something along the lines of 

`variable_a.item ?: variable_b.item` 
or
`variable_a.item :? variable_b.item`

this would stop the repetition of the first variable meaning for cleaner looking code and i don't think it is that hard to mis read and interpret differently if you are skimming code.

**Comment by bathos-wistia** [comment]
This exists; it’s the `||` operator.

**Comment by The-Code-Monkey** [comment]
oh god sake im an idiot lol ill close this then
