### ISSUE TITLE
Agents, forward progress, and HTML event loops

### ISSUE THREAD

**Issue by annevk** [tc39/ecma262#1444]
In a setup where a user has two independently opened `example.com` windows, the resulting JavaScript globals would each be in their own agent and corresponding agent cluster. No overlap, except for origin. Browsers however are likely to share an event loop here to reduce the number of processes. As far as I can tell this violates the [Forward Progress](https://tc39.github.io/ecma262/#sec-forward-progress) requirements, in particular:

> an agent does not cause another agent to become blocked except via explicit APIs that provide blocking.

cc @lars-t-hansen @domenic

**Comment by syg** [comment]
I think I'm missing something basic. Is the point here that for the two `example.com` windows, the share event loop is allowed to always schedule one window in favor of the other, and this is compliant from HTML's POV?

**Comment by annevk** [comment]
They are allowed to share a single scheduler. So if you do `while(true)` in one, it blocks the other.

**Comment by syg** [comment]
I thought there’s a slow script killer for situations like that. Isn’t this restriction mandating the existence of a slow script killer?

**Comment by annevk** [comment]
The way I understand "except via explicit APIs" is that it's about `Atomics.wait`, not `while(true)`. A slow script killer does not prevent halting of forward progress as far as I can tell. It's still halted until the script is killed. If that somehow makes things acceptable, that should really be spelled out more clearly. And #401 would need to be fixed. (That issue also demonstrates some misunderstanding. It seems it was thought that an agent and an event loop could be 1:1, but that's not the case, as we do not want two independently opened windows to be able to share memory, but we also do not necessarily want them to be in a different processes short term. And different threads isn't possible as DOM isn't thread-safe in implementations.)

A potential solution might be that when [[CanBlock]] is false, an agent's event loop can be shared. This would also work for worklets.

**Comment by syg** [comment]
Good points. Let’s chat with Lars.

**Comment by lars-t-hansen** [comment]
> A slow script killer does not prevent halting of forward progress as far as I can tell. It's still halted until the script is killed.

For starters, I probably disagree with that.  IMO a slow script killer (for a main thread) is in principle enough to allow forward progress of another agent that shares the thread with the one that had the slow script, provided the user allows the script to be killed and some handwaving about fairness.

I think we need to be a little careful about "event loop" vs "thread".  I'm not an HTML expert but it would feel strange to me to say that "the event loop can be shared" since this really suggests some shared state that runs counter to the idea that the two agents are in different ACs.  That the thread is shared is  to be expected, and this came up in previous discussions, I believe.  I expect two instances of example.com that are not in the same agent cluster but in the same process to be able to share a thread, but not an event loop (== per-AC data + a thread).

Presumably if the two ACs are in the same process they share the main thread of that process.

**Comment by annevk** [comment]
Thanks, so I guess the second bullet point is the one that effectively requires a slow script blocker:

> in a set of agents that share an executing thread, one agent eventually makes forward progress

It seems defining how a slow script blocker actually works is important then...

Also, assuming an executing thread is effectively a thread, I think that maps to the way @domenic has been viewing an event loop. Apart from [one bug](https://github.com/whatwg/html/issues/4336) and one case specific to workers, the text generally goes from a task on the event loop to the environment and doesn't care much about the event loop concept itself. Nevertheless, I would have preferred a similar setup to what you suggest where we specify event loops to be 1:1 with agents and allow interleaving tasks for some of them. Assuming we can eventually make everything derived from the information stored in a task and not use the event loop itself, either approach seems workable to me, but perhaps there's some gotchas I haven't encountered yet.

**Comment by guest271314** [comment]
> Also, assuming an executing thread is effectively a thread, I think that maps to the way the HTML Standard defines an event loop. Apart from one bug and one case specific to workers, the algorithms generally go from a task on the event loop to the environment and don't care much about the event loop concept itself. Nevertheless, I would prefer a similar setup to what you suggest where we specify event loops to be 1:1 with agents and allow interleaving tasks for some of them. Assuming we can eventually make everything derived from the information stored in a task and not use the event loop itself, either approach seems workable to me, however, but perhaps there's some gotchas I haven't encountered yet?

Am not sure if this is one of the cases conceived of, and am  not sure if `AudioWorkletGlobalScope` is considered a "thread", their is certainly a different execution context from the original `window` that launched the `Worklet`.

While experimenting with attempting to define or import `fetch` into the context, where it is not defined, it is possible to `import` a script that blocks the main thread from closing the `AudioContext` (`close()`) which created the `AudioWorklet`. `AudioWorkletProcessor` is blocked from being constructed during the loading of the module script. Trying to export objects from the module script which is then `AudioWorkletGlobalScope` to `window` could also result in crashing the tab, which could mean that the script did in fact progress, with the result being the halting of all progress for both `window` and `AudioWorkletGlobalScope` when the tab crashes. 

Are module scripts included in the scope of what is being discussed here as to blocking and forward progress?
