### ISSUE TITLE
findEmptyIndex [sugest]

### ISSUE THREAD

**Issue by djmisterjon** [tc39/ecma262#1446]
We need a way to found empty slot from index register.

i suggest add a new method polyfill
Thanks

```javascript
Array.prototype.findEmptyIndex = function() {
    for (let i=0, l=this.length+1; i<l; i++) {
        if(!this[i]){return i};
    };
};
```
it will work fine for this context 
```javascript
A = [];
A[0] = {};
A.findEmptyIndex (); // return 1;
A[1] = {};
A[0] = null; // or delete A[0] or A[0] = void 0; ...
A.findEmptyIndex (); // return 0;
```

**Comment by nicolo-ribaudo** [comment]
I suggest reading https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#new-feature-proposals, which explains how to propose new features.
