### ISSUE TITLE
A few 404 asset references

### ISSUE THREAD

**Issue by bkardell** [tc39/ecma262#1448]
The HTML version of https://www.ecma-international.org/ecma-262/9.0/index.html contains references to assets which are 404 (listed below) - each of these includes kind of funky URL bits which I assume are probably the result of something missing in a processor somewhere or something?:

https://www.ecma-international.org/ecma-262/9.0/ECMAScript%C2%AE%202018%20Language%C2%A0Specification_files/module-graph-missing.svg

https://www.ecma-international.org/ecma-262/9.0/ECMAScript%C2%AE%202018%20Language%C2%A0Specification_files/module-graph-simple.svg

https://www.ecma-international.org/ecma-262/9.0/ECMAScript%C2%AE%202018%20Language%C2%A0Specification_files/module-graph-cycle.svg

https://www.ecma-international.org/ecma-262/9.0/ECMAScript%C2%AE%202018%20Language%C2%A0Specification_files/figure-2.png

**Comment by ljharb** [comment]
From referencing the [latest standard](https://tc39.github.io/ecma262/) it seems like the 4 images you're looking for are:
 - https://tc39.github.io/ecma262/#figure-module-graph-missing
 - https://tc39.github.io/ecma262/#sec-example-source-text-module-record-graphs
 - https://tc39.github.io/ecma262/#figure-module-graph-cycle
 - https://tc39.github.io/ecma262/#figure-2

?

I'll let the folks at Ecma know that they're missing some images.

**Comment by ljharb** [comment]
Three are now fixed:
 - https://www.ecma-international.org/ecma-262/9.0/#figure-module-graph-missing
 - https://www.ecma-international.org/ecma-262/9.0/#figure-module-graph-cycle
 - https://www.ecma-international.org/ecma-262/9.0/#figure-module-graph-simple

The fourth is in progress:
 - https://www.ecma-international.org/ecma-262/9.0/#figure-2

**Comment by patrickcharollais** [comment]
The fourth missing image has been fixed. Thanks for your patience and all the best from a cold but sunny Geneva.
