### ISSUE TITLE
ECMAScript 5.1 - Built-in global object constructor properties 

### ISSUE THREAD

**Issue by zer0uno** [tc39/ecma262#1450]
In ECMAScript 5.1, in the constructor section of (almost) every global object constuctor property it is said:

> When XYZ is called as part of a new expression, it is a constructor: it initialises the newly created object.

With this statement it is not clear how a _newly created object_ is actually created. I think a more specific sentence would be helpful.

**Comment by devsnek** [comment]
This phrasing is no longer part of the spec, and old editions don't get amended, so I guess this is fixed?

**Comment by ljharb** [comment]
@zer0uno the latest spec is https://tc39.github.io/ecma262/ - happy to reopen this if there's something that needs clarifying there.
