### ISSUE TITLE
[[Status]] field not necessarily defined in GetModuleNamespace

### ISSUE THREAD

**Issue by jmdyck** [tc39/ecma262#1455]
`GetModuleNamespace` begins:
```
1. Assert: _module_ is an instance of a concrete subclass of Module Record.
1. Assert: _module_.[[Status]] is not `"uninstantiated"`.
```
but `[[Status]]` is not listed in [Table 37: Module Record Fields](https://tc39.github.io/ecma262/#table-36), so we're not guaranteed that it exists in `_module_`. Instead, it appears in [Table 39: Additional Fields of Cyclic Module Records](https://tc39.github.io/ecma262/#table-cyclic-module-fields).

**Comment by jmdyck** [comment]
Similarly in `InnerModuleInstantiation` re `_requiredModule_.[[Status]]`

**Comment by GeorgNeis** [comment]
Yes, this is wrong. Even though it's okay to recursively call InnerModuleInstantiation on a non-cyclic MR, it's not okay to continue then as if it was a cyclic MR.

**Comment by guybedford** [comment]
Do you think we should lower `[[Status]]` to exist on all Module Records then rather?

**Comment by GeorgNeis** [comment]
Either that, or do the remaining steps in the loop only for cyclic MRs (and in GetModuleNameSpace restrict the assertions to cyclic MRs).

**Comment by littledan** [comment]
I agree these are errors. They predate #1311, and were just copied through. I am not sure we should revisit the layering here, as it was fairly controversial what to include in #1311.

Since this comes up just in assertions, what if we clarify those as, 'Assert: if it's a Cyclic module record, then...'?

**Comment by GeorgNeis** [comment]
It's not only assertions, see InnerModule*:
`If requiredModule.[[Status]] is "instantiating", then`

**Comment by littledan** [comment]
Oops, right. I think we could apply the same treatment, and check if they are cyclic before reading the status.

**Comment by jmdyck** [comment]
@littledan:
> I agree these are errors. They predate #1311, and were just copied through.

It's true that the uses in question predate #1311 and were just copied through, but your wording could be interpreted as saying that they were *errors* in the pre-1311 spec, which I don't think is true.

**Comment by GeorgNeis** [comment]
They were errors already at that time.

**Comment by littledan** [comment]
They were previously part of the Source Text Module Record. There was an idea to put all the Cyclic Module Record things in Abstract Module Record, but the eventual decision was to just split out some of STMR into CMR.
