### ISSUE TITLE
Make the last digit of the ECMAScript edition number consistent with the last digit of the publishing year

### ISSUE THREAD

**Issue by ExE-Boss** [tc39/ecma262#1457]
Right now, the&nbsp;following mapping applies to&nbsp;**ES6**&nbsp;–&nbsp;**ES9**:

| Version | Year |
| ---- | -------- |
| ES6 | ES2015 |
| ES7 | ES2016 |
| ES8 | ES2017 |
| ES9 | ES2018 |

This is somewhat confusing because the ECMAScript edition number doesn’t directly correspond to&nbsp;the&nbsp;publising&nbsp;year.

I propose to make it so that the publishing of ES10 gets delayed by half a year so that it would be possible to call it ES2020 and then publishing ES11 a year and a half after ES10, with ES12 and later being published a year apart, eg.:

| Version | Proposed offset from current schedule (in years) |
| --------------- | --- |
| ES9   (ES2018) | 0 |
| ES10 (ES2019.5 ≐ ES2020) | +0.5 |
| ES11 (ES2021) | +1 |
| ES12 (ES2022) | +1 |

**Comment by devsnek** [comment]
just only refer to editions after es5 by year

**Comment by ljharb** [comment]
Such an offset would make things more confusing imo, since “edition + 2009” wouldn’t give you the ES6+ year anymore.

**Comment by ExE-Boss** [comment]
But edition + 2010 is easier to calculate in the head and feels simpler.

**Comment by ljharb** [comment]
The simplest of all, though, is https://github.com/tc39/ecma262/issues/1457#issuecomment-467897891

**Comment by claudepache** [comment]
*If* some correction is to be done, let’s do it frankly and let’s skip the 2009 next version numbers (ES version 2019 would succeed to ES version 9). Any half-measure [will just increase the confusion](https://en.wikipedia.org/wiki/Swedish_calendar).

**Comment by ljharb** [comment]
Thanks for your suggestion, but I doubt we'll want to skip edition numbers.
