### ISSUE TITLE
FREEDOM

### ISSUE THREAD

**Issue by Thapanawat003** [tc39/ecma262#1459]
THAILAND

**Comment by TejasQ** [comment]
https://www.youtube.com/watch?v=gnlpVPFegGA

**Comment by TejasQ** [comment]
I don't want to add to the trolling but I can't close the issue so

**Comment by ericmartinezr** [comment]
It seems to be related to this https://uk.mobile.reuters.com/article/amp/idUKKCN1QH1OB
