### ISSUE TITLE
Destructuring Assignment rules override Assignment Operators rules?

### ISSUE THREAD

**Issue by dSalieri** [tc39/ecma262#1469]
The fact is that in the specification there are 2 identical sentences. 

First is [here](https://www.ecma-international.org/ecma-262/#sec-assignment-operators-static-semantics-early-errors) and look as:

> **12.15.1 Static Semantics: Early Errors**
>
> _AssignmentExpression: LeftHandSideExpression = AssignmentExpression_
>
> - It is a Syntax Error if LeftHandSideExpression is either an ObjectLiteral or an ArrayLiteral and LeftHandSideExpression is not covering an AssignmentPattern.

 
Second is [here](https://www.ecma-international.org/ecma-262/#sec-destructuring-assignment-static-semantics-early-errors) and look as:

> **12.15.5.1 Static Semantics: Early Errors**
>
> _DestructuringAssignmentTarget: LeftHandSideExpression_
>
> - It is a Syntax Error if LeftHandSideExpression is either an ObjectLiteral or an ArrayLiteral and if LeftHandSideExpression is not covering an AssignmentPattern.

An example of an error is the following expression: `({a:{b:1}}={})`. If I am not mistaken, it serves as an example for two errors that I showed above. But it seems to me that the first error is superfluous, only the second will suffice, does not it seem to you?

**Comment by jmdyck** [comment]
The first rule isn't superfluous, it's needed to catch, for example, `{foo(){}} = {}`, in which `{foo(){}}` is an ObjectLiteral but doesn't cover an AssignmentPattern (because AssignmentPattern doesn't include anything that looks like a MethodDefinition).

**Comment by dSalieri** [comment]
@jmdyck Thanks for the clarification, sometimes it does not work, to notice all aspects.
