### ISSUE TITLE
Abstract Equality Comparison

### ISSUE THREAD

**Issue by sanshiliuxiao** [tc39/ecma262#1472]
In https://www.ecma-international.org/ecma-262/9.0/#sec-abstract-relational-comparison 
```
If Type(x) is Number and Type(y) is String
return the result of the comparison x == !ToNumber(y).
If Type(x) is String and Type(y) is Number, 
return the result of the comparison !ToNumber(x) == y.
If Type(x) is Boolean, return the result of the comparison !ToNumber(x) == y.
If Type(y) is Boolean, return the result of the comparison x == !ToNumber(y).
```
this is  **!ToNumber()**，I think it's a writing error.
because in  https://www.ecma-international.org/ecma-262/5.1/#sec-11.9.3
```
If Type(x) is Number and Type(y) is String,
return the result of the comparison x == ToNumber(y).
If Type(x) is String and Type(y) is Number,
return the result of the comparison ToNumber(x) == y.
If Type(x) is Boolean, return the result of the comparison ToNumber(x) == y.
If Type(y) is Boolean, return the result of the comparison x == ToNumber(y).
```

**Comment by trotyl** [comment]
> Similarly, **prefix ! is used to indicate that the following invocation of an abstract or syntax-directed operation will never return an abrupt completion and that the resulting Completion Record's [[Value]] field should be used in place of the return value of the operation**. For example, the step:
> 
> 1. Let val be ! OperationName().
> is equivalent to the following steps:
> 
> 1. Let val be OperationName().
> 2. Assert: val is never an abrupt completion.
> 3. If val is a Completion Record, set val to val.[[Value]].
> Syntax-directed operations for runtime semantics make use of this shorthand by placing ! or ? before the invocation of the operation:
>
> 1. Perform ! SyntaxDirectedOperation of NonTerminal.

https://www.ecma-international.org/ecma-262/9.0/index.html#sec-returnifabrupt-shorthands

**Comment by sanshiliuxiao** [comment]
Thank you
