### ISSUE TITLE
Related object problem

### ISSUE THREAD

**Issue by mhxy13867806343** [tc39/ecma262#1481]
Related object problem
Can you add a function?
Multiple keys corresponding to a value function
The following format
Const dict ={'a|b|c': 123}
The result of taking out can be as follows
Console.log(dict['a']) // 123
Console.log(dict['b']) // 123
Console.log(dict['c']) // 123

**Comment by nicolo-ribaudo** [comment]
```js
const dict ={'a|b|c': 123};
console.log(dict.a);
```

Currently this code logs `undefined`: changing it to log `123` would be a breaking change.

It might be possible to introduce a new syntax. You can read here how to propose a new feature for ECMAScript: https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#new-feature-proposals
