### ISSUE TITLE
What String does it says in Notational Convention?

### ISSUE THREAD

**Issue by dSalieri** [tc39/ecma262#1484]
The specification says the following:

> NOTE 1
> Parsing the same String multiple times will lead to different Parse Nodes, e.g., as occurs in:
> 
> eval(str); eval(str);

It is not entirely clear what about String it says.

1. The String is `eval(str);`
2. The String is an argument `str` to the eval function.

If this is the first option, then instead of this function there can be anything even a variable declaration (for example: `let a;`), right?

**Comment by ljharb** [comment]
I believe it’s the second option.

**Comment by dSalieri** [comment]
> I believe it’s the second option.

I think we need to clarify this issue.

**Comment by devsnek** [comment]
the only example i can think of is:

```js
eval('tag``'); eval('tag``');
```

**Comment by ljharb** [comment]
In the example referenced in the OP, the only thing happening multiple times is a call to eval, with the same string argument. I’m not clear on how it could be read any differently.

How would you suggest it be clarified?

**Comment by dSalieri** [comment]
@ljharb 

It is necessary to clarify what is a String. Since I do not know what alternative examples can be given except `eval(str); eval(str);`. Regarding this example, I would write this:

> NOTE 1
> Parsing the same String multiple times will lead to different Parse Nodes, e.g., as occurs in **(String is the function argument)**:
>
> eval(str); eval(str); 
> 
As for the other interpretation: This can be understood as `let a; let a;` or `("foo" + "bar"); ("foo" + "bar");`. In this case, a string is a line of code separated by a ";"

**Comment by ljharb** [comment]
By using the capital S, i believe it’s unambiguosly referring to an ECMAScript String value, ie, the contents of `str`. The sentence is indicating that the same string contents won’t produce the same parse node - that it’s the call to eval, not the string contents, that determines the creation of new parse nodes.

**Comment by dSalieri** [comment]
@ljharb I understand you, could you give a couple of examples besides `eval(str);`?

**Comment by jmdyck** [comment]
We could maybe change the wording to something like:
```
Parsing the same String multiple times will lead to different Parse Nodes.
For example, consider:
    eval(str); eval(str);
Each call to `eval` will create its own separate set of Parse Nodes,
even though the same String value is passed to both calls.
```

**Comment by dSalieri** [comment]
@jmdyck Good change. But I will ask you too what **ljharb** asked. Could you give a couple of examples except `eval(str);`?

**Comment by ljharb** [comment]
Other than eval and Function, i’m not sure how you’d demonstrate parsing twice with the same String value.

**Comment by allenwb** [comment]
"strings" aren't parsed, rather "source texts" are parsed and `str` is simply a variable that has some value so it is not exactly clear how this example is illustrating the  the point that two parses of the same _source text_ produces two distinct  parse trees that share no parse nodes.

Perhaps it would be clearer this way:

```js
let str =  "something;"; //a string representation of ECMAScript source text
eval(str); eval(str);
```

Each `eval` converts the value of `str` into an ECMAScript source test and performs an independent parse that  creates its own separate tree of Parse Nodes.
The trees are distinct even though each parse operates upon a source text that was derived from the same String value.

**Comment by dSalieri** [comment]
@allenwb Thanks, now it became clear. I asked above about examples other than `eval (str)` to me, **ljharb** answered that this could be a function. But I honestly do not understand how the function may be in place of `eval(str)`. Do not explain?

**Comment by ljharb** [comment]
I said Function, not “a function” - referring explicitly to the function constructor.

**Comment by dSalieri** [comment]
@ljharb Sorry, did not attach any importance to this. If you are talking about the constructor function, then you mean the creation of a function through the constructor: `new Function (str)`?

**Comment by ljharb** [comment]
@dSalieri yes, although the `new` there is optional.

**Comment by dSalieri** [comment]
@ljharb clear, thank you for your answers.

**Comment by ljharb** [comment]
@dSalieri have your questions all been answered?

**Comment by dSalieri** [comment]
@ljharb if you talk about this topic, definitely yes.
