### ISSUE TITLE
About list resolution issues

### ISSUE THREAD

**Issue by mhxy13867806343** [tc39/ecma262#1485]
Hello, my English is not very good, please forgive me
The following python list parsing syntax
[expr for iter_var in iterable] 
[expr for iter_var in iterable if cond_expr]
python demo:
![1111](https://user-images.githubusercontent.com/4418166/54508796-0f226800-4982-11e9-8f6f-910afdb1f451.jpg)
Can javascript implement Python's list parsing method?

**Comment by ljharb** [comment]
You're asking about comprehensions - see https://esdiscuss.org/topic/comprehensions-where-art-thou, https://esdiscuss.org/topic/array-comprehensions, https://esdiscuss.org/topic/array-generator-comprehensions-in-harmonym https://esdiscuss.org/topic/a-reprieve-for-es6-comprehensions.

Either way, please see https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal for how to best suggest new features for the language.

**Comment by mhxy13867806343** [comment]
3q
