### ISSUE TITLE
Proposal: assigning only defined values ('?=' operator)

### ISSUE THREAD

**Issue by bsurai** [tc39/ecma262#1487]
Imaging we have a code
```
let a = 'any defined value'
let b = getPossibleUndefinedValue()

if (b !== undefined) {
   a = b
}
```

It would be convenient to replace that verbose condition with shorthand expression like 

```
let a = 'any defined value'
let b = getPossibleUndefinedValue()

a ?= b
```

**Comment by nicolo-ribaudo** [comment]
That will probably be possible thanks to https://github.com/tc39/proposal-nullish-coalescing and https://github.com/tc39/proposal-logical-assignment.

**Comment by bsurai** [comment]
@nicolo-ribaudo I gues it won't. There is a case for 
  ```
if (!a) {
    a = b;
  }
```
It say if `a` (old value) isn't defined then do assignment.

But I ask about a bit different case
```
if (b !== undefined) {
   a = b
}
```
It says to do assertion if `b` (new value) is defined.

**Comment by nicolo-ribaudo** [comment]
If you combine those proposals, you will be able to use `a ??= b`. Anyway, if you want to propose a new feature this isn't the right repo where to do so: I suggest reading https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#new-feature-proposals

**Comment by bsurai** [comment]
@nicolo-ribaudo Thanks. I see in the link you've added 

> For small changes to ECMAScript, you can contribute **by filing an issue** or a pull request against the current text of ECMA-262 standard in this repository.

For me it looks like a small change. Therefore it can be placed here. If understand right.

**Comment by ljharb** [comment]
New syntax is a very large change; closing per https://github.com/tc39/ecma262/issues/1487#issuecomment-474829497.
