### ISSUE TITLE
FormalParameters takes a [Yield] parameter that doesn't matter

### ISSUE THREAD

**Issue by jorendorff** [tc39/ecma262#1488]
```js
function* f(x) {
    function* g(y = yield x) {}  // SyntaxError
}
```

This is a SyntaxError thanks to an Early Error rule [here](https://tc39.github.io/ecma262/#sec-generator-function-definitions-static-semantics-early-errors):

> * It is a Syntax Error if *FormalParameters* Contains *YieldExpression* is **true**.

It would be simpler to implement the same restriction in the grammar:

* [ ] Remove the `[Yield]` parameter from *FormalParameters* and various related nonterminals;
* [ ] Have *FormalParameter* pass `[~Yield]` to *BindingElement* to rule out *YieldExpressions*;
* [ ] Remove the Early Error rules about *YieldExpressions* (there are several).

**Comment by bakkot** [comment]
Passing `Yield` to _BindingElement_ would make

```js

function* f(x) {
    function* g(yield) {}
}
```

legal, wouldn't it? That seems undesirable.

**Comment by jorendorff** [comment]
Yep, that's right. Makes sense!  Sorry for the noise.
