### ISSUE TITLE
Annex B.3.5 CatchParameter legacy remedy could be narrower

### ISSUE THREAD

**Issue by ajklein** [tc39/ecma262#150]
The [early errors](http://tc39.github.io/ecma262/#sec-try-statement-static-semantics-early-errors) for Try/Catch names includes the following passage:

"It is a Syntax Error if any element of the BoundNames of CatchParameter also occurs in the VarDeclaredNames of Block."

However, this is modified in [B.3.5](http://tc39.github.io/ecma262/#sec-variablestatements-in-catch-blocks) to allow code of the form:

```js
try {
  ...
} catch (e) {
  var e = 2;
}
```

to run without complaint, presumably for legacy compat reasons. The spec text says:

"It is a Syntax Error if any element of the BoundNames of CatchParameter also occurs in the VarDeclaredNames of Block, unless that element is only bound by a VariableStatement or the VariableDeclarationList of a for statement, or the ForBinding of a for-in statement."

But this means that the following is also allowed:

```js
try {
  ...
} catch ({stack, code}) {
  var stack = 1;
  var code = 2;
}
```

What's the motivation for allowing the destructured form, given that there will be no legacy concerns in that case? One could imagine the spec could instead read:

"It is a Syntax Error if any element of the BoundNames of CatchParameter also occurs in the VarDeclaredNames of Block, unless _BoundNames contains a single element and_ that element is only bound by a VariableStatement or the VariableDeclarationList of a for statement, or the ForBinding of a for-in statement."

**Comment by allenwb** [comment]
Yes, this sounds like a good narrowing of the B.3.5 form of the rule.

**Comment by anba** [comment]
The current specification also allows this:
```javascript
try {
  ...
} catch (e) {
  var [e] = ...
}
```

Should that form also be made invalid?

>  [...] unless BoundNames contains a single element and [...]

"unless CatchParameter is CatchParameter : BindingIdentifier and " to handle `catch ({stack}) {...}` correctly.

**Comment by michaelficarra** [comment]
Yes, that final change should do it.
