### ISSUE TITLE
Download of files .PNG in the browser

### ISSUE THREAD

**Issue by HerculesLimaMaranhao** [tc39/ecma262#1512]
TC39 is open to accepting new feature requests for ECMAScript, referred to as
"proposals". Proposals go through a four-stage process which is documented in
the [TC39 process document](https://tc39.github.io/process-document/).

Feature requests for future versions of ECMAScript should not be made in this
repository. Instead, they are developed in separate GitHub repositories, which
are then merged into the main repository once they have received "Stage 4".

Please see [CONTRIBUTING.md](/CONTRIBUTING.md) for more details.

**Comment by ljharb** [comment]
Hi! Based on the subject, it looks like you have a feature request for web browsers, which is a separate specification. This repo deals with the javascript language itself, which has no concept of images or downloading.
