### ISSUE TITLE
Add 'matrix' primitive type

### ISSUE THREAD

**Issue by EdSaleh** [tc39/ecma262#1536]
Hello,

Matrices are widely used today in in Computer Science, Engineering, and AI. I am proposing a new primitive type of `matrix` which would make working with matrices easier, easily doing operations such matrices `multiplication` and `addition`.

Thank you,

**Comment by ljharb** [comment]
Please see https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal for how to best suggest new features for the language.
