### ISSUE TITLE
What does this mean in 5.2.4 Static Semantics

### ISSUE THREAD

**Issue by dSalieri** [tc39/ecma262#1551]
>Unless otherwise specified every grammar production alternative in this specification implicitly has a definition for a static semantic rule named Contains which takes an argument named symbol whose value is a terminal or nonterminal of the grammar that includes the associated production. The default definition of Contains is:
>
> ```
> 1. For each child node child of this Parse Node, do
>     a. If child is an instance of symbol, return true.
>     b. If child is an instance of a nonterminal, then
>         i. Let contained be the result of child Contains symbol.
>         ii. If contained is true, return true.
> 2. Return false.
> ```
>
>The above definition is explicitly over-ridden for specific productions.

---
**So, I'll start. I will pull out the necessary parts from the quotation and ask questions.**

>Unless otherwise specified

What? Example?

> every grammar production alternative in this specification implicitly has a definition for a static semantic rule named Contains

For example?
Definition `Contains` by default? For which productions of grammar is this definition the default?

>The above definition is explicitly over-ridden for specific productions.

An example of these over-ridden productions?

---
For example, there is such a [paragraph](https://www.ecma-international.org/ecma-262/9.0/index.html#sec-function-definitions-static-semantics-contains):

> With parameter `symbol`.
> 
> *FunctionDeclaration: **function** BindingIdentifier **(** FormalParameters **)** **{** FunctionBody **}***
> *FunctionDeclaration: **function** **(** FormalParameters **)** **{** FunctionBody **}***
> *FunctionExpression: **function** BindingIdentifier **(** FormalParameters **)** **{** FunctionBody **}***
> 
> 1. Return **false**.

The symbol is passed here, but it is not used in the algorithm. What does it mean?

P.S Such implicitness causes a lot of questions.

**Comment by jmdyck** [comment]
Here's a different wording that might answer some of your questions:

Every production alternative has a definition for 'Contains'. That definition can be explicit; i.e., when there's a clause in the spec entitled "Static Semantics: Contains" that has an algorithm associated with that alternative. But if, for a particular alternative, no such explicit definition exists, then the definition is implicitly the default one given in 5.2.4.


> > The above definition is explicitly over-ridden for specific productions.
> 
> An example of these over-ridden productions?

The ones you found in clause 14.1.4.

> For example, there is such a [paragraph](https://www.ecma-international.org/ecma-262/9.0/index.html#sec-function-definitions-static-semantics-contains):
> 
> > With parameter `symbol`.
> > _FunctionDeclaration: **function** BindingIdentifier **(** FormalParameters **)** **{** FunctionBody **}**_
> > _FunctionDeclaration: **function** **(** FormalParameters **)** **{** FunctionBody **}**_
> > _FunctionExpression: **function** BindingIdentifier **(** FormalParameters **)** **{** FunctionBody **}**_
> > 
> > 1. Return **false**.
> 
> The symbol is passed here, but it is not used in the algorithm. What does it mean?

The default definition of Contains, and many of the explicit definitions, are recursive. Roughly speaking, an invocation of Contains traverses the parse tree under a given node, looking for an instance of _symbol_.  So when a definition just says "Return false", it means to omit this subtree from the traversal, regardless of the _symbol_. Mostly, Contains does not descend into function definitions, so a more accurate name for it would be ContainsWithoutDescendingIntoFunctionDefinitions, but (a) that's a mouthful, and (b) it's still only an approximation of the exact semantics embodied by all the definitions of the operation.
 
> P.S Such implicitness causes a lot of questions.

Yeah, but the alternative is explicitness, and in this case that would involve defining Contains for almost every production, which would be a ton of boring definitions that make it hard to see the few interesting ones.

**Comment by dSalieri** [comment]
@jmdyck hello, it's you again :)

>Every production alternative has a definition for 'Contains'. That definition can be explicit; i.e., when there's a clause in the spec entitled "Static Semantics: Contains" that has an algorithm associated with that alternative. But if, for a particular alternative, no such explicit definition exists, then the definition is implicitly the default one given in 5.2.4.

This formulation sounds and is perceived many times better.

---
That is, `Contains` even exists in the statement `if`? If you look into the specification, we will not find the `Contains` section there, but we will find the following sections: `ContainsDuplicateLabels`, `ContainsUndefinedBreakTarget`, `ContainsUndefinedContinueTarget`. Do they relate to `Contains`? If so, how?

I do not quite understand what specific task does `Contains` perform? For what all these recursive travelsar? Can a little illustration of what `Contains` do?

**Comment by jmdyck** [comment]
> That is, `Contains` even exists in the statement `if`? If you look into the specification, we will not find the `Contains` section there,

Right, so `IfStatement` uses the default definition for `Contains`.

> but we will find the following sections: `ContainsDuplicateLabels`, `ContainsUndefinedBreakTarget`, `ContainsUndefinedContinueTarget`. Do they relate to `Contains`? If so, how?

They're not algorithmically connected to `Contains`. They have similar names because they operate similarly, traversing the parse tree looking for particular things. 

> I do not quite understand what specific task does `Contains` perform? For what all these recursive travelsar? Can a little illustration of what `Contains` do?

`Contains` is mostly used in Early Error rules, e.g. for a [`FunctionDeclaration`](https://tc39.github.io/ecma262/#sec-function-definitions-static-semantics-early-errors):
> It is a Syntax Error if |FunctionBody| Contains |SuperCall| is *true*.

As far as the *grammar* is concerned, a `SuperCall` can occur all over the place, including lots of contexts where it doesn't make sense. To disallow it from such contexts, we use rules such as the above.

**Comment by dSalieri** [comment]
@jmdyck
That is, the specification clearly shows where `Contains` should be called? That is, a person who will implement the language according to the specification should not think where to use `Contains`. So?

Heck, if runtime semantics is clear, then there are questions about static semantics.

Look here, let an example be some simple production. For example, this: `1 + 2;`

Specification will explain this as [production](https://tc39.github.io/ecma262/#sec-additive-operators):

> AdditiveExpression:
>     AdditiveExpression + MultiplicativeExpression

There is no section with `Contains`, but as we found out earlier, it is there, but implicitly. I do not understand how following this [rule](https://tc39.github.io/ecma262/#sec-static-semantic-rules) should I analyze the expression I wrote above, taking into account all static rules?

**Comment by jmdyck** [comment]
> That is, the specification clearly shows where `Contains` should be called?

Yes.

> Look here, let an example be some simple production. For example, this: `1 + 2;`
> 
> Specification will explain this as [production](https://tc39.github.io/ecma262/#sec-additive-operators):
> 
> > AdditiveExpression:
> > AdditiveExpression + MultiplicativeExpression
> 
> There is no section with `Contains`, but as we found out earlier, it is there, but implicitly.

Right.

> I do not understand how following this [rule](https://tc39.github.io/ecma262/#sec-static-semantic-rules) should I analyze the expression I wrote above, taking into account all static rules?

The question doesn't really make sense to me. Following the default definition for `Contains` doesn't in itself allow you to analyze `1 + 2` or take all static rules into account.

- What kind of analysis do you have in mind?

- The way to take all static rules into account is to enforce all Early Error rules.

**Comment by dSalieri** [comment]
@jmdyck
>What kind of analysis do you have in mind?

I meant the analysis using static semantics.

>The way to take all static rules into account is to enforce all Early Error rules.

Well, I understand that static semantics is needed for Early Errors. I just would like to know more precisely where to start from to analyze the expression `1 + 2;` on Early Errors.

P.S This is probably not the case for my initial question (although it is still not clear to me how the algorithm from 5.2.4 should be used in situations where it is the default). But why not ask why miss a chance.

**Comment by jmdyck** [comment]
> I just would like to know more precisely where to start from to analyze the expression `1 + 2;` on Early Errors.

There aren't any Early Error rules associated with the production
> AdditiveExpression: AdditiveExpression + MultiplicativeExpression

or with *any* of the productions used to parse the expression `1 + 2`. If you want to understand how Early Errors work, you'd be better off starting with a production that has at least one associated Early Error rule.

> it is still not clear to me how the algorithm from 5.2.4 should be used in situations where it is the default

Whether or not you're using the default definition for `Contains` shouldn't make a difference to *how* it's used. If you understand how non-default definitions are used, what stops you applying that understanding to the default?

**Comment by dSalieri** [comment]
@jmdyck
Well, I will follow your advice to analyze a specific early error. Although I have already tried and have some questions.

Well, for example, you referred to [`FunctionDeclaration`](https://tc39.github.io/ecma262/#sec-function-definitions-static-semantics-early-errors). There for example you can see the following error:
>It is a Syntax Error if FunctionBody Contains SuperCall is true.

Here I personally have a question (maybe I misunderstand something): which `Contains` from the set in the specification should be applied specifically to this error?

>There aren't any Early Error rules associated with the production or with any of the productions used to parse the expression `1 + 2`

But as I recall, the static rule `Contains` exists implicitly in the [Additive Operators](https://tc39.github.io/ecma262/#sec-additive-operating) chapter. For what if there is no Early Errors?

---
>Whether or not you're using the default definition for Contains shouldn't make a difference to how it's used. If you understand how non-default definitions are used, what stops you applying that understanding to the default?

Probably no, you're right.

**Comment by jmdyck** [comment]
> > It is a Syntax Error if FunctionBody Contains SuperCall is true.
> 
> which `Contains` from the set in the specification should be applied specifically to this error?

`Contains` is a [syntax-directed operation](https://tc39.github.io/ecma262/#sec-algorithm-conventions-syntax-directed-operations) (although its invocation syntax is infix rather than prefix). "Syntax-directed operations are invoked with a parse node and, optionally, other parameters". In this example, the parse node (call it X) is given by the `FunctionBody` symbol, and the other parameter is the `SuperCall` symbol. So the definition of `Contains` that will be invoked by this rule is the one associated with the production of which X is an instance.

`FunctionBody` has only one production:
>  FunctionBody : FunctionStatementList

so you're looking for a definition of `Contains` associated with that production. There isn't an explicit one (if there were, it would be [here](https://tc39.github.io/ecma262/#sec-function-definitions-static-semantics-contains), so the default one from 5.2.4 is used.

The default definition is recursive, so executing it on X will cause `Contains` to be invoked on X's `FunctionStatementList`, so you have to look for a definition of `Contains` associated with a production for `FunctionStatementList`, and so on.

That one invocation of `Contains` in the Early Error rule could easily lead to hundreds or thousands of recursive invocations of `Contains`, each one localized to one parse node in the subtree under X, each one using the definition (explicit or implicit) appropriate for that parse node.

 
> > There aren't any Early Error rules associated with the production or with any of the productions used to parse the expression `1 + 2`
> 
> But as I recall, the static rule `Contains` exists implicitly in the [Additive Operators](https://tc39.github.io/ecma262/#sec-additive-operating) chapter. For what if there is no Early Errors?

If X contains the expression `1 + 2`, then the above recursion will eventually hit that expression (assuming it isn't within a nested function, or some other construct that prunes the recursion), and at that point you'll need a definition of `Contains` associated with the production:
> AdditiveExpression : AdditiveExpression + MultiplicativeExpression

As we've seen above, this will be the default definition. After some more recursion, it will return the value `false`, indicating that the expression `1 + 2` does not contain a `SuperCall`.

**Comment by dSalieri** [comment]
@jmdyck Yes, I like that answer, now I understand everything.

**Comment by dSalieri** [comment]
@jumdyck one more moment interests all from this chapter. There is such a sentence:
>Evaluation of most early error rules are not explicitly invoked within the algorithms of this specification.

Not quite clear the meaning of this sentence. What is the meaning of the `most early error rules`? Is there any difference from not `most early error rules`?

**Comment by jmdyck** [comment]
The use of "most" implies that there are some early error rules that **are** explicitly invoked within the algorithms of this specification. I suspect this is talking about, e.g.:
- when [PerformEval](https://tc39.es/ecma262/#sec-performeval) says:
```1. If _inFunction_ is false, additional early error rules from 18.2.1.1.1 are applied.```
- when [CreateDynamicFunction](https://tc39.es/ecma262/#sec-createdynamicfunction) says:
```If _strict_ is true, the Early Error rules for UniqueFormalParameters : FormalParameters are applied.```

**Comment by bakkot** [comment]
Now that the definition of [Contains](https://tc39.es/ecma262/#sec-static-semantics-contains) is all in one place, I think this should be clearer.
