### ISSUE TITLE
New for loop with ';' semicolons replaced with either ':' colons or ',' commas

### ISSUE THREAD

**Issue by ShadyGaDa** [tc39/ecma262#1555]
**THIS IS THE ONE MOST IMPORTANT THINGS MISSING FROM ECMA6**
_semicolons_ 
`for (var i=1; i<colons.length; i++) { colons[i] = i }`
_colons_ 
`for (var i=1: i<colons.length: i++) { colons[i] = i }`
_commas_
`for (var i=1, i<colons.length, i++) { colons[i] = i }`

here is a similar but more advanced idea
[https://github.com/tc39/ecma262/issues/1535]
`range(start, end, step=1)` iterator function

nb mr ljharb
i dont think quoting the md every time will get you the deserved coffee breaks.

`for(let i of range(1,<colons.length,primes)) { colons[i] = i }`
conceptual
`for(Why_Not(Insignificant,<Less_Than_Perfect,Stepping_Up)) { Disarray[Why_Not] = ¿Lose }`

**Comment by ljharb** [comment]
As I already explained in #1553, this repo is *not* for feature suggestions for the language.

Please follow the recommendations [here](https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal) if you want to pursue this direction.
