### ISSUE TITLE
Modules - Automatically import all named exports in folder if no index.js is found

### ISSUE THREAD

**Issue by alshdavid** [tc39/ecma262#1558]
**The problem**

When writing package/module based code, often you will group actions/concerns/functions inside folders.

This is a great way to keep your projects neat and concerns modular.

In order to do this effectively, one must create a barrel file (an index.js) which functions to re-export all of the things in that folder.

module/a.js
```javascript
export const hi = () => console.log('Hello!')
```

module/b.js
```javascript
export const peeps = () => console.log('World!')
```

module/index.js
```javascript
export * from './a.js'
export * from './b.js'
// etc
```

Barrel files can quickly become very verbose and annoying to maintain. I have seen solutions for this ranging from automatically generated barrel files to patching `require()` in node to have it scan a directory to build an import.

**The solution**

When importing a folder that doesn't already have an `index.js`, import all of the named exports in the files that live inside it.

This would mean that the following code works with or without an index.js file in the root of the folder.

main.js
```javascript
import * as myModule from './module'
myModule.hi()
myModule.peeps()
```

**Comment by ljharb** [comment]
The language spec doesn't have a concept of "folders", nor of "files", nor do browsers.

Either way, this repo isn't the place for feature suggestions - please see https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal for how to go about that.
