### ISSUE TITLE
`PromiseResolve(%Promise%, value)`'s value is sometimes erroneously assumed to have the internal slots of a promise

### ISSUE THREAD

**Issue by isiahmeadows** [tc39/ecma262#1578]
**Description:**

In a few places ([1](http://tc39.es/ecma262/#_ref_1230), [2](http://tc39.es/ecma262/#_ref_7976), [3](http://tc39.es/ecma262/#_ref_8125)), the result of `PromiseResolve(%Promise%, value)` is plugged straight into [`PerformPromiseThen`](http://tc39.es/ecma262/#sec-performpromisethen). This may seem rational, but the result of `PromiseResolve(%Promise%, value)` should return the instance directly without further type checks when `value.constructor` refers to the current realm's `%Promise%` value. It follows naturally from this to my understanding of the spec that `Promise.resolve({constructor: Promise})` should return the argument itself, not a Promise instance. And this means the assertion in step 1 of `Perform PromiseThen` does not hold. (All that's been proven is that `Type(promise)` is `Object` - it could just as easily change and/or remove its `constructor` property, and it could be a proxy that decided just that one time to claim it had a `constructor` property set to that value.)

In implementations, I'm seeing an entirely different set of semantics:

- Everyone agrees that `Promise.resolve({constructor: Promise})` should return a `Promise` instance. The parameter is obviously not one, so nobody is returning the argument here.
- Nobody performs an observable `constructor` access in any of these scenarios. Everyone checks that it's a native promise first, and only proceeds to wrap if it's not. (See #1577 for the case when it *is* a native promise.)
- Everyone unconditionally invokes `.then` on the object literal, ignoring the constructor altogether.
- XS oddly doesn't resolve the promise on synchronous error, although I suspect that's a likely bug on their part.

The spec seems broken here IMHO.

**eshost Output:**

```
$ eshost -e 'Promise.resolve({constructor: Promise})'
#### ch, jsc, sm, v8, xs
[object Promise]

$ eshost async-resolve.js
#### ch, jsc, sm, v8, xs
call then
resolve then
result: 1 (normal)

$ eshost async-reject.js
#### ch, jsc, sm, v8, xs
call then
resolve then
result: 1 (throw)

$ eshost async-throw.js
#### ch, jsc, sm, v8
call then
result: 1 (throw)

#### xs
call then

$ eshost then-resolve.js
#### ch, jsc, sm, v8, xs
call then
resolve then
result: 1 (normal)

$ eshost then-reject.js
#### ch, jsc, sm, v8, xs
call then
resolve then
result: 1 (throw)

$ eshost then-throw.js
#### ch, jsc, sm, v8
call then
result: 1 (throw)

#### xs
call then
```

Source files:

```js
// async-resolve.js
;(async () => {
    let type = "other"
    let result
    try {
        result = await {
            get constructor() {
                print("get promise")
                return Promise
            },
            then(resolve, reject) {
                print("call then")
                resolve(1)
                print("resolve then")
            },
        }
        type = "normal"
    } catch (e) {
        result = e
        type = "throw"
    }

    print(`result: ${result} (${type})`)
})()

// async-reject.js
;(async () => {
    let type = "other"
    let result
    try {
        result = await {
            get constructor() {
                print("get promise")
                return Promise
            },
            then(resolve, reject) {
                print("call then")
                reject(1)
                print("resolve then")
            },
        }
        type = "normal"
    } catch (e) {
        result = e
        type = "throw"
    }

    print(`result: ${result} (${type})`)
})()

// async-throw.js
;(async () => {
    let type = "other"
    let result
    try {
        result = await {
            get constructor() {
                print("get promise")
                return Promise
            },
            then(resolve, reject) {
                print("call then")
                throw 1
            },
        }
        type = "normal"
    } catch (e) {
        result = e
        type = "throw"
    }

    print(`result: ${result} (${type})`)
})()

// then-resolve.js
let type = "other"
let result

Promise.resolve({
    get constructor() {
        print("get promise")
        return Promise
    },
    then(resolve, reject) {
        print("call then")
        resolve(1)
        print("resolve then")
    },
}).then(
    r => { type = "normal"; result = r },
    e => { type = "throw"; result = e }
).then(() => {
    print(`result: ${result} (${type})`)
})

// then-reject.js
let type = "other"
let result

Promise.resolve({
    get constructor() {
        print("get promise")
        return Promise
    },
    then(resolve, reject) {
        print("call then")
        reject(1)
        print("resolve then")
    },
}).then(
    r => { type = "normal"; result = r },
    e => { type = "throw"; result = e }
).then(() => {
    print(`result: ${result} (${type})`)
})

// then-throw.js
let type = "other"
let result

Promise.resolve({
    get constructor() {
        print("get promise")
        return Promise
    },
    then(resolve, reject) {
        print("call then")
        throw 1
    },
}).then(
    r => { type = "normal"; result = r },
    e => { type = "throw"; result = e }
).then(() => {
    print(`result: ${result} (${type})`)
})
```

**Comment by anba** [comment]
[PromiseResolve, step 2.b](https://tc39.es/ecma262/#sec-promise-resolve) is only taken for Promise objects, i.e. objects with a [[PromiseState]] internal slot, cf. [IsPromise](https://tc39.es/ecma262/#sec-ispromise).

**Comment by isiahmeadows** [comment]
@anba Oh okay. Misread that line. So I guess the issue here is that nobody is performing the `constructor` access required by step 2.a of PromiseResolve.

**Comment by anba** [comment]
`constructor` is only accessed for proper Promise objects, so if you pass a normal object, `constructor` is never read.

**Comment by isiahmeadows** [comment]
Oh okay. My brain has been elsewhere for a while, so I didn't quite follow what I originally filed. I see everything appears to be in working order (mod XS), so I'll go ahead and close it.
