### ISSUE TITLE
Re-Constructing

### ISSUE THREAD

**Issue by ertankara** [tc39/ecma262#1581]
Demonstrating an example to explain the proposal

```javascript
// Assume that I need to loop over some data source to extract the props I need
// from the objects

// Empty array to store new data after applying changes
const editedPeople = [];

for (const person of people) {
  // Let's say each person has the following props
  // person = { name, lastname, birthday, id, registerDate, lastLogin, uuid  }
  // but I only need some of them so I naturally de-construct it
  const { name, lastname, id, lastLogin } = person;

  // now I'm adding them to new array as a new object
  // I need to retype every prop I extracted and an additional prop `isExpired`
  editedPeople.push({ name, lastname, id, lastLogin, isExpired: false });
}
```

After writing similar code I thought it would be good if I could re-construct an object in place
as follows

```javascript
for (const person of people) {
  const { name, lastname, id, lastLogin } as newPerson = person;
  newPerson.isExpired = false;
  editedPeople.push(newPerson);
}
```

**Comment by nicolo-ribaudo** [comment]
I suggest reading https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#new-feature-proposals on how to propose a new feature :wink:

Also, it might be useful to read
https://esdiscuss.org/topic/proposal-syntactic-sugar-for-extracting-fields-from-objects
https://esdiscuss.org/topic/proposal-object-pick
https://esdiscuss.org/topic/extended-dot-notation-pick-notation-proposal
https://esdiscuss.org/topic/picking-deconstructing-properties-into-object-literals
