### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by mhxy13867806343** [tc39/ecma262#1584]
TC39 is open to accepting new feature requests for ECMAScript, referred to as
"proposals". Proposals go through a four-stage process which is documented in
the [TC39 process document](https://tc39.es/process-document/).

Feature requests for future versions of ECMAScript should not be made in this
repository. Instead, they are developed in separate GitHub repositories, which
are then merged into the main repository once they have received "Stage 4".

Please see [CONTRIBUTING.md](/CONTRIBUTING.md) for more details.

**Comment by ljharb** [comment]
This is just copy-pasted content from https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md.
