### ISSUE TITLE
27.5.5 ComposeWriteEventBytes abstract operation not clear

### ISSUE THREAD

**Issue by jaag5678** [tc39/ecma262#1586]
Could someone give a clarification on what the iteration within this operation is doing?

AS per my current understanding, it only picks one byte per Write event (even though the write can be to an entire chunk of bytes) and appending it to the list of bytes to be returned. 

My question is why is it composing a list as such, for we are only collecting one byte per Write event for a chunk, the resulting list of bytes makes little sense to me. 

A clarification on the Write events that compose the list Ws would also be appreciated.

An example of how this operation works for a given Ws, byteIndex  would also be good.

Thanks,
Akshay

**Comment by ljharb** [comment]
Closing; please ask this on the [Discourse](https://es.discourse.group/) instead.
