### ISSUE TITLE
27.6.2 read-bytes-from question 

### ISSUE THREAD

**Issue by jaag5678** [tc39/ecma262#1587]
Here are my questions : 

- Is the list mentioned having size R.ElementSize ?

- "Each event W with index i in Ws" -> What is 'i' here. Which index does it correspond to ? The list index ? 

- Is Ws strictly of size R.ElementSize ? 

Thanks,
Akshay

**Comment by michaelficarra** [comment]
A more appropriate place for this question would be [the discourse](https://es.discourse.group/).

**Comment by ljharb** [comment]
Closing; please ask this on the [Discourse](https://es.discourse.group/) instead.
