### ISSUE TITLE
12.9.2.1: Early Errors for NoSubstitutionTemplate

### ISSUE THREAD

**Issue by scole66** [tc39/ecma262#1588]
**Description:** Early Errors for Template Literals incorrect for NoSubstitutionTemplate

In section 12.2.9.1, the Early Errors for TemplateLiterals are spelled out. The first section there, for the production _TemplateLiteral : NoSubstitutionTemplate_, says that it should be a syntax error if the number of TemplateStrings for the production is too large.

The thing is, the number of TemplateStrings for a NoSubstitutionTemplate is, by definition, always equal to one.

I suspect the first condition should _actually_ be applied to the production _TemplateLiteral : SubstitutionTemplate_. (There are no early error rules specified for this production at all; rather they exist for its child productions, but never talk about a limit on the number of substitutions.)

**Comment by jmdyck** [comment]
Here's what happened:
- 2017-06-04: Originally, in 3d83089f (from PR #866), @anba associated that Early Error rule with the full production for `TemplateLiteral`.
- 2017-08-02: 138c9ef (from PR #773) made a lot of changes to that clause, accidentally deleting the rule.
- 2017-08-03: 38e9a19 (no PR) reinstated the rule, but associated it with the wrong production.

Someone should probably check if anything else was lost/misplaced by the above events.

**Comment by scole66** [comment]
Thanks for pointing out the history. Helps me to know that, no, I'm not misunderstanding some subtle point. It's just wrong.

**Comment by jorendorff** [comment]
I just ran into this independently, fwiw.
