### ISSUE TITLE
Promise.race can be optimized to stop iterating when it reaches an already resolved/rejected promise or value

### ISSUE THREAD

**Issue by bughit** [tc39/ecma262#1594]
```js
  function* lazyGen(iterable) {
    for (const lazy of iterable)
      yield lazyVal(lazy);
  }

  function lazyVal(valOrFn) {
    if (typeof valOrFn === 'function')
      return valOrFn();
    else
      return valOrFn;
  }

  function lazyRace(...promisesOrVals) {
    return Promise.race(lazyGen(promisesOrVals));
  }

  const result = await lazyRace(1, () => (console.log('invoked'), 2))

  console.log(result);
```

The iterable can be of arbitrary length and each iteration can execute an arbitrary amount of code, so it does not make sense to keep iterating after you know the race is won.

It's not obvious that the spec forbids this optimization, does it?

**Comment by ljharb** [comment]
Since the resolution can't be determined until a future tick, it seems like it should be forbidden?

**Comment by bughit** [comment]
Of course it can. We are not talking about user code here, but implementation, which has access to [[PromiseState]], so it's capable of detecting that iteration yielded a value or a non-pending promise.

**Comment by ljharb** [comment]
What I mean is, I believe the spec is written such that it's not observable in the same tick - this optimization seems like it would violate that.

**Comment by claudepache** [comment]
What is the point of this optimisation anyway? Do you expect to often feed lazily Promise.race with a great number of promises that are costly to grab, one of which is already settled?

(Note that Promise.all could be “optimised” the same way, if one of the promises is already rejected...)

**Comment by bughit** [comment]
> What is the point of this optimisation anyway?

The right question is what's the point of continued iteration after you know the race is won? The answer is, there is no point, so it shouldn't be done.

>  Do you expect to often feed lazily Promise.race with a great number of promises that are costly to grab, one of which is already settled?

Not doing unnecessary work, is a reasonable expectation for core api primitives.

> Note that Promise.all could be “optimised” the same way, if one of the promises is already rejected...

And it should be.

**Comment by ljharb** [comment]
The point is that the order of promises you pass into the combinators doesn't and shouldn't matter - it's the order of their resolution that matters. It's important to deterministically exhaust the iterator.

**Comment by bughit** [comment]
> The point is that the order of promises you pass into the combinators doesn't and shouldn't matter

That's wrong. For already resolved promises or values, the order of resolution is unknown, they are already resolved, and it is the order of iteration that determines the race result. Promise.race(1, 2) will always resolve with 1.

>  It's important to deterministically exhaust the iterator.

The core semantics of race is that the first resolved/rejected promise/value wins, there is no importance to exhausting the iterator. It's just as absurd as exhausting the iterator in Array#find after a match.

**Comment by devsnek** [comment]
there is no iterator in Array#find. the issue with your optimization is that it creates user-observable behaviour (since one can make a custom iterator) that defies the behaviour of promises, which is that their value is only available in a resolution handler.

**Comment by bughit** [comment]
> there is no iterator in Array#find

"exhausting the iterator" in this context means continuing the search after a mach

> that defies the behaviour of promises, which is that their value is only available in a resolution handler.

This optimization will not make the value of an already resolved promise available outside a handler. Promise.race does not return a value, but a promise.

It would indirectly leak the promise state, but that was not your argument.

So far you have provided three invalid arguments:

1. The point is that the order of promises you pass into the combinators doesn't and shouldn't matter
   - turns out the order matters
2. It's important to deterministically exhaust the iterator.
   - an assertion without backing, "it's important" is not an argument 
3. that defies the behaviour of promises, which is that their value is only available in a resolution handler
   - nope, value is not made available outside a handler

So now that I have formulated the argument for you, "It would indirectly leak the promise state", I will have to accept it, if the spec does indeed forbid the implementation form in any way, however indirectly, leaking the promise state. Does it?

**Comment by bakkot** [comment]
> It's not obvious that the spec forbids this optimization, does it?

It does forbid it. The spec [precisely defines the behavior of Promise.race](https://tc39.es/ecma262/#sec-performpromiserace), and that behavior does not include this optimization.

> if the spec does indeed forbid the implementation form in any way, however indirectly, leaking the promise state. Does it?

No, implementations are generally free to expose APIs other than those defined in the spec (but not to change the behavior of those it does define, including this one). However, that [doesn't mean it would be a good idea](https://blog.izs.me/2013/08/designing-apis-for-asynchrony).

**Comment by bughit** [comment]
> It does forbid it.

Well, that's what make this a feature request. There's [precedent](https://v8.dev/blog/fast-async) for altering the spec for optimization that don't break use code.

**Comment by ljharb** [comment]
This would break the inability to synchronously inspect promise state - with this optimization, I'd be able to, for example, do something akin to:
```js
function isResolved(promise) {
  let resolved = false;
  function* gen() {
    yield promise;
    resolved = true;
  }
  Promise.race(gen());
  return resolved;
}
```
(no idea if this exact code would work, but something similar to this approach, perhaps combining `Promise.all` as well, would enable me to synchronously inspect the state of a promise - which is intentionally and explicitly made impossible.
