### ISSUE TITLE
Multi Level Destructuring

### ISSUE THREAD

**Issue by sonsor** [tc39/ecma262#1610]
here is my purposal
```js
const data = {
    a: 10,
   b: {
    c: 5,
    d: {
       e: 15
    }
   }
}
const {
    a,
   { c } = b,
   { d } = b,
   { e } = { d }
} = data
```
or 
```
const {
   a,
   b{c},
  b{d}{e}
} = data
```
like what i going to purpose is do a multi level destructuring in one go instead of doing again and again in seperate line so i can grad only specific data from an object instead of grabbing complete object.
like what i mostly faced in react development got get a sub level value and for that i have to do same amount of destructuring as value hirachy level.

**Comment by nicolo-ribaudo** [comment]
```js
const {
  a,
  b: {
    c,
    d,
    d: { e }
  },
} = data
```

It already exists.

**Comment by ljharb** [comment]
In addition, this repo isn’t the right place for feature requests. See https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal
