### ISSUE TITLE
正则这一块不太懂，有比较好的博客推荐吗？

### ISSUE THREAD

**Issue by hushilin01** [tc39/ecma262#1619]
**Description:** Adding 1 and 1 is two, but it should be...

**eshost Output:**

```
$ eshost -s -e "1 + 1"
#### Chakra, JavaScriptCore, SpiderMonkey, V8, XS
2
```

**Comment by ljharb** [comment]
I’m very unclear on what your question is.

**Comment by ljharb** [comment]
Closing as spam, since the issue template is being posted unmodified.
