### ISSUE TITLE
%RegExpStringIteratorPrototype% unlisted in Well-Known Intrinsic Objects table

### ISSUE THREAD

**Issue by bathos** [tc39/ecma262#1624]
This is probably just a minor oversight: it seems like %RegExpStringIteratorPrototype% should be present alongside the rest of the intrinsic objects that are referenced in algorithms in [this table](https://tc39.es/ecma262/#sec-well-known-intrinsic-objects).

**Comment by ljharb** [comment]
While an oversight, my hope is that that entire table becomes largely obsolete once #1376 lands - however i think this particular intrinsic might still need to be documented anyways.

**Comment by ljharb** [comment]
→ #1625
