### ISSUE TITLE
A new edition of IEEE-754 has been published

### ISSUE THREAD

**Issue by allenwb** [tc39/ecma262#1650]
Note that  IEEE 754-2019 has been published.

Changes summarized in http://754r.ucbtest.org/background/ 

Probably nothing that impacts ECMA-262 but we may want to update any normative references.

**Comment by leobalter** [comment]
I wonder if these items might find some entertainment on ECMA-262's work:

- new quantum operation for decimal formats is recommended
- new tanPi, aSinPi, and aCosPi operations are recommended

**Comment by leobalter** [comment]
Thanks for sharing this, @allenwb!

**Comment by waldemarhorwat** [comment]
What is "new quantum operation for decimal formats"?

**Comment by apaprocki** [comment]
> What is "new quantum operation for decimal formats"?

It adds to existing *5.3.2 Decimal operation* section (containing `quantize(x)`) a new `quantum(x)` operation that returns the number represented by `(0, q, 1)` where `q` is the exponent of `x`.
