### ISSUE TITLE
Why is it still called ECMAScript if the organization has officially changed it's name to Ecma (lowercase)?

### ISSUE THREAD

**Issue by Ursi** [tc39/ecma262#1659]

**Comment by ljharb** [comment]
cc @ecmageneva

**Comment by ecmageneva** [comment]
It is a good question. Brendan would know better the exact reason. My guess is the following:  Actually "ECMA" became in 1994 "Ecma International". But in the standards numbering we have kept "ECMA-xxx". So my feeling is that the ECMA in ECMAScript came from there, which became Ecma standard in 1997 or 1998. This was also a not ideal solution, but Sun / Oracle had/has the trademark on JavaScript, which they do not want to give up until today....

**Comment by allenwb** [comment]
Having reviewed a lot of Ecma documents from 1996-1997 it appears to me that ECMA was stilling in common usage at that time.

**Comment by jorydotcom** [comment]
In addition to that from @ecmageneva - Ecma officially registered the 'ECMAscript' mark that accompanies ECMA-262 on the standard; I don't imagine at this point it makes sense for us to switch it up. Also I think maybe Ecmascript seems harder to read?

**Comment by leobalter** [comment]
there are too many places to update the name if it changes. Unless we come up with an amazing new name, like Froyo, Smooch, or even JavaScript (if released by Oracle), I don't think it's worth the work.

**Comment by ljharb** [comment]
Closing as answered.

**Comment by Ursi** [comment]
@jorydotcom Actually the S is capitalized, so it would be EcmaScript.
