### ISSUE TITLE
Normative: bug re Annex B production for AtomEscape

### ISSUE THREAD

**Issue by jmdyck** [tc39/ecma262#1672]
The main-body definition of [AtomEscape](https://tc39.es/ecma262/#prod-AtomEscape) says (in part):
> AtomEscape[U, N] :: CharacterEscape[?U]

but the Annex-B definition of [AtomEscape](https://tc39.es/ecma262/#prod-annexB-AtomEscape) says:
> AtomEscape[U, N] :: CharacterEscape[~U, ?N]

So if `AtomEscape` is 'invoked' with `+U`, main-body uses `CharacterEscape[+U]` whereas Annex-B uses `CharacterEscape[~U]`.

This is presumably a bug, since Annex B claims that it doesn't change any [+U] syntax.

----

It looks like the bug was introduced in 251dcef6 (for PR #403), where (using the old notation for grammatical parameters)
```
AtomEscape[U] ::
  [+U] CharacterEscape[U]
  [+U] CharacterClassEscape
  [~U] CharacterClassEscape
  [~U] CharacterEscape

```
was changed to:
```
AtomEscape[U] ::
  CharacterClassEscape
  CharacterEscape
```
but should have been changed to:
```
AtomEscape[U] ::
  CharacterClassEscape
  CharacterEscape[?U]
```

(Compare to the same commit's parallel change to the `ClassEscape` production, where `CharacterEscape` *does* get the `[?U]`.)

@anba, please confirm.

**Comment by mathiasbynens** [comment]
@jmdyck's reasoning makes sense to me. I'd love to hear from @anba in case I'm missing something.

**Comment by bakkot** [comment]
I agree with @jmdyck. Having CharacterEscape parsed with `~U` here would mean `/\z/u` would be legal (NB `z` is not a valid escape), as derived from `CharacterEscape[U] :: IdentityEscape[?U]` -> `IdentityEscape[U] -> [~U] SourceCharacterIdentityEscape`. That definitely is not the intent, and indeed all major engines reject `/\z/u`.

**Comment by bakkot** [comment]
Fixed by https://github.com/tc39/ecma262/pull/2235.
