### ISSUE TITLE
bug? re lookbehind assertions in Annex B

### ISSUE THREAD

**Issue by jmdyck** [tc39/ecma262#1674]
When lookbehind assertions were introduced in bf8a9be4 (PR #1029), there was no change to Annex B.

Later, e5b66059 (PR #1102) added lookbehind assertions to the 'Assertion' production in Annex B.

However, I think Annex B needs one more collateral change. The original PR added the `direction` parameter to the `evaluate` semantics for Disjunction, Alternative, Term, Atom, and AtomEscape, and also added it to the parameter list for CharacterSetMatcher. Annex B picks up most of these changes implicitly, but I believe it needs to add the `_direction_` parameter to the calls to CharacterSetMatcher in the two evaluation rules for ExtendedAtom.

Attn @mathiasbynens, @littledan, @claudepache, @IgnoredAmbience ?

**Comment by mathiasbynens** [comment]
Yeah, that makes sense to me. Thanks for catching this!
