### ISSUE TITLE
Remove Keyword

### ISSUE THREAD

**Issue by jorendorff** [tc39/ecma262#1678]
This proposes a change in presentation with no normative effect.

For readers, the existence of the *Keyword* nonterminal is suggestive. It sounds like it's a category that means something, that these 34 words have some syntactic property in common that is not also shared by other words like `static` and `let`.

But they don't. The word "keyword" appears 18 times in the current draft, but **its only normative use is to include the *Keyword* list in the *ReservedWord* list.** This really set me on the wrong track; I felt misled by the spec.

So I propose defining *ReservedWord* by listing all the reserved words, and removing *Keyword* and *FutureReservedWord*, to simplify the spec.

**Comment by allenwb** [comment]
Is there an actual significant problem the  change would address?  Perhyaps, something new that needs to be expressed that the current formulation interferes with?  If not, why is anybody worrying about it.

**Comment by ljharb** [comment]
The OP suggests making a change would reduce confusion.

**Comment by devsnek** [comment]
It's worth mentioning that "keyword" and "reserved word" are not just terms made up for ecma262, they have meaning in computer science, so i think it makes sense to use them.

**Comment by jorendorff** [comment]
This issue is about the *Keyword* grammar symbol.

I endorse @allenwb's definitions of "keyword" and "reserved word". In fact that's why *Keyword* should be deleted. The problem is that *Keyword* does not mean "keyword".

Also, it's unused.

The initial post explains further.
