### ISSUE TITLE
optional type declaration for function parameter and return value like Python

### ISSUE THREAD

**Issue by lithic** [tc39/ecma262#1682]

**Comment by ljharb** [comment]
Please see https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal for how to best suggest new features for the language.

Duplicate of https://github.com/tc39/proposals/issues/239

**Comment by lithic** [comment]
Are you a robot

**Comment by ljharb** [comment]
Not that I’m aware.

**Comment by lithic** [comment]
@ljharb please reopen this issue

**Comment by lithic** [comment]
@ljharb there are many issues that are opened for discussion. please also make this one of them.

**Comment by lithic** [comment]
@ljharb i am sorry for
>are you a robot

**Comment by nicolo-ribaudo** [comment]
@lithic The issues opened for discussion are only for editorial changes to the spec text, or for really minor behavioral changes. New features, or big changes, require a separate proposal.

**Comment by ljharb** [comment]
Specifically, no new features are discussed on this repo.
