### ISSUE TITLE
How property may change if it is non-configurable and non-writable

### ISSUE THREAD

**Issue by dSalieri** [tc39/ecma262#1688]
And the question is, I quote:

> **[[GetOwnProperty]] ( P )**
> 
> - The Type of the return value must be either Property Descriptor or Undefined.
> - If the Type of the return value is Property Descriptor, the return value must be a complete property descriptor.
> - _**If P is described as a non-configurable, non-writable own data property, all future calls to [[GetOwnProperty]] ( P ) must return Property Descritor whose [[Value]] is SameValue as P's [[Value]] attribute.**_
> - If P's attributes other than [[Writable]] may change over time or if the property might be deleted, then P's [[Configurable]] attribute must be true.
> - If the [[Writable]] attribute may change from false to true, then the [[Configurable]] attribute must be true.
> - If the target is non-extensible and P is non-existent, then all future calls to [[GetOwnProperty]] (P) on the target must describe P as non-existent (i.e. [[GetOwnProperty]] (P) must return undefined).
>
>NOTE 2
>As a consequence of **the third invariant**, if a property is described as a data property and it may return different values over time, then either or both of the [[Writable]] and [[Configurable]] attributes must be true even if no mechanism to change the value is exposed via the other internal methods.

It seems to me (but maybe I didn’t understand something) that this is not logical. How can a non-configurable, non-writable property somehow change its value over time? For me, what is written in the note does not follow logically from the third invariant. In the third invariant, it is clearly written to always return the same value if the property is non-configurable, non-writable. What is wrong here?

**Comment by bakkot** [comment]
> How can a non-configurable, non-writable property somehow change its value over time?

It can't. I think you've misread the Note.

"If a property is described as a data property and it may return different values over time, then either or both of the [[Writable]] and [[Configurable]] attributes must be true" (which is what is in the note) is [logically equivalent to](https://en.wikipedia.org/wiki/Contraposition) "if property is described as a data property and both the [[Writable]] and the [[Configurable]] attributes are false, then the property man not return different values over time" (which is what is in the third invariant).

**Comment by dSalieri** [comment]
@bakkot Do you say the law of counterposition?  `A => B` is thus `¬B => ¬A`
Then the statement is the third invariant `(A)`, and the consequence is the note `(B)`.
You in your answer to me, do the negation of the note `(B) --> (¬B)`, but do not negate the invariant `(A) --x (¬A)`. According to the rules of contraposition: if `A => B`, then `¬B => ¬A`.

Your example is the usual discrete negation of a note `(B) --> (¬B)`. You negate the note, and then it turns out logically that the note corresponds to the invariant that is, `¬B => A`
Or didn’t I understand something again?

**Comment by bakkot** [comment]
> Then the statement is the third invariant (A), and the consequence is the note (B).

I think you have misunderstood.

Both the invariant and the note are if-then statements about data properties.

The invariant is, paraphrasing, "(not configurable AND not writable) => (value does not change)".

The note is, paraphrasing, "(value changes) => (configurable OR writable)".

The contrapositive of the first statement is "not (value does not change) => not (not configurable AND not writable)". Apply De Morgan's law to the consequent this and it becomes "not (value does not change) => (not not configurable OR not not writable)". Cancel double negations in both the antecedent and the consequent and this becomes "(value changes) => (configurable OR writable)". This is now exactly the note. So the invariant and the note are logically equivalent.

**Comment by dSalieri** [comment]
@bakkot
>The invariant is, paraphrasing, "(not configurable AND not writable) => (value does not change)".

Got it! `(¬A ⋀ ¬B) => (¬C)`

>The note is, paraphrasing, "(value changes) => (configurable OR writable)".

Got it! `(С) => (A ⋁ B)`

>The contrapositive of the invariant is "not (value does not change) => not (not configurable AND not writable)"

Got it! `¬(¬C) => ¬(¬A ⋀ ¬B)`

>The contrapositive of the invariant is "not (value does not change) => not (not configurable AND not writable)". Apply De Morgan's law to the consequent this and it becomes "not (value does not change) => (not not configurable OR not not writable)". Cancel double negations in both the antecedent and the consequent and this becomes "(value changes) => (configurable OR writable)". This is now exactly the note. So the invariant and the note are logically equivalent.

`¬(¬C) => ¬(¬A ⋀ ¬B) -->
 ¬(¬C) => (¬¬A ⋁ ¬¬B) --> 
(С) => (A ∨ B)`

Yes, according to logical laws, everything is clean, you can’t find fault, but ...
_Why it is not explicitly?_ _Why it was impossible to write in an understandable form without applying the laws of logic?_ It is not obvious if you do not know this thin moment.
P.S In fact, the question is answered, but if you know the answers to the questions above, answer.

**Comment by bakkot** [comment]
If you have a better phrasing to propose, feel free to submit a PR! Usually the answer to "why is this written in this way" is "it's the best we've come up with so far".

**Comment by dSalieri** [comment]
@bakkot I want to notice that in ECMAScript 5.1, the note is the first invariant, and the second invariant is the third invariant from here. This is a strange reorganization, from an invariant into a note, and not just into a note, but as a consequence of the third invariant. So it's hard for me to advise anything. But it is worth asking a question, is this note necessary, and how important is it here?

**Comment by ljharb** [comment]
I'd assume every note is necessary and important :-)

This seems answered.
