### ISSUE TITLE
Missing completion reform in 13.7.5.12

### ISSUE THREAD

**Issue by bterlson** [tc39/ecma262#169]
At least based on a cursory glance, the following statement results in a completion value of "Empty":

```
for (let x of returnsUndefinedOrNull()) { }
```

Probably need an UpdateEmpty in there.

**Comment by anba** [comment]
Evaluation of *BreakableStatement*s goes through 13.1.8 and 13.1.7. 13.1.7, step 2 takes care of empty break completions.

**Comment by bterlson** [comment]
Indeed! UpdateEmpty is used for other IterationStatements though.
