### ISSUE TITLE
Editorial: add links to individual algorithms

### ISSUE THREAD

**Issue by brabalan** [tc39/ecma262#1690]
Some sections of the specification (such as https://tc39.es/ecma262/#sec-equality-operators-runtime-semantics-evaluation) contain multiple algorithms for different syntactic constructs. Is there a way to add an anchor to each one? It could either be as subsections or as internal anchors.

**Comment by ljharb** [comment]
This seems like more of an ecmarkup question; could you file an issue there? https://github.com/bterlson/ecmarkup

**Comment by jmdyck** [comment]
@ljharb, are you thinking that ecmarkup could auto-generate long-term-stable anchors for each such algorithm? I think that might be somewhat difficult. (Easy if you don't care about stability, of course.)

**Comment by ljharb** [comment]
Yes, or alternatively, provide a mechanism for attaching a stable identifier that's more structured than just sticking an anchor tag in.

**Comment by brabalan** [comment]
Thanks, I will file an issue there. Feel free to close this unless you want to keep it open to track it.

**Comment by ljharb** [comment]
Closing in favor of https://github.com/bterlson/ecmarkup/issues/156
