### ISSUE TITLE
What should be the result of `''.split('')`?

### ISSUE THREAD

**Issue by hoang4** [tc39/ecma262#1699]
What should be an answer to an empty string splitted by an empty string?
It should either be:
- `undefined`
- `['']`
- `throw new RangeError('')`

**Comment by ljharb** [comment]
I believe split always produces an array, so i wouldn’t expect any of those.

**Comment by hoang4** [comment]
The second option should be an array, my mistake

**Comment by nicolo-ribaudo** [comment]
It's `[]`. `anyString.split("")` gives you an array of the characters in the string. If there isn't any character (`""`), the resulting array is empty:
```js
"abc".split("") // ["a", "b", "c"]
"a".split("") // ["a"]
"".split("") // []
```

**Comment by ljharb** [comment]
Given that it [currently produces](https://repl.it/repls/UniformFastMoto) `[]`, what’s the goal of your question?

**Comment by jorendorff** [comment]
Haha, this is one of those 0**0 situations—no matter what the answer was, it was going to break two out of the following three "laws", all of which are true for all nonempty strings `s`:

*   `s.split("")` is `[...s]`
*   `"".split(s)` is `[""]`
*   `s.split(s)` is `["", ""]`

That said, even if there were a clear winner, backward compatibility is a higher law altogether. Better leave it how it is.
