### ISSUE TITLE
Generate a multi‑page version of the ECMA‑262 specification

### ISSUE THREAD

**Issue by ExE-Boss** [tc39/ecma262#1700]
The **ECMA‑262** single‑page specification is very long.

I propose to also generate a multi‑page version similar to what the **WHATWG** is doing with **HTML:** https://html.spec.whatwg.org/multipage/

This way, every top‑level heading will be placed on its own sub‑page.

I expect the resulting URL to be: https://tc39.es/ecma262/multipage/

---

This will probably require support in [ecmarkup](https://github.com/bterlson/ecmarkup).

**Comment by cpplearner** [comment]
See https://github.com/bterlson/ecmarkup/issues/151

**Comment by ExE-Boss** [comment]
Closing as duplicate of #1270
