### ISSUE TITLE
Note in CreateDynamicFunction unclear

### ISSUE THREAD

**Issue by erights** [tc39/ecma262#1701]
At https://www.ecma-international.org/ecma-262/10.0/index.html#sec-createdynamicfunction is the note

> A prototype property is created for every non-async function created using CreateDynamicFunction to provide for the possibility that the function will be used as a constructor.

Unclear if "non-async functions" is intended to include async generator functions.

**Comment by ljharb** [comment]
Given that out of `(async function(){}).prototype`, `(async function*(){}).prototype`, and `(function*(){}).prototype`, the only one without a prototype is `async function`, perhaps the text should read `any function whose _kind_ is not *"async"*`?
