### ISSUE TITLE
Fix accidental non-determinism in spec of %GeneratorFunction%[[Prototype]]

### ISSUE THREAD

**Issue by erights** [tc39/ecma262#1707]
See 
https://github.com/Agoric/harden/issues/47#issuecomment-522341574
https://github.com/Agoric/harden/issues/47#issuecomment-524299183

I always assumed that the %GeneratorFunction% constructor must directly inherit from the %Function% constructor, mimicking a subclass relationship. Indeed, this is what is shown in the diagram at the top of 25.2. However, as @phoddie point out at https://github.com/Agoric/harden/issues/47#issuecomment-522341574
this diagram is explicitly non-normative. However, since it is so much easier to navigate than the spec text, I never noticed that the spec text fails to say normatively everything the diagram says informatively.

This failure was accidental. TC39 never agreed that there's any reason to leave, for example, this inheritance relationship to implementor choice. Likely, it was just a failure to turn diagram into precise text. The result was spec non-determinism for no reason whatsoever. @allenwb , do you agree?

In general, the *entire* points-to graph among all the primordial objects should be specified precisely and normatively. If there is any primordial points-to relationship that we wish to intentionally leave to implementor choice, the spec should say so explicitly, so that we can distinguish these case from the much more likely spec writing oversight.

**Comment by allenwb** [comment]
I don't see where this is under-specified.  In ES6 [25.2.2](https://www.ecma-international.org/ecma-262/6.0/index.html#sec-properties-of-the-generatorfunction-constructor) said: 

> The value of the [[Prototype]] internal slot of the GeneratorFunction constructor is the intrinsic object %Function%.

The [current drafts](https://tc39.es/ecma262/#sec-properties-of-the-generatorfunction-constructor) is formatted differently, but still says essentially the same thing.

What am I missing?

**Comment by erights** [comment]
Hi @allenwb my mistake. I don't know how both @phoddie and I missed that. Thanks! Closing.
