### ISSUE TITLE
What is the meaning of the following sentence in "6.2.2 The Set and Relation Specification Types"

### ISSUE THREAD

**Issue by dSalieri** [tc39/ecma262#1711]
The specification has the following sentence, sounds like:

>A Relation is least with respect to some conditions when it is the smallest Relation that satisfies those conditions.

Is it possible to somehow formulate this sentence by another way? Well, this sentence clearly needs an example of a relations, otherwise it sounds abstract enough to understand it.

I know this section, strange enough for people who are at least fundamentally unfamiliar with set theory. But here it is clearly evident. So clarify with examples this sentence or the corresponding terminology from mathematics.

---

As additional data:
[Agent-Order](https://tc39.es/ecma262/#sec-agent-order) is simple **Relation**
but
[Reads-From](https://tc39.es/ecma262/#sec-reads-from) is **least Relation**
Any reasons why so it is?

**Comment by waldemarhorwat** [comment]
My nitpicking is partially responsible for the _least_ requirement here, as some of the uses of Relations would be incorrect if they weren't _least_.

To clarify, perhaps extend the sentence to something like:

"A Relation is least with respect to some conditions when it is the smallest Relation that satisfies those conditions. In other words, Relation _R_ is least with respect to conditions _C_ if _R_ satisfies _C_ and there exists no other Relation _R'_ such that _R'_ also satisfies _C_ and,  for some _a_ and _b_, _a R b_ but not _a R' b_.

**Comment by dSalieri** [comment]
@waldemarhorwat You again imitate the specification itself, trying to communicate what the least relation is. From the point of view of logic, this is a relation that corresponds to some conditions, but at the same time the number of pairs must be the smallest that correspond some condition.

Your sentence is also not clear, you are trying to play with terms from set theory and at the same time confuse the reader (I did not understand the last part of the sentence - what is R with '). This section needs to be described (as I think) in strict terms of logic and nothing more.

And again, there are no examples of the relations themselves. It is impossible to understand what will have to operate in the future. Here, at least, the smallest relation and not the smallest, as well as the elements of these relations, should be illustrated. An example of a relationship with ordinary numbers is not good :)

**Comment by ljharb** [comment]
This seems answered? Will reopen if not.
