### ISSUE TITLE
Don't understand the meaning of the Ecma specification == coercion

### ISSUE THREAD

**Issue by V0lantis** [tc39/ecma262#1715]
In taking a look in the latest ECMAScript specifications, I read [7.2.14Abstract Equality Comparison](https://www.ecma-international.org/ecma-262/10.0/index.html#sec-abstract-equality-comparison).

It says : 
**4. If Type(x) is Number and Type(y) is String, return the result of the comparison x == ! ToNumber(y).**

why is there an exclamation (!) point before the `ToNumber` function?.
if this function coerce the `y`string into a number (as far as possible), why coerce it into a boolean afterward? And furthermore, why wanted to do a 'not `y`'? 

does it mean that
```Javascript
let x = 3, y = '3';
x == y // false ?
```
I'm sorry if this question has been asked before, and if the answer is trivial, but I didn't find an answer on Google, otherwise I wouldn't have asked.
I'm seeking for an explanation of what this specification means.

Thank you for your time and your answers !

**Comment by brabalan** [comment]
This is not a negation, but a shorthand indicating that `ToNumber` cannot return an abrupt completion: https://tc39.es/ecma262/#sec-returnifabrupt-shorthands
