### ISSUE TITLE
Editorial: mathematical operations on BigInts

### ISSUE THREAD

**Issue by jmdyck** [tc39/ecma262#1723]
[5.2.5 Mathematical Operations](https://tc39.es/ecma262/#sec-mathematical-operations) begins:
```
This specification makes reference to two kinds of numeric values:
[Number and Mathematical value]
```
This clause should presumably be updated to acknowledge BigInts.

(Of the specific operations defined, I think `modulo` is the only one that the spec currently applies to BigInt values.)

**Comment by ljharb** [comment]
cc @caiolima @littledan

**Comment by bakkot** [comment]
I believe #2007 comprehensively resolved this.
