### ISSUE TITLE
List in "Mailing List Archives" auto-linked

### ISSUE THREAD

**Issue by michaelficarra** [tc39/ecma262#1730]
![Screenshot from 2019-10-08 16-34-56](https://user-images.githubusercontent.com/218840/66440933-b253d100-e9e9-11e9-8a42-d9645c27643b.png)

The word "List" above links to section 6.2.1, The List and Record Specification Types. That shouldn't be linked.

**Comment by ljharb** [comment]
I noticed that - is there a way in ecmarkup to prevent auto-dfn-linking?
