### ISSUE TITLE
Use of [[value]] internal slot on ECMAScript language type.

### ISSUE THREAD

**Issue by Ursi** [tc39/ecma262#1744]
[25.6.1.3.2](https://www.ecma-international.org/ecma-262/#sec-promise-resolve-functions) step 9 is

Let `then` be `Get(resolution, "then")`

`Get` returns an ECMAScript language type, not a [Property Attribute](https://www.ecma-international.org/ecma-262/#sec-property-attributes). However, the algorithm goes on to use `then.[[value]]`. As far as I can tell, ECMAScript language types don't have a `[[value]]` internal slot.

**Comment by devsnek** [comment]
Get returns a Completion, which does have [[Value]].

**Comment by Ursi** [comment]
uhg, the `?` of course. I feel like I've trained myself to just filter those out. My bad.

**Comment by jmdyck** [comment]
No, you're right, the `?` (on step 3 of `Get`) indicates that `Get` can return an abrupt completion. The Promise Resolve Function's step 10 checks to see if it did, and if so, 10.a extracts that abrupt completion's `[[Value]]` field.

**Comment by Ursi** [comment]
@jmdyck the real culprit was [5.2.3(.1)](https://www.ecma-international.org/ecma-262/#sec-runtime-semantics). I was unaware that `Return` implicitly wrapped its value in `NormalCompletion`.

**Comment by michaelficarra** [comment]
@Ursi Yes, section [5.2.3.1, Implicit Completion Values](https://www.ecma-international.org/ecma-262/#sec-implicit-completion-values), has been the source of much spec reader pain. Follow along at #497, #1572, #253, and others.
