### ISSUE TITLE
No implementation distinguishes -0 in Strings and TypedArrays

### ISSUE THREAD

**Issue by syg** [tc39/ecma262#1751]
**Description:** The String and TypedArray exotic objects special case **-0** as an index:

Jakob Kummerow from V8 noticed that no implementations special case **-0** for TypedArrays, so I did some more digging.

- [[[StringGetOwnProperty]]](https://tc39.es/ecma262/#sec-stringgetownproperty) step 7 says strings don't have **-0** as an own property.
- Integer-Indexed exotic objects' [[[HasProperty]]](https://tc39.es/ecma262/#sec-integer-indexed-exotic-objects-hasproperty-p) step 3.b.iv, [[[DefineOwnProperty]]](https://tc39.es/ecma262/#sec-integer-indexed-exotic-objects-defineownproperty-p-desc) step 3.b.ii, [IntegerIndexedElementGet](https://tc39.es/ecma262/#sec-integerindexedelementget) step 6, and [IntegerIndexedElementSet](https://tc39.es/ecma262/#sec-integerindexedelementset) step 8 all consider **-0** as out of bounds on TypedArrays.

However, implementation reality is that nothing distinguishes **-0** from **0** as an index:

**eshost Output:**

neg-zero.js
```javascript
let str = "foo";
let ta = new Uint8Array(32);
ta[-0] = 42;
print(Object.getOwnPropertyDescriptor(str, -0).value,
      ta[-0],
      Object.prototype.hasOwnProperty.call(ta, -0));
```

```
$ eshost -s neg-zero.js
#### Chakra, JavaScriptCore, SpiderMonkey, V8, XS
f 42 true
```

We ought to not distinguish **-0** for those exotic objects.

**Comment by ljharb** [comment]
Strings don't have -0 as an own property; but I'd expect `-0` to be run through `ToPropertyKey` which normalizes it to `'0'`.

**Comment by syg** [comment]
Ah indeed, I think I may be wrong about this whole thing then.

**Comment by syg** [comment]
I am indeed wrong. Integer-Indexed exotic objects run their keys through CanonicalNumericIndexString, and indeed, `ta["-0"]` always returns undefined.
