### ISSUE TITLE
JSON.stringify with bigint

### ISSUE THREAD

**Issue by devsnek** [tc39/ecma262#1755]
It is expected by test262 and perhaps the world at large that adding a `toJSON` function to `BigInt.prototype` will result in that `toJSON` function being called if `JSON.stringify(some bigint)` is performed.

However, `SerializeJSONProperty` only checks for `toJSON` if the value is an Object:

1. Let value be ? Get(holder, key).
2. If Type(value) is Object, then
  a. Let toJSON be ? Get(value, "toJSON").
  b. If IsCallable(toJSON) is true, then
    1. Set value to ? Call(toJSON, value, « key »).
3. ...

cc @littledan @caiolima

**Comment by ljharb** [comment]
I assume Number.prototype.toJSON is thus  not called either?

**Comment by devsnek** [comment]
@ljharb no, but it's not supposed to be either. BigInt seems to be a special case.

**Comment by ljharb** [comment]
the implication is that when discussing bigint, the committee *did* think it’s supposed to be - otherwise I’d expect bigint to not be called either.

iow i don’t think bigint should be a special case, whichever direction we go.

**Comment by devsnek** [comment]
There is a web reality problem though:

```
$ eshost -ts -x "BigInt.prototype.toJSON = () => 'bigint'; print(JSON.stringify(1n))"
┌────────────────┬──────────────────────────────────────────────────────────────────────┐
│ ChakraCore     │                                                                      │
│                │ SyntaxError: Unexpected identifier after numeric literal             │
├────────────────┼──────────────────────────────────────────────────────────────────────┤
│ engine262      │                                                                      │
│ engine262+     │ TypeError: Cannot serialize a BigInt to JSON                         │
├────────────────┼──────────────────────────────────────────────────────────────────────┤
│ JavaScriptCore │                                                                      │
│                │ SyntaxError: No identifiers allowed directly after numeric literal   │
├────────────────┼──────────────────────────────────────────────────────────────────────┤
│ QuickJS        │ at /tmp/uqzc9Ybuyjxq16iNykim/f-1571950091961-10970-2b77w1.mlgd2.js:1 │
│                │ SyntaxError: invalid number literal                                  │
├────────────────┼──────────────────────────────────────────────────────────────────────┤
│ SpiderMonkey   │ "bigint"                                                             │
│ V8             │                                                                      │
│ XS             │                                                                      │
└────────────────┴──────────────────────────────────────────────────────────────────────┘
```

**Comment by ljharb** [comment]
We can make an error not be one and it’s still backwards compatible, i believe.

**Comment by rkirsling** [comment]
(FWIW, JSC matches SM/V8/XS in that chart when the flag is on.)

**Comment by apaprocki** [comment]
I specifically asked for this in plenary and there was consensus to add it. @littledan added the normative text in tc39/proposal-bigint@4be12d62f9371f46ee4001b30baddf4d10591bc9. So this appears to be an omission when crafting the PR from the repo.

Related links:
- tc39/proposal-bigint@18597c360565e2dd047dd831c15fd8becdfd14fa
- tc39/proposal-bigint@58e0abb455560f47bfd713e8dcbcc1862bb12c41
- https://github.com/tc39/proposal-bigint/issues/47

**Comment by apaprocki** [comment]
https://tc39.es/proposal-bigint/#sec-serializejsonproperty shows the rendered diff:

<img width="894" alt="Screen Shot 2019-10-24 at 9 46 10 PM" src="https://user-images.githubusercontent.com/767372/67537032-b3eaed80-f6a7-11e9-8e8a-9e403008f2ec.png">

**Comment by Lizard-King101** [comment]
You should update your tooling
