### ISSUE TITLE
try grammar 

### ISSUE THREAD

**Issue by linushp** [tc39/ecma262#1763]
like these :

> let x = try a.b.c.d
> let y = try a.b.c.d || e.a.d.c || d.d.f.s
> let z = try a.b.c.d && e.a.d.c || d.d.f.s

**Comment by devsnek** [comment]
if you're talking about safe chain access, js has `a?.b?.c?.d`. check out https://v8.dev/features/optional-chaining

**Comment by linushp** [comment]
> if you're talking about safe chain access, js has `a?.b?.c?.d`. check out https://v8.dev/features/optional-chaining

Yes, but the optional-chaining grammar is very ugly

**Comment by claudepache** [comment]
> try grammar

And what are the semantics? And before that: What is the problem you’re trying to solve?

* If you’re proposing a variant of the try/catch construct that is more practical to use, you may be interested in this thread: https://es.discourse.group/t/try-catch-oneliner/107.
* If you’re proposing something that will just ignore thrown exceptions, I fear you’re out of luck. (Note that Optional chaining does not swallow exceptions.)
* If you’re proposing something that is already solvable by Optional chaining, I fear you’re also out of luck, however ugly its grammar is.

In any case, this repo is most probably not the right venue (per https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#new-feature-proposals).

**Comment by ljharb** [comment]
Closing; see last sentence of previous comment.
