### ISSUE TITLE
set{Hours,Minutes,Seconds} inconsistent across Browsers for DST

### ISSUE THREAD

**Issue by Dru89** [tc39/ecma262#1767]
**Description:** `setMinutes` doesn't appear to do the right thing with respect to Daylight Saving Time in general and behaves inconsistently across browsers. (The same is true for `setHours` and `setSeconds`, but I'll use `setMinutes` to demonstrate here.)

Both [the TC39 docs for setMinutes](https://tc39.es/ecma262/#sec-date.prototype.setminutes) and [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setMinutes#Description) seem to indicate that if you use it like `date.setMinutes(date.getMinutes() + 30)`, that it will "add thirty minutes to the current time." When you get to a DST overlap, though, this doesn't seem accurate.

Instead of showing "1:00am PDT, 1:30am PDT, 1:00am PST, 1:30am PST, 2:00am PST" it shows something more like "1:00am PDT, 1:30am PDT, 2:00am PST, 2:30am PST", skipping over the "extra hour" altogether. And deciding whether that initial 1:00am and 1:30am is PDT or PST seems to vary across browsers as well.

Apologies if this doesn't feel like the right place. But as I was reading the spec for 262 it doesn't seem to capture this case so it seemed like a natural first stop. If you don't feel like it belongs here but have a better idea where it might, I'm happy to go bark up that tree.

#### `wrong-output.js`
```js
let date, node, result = "";
let fmt = new Intl.DateTimeFormat("en-US", {
  day: "numeric",
  month: "short",
  hour: "numeric",
  minute: "numeric",
  timeZoneName: "long"
});

let log = data => (result = `${result}\n${data}`);

// Gives the "incorrect" response.
// (And has inconsistent behavior w.r.t. timezone across browsers.)
date = new Date(2019, 10, 3);
for (let i = 0; i < 9; i++) {
  log(fmt.format(date));
  date.setMinutes(date.getMinutes() + 30);
}

print(result);
```

#### `right-output.js`
```js
let date, node, result = "";
let fmt = new Intl.DateTimeFormat("en-US", {
  day: "numeric",
  month: "short",
  hour: "numeric",
  minute: "numeric",
  timeZoneName: "long"
});

let log = data => (result = `${result}\n${data}`);

// Gives the correct response.
date = new Date(2019, 10, 3);
for (let i = 0; i < 9; i++) {
  log(fmt.format(date));
  date = new Date(date.getTime() + 30 * 60 * 1000);
}

print(result);
```

#### `wrong-output.js` (uses `setMinutes(...)`)
```
$ eshost -s wrong-output.js
#### Chakra
Nov 3, 12:00 AM Pacific Daylight Time
Nov 3, 12:30 AM Pacific Daylight Time
Nov 3, 1:00 AM Pacific Daylight Time
Nov 3, 1:30 AM Pacific Daylight Time
Nov 3, 1:00 AM Pacific Standard Time
Nov 3, 1:30 AM Pacific Daylight Time
Nov 3, 1:00 AM Pacific Standard Time
Nov 3, 1:30 AM Pacific Daylight Time
Nov 3, 1:00 AM Pacific Standard Time

#### JavaScriptCore
Nov 3, 12:00 AM Pacific Daylight Time
Nov 3, 12:30 AM Pacific Daylight Time
Nov 3, 1:00 AM Pacific Standard Time
Nov 3, 1:30 AM Pacific Standard Time
Nov 3, 2:00 AM Pacific Standard Time
Nov 3, 2:30 AM Pacific Standard Time
Nov 3, 3:00 AM Pacific Standard Time
Nov 3, 3:30 AM Pacific Standard Time
Nov 3, 4:00 AM Pacific Standard Time

#### SpiderMonkey, V8
Nov 3, 12:00 AM Pacific Daylight Time
Nov 3, 12:30 AM Pacific Daylight Time
Nov 3, 1:00 AM Pacific Daylight Time
Nov 3, 1:30 AM Pacific Daylight Time
Nov 3, 2:00 AM Pacific Standard Time
Nov 3, 2:30 AM Pacific Standard Time
Nov 3, 3:00 AM Pacific Standard Time
Nov 3, 3:30 AM Pacific Standard Time
Nov 3, 4:00 AM Pacific Standard Time

#### XS

ReferenceError: ?: get Intl: undefined variable
```

#### `right-output.js` (uses `new Date(...)`)
```
$ eshost -s right-output.js
#### Chakra, JavaScriptCore, SpiderMonkey, V8
Nov 3, 12:00 AM Pacific Daylight Time
Nov 3, 12:30 AM Pacific Daylight Time
Nov 3, 1:00 AM Pacific Daylight Time
Nov 3, 1:30 AM Pacific Daylight Time
Nov 3, 1:00 AM Pacific Standard Time
Nov 3, 1:30 AM Pacific Standard Time
Nov 3, 2:00 AM Pacific Standard Time
Nov 3, 2:30 AM Pacific Standard Time
Nov 3, 3:00 AM Pacific Standard Time

#### XS

ReferenceError: ?: get Intl: undefined variable
```

**Comment by ljharb** [comment]
What docs are you referring to?

**Comment by Dru89** [comment]
Yikes, sorry! I was looking at https://tc39.es/ecma262/#sec-date.prototype.setminutes.

**Comment by Dru89** [comment]
Interestingly enough, this seems to just send Chakra into a loop if you let it continue.

```
#### Chakra
Nov 3, 12:00 AM Pacific Daylight Time
Nov 3, 12:30 AM Pacific Daylight Time
Nov 3, 1:00 AM Pacific Daylight Time
Nov 3, 1:30 AM Pacific Daylight Time
Nov 3, 1:00 AM Pacific Standard Time
Nov 3, 1:30 AM Pacific Daylight Time
Nov 3, 1:00 AM Pacific Standard Time
Nov 3, 1:30 AM Pacific Daylight Time
Nov 3, 1:00 AM Pacific Standard Time
Nov 3, 1:30 AM Pacific Daylight Time
Nov 3, 1:00 AM Pacific Standard Time
Nov 3, 1:30 AM Pacific Daylight Time
Nov 3, 1:00 AM Pacific Standard Time
Nov 3, 1:30 AM Pacific Daylight Time
Nov 3, 1:00 AM Pacific Standard Time
...
```

**Comment by apaprocki** [comment]
At first reading it appears the 12:00, 12:30, (1:00, 1:30)* progression is what *should* happen, but it should always print daylight time in the example.

The *LocalTZA* implementation calls out the US fall-back case and specifically states that 1:30 must always be interpreted as the daylight offset, not the standard time offset. Therefore a local time of 2:00 should be interpreted as the *daylight* (first) value.

Getting the minutes value 30 and adding 30 to it yields parameters of hours=1, minutes=60, which should be the same as specifying hours=2.

The answer should be
> LocalTZA(TimeClip(MakeDate(MakeDay(2019, 10, 3), MakeTime(2, 0, 0, 0))), false) is -4 × msPerHour

Therefore the 2:00 in local time should result in a 1:00 daylight equivalent in the object, causing the 1:00, 1:30 sequence to repeat indefinitely if the loop continues. So while that should be the pattern with the numbers, it should always be printing daylight and not standard, as <= 2:00 are interpreted as daylight.

The new Date comparison isn’t relevant because that does not involve interpreting ambiguous local time. The code is simply advancing the UTC timestamp by 30 minutes and the Date object correctly represents that UTC instant in local time.

@gibson042 can you check my logic?

**Comment by apaprocki** [comment]
An alternative reading would be 2:00 does not have a daylight dual representation so *LocalTZA* should explicitly state the far boundary of a leap back is only standard time, allowing the behavior to jump from 1:30 daylight to 2:00 standard. We should clarify this and, if necessary, provide guidance for that case similar to the 1:30 example.

**Comment by Dru89** [comment]
> The new Date comparison isn’t relevant because that does not involve interpreting ambiguous local time. The code is simply advancing the UTC timestamp by 30 minutes and the Date object correctly represents that UTC instant in local time.

Yeah, that's true. Would it be more appropriate to compare this to the behavior `setUTCMinutes` doing the same thing?

**Comment by vmukhachev** [comment]
It seems, now Chrome 85, Firefox 81, Edge 17, IE 11 give the same result.
And the spec describes the behavior.
"Nov 3, 2:00 AM Pacific Standard Time" (timezone transition point) is considered as non-existing with the old offset.
