### ISSUE TITLE
Note on usage of the name NewTarget

### ISSUE THREAD

**Issue by yasushikuno** [tc39/ecma262#177]
[JP22] 15.2.2.1 Bullet 6 says "It is a Syntax Error if MouduleItemList Contains NewTarget" and I was first puzzled on what this "NewTarget" means.  Isn't it more kind to just use "new . target" (in typeface)? The problem stems from the fact that identifier "NewTarget" is used in multiple ways throughout the document, and it might be difficult to resolve.  However, I guess the above change will resolve the problem here.  (I also noticed that a period is missing at the end of the sentence.)

**Comment by rwaldron** [comment]
I think you're looking at an outdated version of the specification? The section you're referring to is 15.2.1.1. _NewTarget_ (italics) in the context of static semantics, can only ever refer to the grammar: 

_NewTarget_ : 
   `new . target`

**Comment by yasushikuno** [comment]
[JP22] Thank you for reply. I will look for current version.

**Comment by bterlson** [comment]
Italics (emu-nt in the source text) refers to a particular non-terminal of the grammar.

(By the way, I think you can just prefix your title with JP22 rather than each comment :))
