### ISSUE TITLE
new primitive immutable data type: Tuple

### ISSUE THREAD

**Issue by Fenzland** [tc39/ecma262#1779]
This issue is for proposing to add a new data type Tuple like what in Python.
We can use the syntax just like Python, only if the trailing comma is required:
```javascript
(0,1,2) === 2;
(0,1,2,); // as a tuple

typeof (0,) === 'tuple';
```

It should be immutable and primitive so that we can use it as the key of Map.
```javascript
const tuple_0 = ('foo', 'bar',);
const tuple_1 = ('foo', 'bar',);

tupple_0 === tupple_1; // true


const map= new Map();

map.set(tuple_0, 'value');
map.get(tuple_1) === 'value';
```

**Comment by devsnek** [comment]
There's an existing proposal for frozen array/tuples: https://github.com/tc39/proposal-record-tuple

**Comment by nicolo-ribaudo** [comment]
I believe that completely chaining the meaning of an expression based on a single trailing comma would be really confusing.

That said, this repository isn't the correct place where you should propose a new feature :wink: 
I suggest reading https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#new-feature-proposals

Also, did you see https://github.com/tc39/proposal-record-tuple?

**Comment by Fenzland** [comment]
Sorry for not found https://github.com/tc39/proposal-record-tuple
