### ISSUE TITLE
Some assert in algorithm description can not be interpreted as a condition.

### ISSUE THREAD

**Issue by nisiyama** [tc39/ecma262#178]
[JP22] Foe example, step 7 of “22.1.2.1 Array.from(items [, mapfn [, thisArg ]])” is described as “Assert: items is not an Iterable so assume it is an array-like object.”.  This assertion can not be interpreted as a condition.

**Comment by ljharb** [comment]
The assertion there is "items is not an iterable", "assume it is an array-like object" is more like an explanatory note - but I agree this is confusingly worded.

**Comment by bterlson** [comment]
Asserts are simply used to clarify algorithms. One could argue for these to be notes instead of asserts. I'll change that for the two instances of "items is not an Iterable". Feel free to file bugs for any remaining issues.
