### ISSUE TITLE
Needs “O” at end of callbackfn parameters

### ISSUE THREAD

**Issue by nisiyama** [tc39/ecma262#179]
[JP22] In step 8-c-ii of “22.1.3.19 Array.prototype.reduceRight(callbackfn [, initialValue])”, callbackfn, which takes four arguments, called with three arguments (“«accumulator, kValue, k, »”).  Need “O” at the end of parameters (e.g., «accumulator, kValue, k, O»)?

**Comment by ljharb** [comment]
Great catch! This is clearly a typo introduced sometime between [ES5.1](http://www.ecma-international.org/ecma-262/5.1/#sec-15.4.4.22) and [ES6](http://www.ecma-international.org/ecma-262/6.0/#sec-array.prototype.reduceright)
