### ISSUE TITLE
RegExp Lookahead and lookbehind routines have the wrong signature

### ISSUE THREAD

**Issue by scole66** [tc39/ecma262#1795]
I'm currently looking at the regexp specifications.

`Term :: Assertion` evaluates Assertion to get an AssertionTester: https://tc39.es/ecma262/#sec-term

The beginning-of-input and end-of-input and word boundary Assertions do exactly that.

The lookahead and lookbehind Assertions, however, return Matchers. (https://tc39.es/ecma262/#sec-assertion)

This seems .... wrong. Some kind of translation needs to happen to move from states to booleans? (Probably: not-failure -> True, failure -> False), though a Matcher takes a continuation and an AssertionTester doesn't so there's a bit more that ought to change there.

Or am I just missing something?

Relevant spec portions:
> The production Term::Assertion evaluates as follows:
>
> 1. Return an internal Matcher closure that takes two arguments, a State x and a Continuation c, and performs the following steps:
> a. Evaluate Assertion to obtain an AssertionTester t.
> b. Call t(x) and let r be the resulting Boolean value.
> c. If r is false, return failure.
> d Call c(x) and return its result.

> The production Assertion::$ evaluates as follows:
>
> 1. Return an internal AssertionTester closure that takes a State argument x and performs the following steps:
> a. Let e be x's endIndex.
> b. If e is equal to InputLength, return true.
> c. If Multiline is false, return false.
> d. If the character Input[e] is one of LineTerminator, return true.
> e. Return false.

> The production Assertion::(?=Disjunction) evaluates as follows:
> 
> 1. Evaluate Disjunction with +1 as its direction argument to obtain a Matcher m.
> 2. Return an internal Matcher closure that takes two arguments, a State x and a Continuation c, and performs the following steps:
> a. Let d be a Continuation that always returns its State argument as a successful MatchResult.
> b. Call m(x, d) and let r be its result.
> c. If r is failure, return failure.
> d. Let y be r's State.
> e. Let cap be y's captures List.
> f. Let xe be x's endIndex.
> g. Let z be the State (xe, cap).
> h. Call c(z) and return its result.

**Comment by scole66** [comment]
Or maybe, since the lookaheads are supposed to capture their groups, the whole AssertionTester signature itself is wrong, and Term::Assertion needs to change. (And the boundary checkers.)

Or maybe the boundary checkers shouldn't be capital-A Assertions at all but be their own thing (BoudaryTests or something).

**Comment by scole66** [comment]
Apparently things have been this way since the ecma-262 spec moved to github.

**Comment by scole66** [comment]
This is old. Makes me think I'm misunderstanding something. Help? (I see it in EC5; but not EC3 (lookaround assertions hadn't been added yet).)

**Comment by claudepache** [comment]
There is indeed an old bug here.

Positive lookaheads and lookbehinds cannot just produce an AssertionTester (as currently specified), because, as you noted, they may include capturing groups, and therefore they need to modify the State that will be passed to the continuation.

**Comment by scole66** [comment]
Honestly, as I compare how I think things should work rather than what the spec says, if we put the lookarounds at the same place as normal grouping all is good. I.e., rather than having an `Assertion :: ( ? = Disjunction )` if we had defined `Atom :: ( ? = Disjunction )` instead, then the currently spec'ed evaluation looks to be exactly correct. (They get handled by `Term::Atom` rather than `Term::Assertion`.)

I'll admit to not having looked at commercial implementations to see what they did.

**Comment by claudepache** [comment]
@scole66  We shouldn’t classify lookarounds as `Atom`, because `Atom`s may be followed by a `Quantifier`, and lookarounds are not supposed to be quantified (notwithstanding web reality described in Annex B). 

I propose:

```
Term ::
    SimpleAssertion
    LookaroundAssertion
    Atom
    Atom Quantifier

SimpleAssertion ::
    ^
    $
    \b
    \B

LookaroundAssertion ::
    (?= Disjunction )
    (?! Disjunction )
    (?<= Disjunction )
    (?<! Disjunction )
```

The evaluation of `Term :: LookaroundAssertion` would be the same as `Term :: Atom`, except that it doesn’t take the argument _direction_.

**Comment by claudepache** [comment]
The alternative solution is to leave the grammar as is, but to modify the evaluation semantics of the other `Assertion`s, so that they all evaluate to a Matcher instead of a boolean.

**Comment by bakkot** [comment]
@claudepache To check my understanding:

---

For the first approach (change the grammar), we would remove the `The production Term::Assertion evaluates as follows:` part of the current spec and replace it with

```
The production Term::SimpleAssertion evaluates as follows:

1. Return an internal Matcher closure that takes two arguments, a State x and a Continuation c, and performs the following steps:
  a. Evaluate SimpleAssertion to obtain an AssertionTester t.
  b. Call t(x) and let r be the resulting Boolean value.
  c. If r is false, return failure.
  d. Call c(x) and return its result.

The production Term::LookaroundAssertion evaluates as follows:

1. Return the Matcher that is the result of evaluating LookaroundAssertion.
```

---

For the second approach (modify the semantics of other assertions), we would change the `The production Term::Assertion evaluates as follows:` part of the current spec to read

```
1. Return the Matcher that is the result of evaluating Assertion with argument direction.
```

And also change the existing simple assertions so that they were all along the lines of

```
The production Assertion::^ evaluates as follows:

1. Return an internal Matcher closure that takes two arguments, a State x and a Continuation c, and performs the following steps:
  a. Let e be x's endIndex.
  b. If e is zero, call c(x) and return its result.
  c. If Multiline is false, return failure.
  d. If the character Input[e - 1] is one of LineTerminator, call c(x) and return its result.
  e. Return failure.
```

which would get rid of AssertionTester entirely, or alternatively

```
The production Assertion::^ evaluates as follows:

1. Let t be an internal AssertionTester closure that takes a State argument x and performs the following steps:
  a. Let e be x's endIndex.
  b. If e is zero, return true.
  c. If Multiline is false, return false.
  d. If the character Input[e - 1] is one of LineTerminator, return true.
  e. Return false.
2. Return an internal Matcher closure that takes two arguments, a State x and a Continuation c, and performs the following steps:
  a. Call t(x) and let r be the resulting Boolean value.
  b. If r is false, return failure.
  c. Call c(x) and return its result.
```

Right?

**Comment by claudepache** [comment]
@bakkot Right.

I prefer the second approach (the version thereof that get rid of AssertionTester entirely), as it conceptually simplifies the spec: it reduces the number of thing types that are produced when evaluating an isolable subpart of a pattern (Disjunction, Alternative, Term, Assertion and Atom would all evaluate to a Matcher; that leaves only CharacterClass as an outsider.)

**Comment by bakkot** [comment]
Great. I'd be happy with any of these, though if we go with your preferred approach I'd want to rewrite the control flow on the assertions so that they don't alternate between "call c(x) and return its result" and "return failure" quite so much - for example,

```
The production Assertion::^ evaluates as follows:

1. Return an internal Matcher closure that takes two arguments, a State x and a Continuation c, and performs the following steps:
  a. Let e be x's endIndex.
  b. If e is zero, or if Multiline is true and the character Input[e - 1] is one of LineTerminator, then
    i. Call c(x) and return its result.
  c. Return failure.

The production Assertion::$ evaluates as follows:

1. Return an internal Matcher closure that takes two arguments, a State x and a Continuation c, and performs the following steps:
  a. Let e be x's endIndex.
  b. If e is equal to InputLength, or if Multiline is true and the character Input[e] is one of LineTerminator, then
    i. Call c(x) and return its result.
  c. Return failure.

The production Assertion::\b evaluates as follows:

1. Return an internal Matcher closure that takes two arguments, a State x and a Continuation c, and performs the following steps:
  a. Let e be x's endIndex.
  b. Call IsWordChar(e - 1) and let a be the Boolean result.
  c. Call IsWordChar(e) and let b be the Boolean result.
  d. If a is true and b is false, or if a is false and b is true, then
    i. Call c(x) and return its result.
  e. Return failure.

The production Assertion::\B evaluates as follows:

1. Return an internal Matcher closure that takes two arguments, a State x and a Continuation c, and performs the following steps:
  a. Let e be x's endIndex.
  b. Call IsWordChar(e - 1) and let a be the Boolean result.
  c. Call IsWordChar(e) and let b be the Boolean result.
  d. If a is true and b is false, or if a is false and b is true, then
    i. Return failure.
  e. Call c(x) and return its result.
```
