### ISSUE TITLE
Proposal: Array.prototype.clear

### ISSUE THREAD

**Issue by Shinigami92** [tc39/ecma262#1802]
In TypeScript we can already use the following as a function extension:

```ts
interface Array<T> {
  clear(): T[];
}

Array.prototype.clear = function(): unknown[] {
  return this.splice(0, this.length);
};
```

Could we have this in JavaScript natively?

**Comment by bathos** [comment]
FWIW, this doesn’t require splicing, which entails created a new Array of the same reported species and collecting the removed values in it.

```js
array.length = 0
```

**Comment by WebReflection** [comment]
FWIW `splice(0)` is sufficient, so that `arr.clear()` can be just `add.splice(0)`.

Accordingly, this (imho) doesn't see a compelling reason to add yet another method to one of the most polluted native prototypes already.

**Comment by ljharb** [comment]
Thanks for the suggestion! This repo is not the place for feature requests; see https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal for the appropriate places to make those.
