### ISSUE TITLE
Auto object destructuring

### ISSUE THREAD

**Issue by AlexSHoffman** [tc39/ecma262#1803]
Let's say we have data object `someDescriptiveName` and we need to destructure it multiple times in different functions with the purpose of being able to use shorter property names.

### For example:
`property1` Instead of `this.someDescriptiveName.property1`

## Data
```JS
someDescriptiveName: {
  property1: false,
  property2: false,
  property3: false,
  property4: false,
  property5: false,
}
```
## Current method
```JS
function func1() {
  let {
    property1,
    property2,
    property3,
    property4,
    property5,
  } = this.someDescriptiveName
  console.log(property1)
}

function func2() {
  let {
    property1,
    property2,
    property3,
    property4,
    property5,
  } = this.someDescriptiveName
  console.log(property1)
}
```

## Proposed method
```JS
function func1() {
  let {*} = this.someDescriptiveName
  console.log(property1)
}

function func2() {
  let {*} = this.someDescriptiveName
  console.log(property1)
}
```

**Comment by ljharb** [comment]
Thanks for the feature suggestion! Please see https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal for how to best suggest new features to the language (also, the "feature request" issue template you modified to post this issue).

**Comment by bathos** [comment]
@AlexSHoffman This exists: it’s the `with` statement. It’s disallowed in strict mode because it leads to a variety of [problems](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/with).

**Comment by AlexSHoffman** [comment]
@bathos thanks for letting me know about this
