### ISSUE TITLE
Missing ? in spec for Evaluation of `in` expression

### ISSUE THREAD

**Issue by jorendorff** [tc39/ecma262#1806]
In the rule for evaluating "*RelationalExpression* : *RelationalExpression* `in` *ShiftExpression*", step 6 is:

> 6. Return ? HasProperty(*rval*, ToPropertyKey(*lval*)).

[HasProperty](https://tc39.es/ecma262/#sec-hasproperty) asserts that the second argument is a property key. [ToPropertyKey](https://tc39.es/ecma262/#sec-topropertykey) can fail.

It seems like this should be split into two steps.

**Comment by ljharb** [comment]
Thanks, it definitely needs the extra `?`.

As for splitting into two steps, that's more of a subjective question - it's totally fine to combine steps like that.
