### ISSUE TITLE
Add callback option to `scrollIntoView()` and `window.scroll()`

### ISSUE THREAD

**Issue by Dan503** [tc39/ecma262#1809]
## The problem

Currently, if we use `element.scrollIntoView({ behavior: 'smooth', block: 'start' })`, the screen will scroll but we have no way of telling when the screen has stopped scrolling.

An accessibility requirement of smooth scrolling in-page links is that we apply focus to the target element when the screen has stopped scrolling. We can't do that easily at the moment. We have to use an arbitrary `setTimeout` value (I typically use 500 milliseconds).

More details about the accessibility issues when smooth scrolling can be read about in this CSS Tricks article:
https://css-tricks.com/smooth-scrolling-accessibility/

It makes specific mention of native smooth scrolling here:
https://css-tricks.com/smooth-scrolling-accessibility/#article-header-id-4

## Proposed solution

Add a `callback` option to the options object that is triggered at the end of the scroll event.

```js
element.scrollIntoView({ behavior: 'smooth', block: 'start', callback: scrollEvent => {
  console.log('The browser has finished scrolling')
}})
```

This should also be applied to `window.scroll`

```js
window.scroll({ top: 0, left: 0, behavior: 'smooth', callback: scrollEvent => {
  console.log('The browser has finished scrolling')
}})
```

**Comment by Dan503** [comment]
I would actually prefer the scroll events to return a `Promise` object so that I can run a `.then()` call on it or an `await` call to wait until it has finished scrolling but I think that might break backwards compatibility which is why I suggested a callback option instead.

**Comment by claudepache** [comment]
@Dan503 You are on the wrong repo: scrollIntoView is not part of ECMAScript (the core language), but of CSSOM. You may be interested in this: https://github.com/w3c/csswg-drafts/issues/3744

**Comment by Dan503** [comment]
Yep, that basically covers the problem I have with the existing scroll functions.

**Comment by asaugat04** [comment]
Any known solutions to this exist?

**Comment by ronakrrb** [comment]
I have build something for this. Hope this solves
https://www.npmjs.com/package/scroll-into-view-promise

**Comment by asaugat04** [comment]
> I have build something for this.


These two functions worked for me @ronakrrb
```
function scrollTo(element,options,callback){
let scrollPromise = new Promise(resolve => element?.addEventListener("scrollend", resolve, {once: true}));
element.scroll(options);
scrollPromise.then(callback);
}
```

```
function scrollIntoView(element,options,callback){
let scrollPromise = new Promise(resolve => window.addEventListener("scrollend", resolve, {once: true}));
element.scrollIntoView(options);
scrollPromise.then(callback);
}
```
