### ISSUE TITLE
Feature request: convert string to bigint of any radix.

### ISSUE THREAD

**Issue by GhbSmwc** [tc39/ecma262#1810]
Hello, I’m new here. Liked the new bigint feature.

While ‘parseInt(string, radix)’ works with ‘number’ it does not work with bigint. I was thinking parseBigInt(string, radix) or just ‘bigInt(string, radix)’. According to Mozilla, it only supports binary (0b), decimal or hex (0x).

**Comment by ljharb** [comment]
Thanks for your thoughts! This repo isn't the proper place for feature suggestions; see https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal as well as the issue template you clicked through.

Specifically for your request, however, see https://github.com/tc39/proposal-number-fromstring.
