### ISSUE TITLE
Chain production definition

### ISSUE THREAD

**Issue by dSalieri** [tc39/ecma262#1811]
The specification contains a definition of the term _chain production_. It reads as follows:

> A _chain production_ is a production that has exactly one nonterminal symbol on its right-hand side along with zero or more terminal symbols.

This definition, in truth, does not mean anything, since the term chain production is used only once in such a place that it is impossible to understand what it is.

As an example, take the definition of production in context-free grammar

> A _context-free grammar_ consists of a number of _productions_. Each production has an abstract symbol called a _nonterminal_ as its _left-hand side_, and a sequence of zero or more nonterminal and _terminal_ symbols as its _right-hand side_. For each grammar, the terminal symbols are drawn from a specified alphabet.

From this definition, we clearly have an idea of ​​what production is. For example:

> MemberExpression: MemberExpression [ Expression ]

The `left-hand side` is all that is up to the ":" symbol `MemberExpression`. And the `right-hand side` part is all that is after the ":" is `MemberExpression`**[**`Expression`**]** . Moreover, the `left-hand side` part is always one nonterminal. And the `right-hand side` one is a combination of terminals and nonterminals in different amounts.

Now back to chain production. The definition says that this is only one nonterminal on the `right-hand side` with zero or more terminal symbols.
Let's look again at the example that I gave to define "production"

> MemberExpression: MemberExpression [ Expression ]

On the `right-hand side` we have two nonterminals (`MemberExpression`, `Expression`) and two terminals (`[`,`]`). Which does not meet the definition of chain production. Either I'm misinterpreting something or the specifications should clarify this definition in more detail.
What is chain production?

**Comment by jmdyck** [comment]
> `MemberExpression: MemberExpression [ Expression ]` ... does not meet the definition of chain production.

That's right. A chain production is a restricted form of production: some productions are chain productions, and some aren't. You have correctly ascertained that this particular production isn't.

**Comment by dSalieri** [comment]
@jmdyck
That is, these are chain production:
>ObjectLiteral: { PropertyDefinitionList }
>Initializer: =AssignmentExpression
>MemberExpression: PrimaryExpression

And this is not a chain production:

>ObjectLiteral: { }
>CallMemberExpression: MemberExpression Arguments
>PropertyDefinitionList: PropertyDefinitionList, PropertyDefinition

It is right? In this case, the definition of the production chain makes sense in the place where it is used.

**Comment by jmdyck** [comment]
Yup, all correct.

**Comment by dSalieri** [comment]
@jmdyck well thanks for your help
