### ISSUE TITLE
Incorrect assertion in ForIn/OfHeadEvaluation

### ISSUE THREAD

**Issue by jorendorff** [tc39/ecma262#1812]
https://tc39.es/ecma262/#sec-runtime-semantics-forin-div-ofheadevaluation-tdznames-expr-iterationkind

Steps 7.a-b. say:

> a. Assert: iterationKind is iterate.
> b. If iterationKind is async-iterate, let iteratorHint be async.

The assertion rules out the condition on the next line.

**Comment by ljharb** [comment]
The implication is that the assertion should have been removed in #1066.

**Comment by jmdyck** [comment]
or else changed to: `Assert: _iterationKind_ is ~iterate~ or ~async-iterate~.`

**Comment by ljharb** [comment]
Good call, that seems better.

**Comment by ExE-Boss** [comment]
Or&nbsp;changed&nbsp;to:
> <ol type="a">
> <li>If <var>iterationKind</var> is ~async-iterate~, then let <var>iteratorHint</var> be ~async~.
> <li>Else,
>	<ol type="i">
>	<li>Assert: <var>iterationKind</var> is ~iterate~.
>	<li>Let <var>iteratorHint</var> be ~sync~.
>	</ol>
> </ol>

```markdown
1. If _iterationKind_ is ~async-iterate~, then let _iteratorHint_ be ~async~.
1. Else,
	1. Assert: _iterationKind_ is ~iterate~.
	1. Let _iteratorHint_ be ~sync~.
```

This&nbsp;is&nbsp;used in&nbsp;[ValidateAndApplyPropertyDescriptor](https://tc39.es/ecma262/#sec-validateandapplypropertydescriptor) §&nbsp;**Step&nbsp;2.d.**
