### ISSUE TITLE
Can you provide a method or symbol to turn a string into a variable name

### ISSUE THREAD

**Issue by thegithubs** [tc39/ecma262#1816]
Can you provide a method or symbol to turn a string into a variable，like eval

**Comment by nicolo-ribaudo** [comment]
`eval` works well for you usecase:

```js
var varName = "foo";
var foo = 2, bar = 3;

console.log(eval(id(varName))); // logs 2


function id(name) {
  if (!/^\p{ID_Start}\p{ID_Continue}*$/u.test(name)) throw new Error("Invalid identifier");
  return name;
}
```

Anyway, this is not the correct place to propose new ECMAScript features. Please read https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#new-feature-proposals!
