### ISSUE TITLE
Needs “?” before “ToNumber”

### ISSUE THREAD

**Issue by nisiyama** [tc39/ecma262#182]
[JP22] In step 4 of “22.2.1.2 %TypedArray%(length)”, the result of “ToNumber” is not checked for abrupt completion.  We need “?” before “ToNumber”?

**Comment by ljharb** [comment]
Please feel free to make these edits yourself and submit them as PRs :-)

**Comment by ljharb** [comment]
Turns out this isn't necessary - see https://github.com/tc39/ecma262/pull/184#discussion_r44875464
