### ISSUE TITLE
CreateImmutableBinding called with only one argument

### ISSUE THREAD

**Issue by erights** [tc39/ecma262#1824]
At https://tc39.es/ecma262/#sec-asyncgenerator-definitions-evaluation 
and https://tc39.es/ecma262/#sec-async-function-definitions-runtime-semantics-evaluation

for the Async*Expression cases where there's a Bindingidentifier, step 5 is

> ```
> 5. Perform ! envRec.CreateImmutableBinding(name).
> ```

By analogy with FunctionExpression https://tc39.es/ecma262/#sec-function-definitions-runtime-semantics-evaluation and GeneratorExpression https://tc39.es/ecma262/#sec-generator-function-definitions-runtime-semantics-evaluation It should be

```
5. Perform ! envRec.CreateImmutableBinding(name, false).
```

**Comment by ljharb** [comment]
https://tc39.es/ecma262/#sec-declarative-environment-records-createimmutablebinding-n-s does implicitly assert that the arg is a Boolean and not optional, but only cares if it’s true. This seems like a good thing to tighten up, but not a spec bug persay.

**Comment by erights** [comment]
I don't understand how it can be not a spec bug. The spec violates its own consistency rules, and so is not well formed.

**Comment by ljharb** [comment]
What i mean is, i can’t conceive how anybody could have implemented it incorrectly, since “false” and “not present” (implicitly undefined for abstract ops, per spec) are both not “true”.

**Comment by jmdyck** [comment]
> What i mean is, i can’t conceive how anybody could have implemented it incorrectly,

Agreed.

> “not present” (implicitly undefined for abstract ops, per spec)

Citation? That's for functions, not abstract ops.

And even if there were such a rule, it wouldn't apply, because there's nothing to indicate that CreateImmutableBinding's second parameter is optional.

**Comment by ljharb** [comment]
Right, that’s what needs fixing - either adding the false or making it optional.

**Comment by allenwb** [comment]
In the ES6 spec Table 15 said that the second argument to CreateImmutableBinding is optional and defaults to false

**Comment by jmdyck** [comment]
That went away when PR #430 (9e15064) was merged. That PR also changed the existing 1-arg invocations to 2-args. The 1-arg invocations returned in PR #692 (869f1c6) and PR #1066 (b564aa9).

**Comment by erights** [comment]
> In the ES6 spec Table 15 said that the second argument to CreateImmutableBinding is optional and defaults to false

I don't see any reason to complexify internal-only operations with optional parameters. Are there any others?

**Comment by ljharb** [comment]
There’s a few, but in this case it seems clear that the reintroductions were based on a spec that predates the change to make it required, so the bug was in making them optional. We should just add the missing falses, i think.

**Comment by erights** [comment]
What are the other internal-only operations with optional parameters?

**Comment by ljharb** [comment]
https://tc39.es/ecma262/#sec-getiterator, https://tc39.es/ecma262/#sec-iteratornext, https://tc39.es/ecma262/#sec-toprimitive, https://tc39.es/ecma262/#sec-call, https://tc39.es/ecma262/#sec-construct, https://tc39.es/ecma262/#sec-createlistfromarraylike, https://tc39.es/ecma262/#sec-createlistfromarraylike, to name a few.

**Comment by erights** [comment]
I see. Yes, in general worth it. Thanks.

**Comment by allenwb** [comment]
For some background, I believe that originally CreateImmutableBinding only had one argument and that the second argument was added to support a special case that was identified later. I don't recall  specifically, but that special case probably only had a single "call site" that need to trigger it with the second argument.  In that case I would have made it optional to avoid churn in algorithms that already used the one argument form (partially to minimize spec maintanance over head and partially to avoid signalling implementors that there was a meaningful change to the existing algorithms).

Given the existing world of multiple proposal streams, multiple implementations, and multiple editors I would think that such churn issues would be an even bigger concern.

**Comment by jmdyck** [comment]
> I don't see any reason to complexify internal-only operations with optional parameters.

I'm inclined to agree, especially when omitting the argument has a semantics that could easily and briefly be supplied explicitly instead (e.g., an empty list). But I don't feel strongly enough to propose de-optionalizing the ones we currently have.

> Are there any others?

I think this is a complete list (25):
- 7.1.1 ToPrimitive ( _input_ [ , _PreferredType_ ] )
- 7.3.12 Call ( _F_, _V_ [ , _argumentsList_ ] )
- 7.3.13 Construct ( _F_ [ , _argumentsList_ [ , _newTarget_ ] ] )
- 7.3.18 CreateListFromArrayLike ( _obj_ [ , _elementTypes_ ] )
- 7.3.19 Invoke ( _V_, _P_ [ , _argumentsList_ ] )
- 7.4.1 GetIterator ( _obj_ [ , _hint_ [ , _method_ ] ] )
- 7.4.2 IteratorNext ( _iteratorRecord_ [ , _value_ ] )
- 8.3.2 ResolveBinding ( _name_ [ , _env_ ] )
- 9.1.12 ObjectCreate ( _proto_ [ , _internalSlotsList_ ] )
- 9.1.13 OrdinaryCreateFromConstructor ( _constructor_, _intrinsicDefaultProto_ [ , _internalSlotsList_ ] )
- 9.2.5 MakeConstructor ( _F_ [ , _writablePrototype_ [ , _prototype_ ] ] )
- 9.2.8 SetFunctionName ( _F_, _name_ [ , _prefix_ ] )
- 9.3.3 CreateBuiltinFunction ( _steps_, _internalSlotsList_ [ , _realm_ [ , _prototype_ ] ] )
- 9.4.2.2 ArrayCreate ( _length_ [ , _proto_ ] )
- 13.7.5.13 ForIn/OfBodyEvaluation ( _lhs_, _stmt_, _iteratorRecord_, _iterationKind_, _lhsKind_, _labelSet_ [ , _iteratorKind_ ] )
- 15.2.1.17.2 GetExportedNames ( [ _exportStarSet_ ] ) Concrete Method
- 15.2.1.17.3 ResolveExport ( _exportName_ [ , _resolveSet_ ] ) Concrete Method
- 22.1.3.10.1 FlattenIntoArray ( _target_, _source_, _sourceLen_, _start_, _depth_ [ , _mapperFunction_, _thisArg_ ] )
- 22.2.4.2.1 AllocateTypedArray ( _constructorName_, _newTarget_, _defaultProto_ [ , _length_ ] )
- 24.1.1.3 DetachArrayBuffer ( _arrayBuffer_ [ , _key_ ] )
- 24.1.1.10 GetValueFromBuffer ( _arrayBuffer_, _byteIndex_, _type_, _isTypedArray_, _order_ [ , _isLittleEndian_ ] )
- 24.1.1.12 SetValueInBuffer ( _arrayBuffer_, _byteIndex_, _type_, _value_, _isTypedArray_, _order_ [ , _isLittleEndian_ ] )
- 24.1.1.13 GetModifySetValueInBuffer ( _arrayBuffer_, _byteIndex_, _type_, _value_, _op_ [ , _isLittleEndian_ ] )
- 24.4.1.1 ValidateSharedIntegerTypedArray ( _typedArray_ [ , _waitable_ ] )
- 25.6.5.4.1 PerformPromiseThen ( _promise_, _onFulfilled_, _onRejected_ [ , _resultCapability_ ] )

(There's also the _direction_ parameter for some definitions of regex evaluation, which is an odd case.)

**Comment by devsnek** [comment]
Some of these optional parameters help contain the invariants of an operation. For example GetExportedNames and ResolveExport required passing in an empty list at the top-level call. The recursive nature of those operations is not really of any concern to the caller, so making the parameter optional helps keep details encapsulated.

**Comment by jmdyck** [comment]
Good point. Though I think those two are the only ops for which that argument applies.

**Comment by michaelficarra** [comment]
I'm in favour of refactoring out the optional parameters wherever it is reasonable to do so.
