### ISSUE TITLE
Rest of arguments for %TypedArray%

### ISSUE THREAD

**Issue by nisiyama** [tc39/ecma262#183]
[JP22] In “22.2.1.3 %TypedArray%(typedArray)”, parameters for “%TypedArray%” is described as “... the %TypedArray% function is called with at least one argument and ...".  This description assumes that “%TypedArray%” can take more than one parameters. We need “, ...” after the “typedArray” argument (e.g. %TypedArray%(typedArray, ...)).

**Comment by anba** [comment]
Additional arguments are always accepted by built-in functions, cf. [17 ECMAScript Standard Built-in Objects](http://tc39.github.io/ecma262/#sec-ecmascript-standard-built-in-objects), fifth paragraph:

> Unless otherwise specified in the description of a particular function, if a built-in function or constructor described is given more arguments than the function is specified to allow, the extra arguments are evaluated by the call and then ignored by the function.
