### ISSUE TITLE
[Await] is wrongly linked to the Await(value) algorithm

### ISSUE THREAD

**Issue by nicolo-ribaudo** [tc39/ecma262#1836]
Example: https://tc39.es/ecma262/#sec-identifiers-static-semantics-early-errors
The `[Await]`-related early errors all link to https://tc39.es/ecma262/#await, which should be unrelated.

If you Crtl+F for `[Await]`, this happens for every occurrence.

**Comment by ljharb** [comment]
This seems like something ecmarkup will have to fix.

**Comment by ljharb** [comment]
This seems like something ecmarkup will have to fix.
