### ISSUE TITLE
Table 48 doesn't fit on the page

### ISSUE THREAD

**Issue by rkirsling** [tc39/ecma262#1843]
Table 48 is having a bad time at the moment:
![image](https://user-images.githubusercontent.com/2172590/72225826-b9393500-353e-11ea-96a6-b9aa71a60ad5.png)
It doesn't fit on the page, and scrolling is disabled so there isn't even a way to see the rest of the content.

If it weren't inside a note, it just fits _visually_ on my screen, but it still spills out of the containing `<figure>`:
![image](https://user-images.githubusercontent.com/2172590/72225948-3e711980-3540-11ea-82a1-0e8d6f3a6bd3.png)

The only way I can see to address this without removing a column is by ensuring that the code can wrap:
![image](https://user-images.githubusercontent.com/2172590/72226043-5f863a00-3541-11ea-83ab-e3aa3e758166.png)
This is achievable with `emu-table td code { white-space: normal; }`.
(I don't think it needs to be specific to tables-in-notes?)

**Comment by ljharb** [comment]
I think in general it'd be better if code didn't wrap; but in this one situation that seems like a reasonable workaround to me.

**Comment by bakkot** [comment]
Reopening until ecmarkup is upstreamed.
