### ISSUE TITLE
Object.prototype.toString.call(BigInt) should be [object BigInt]?

### ISSUE THREAD

**Issue by moonformeli** [tc39/ecma262#1845]
```js
typeof BigInt(1) === 'bigint'
Object.prototype.toString.call(BigInt(1)) === '[object Object]'
```

Shouldn't this be `[object BigInt]`?
Because [7.1.8 ToObject](https://tc39.es/ecma262/#sec-toobject), there's [[BigInt]] data type.
So I think we should add 
```
Else if O has a [[BigInt]] internal slot, let builtinTag be "BigInt".
```
[in 19.1.3.6 Object.prototype.toString](https://tc39.es/ecma262/#sec-object.prototype.tostring)

Does it make sense?

**Comment by zloirock** [comment]
https://tc39.es/ecma262/#sec-bigint.prototype-@@tostringtag

**Comment by moonformeli** [comment]
Ooops, what I've tested on the console was just `toString`, not `toString.call`. Shamed on myself.
But what about the documentation?

**Comment by moonformeli** [comment]
Ahh, now I get it. Thank you !
