### ISSUE TITLE
New atomic ECMAScript type date to box a Date object.

### ISSUE THREAD

**Issue by ExtAnimal** [tc39/ecma262#1846]
In a similar way to how `const myString = 'value'` creates a string which is *not* `instanceof String`, but `typeof myString` will be `'string'`.

There should be an atomic type `date` alongside `boolean`, `number` and `string`.

This will require a new format for creating date literals. Unfortunately, backticks for use as quoting values has been used up on the rather pointless "template" concept. 

I propose that `const myBirthday = ~1982-06-17~` would parse the value according to ISO 8601 as a UTC timepoint. This would be the converse to the `Date.toISOString` method.

Now, `typeof myBirthday` would be `'date'`.

The `date` boxed type would expose the methods of the `Date` class in the same way the `string` boxed type exposes the methods of the `String` class.

This would unravel some problems in the web world.

The JSON standard has a lacuna around dates. Date values have to be transferred as strings with an agreement on format between the two parties, and no type inference can be done by the receiver.

`JSON.stringify` currently encodes `Date` objects as strings using `toISOString`, so perhaps new behaviour to encode within `~` marks could be opt-in?

`JSON.parse` would acquire a new ability to read `~` delimited dates.

Boxed `date` values from other execution contexts such as frames would still yield the correct `typeof`. As we know, `instanceof Date` fails on dates from other contexts.

**Comment by ljharb** [comment]
Thanks for your thoughts. This repo isn't the appropriate place for feature requests; please see https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal

For future reference, the issue template you cleared to file this issue also says this:
> Feature requests for future versions of ECMAScript should not be made in this
repository. Instead, they are developed in separate GitHub repositories, which
are then merged into the main repository once they have received "Stage 4".
>
> Please see [CONTRIBUTING.md](/CONTRIBUTING.md) for more details.

You may also be interested in https://github.com/tc39/proposal-temporal
