### ISSUE TITLE
Why does the text in the note in 14.9.1 refer to 9.2.4?

### ISSUE THREAD

**Issue by dSalieri** [tc39/ecma262#1848]
In `14.9.1 Static Semantics: IsInTailPosition (call)` there is a note that says:

> Tail Position calls are only defined in strict mode code because of a common non-standard language extension (see 9.2.4) that enables observation of the chain of caller contexts.

Why does the note refer to 9.2.4 (in 9.2.4 a common non-standard language extension is not described)? 9.2.4 describes an abstract operation that creates 2 properties for `Function.prototype` of an object which, when called, should throw an error. Thereby preventing observation of the chain of caller contexts.

In more detail: I wanted to say that the reference to 9.2.4 somehow seems to be out of place in the note (by my opinion). If you do not follow this link (9.2.4), you might think that it describes a common non-standard language extension, its rules or something like that - but it is not. Is it possible to paraphrase this note somehow?

How can you comment on this situation?

**Comment by ljharb** [comment]
https://tc39.es/ecma262/#sec-addrestrictedfunctionproperties describes a function's caller and arguments properties, which are indeed common non-standard language extensions; additionaly, if you look at the [2015 snapshot](https://www.ecma-international.org/ecma-262/6.0/index.html#sec-isintailposition) you'll see that it links to 9.2.7, which is the same section that 9.2.4 now refers to.

**Comment by dSalieri** [comment]
@ljharb wait a minute but they (property names: "caller", "arguments") are described by the specification here (in 9.2.4). Or what did I miss? Yes, I saw a snapshot of 2015 - everything is identical there.

**Comment by ljharb** [comment]
The spec has them as restricted; i believe prior to having that, the properties may have been nonstandard (as in, not in the spec, and only supplied by browsers)

**Comment by claudepache** [comment]
The problem is that there is no good place to link, because the spec currently avoid to name explicitly the incriminated well-known “non-standard language extension” like dirty words. Hopefully, the issue will be resolved the same day as #562.

**Comment by dSalieri** [comment]
@ljharb In other words, the `"caller"` and `"arguments"` properties are not defined by the specification, but they have a number of restrictions described in the specification, and the abstract operation (9.2.4) also adjoins these restrictions. Right? But the question remains the same: why does the text in note 14.9.1 refer to 9.2.4 if 9.2.4 is a standardized abstract operation by specification?

@claudepache hmm, and that sounds pretty convincing. Although it’s strange for me personally, you can somehow formulate it so that it doesn’t sound like dirty words. And then this is a browser issue, not a specification. They continue to use from year to year that which has never been officially specified in the specification (excluding restrictions imposed by the specification). In any case, if my issue is solved on the same day as yours, this will be wonderful.

**Comment by ljharb** [comment]
@dSalieri no, i meant to write "restricted", the adjective form; "restriction" is the noun form. The spec has them as restricted; the spec also has them as restrictions - both phrases are correct and mean effectively the same thing.

**Comment by dSalieri** [comment]
@ljharb in my language, this makes a big difference to the meaning. But I understand you. By the way, you didn’t react at all to the second paragraph. I would like to see your comment on this.

**Comment by ljharb** [comment]
If the properties exist and accessing them doesn't throw, they're non-standard. That non-standard extension is the reason the restrictions were added in the first place.

**Comment by dSalieri** [comment]
@ljharb yeah understood, then 9.2.4 is a restrictions for "caller" and "arguments". Right?

**Comment by ljharb** [comment]
Yes, that’s my understanding.

**Comment by dSalieri** [comment]
@ljharb thank you for your responses
