### ISSUE TITLE
validateAndApplyPropertyDescriptor step 5

### ISSUE THREAD

**Issue by Adamk93** [tc39/ecma262#1850]
In step 5 of validateAndApplyPropertyDescriptor (permalink sec-validateandapplypropertydescriptor) it's not clear what "no further validation is required." means. This is quite ambiguous and it does not give any indication on what it should be the boolean result of the case in which Desc is a generic descriptor.

**Comment by ljharb** [comment]
The final result depends on what `O` is - you can see in https://tc39.es/ecma262/#sec-validateandapplypropertydescriptor that control moves down to step 9, and then step 10 if `O` is `undefined`.

I've also implemented this in https://npmjs.com/es-abstract: https://github.com/ljharb/es-abstract/blob/master/2015/ValidateAndApplyPropertyDescriptor.js#L102 if that helps you visualize the flow better.

**Comment by Adamk93** [comment]
@ljharb Yes, you're right, even though that the structure of this method is somehow tricky. Thank you!
