### ISSUE TITLE
14.1.19 Runtime Semantics: IteratorBindingInitialization can use chain rule for Formal[Rest]Parameter

### ISSUE THREAD

**Issue by anba** [tc39/ecma262#1852]
<https://tc39.es/ecma262/#sec-function-definitions-runtime-semantics-iteratorbindinginitialization> could omit both `FormalParameter : BindingElement` and `FunctionRestParameter : BindingRestElement`, because the chain production rule already covers this case.

**Comment by shvaikalesh** [comment]
@anba could you please link productions that cover this case?

Both

```
FormalParameters: FormalParameterList , FunctionRestParameter
FormalParameterList: FormalParameterList , FormalParameter
```

have terminal `,` commas and `FormalParameterList` can't be `[empty]` (unlike [`FormalParameters`](https://tc39.es/ecma262/#prod-FormalParameters)).

**Comment by anba** [comment]
I was referring to the following rules in my comment:
```
 FormalParameter:BindingElement
    Return the result of performing IteratorBindingInitialization for BindingElement with arguments iteratorRecord and environment.

FunctionRestParameter:BindingRestElement
    Return the result of performing IteratorBindingInitialization for BindingRestElement with arguments iteratorRecord and environment.
```

**Comment by shvaikalesh** [comment]
> I was referring to the following rules in my comment:

If we remove `FormalParameter : BindingElement` and `FunctionRestParameter : BindingRestElement`, what productions would cover initialization via chain production rule?

**Comment by anba** [comment]
That would be <https://tc39.es/ecma262/#sec-destructuring-binding-patterns-runtime-semantics-iteratorbindinginitialization>. 

[Chain production](https://tc39.es/ecma262/#sec-context-free-grammars) is defined as:
> A chain production is a production that has exactly one nonterminal symbol on its right-hand side along with zero or more terminal symbols.

And per [5.2.2 Syntax-Directed Operations](https://tc39.es/ecma262/#sec-algorithm-conventions-syntax-directed-operations):
> Unless explicitly specified otherwise, all chain productions have an implicit definition for every operation that might be applied to that production's left-hand side nonterminal. The implicit definition simply reapplies the same operation with the same parameters, if any, to the chain production's sole right-hand side nonterminal and then returns the result.

These definitions can be applied for both `FormalParameter : BindingElement` and `FunctionRestParameter : BindingRestElement`, because the right-hand side has exactly one nonterminal and it applies the same operation on the sole right-hand side operand.

**Comment by shvaikalesh** [comment]
I appreciate the detailed explanation. PR: #2084.
