### ISSUE TITLE
JP22: Implementations are discouraged?

### ISSUE THREAD

**Issue by satou441** [tc39/ecma262#186]
[JP22] At pp168, 12.5.6.1 Runtime Semantics, NOTE of Evaluation says "Implementation are discouraged from defining ...". What does it mean by "discouraged"? Should it behave as implementation defined, undefined, some error, or something else?

**Comment by bterlson** [comment]
Notes are non-normative. This is just an editorial note conveying the opinion of TC39 (or the editor) that implementations should not choose to define a new typeof value for exotic objects, but they are free to do so per the previous table.
