### ISSUE TITLE
'InitializeBinding' incorrectly links to 'Record' spec type

### ISSUE THREAD

**Issue by lazdmx** [tc39/ecma262#1875]
Step 4 of [8.1.1.1.4 InitializeBinding](https://tc39.es/ecma262/#sec-declarative-environment-records-initializebinding-n-v) algorithm starts with a hyperlink to `Record` type which is obviously incorrect. `Record` is a verb, not a specification type.

**Comment by claudepache** [comment]
In rare cases, autolinking is overzealous. See also #1079.
