### ISSUE TITLE
Question about level of formalism of spec

### ISSUE THREAD

**Issue by lazdmx** [tc39/ecma262#1876]
Sorry for making noise here, but I have a question which I cannot get resolve.  The question is: why in different parts of spec, especially in steps of algorithms there are some steps that defined by non-formal definitions, even if they could (as I think) be defined precisely by methods and operations that already defined?

For instance: Steps 4–5 of [9.1.5.1 OrdinaryGetOwnProperty](https://tc39.es/ecma262/#sec-ordinarygetownproperty) defined as:

```
4. Let X be O's own property whose key is P.
5. If X is a data property, then
```

why instead they aren't defined like:

```
4. Let X be !O.[[GetOwnProperty]](P)
5. If IsDataDescriptor(X) is true, then
```

This is not a big question however it just makes me fill like I've missed something important in spec, or there are real issues exist with formal definitions that should be nailed down and fixed.  

Thanks

**Comment by devsnek** [comment]
In this case, `O.[[GetOwnProperty]] == OrdinaryGetOwnProperty`. `OrdinaryGetOwnProperty` is the actual implementation of `[[GetOwnProperty]]` for ordinary objects. The spec doesn't define data structure used for ordinary objects, so it has to stay kind of abstract.

**Comment by lazdmx** [comment]
@devsnek 🤦‍♂ thanks) I just got that it was chicken-egg problem with `GetOwnProperty`. Nonetheless, what problems may be with `IsDataDescriptor(X)` in step 5?

**Comment by devsnek** [comment]
@lazdmx There is no descriptor to call it on. The information about the property exists in an implementation defined structure. OrdinaryGetOwnProperty gets the property, then builds a descriptor (`Let D be a newly created Property Descriptor with no fields.`) from that abstract information.

**Comment by lazdmx** [comment]
Thanks. All pretty clear now
