### ISSUE TITLE
InternalizeJSONProperty missing reviver argument

### ISSUE THREAD

**Issue by erights** [tc39/ecma262#1878]
At https://tc39.es/ecma262/#sec-json.parse JSON.parse calls InternalizeJSONProperty but does not pass the reviver as an argument. InternalizeJSONProperty does not have it as a parameter. But then InternalizeJSONProperty uses the reviver that JSON.parse should have passed to it.

Attn @FUDCo

**Comment by bakkot** [comment]
Yeah, there's some kind of sketchy prose which just says it gets to use it anyway:

> InternalizeJSONProperty uses the value of reviver that was originally passed to the above parse function.

It should probably be explicitly threaded through.

**Comment by ljharb** [comment]
Between http://www.ecma-international.org/ecma-262/5.1/#sec-15.12.2 and https://www.ecma-international.org/ecma-262/6.0/index.html#sec-json.parse, the InternalizeJSONProperty operation was introduced - but its prose says “InternalizeJSONProperty uses the value of reviver that was originally passed to the above parse function, which remains in the link you sent.

In other words, i don’t think there’s a bug, but it’s exceedingly strange for an abstract operation to infer arguments, so I’d prefer it be explicitly passed through.

**Comment by erights** [comment]
I consider this a bug in that the internal computational model elsewhere consistently avoids dynamic scoping. Although this text is prose, so is everything else. I is an programming language that, currently, only people execute. But it does obey a consistent computational model that this text violates.

In any case, however we classify it, it should be fixed.

**Comment by jmdyck** [comment]
> it’s exceedingly strange for an abstract operation to infer arguments

There are about 14 operations that "have access to" non-local aliases/metavariables:
- WordCharacters, IsWordChar, CharacterSetMatcher, Canonicalize, BackreferenceMatcher, RegExpBuiltinExec, CharacterRangeOrUnion, Evaluate for regexp
- SortCompare, TypedArray SortCompare
- InternalizeJSONProperty, SerializeJSONProperty, SerializeJSONObject, SerializeJSONArray

> I consider this a bug in that the internal computational model elsewhere consistently avoids dynamic scoping.

Personally, I think of it as static scoping where you imagine that the above operations are defined *within* the scope of the operation whose metavariables they're accessing non-locally. (I *think* that all works out.) It's still a bit odd, but thinking about it that way made me dislike it less.

(Not that I'm objecting to explicit passing, just giving a different perspective.)
