### ISSUE TITLE
LabelledIdentifier is not used when evaluating LabelledStatement

### ISSUE THREAD

**Issue by nanto** [tc39/ecma262#188]
[JP22] In 13.13.15, LabelledIdentifier of LabelledStatement is not used. LabelledIdentifiers are ignored unless the labelled statements are nested. To use LabelledIdentifier, 13.13.15 step 2 can be:

> Return LabelledEvaluation of this LabelledStatement with argument newLabelSet.

**Comment by allenwb** [comment]
While it is sometimes necessary to apply an abstract operation to a production LHS, it is something that I think can be confusing. To avoid that, instead of the fix suggested above, I would simply add a new step after step one that says:

```
Append the string value of LabelIdentifier to newLabelSet.
```

**Comment by anba** [comment]
Simply appending the label identifier to newLabelSet does not work, because break abrupt completions also need to be handled.

**Comment by allenwb** [comment]
@anba
Yup, as usual you're correct.

So, the original fix is fine.

**Comment by nanto** [comment]
A production LHS is also used in 13.1.8, evaluation of BreakableStatement.
