### ISSUE TITLE
why create new `globalThis` variable instead of using `global`

### ISSUE THREAD

**Issue by kcwitt** [tc39/ecma262#1880]
Why was a new variable called `globalThis` created instead of having all implementations expose `global`?

**Comment by bathos** [comment]
There is a detailed document explaining the [naming rationale and constraints](https://github.com/tc39/proposal-global/blob/master/NAMING.md).

**Comment by ljharb** [comment]
See https://github.com/tc39/proposal-global/blob/master/NAMING.md#names-ruled-out-by-this-restriction-4 (the rest of the document will hopefully answer any further questions)

**Comment by kcwitt** [comment]
But why would using `global` break Node? It is already implemented in Node. How did this break flickr?

**Comment by kcwitt** [comment]
Wow, awesome write-up!
