### ISSUE TITLE
Regex Production "IdentityEscape" needs to be relaxed

### ISSUE THREAD

**Issue by scole66** [tc39/ecma262#1888]
**Description:** The Regex Production for IdentityEscape, when the U flag is False, is too restrictive

(I've been looking at regexps again...)

The definition in [section 21.2.1](https://tc39.es/ecma262/#prod-IdentityEscape) is:
```
IdentityEscape[U]::
    [+U] SyntaxCharacter
    [+U] /
    [~U] SourceCharacter but not UnicodeIDContinue
```

And it's that last line is the troublesome one. It means that, for instance, `/\a/` should be a syntax error. Web reality says it's the same as `/a/`.

But it's worse than that. In section [21.2.3.2.2, Runtime Semantics: RegExpInitialize](https://tc39.es/ecma262/#sec-regexpinitialize), step 7b (paraphrased):
* Parse with N flag off
* If groupnames detected, parse with N flag on

The N flag turns on the `\k` escape. But if `\k` was a syntax error in the first attempted parse, we actually don't know if there were groupnames or not. 

I propose just eliminating the "but not UnicodeIDContinue" from the definition.

**Comment by bakkot** [comment]
The actual grammar for regular expressions is given [in Annex B](https://tc39.es/ecma262/#sec-regular-expressions-patterns). The part you're looking at is just a polite fiction. See other issues about integrating Annex B into the main grammar.

**Comment by scole66** [comment]
Well, that's obnoxious.

**Comment by bakkot** [comment]
Yup. We're hopefully going to fix this soon; you're far from the first person to be misled.
