### ISSUE TITLE
16.1 and Annex C don't forbid NonOctalDecimalIntegerLiteral

### ISSUE THREAD

**Issue by nanto** [tc39/ecma262#189]
[JP22] B.1.1 adds LegacyOctalIntegerLiteral and NonOctalDecimalIntegerLiteral, and forbid them for strict mode code. On the other hand, 16.1 and Annex C forbids only LegacyOctalIntegerLiteral. Is NonOctalDecimalIntegerLiteral allowed for strict mode code or not?

**Comment by mazkasa** [comment]
In NOTE of 11.8.3 Numeric Literals, both of extends seems forbidden on strict mode code.

> A conforming implementation, when processing strict mode code (see 10.2.1), must not extend, as described in B.1.1, the syntax of NumericLiteral to include LegacyOctalIntegerLiteral, nor extend the syntax of DecimalIntegerLiteral to include NonOctalDecimalIntegerLiteral.

**Comment by nanto** [comment]
Thank you! I have missed it. I change the issue title to "16.1 and Annex C don't forbid NonOctalDecimalIntegerLiteral".
