### ISSUE TITLE
use abstract closures for CreateBuiltInFunction

### ISSUE THREAD

**Issue by bakkot** [tc39/ecma262#1894]
https://github.com/tc39/ecma262/pull/1889 introduced a notion of an abstract closure, but we still pass algorithm steps around directly as an argument to CreateBuiltInFunction. It would be nice to replace those with abstract closures too. Plus, the inline style for abstract closures is probably more readable - this would resolve https://github.com/tc39/ecma262/issues/933.

**Comment by michaelficarra** [comment]
@bakkot Is this fixed by #2109?

**Comment by bakkot** [comment]
No, there's still a bunch of places we do this. I'm preparing a PR.
