### ISSUE TITLE
Use abstract closures for Atomics semantic functions

### ISSUE THREAD

**Issue by syg** [tc39/ecma262#1895]
Now that we have abstract closures we should stop using the "semantic functions" used in the Atomics section.

**Comment by Jack-Works** [comment]
Do we have abstract generators to simplify the builtin iterators that can be used in https://tc39.es/proposal-iterator-helpers/#sec-asynciteratorprototype-map? 👀

**Comment by ljharb** [comment]
@Jack-Works that would only be helpful if it provided spec notation for an iterator-producing function (which is distinct from a generator), so it could be used for all the existing examples of those.

**Comment by syg** [comment]
Async iterator stuff is off-topic to this issue.

**Comment by syg** [comment]
This needs some more thinking through. These were pure semantic functions originally because they are pure semantic functions whose steps are not observable, to be used in the event semantics of RMW events.

That said, for ease of exposition the event semantics *does* use abstract operations, e.g., ComposeWriteEventBytes. To refactor these semantic functions to abstract closures, I think it'd be good to introduce an abstract closure "subclass", like Matchers, to clarify that these abstract closures are:

- Only observed atomically as part of event semantics in the memory model
- Steps are never observable
- Are actual mathematical functions (i.e. pure)
