### ISSUE TITLE
How can I translate this document into another language.

### ISSUE THREAD

**Issue by 244462375** [tc39/ecma262#1901]
I want to translate this document into Chinese. How can I get it.

**Comment by Jack-Works** [comment]
You can download it from https://www.ecma-international.org/publications/standards/Ecma-262.htm

Good luck

**Comment by peterzhangsnail** [comment]
If you really want to do it, better do it right. There are some [Chinese translations](http://lzw.me/pages/ecmascript/) of older versions of ECMAScript for reference, so you just need to work with all the new things and differences between old and new versions.

**Comment by 244462375** [comment]
I didn't even notice that. Thanks ! 

> If you really want to do it, better do it right. There are some [Chinese translations](http://lzw.me/pages/ecmascript/) of older versions of ECMAScript for reference, so you just need to work with all the new things and differences between old and new versions.
