### ISSUE TITLE
Why don’t `Promise.{allSettled,all,race}` also support async iterators?

### ISSUE THREAD

**Issue by ExE-Boss** [tc39/ecma262#1909]
This is something that I’d expect to be supported, since `Promise.{allSettled,all,race}` return a `Promise`, so they’re essentially already asynchronous.

**Comment by bakkot** [comment]
It makes sense for `all`, but not so much `allSettled` or `race` (or `any`) - the expectation is that the promises returned by the async iterator settle in the order they're omitted (that's how async generators work, certainly), and that if one of them rejects then any subsequent promises just hold `{ done: true }`.

It does not always make sense for promise-returning APIs which take iterables to also take async iterables.

Anyway, the [iterator helpers proposal](https://tc39.es/proposal-iterator-helpers/#sec-asynciteratorprototype-toarray) adds `%AsyncIterator.prototype%.toArray()`, which allows you to get a promise for a list out of an async iterator, which is a similar to what `Promise.all` does.

**Comment by bakkot** [comment]
Closing this as resolved, but @ExE-Boss if there's something else feel free to reopen.
