### ISSUE TITLE
 A closing parenthesis is missing.

### ISSUE THREAD

**Issue by mazkasa** [tc39/ecma262#191]
[JP22] A closing parenthesis behind "LINE FEED (LF)" is missing in the second paragraph in NOTE of 10.1 Souce Text.
The parenthesis existed in the rev 38, but in the current rev, is disappeared.

**Comment by jmdyck** [comment]
Specifically, I believe you mean that there should be (another) right-paren after:
    (Unicode code point U+000A is LINE FEED (LF)

It looks like it disappeared between rev 38 and the June 17 version of the ES6 spec.

**Comment by mazkasa** [comment]
Yeah, I think so.
