### ISSUE TITLE
JavaScript Logical Operators - Short-circuit evaluation

### ISSUE THREAD

**Issue by mendezjose** [tc39/ecma262#1952]
**Description:** The expression "false && true || true" return true. But it should return false because of the short circuit evaluation.

**eshost Output:**

```
C:\Users\User\Documents\bug-report>eshost -s -x "const a = false && true || true; print(a)"
#### Chakra, SpiderMonkey, V8, V8 --harmony, XS
true

#### JavaScriptCore

```

**Comment by bakkot** [comment]
This is not a bug. `false && true || true` is evaluated as `(false && true) || true`, which is `false || true`, which is `true`.

(This also isn't the appropriate place for this kind of thing - might I recommend [StackOverflow](https://stackoverflow.com/questions/tagged/javascript) next time?)
