### ISSUE TITLE
FunctionExpression doesn't seem to have `Yield` or `Await`

### ISSUE THREAD

**Issue by Razican** [tc39/ecma262#1957]
**Description:** When looking at the [`FunctionExpression`][spec] specification, it seems that it should contain the parameters `[Yield, Await]`, since it then uses them in `BindingIdentifier`, `FormalParameters` and `FunctionBody`, but it seems they are missing.

[spec]: https://tc39.es/ecma262/#prod-FunctionExpression

**Comment by bathos** [comment]
It doesn’t use them in the sense of propagating from above — it’s _supplying_ them to those productions. The tilde is “not” here, so `BindingIdentifier[~Yield, ~Await]` is saying “BindingIdentifier, with Yield: false, Await: false”. If you see `[?Yield]`, that would imply the need for a corresponding “input” parameter (cause it means passing down a param which may be true or false).

**Comment by Razican** [comment]
True! I misread :/ thanks for the explanation :)
