### ISSUE TITLE
JP22: 20.2.2.26 Math.pow(1, inf) and Math.pow(1, -inf)

### ISSUE THREAD

**Issue by akr** [tc39/ecma262#196]
The section, "20.2.2.26 Math.pow(x, y)" defines Math.pow(1, inf) and Math.pow(1, -inf) as follows.

| If abs(x) is 1 and y is +inf, the result is NaN.
| If abs(x) is 1 and y is -inf, the result is NaN.

Is it appropriate?
They can be considered as 1.

**Comment by anba** [comment]
This is a known difference between ECMAScript and IEEE 754-2008. The first ECMAScript edition (released 1997) used the definitions from fdlibm (i.e. Math.pow(&plusmn; 1, &plusmn; Infinity) = NaN), whereas C99 (and later IEEE 754-2008) chose to use Math.pow(&plusmn; 1, &plusmn; Infinity) = 1.

**Comment by anba** [comment]
We should probably add a note to Math.pow to point out the definition differs from IEEE 754-2008.

**Comment by bterlson** [comment]
Agreed. Note:


<p>The result of `Math.pow(x, y)` when abs(_x_) is 1 and _y_ is *+Infinity* or *-Infinity* differs from IEEE 754-2008 for historical reasons. The first edition of ECMAScript specified a result of *NaN* for this operation, whereas later versions of IEEE 754-2008 specified *1*. The historical ECMAScript behavior is preserved for compatibility reasons.</p>

**Comment by domenic** [comment]
Editorial nit: drop the last "reasons"

**Comment by bterlson** [comment]
I didn't like it either, I think the text I committed is better in this respect :)
