### ISSUE TITLE
JP22: "20.3.2.2 Date (value)" uses thisTimeValue() defined later

### ISSUE THREAD

**Issue by akr** [tc39/ecma262#198]
In the section, 20.3.2.2 Date (value), the step 3.a.i uses thisTimeValue() which is defined later (20.3.4).
It is better to define thisTimeValue() first, or add a forward reference such as "(thisTimeValue() is defined in 20.3.4.)".

**Comment by huei90** [comment]
what is `thisTimeValue()` ?

**Comment by bterlson** [comment]
`thisTimeValue` is an abstract operation that takes some ECMAScript value and if it's a date, returns its DateValue slot, and otherwise throws a TypeError exception.

I've committed a fix that will make thisTimeValue be a link you can click to find its definition.
