### ISSUE TITLE
JP22: character reference inconsistency in 20.1.3.2, 20.1.3.3 and 20.1.3.5

### ISSUE THREAD

**Issue by akr** [tc39/ecma262#199]
In the sections 20.1.3.2 (Number.prototype.toExponential), 20.1.3.3 (Number.prototype.toFixed) and 20.1.3.5 (Number.prototype.toPrecision), characters are referenced inconsistently.
For example, 20.1.3.2 step 13.b. and 20.1.3.3 step 10.c.iv refers a character as "." but
20.1.3.5 step 12.c.iii refers it as "code unit 0x002E (FULL STOP)".

Unicode character names identify the characters more reliably than the character glyphs.

**Comment by bterlson** [comment]
I tend to think the character names are unnecessary. In this case it'd be pretty easy to use the character name as we're talking about one character, but morally the same would apply to any multi-character strings used in the document. I will fix the inconsistency by making 20.1.3.5 step 12.c.iii use `"."`.

**Comment by bterlson** [comment]
Removing all mentions of "code unit X (NAME)" would be a good regexp replace someone could do. One concern would be tough-to-read code units like HYPHEN-MINUS, but since we consider the HTML normative now (and printed copies non-normative), and the HTML actually has the code point we want in its source, I think this is fine. What do you think?

**Comment by ljharb** [comment]
Should the [string padding proposal](https://github.com/tc39/proposal-string-pad-start-end/blob/master/spec.md) then use `" "` to indicate a single space? Or is the code point helpful there (and should the formatting be tweaked)?

**Comment by anba** [comment]
The code unit notation is definitely helpful when U+0020 SPACE is used, for example I didn't realize [SIMD ToString](http://tc39.github.io/ecmascript_simd/#to-string) uses ", " (U+002C U+0020) instead of "," (U+002C) until running the SIMD test suite.

**Comment by bterlson** [comment]
@anba yeah, totally agreed. "Easily confused" characters should probably continue to use character names (including all form of dashes and spaces).

**Comment by ljharb** [comment]
Is there a formatting convention that should be followed for this case?
