### ISSUE TITLE
[es6-super-construct] Make 'super()' an early error in ordinary functions

### ISSUE THREAD

**Issue by dslomov-chromium** [tc39/ecma262#20]
Per es6-super-construct proposal, 'super()' invocation in ordinary functions always throws:
  * In [[Call]] of that function 'super()' throws because 'super()' always throws on [[Call]] (due to 'this' being always initialized in [[Call]])
   * In [[Construct]] of that function 'super()' throws, because ordinary functions are not "defined using a class definition that has an extends clause" so 'this' starts initialized when [[Construct]]ing.

We have a precedent already for concise methods where an occurrence of 'super()' call (DirectSuper) is an early error.
It will greatly help language usability if the same applies to ordinary functions (implementations can provide better error messages; the bugs are sure to be discovered)

**Comment by wycats** [comment]
I think I remember Microsoft being worried about too many early errors because they force more aggressive evaluation of function bodies? @bterlson ?

**Comment by allenwb** [comment]
On Jan 9, 2015, at 9:42 AM, Yehuda Katz wrote:

> I think I remember Microsoft being worried about too many early errors because they force more aggressive evaluation of function bodies? @bterlson ?
> 
> 
No, its more extensive analysis of function bodies prior to first evaluation of anything in a script because a script with early errors must not execute any code.

However, this one additional early error, given the early errors we already have seems unlike to make much difference.

**Comment by domenic** [comment]
ES6 is done, doing some housecleaning!
