### ISSUE TITLE
Should `SetIntegrityLevel` in the documentation should be updated?

### ISSUE THREAD

**Issue by moonformeli** [tc39/ecma262#2011]
Hi, I'm reading [SetIntegrityLevel](https://tc39.es/ecma262/#sec-setintegritylevel) section in the documentation for getting to know about how `Object.freeze` and `Object.seal` actually work, but I got confused by the documentation.

In MDN, `Object.freeze` prevents the existing properties from being deleted or the new properties from being added to the object.

But the documentation seems it's only describing how each property of an object would be affected, not the object itself. 
So shouldn't something like this as below be added in the documentation?

>a. Assert: level is _frozen_
>b. For each element _k_ of _keys_, do
>...
>c. Let _desc_ be the PropertyDescriptor { [[Configurable]]: **false** }
>    i. Perform ? DefinePropertyOrThrow(_globalThis_, _O_, _desc_); 

Through this section with the current version, I don't know where to find the logical reasons that the object itself also gets frozen (configurable: false)

**Comment by ljharb** [comment]
Step 3 ensures no new properties can be added. When sealing, step 6.a.i makes all existing properties nonconfigurable. When freezing, step 7.b.ii ensures all existing properties are nonconfigurable and nonwritable (if a data property).

The object itself doesn’t get anything beyond preventing extensions.

**Comment by moonformeli** [comment]
Thank you :)
