### ISSUE TITLE
Grammar ambiguity in `for ( async of`

### ISSUE THREAD

**Issue by bakkot** [tc39/ecma262#2034]
The token sequence `for ( async of` can begin two different parses: either `for (async of => {};;);` or `for (async of foo);`.

@waldemarhorwat [raised this issue](https://github.com/tc39/notes/blob/425ab0e16a32f8199b5521a1cf7439d10d4c8a83/meetings/2019-12/december-3.md#async-of-grammar-ambiguity) at the December 2019 meeting. During that discussion we decided to resolve this by using a lookahead restriction to disallow for-of loops which start with the token `async`.

**Comment by Fenzland** [comment]
why allow keyword like `async`, `of` and even `undefined` as variable name?

**Comment by ljharb** [comment]
Because they’ve always been allowed, and it wouldn’t be web compatible to disallow them now.

**Comment by strager** [comment]
For reference, the following code prints `42` in Node.js version v12.20.0 and in Chromium version 88.0.4324.150, but emits a SyntaxError in Firefox 84.0.1 and in macOS Safari version 12.1.2 (14607.3.9):
```js
var async;
for (async of [42]) {}
console.log(async);
```

**Comment by syg** [comment]
@strager A fix was recently merged (https://chromium-review.googlesource.com/c/v8/v8/+/2683221), and Chrome 90 / V8 9.0 will correctly disallow `for ( async of`.
