### ISSUE TITLE
`2 == true` is false but I think it should be true.   

### ISSUE THREAD

**Issue by 1t1e1** [tc39/ecma262#2064]
`2 == true` is `false` and `2 == false` is `false`. `ToBoolean(2)` is `true`, I expect `2 == true` equal to `true`.

I think using `ToBoolean(number)` rather than `ToNumber(boolean)` in 8, 9 statement in [Abstract Equality Comparison](https://tc39.es/ecma262/#sec-abstract-equality-comparison) makes more sense. What is the point here? I don't get it.

**Comment by Jack-Works** [comment]
Hmm. Whatever the reason makes it false, it's not possible to change it. It will destroy the web.

**Comment by WebReflection** [comment]
Number(true) is 1 though, and Number(false) is 0, so you have a coercion
issue you can very easily solve via `if (!!2) ...` which is false only with
0 (and -0).

**Comment by devsnek** [comment]
> What is the point here? I don't get it.

Abstract equality, as evidenced by the name, is not based on any concrete rules of how values fit together. It's just a sort of conglomeration of behaviours that the creators of JS felt were "useful" when building it. Aside from being web incompatible to change its behaviour, we have `===` in the language which you should probably just use instead.

**Comment by claudepache** [comment]
See: https://esdiscuss.org/topic/rationale-for-why-ecmascript-converts-primitive-values-to-numbers-in-operator-comparisons-when-one-is-boolean

**Comment by michaelficarra** [comment]
Regardless of the merit of this proposal, the ecma262 issue tracker is not the appropriate place for this discussion. See [CONTRIBUTING.md](https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md) for the best ways to contribute. This particular topic seems to belong on the [TC39 Discourse](https://es.discourse.group/).
