### ISSUE TITLE
object compares with boolean on Abstract Equality Comparison

### ISSUE THREAD

**Issue by Ende93** [tc39/ecma262#2074]
>10. If Type(x) is either String, Number, BigInt, or Symbol and Type(y) is Object, return the result of the comparison x == ? ToPrimitive(y).
>11. If Type(x) is Object and Type(y) is either String, Number, BigInt, or Symbol, return the result of the comparison ? ToPrimitive(x) == y.

The doc doesn't mention `Boolean` compare with `Object`, but the code returns true on browsers:
```
var a = {valueOf: () => true};
a == true; // true
``` 
Does the doc lost `Boolean` or browsers not follow spec?

**Comment by ljharb** [comment]
`ToPrimitive(a)` ends up being `true`, which `== true`.
