### ISSUE TITLE
Editorial - Array.forEach Note 1 has some missing part

### ISSUE THREAD

**Issue by bendtherules** [tc39/ecma262#2075]
In [array.map](https://tc39.es/ecma262/#sec-array.prototype.map), the note says that new elements in array are not considered after map starts (last para in note 1). 

But a similar note in [array.foreach](https://tc39.es/ecma262/#sec-array.prototype.foreach) doesn't have that part of the note - even though it works in the same way.

**Comment by jmdyck** [comment]
(Revision 34 of ES6 had that paragraph for 'every', 'filter', 'forEach', and 'map'. Revision 35 removed it for 'forEach' only.)
