### ISSUE TITLE
Editorial - CreateRegExpStringIterator position

### ISSUE THREAD

**Issue by Huxpro** [tc39/ecma262#2081]
What's the rationale behind positioning **CreateRegExpStringIterator** (currently 21.2.5.8.1) as a subsection of **RegExp.prototype [ @@matchAll ]** (currently 21.2.5.8) instead of **RegExp String Iterator Objects** (21.2.7)? 

All other **Create {Map | Set | Array | String | AsyncFromSync | For-In } Iterator** operations are under their corresponding **X Iterator Objects** sections. Why the difference?

I understood that's the only call site, but still, **CreateStringIterator** had only one call site as well.

**Comment by ljharb** [comment]
It wasn’t an intentional placement. it’d be fine to move it imo. Want to make a PR?

**Comment by Huxpro** [comment]
Sure, #2082 should fix this. 

I made a typo in the commit message though. 
It should be "(**fix** #2081)" instead of just "(#2081)", but I hope that's fine.
