### ISSUE TITLE
npm watch script gives error (ecmarkup)

### ISSUE THREAD

**Issue by bendtherules** [tc39/ecma262#2083]
In the `watch` script (from package.json),  ecmarkup throws `Cannot use --lint-spec with --watch`.

It seems like ecmarkup doesn't support both at the same time. So, should we remove lint-spec during watch?

cc @rkirsling

**Comment by ljharb** [comment]
cc @bakkot; this is an easy fix (change `"watch": "npm run build-master -- --watch",` to `"watch": "npm run build-only -- --watch",`) but it seems like watch mode should be usable with linting?

**Comment by bendtherules** [comment]
SHould we change it to `build-only` for now? Or wait bit more?

**Comment by bakkot** [comment]
I am updating ecmarkup such that it makes sense to use --lint-spec with --watch, and will change it here once I have that released.
