### ISSUE TITLE
Implicit undefined issue

### ISSUE THREAD

**Issue by ubuntugod** [tc39/ecma262#2087]
```
const UNDEFINED = Symbol('undefined').toString() // This is always != undefined

 const sideEffectFunctionOne = (input) => {
 if (input) return undefined; //Some side-effect causing undefined
 }
 
 const sideEffectFunctionTwo = (input) => {
 if (input) return undefined; //Some side-effect causing undefined
 return UNDEFINED // Assuming implicit return gives symbolic undefined
 }
 
 const resultOne = sideEffectFunctionOne(false);
 const resultTwo = sideEffectFunctionTwo(false);
 
 console.log(`resultOne = ${resultOne}, resultTwo = ${resultTwo}`)
```
Consider the two cases above. Assume, that for some reason a side-effect in a function returns a non-implicit `undefined`.

Function `sideEffectFunctionOne` shows the default behaviour of what happens in this situation. The problem is that the user is not able to distinguish between the side-effect `undefined` and the implicit `undefined` returned by the function.

Wouldn't it be better, if we have a standard way to distinguish between the implicit `undefined` and a non-implicit `undefined`?

Although my example above of function `sideEffectFunctionTwo` makes use of a symbolic undefined called `UNDEFINED`, to express how a unique form of implicit undefined can be done naively, can't we have some better way to handle this in a standard way that can maintain backward compatibility?

**Comment by ljharb** [comment]
Why would it be better to have three kinds of "nothing" values (`null`, implicit `undefined`, and explicit `undefined`), instead of the two we already have (`null` and `undefined`)?

If you're trying to determine if a property exists, you'd use `Object.prototype.hasOwnProperty.call`; if you're trying to determine if a `undefined` function argument was passed, you'd use a non-arrow function and `arguments.length`; I'm not sure I understand when you'd use this ability to distinguish them?

That said, this repo isn't the place for feature requests. Please see https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal for the best places to do that.

**Comment by ubuntugod** [comment]
@ljharb The reason why I thought about distinguishing between an implicit and an explicit return is because of semantic value. I am not sure I would be able to explain properly, but let me explain the best I can.

ECMAScript Language types like the `undefined` and `null` indicate the following semantics I believe:
`undefined` - anything that has not yet been given any value depicting an undeclared/undefined instance
`null` - used to express/assign the idea of no value

In JavaScript, since `undefined` can have R-Value as well as L-Value semantics this is possible:
`const a = undefined` (R-Value semantics)
`undefined = null` (L-Value semantics)

But, `null = undefined` is not possible because of `null` has R-Value semantics. The language beautifully prevents this with a `ReferenceError` (although `null` is basically an 'object' to not break legacy codebase I think).

Consider the use-cases of `null` and `undefined` as function returns:
1. When the function only deals with doing some task that doesn't return anything - implicit `undefined`
2. When the function does some work and returns a value that can be processed/used further - any type or `null` if the data is not available
3. When the function should return with partial work(early return) indicating undefined behaviour that doesn't require any processing further and doesn't enforce user to throw an error - explicit `undefined` using `return;`

The use of an implicit undefined that can be distinguished from the explicit undefined is that it provides the intent of the developer. If the side-effect I mentioned in my original example is from a third-party library, having an explicit undefined then the developer can skip making a conclusion as to what the library dev intended - was it an implicit undefined(don't expect any result) or an explicit undefined(explicit early return)
