### ISSUE TITLE
Editorial: Spec is inconsistent in checking the result of OrdinaryObjectCreate

### ISSUE THREAD

**Issue by Ms2ger** [tc39/ecma262#2097]
The spec uses both "OrdinaryObjectCreate(..)" and "! OrdinaryObjectCreate(..)" ([sometimes in the same section](https://tc39.es/ecma262/#sec-asyncgenerator-definitions-instantiatefunctionobject)); #2045 also adds "? OrdinaryObjectCreate(..)".

They should probably be consistent.

**Comment by bakkot** [comment]
This is an instance of a fairly prevalent problem, tracked in https://github.com/tc39/ecma262/issues/1796. I am still intending to address this as soon as I can, though it is going to have to wait on the stage-4 proposal PRs, fixing the spec's use of arithmetic (https://github.com/tc39/ecma262/issues/1964 / https://github.com/tc39/ecma262/pull/2007), and probably https://github.com/tc39/ecma262/issues/1950.

**Comment by ljharb** [comment]
The ones missing a `!` are an oversight. Pending #1796, they should all be added.

**Comment by bakkot** [comment]
The spec currently allows omitting `!`. They are not incorrect as written, merely inconsistent.
