### ISSUE TITLE
Elladamalikova@hotmail.com

### ISSUE THREAD

**Issue by saimakin** [tc39/ecma262#2100]
**Description:** Adding 1 and 1 is two, but it should be...

**eshost Output:**

```
$ eshost -s -e "1 + 1"
#### Chakra, JavaScriptCore, SpiderMonkey, V8, XS
2
```

**Comment by saimakin** [comment]
Elladamalikova@hotmail.com

**Comment by ljharb** [comment]
Duplicate of #2080. Duplicate of #2079.

Also, spam.
