### ISSUE TITLE
BigInt implicit conversions

### ISSUE THREAD

**Issue by ufocoder** [tc39/ecma262#2102]
There's a paragraph about `BigInt` in [7.1 Type Conversion](https://tc39.es/ecma262/#sec-type-conversion):

```
The BigInt type has no implicit conversions in the ECMAScript language; programmers must call BigInt explicitly to convert values from other types.
```

At the same time `BigInt` value can be conversed to `Boolean` value according [Table 10: ToBoolean Conversions](https://tc39.es/ecma262/#table-10), likes the following:

```
1n ? 'true' : 'false' // 1n will be converted to true
```

So I suppose that paragraph about BigInt implicit conversions should be removed

**Comment by devsnek** [comment]
I believe the paragraph's intention is to say that there is no way to implicitly convert a value into a BigInt, which is true.

**Comment by ljharb** [comment]
Indeed; it’s saying you can’t implicitly coerce into BigInt. You can coerce everything into other things.

**Comment by ufocoder** [comment]
@devsnek @ljharb But you can implicitly coerce into BigInt :)

Please check this section [7.1.13 ToBigInt](https://tc39.es/ecma262/#sec-tobigint). It has the following conversion table:

<img width="616" alt="ToBigInt" src="https://user-images.githubusercontent.com/2094547/87922768-1e895800-ca85-11ea-88fa-054412e14cb3.png">

Therefore `BitInt` has conversion from `Boolean` and `String` types.

So developer can explicit convert to `BigInt`:

```
BigInt(false)   // will be converted to 0n
BigInt(true)    // will be converted to 1n
BigInt('1')     // will be converted to 1n
BigInt('2')     // will be converted to 2n
```

But **coercions exist** for `String` type, for example:

```
"1n" > 1n      // string "1n" will be converted to 1n BigInt, 
"2n" == 2n     // string "2n" will be converted to 2n BigInt, 
```
This coercions described in [7.2.14 Abstract Relational Comparison](https://tc39.es/ecma262/#sec-abstract-relational-comparison) and [7.2.15 Abstract Equality Comparison](https://tc39.es/ecma262/#sec-abstract-equality-comparison)

**Comment by ljharb** [comment]
That's an explicit, not an implicit, coercion to BigInt.

**Comment by ufocoder** [comment]
I try to describe my position other words

Explicit conversion (type casting) when developer call BigInt: 

```
BigInt(false)   // 0n
BigInt(true)    // 1n
BigInt('1')     // 1n
BigInt('2')     // 2n
```

Not let's analyze one simple block of code:

```
'2' > 1n
```

In this binary expression will be executed abstract relational comparison operator **`>`**

There's a quote of **[7.2.14 Abstract Relational Comparison](https://tc39.es/ecma262/#sec-abstract-relational-comparison)**

<img width="482" alt="Снимок экрана 2020-07-21 в 02 09 46" src="https://user-images.githubusercontent.com/2094547/87995125-55985180-caf7-11ea-9a66-7dbf9bcd5089.png">

Further `String` value `'2'` will be implicitly converted to `BigInt` via abstract operator `StringToBigInt`

`'2' > 1n` expression after `StringToBigInt` operator eval will be converted to `2n > 1n` 

@ljharb Can you explain please why there's no implicit conversion (type coercion) in `'2' > 1n` . Because it is it :)

--
p.s. I've just try to understand why I not right in your opinion

**Comment by ljharb** [comment]
I consider `<` and `>` "coercions" the same as `if (x)` "coercions" - not actually coercing the values; that's just how the spec describes those comparisons. You can never *observe* the "coerced" values, so they don't actually exist.

**Comment by ufocoder** [comment]
If coercion doesn't exist that you'll get a `TypeError`, isn't it? 
Observed "coerced" values and not observed "coerced" values are coerced values both ;)

Anyway our dialog creates questions around paragraph from `7.1 Type Conversion`. 
I think it must be edit to exclude potential questions. So spec must be improved:

- Maybe specification needs to add its' meaning for `coercion` term. 
- Maybe specification needs to add some comments for sentence: `The BigInt type has no implicit conversions ..`

But now without any improvements spec writes that coercion for `BigInt` exists via `Table 12. BigInt conversions`

**Comment by NoUJoe** [comment]
Yeah, this really needs to be clarified. `2n > '1'` absolutely converts string to bigint, you just can't observe the conversion. Also, what about `undefined`, `null` and `Symbol`? I can't think of any implicit conversions to these where you can observe the result either.

**Comment by ljharb** [comment]
@NoUJoe `1 + undefined` is `NaN` and `1 + null` is `1`. Symbol does not implicitly coerce to anything.

**Comment by NoUJoe** [comment]
@ljharb I mean conversions to these types, not from.
