### ISSUE TITLE
ASI of do-while statement should be rephrased.

### ISSUE THREAD

**Issue by nbp** [tc39/ecma262#2123]
**Description:** Automatic Semicolon Insertion specifies that [`The previous token is ) and the inserted semicolon would then be parsed as the terminating semicolon of a do-while statement`](https://tc39.es/ecma262/#sec-automatic-semicolon-insertion).

This statement [was meant to include the do-while statement as part of the rules considered for ASI](https://tc39.es/ecma262/#sec-additions-and-changes-that-introduce-incompatibilities-with-prior-editions), but the phrasing implies that code such as:

```js
function foo() {
  return bar()
  "haha"
}
```

Should be rejected, as the inserted semicolon after the `)` of the expression `bar()`, should be parsed as `the terminating semicolon of a do-while statement`, which it is not. Thus this rule should cause the previous code to raise a Parse error.

**Comment by bakkot** [comment]
> The previous token is ) and the inserted semicolon would then be parsed as the terminating semicolon of a do-while statement.

That sentence is preceded by

> if one or more of the following conditions is true

and two other possibilities. I don't see a reading where it would imply all ASI involves a do-while statement.

**Comment by codehag** [comment]
Arguably this could be clearer. It doesn't tell us how to apply these rules in the case that more than one of them is true or that there is an ordering to them. Could we change it to the following?

Change (in bold):
When, as the source text is parsed from left to right, a token (called the offending token) is encountered that is not allowed by any production of the grammar, then a semicolon is automatically inserted before the offending token if **any** of the following conditions are true, **applied in the order they are written here**:

**Comment by nbp** [comment]
To be honest, I would suggest removing this statement, and just explicitly state for which production of the grammar should these rules apply.
This would avoid having to consider context while solving ASI rules, and solve the initial issue for which this statement got introduced.

**Comment by bakkot** [comment]
@ystartserv:

> doesn't tell us how to apply these rules in the case that more than one of them

Doesn't it? "Do X if one or more of the following is true" seems like it covers the case that more than one is true, to me.

> or that there is an ordering to them.

I'm not sure what ordering you're referring to.

@nbp:

> This would avoid having to consider context while solving ASI rules

I don't think you can really avoid considering the context when applying ASI rules.

**Comment by codehag** [comment]
I think the issue is that it is suggesting that the previous statement be interpreted differently. That's the issue and why i thought ordering might help. 

"The previous token is ) and the inserted semicolon would then be parsed as the terminating semicolon of a do-while statement."

It suggests that you need to consider context when applying ASI rules. Do we really need this specificity?

**Comment by nbp** [comment]
The problematic part with the statement is that this inserted semicolon would be parsed as a do-while semicolon.
Which is adding one extra interpretation to what the inserted semicolon is, which suggest that this is not an ordinary semicolon, but only a do-while semicolon (not a return statement semicolon).

If this statement were to include "if applicable" then this could be any semicolon or a do-while semicolon, but this make this statement even more complex.

We cannot ignore the context, as we do not want ASI to apply to all semicolon in [`IterationStatement`](https://tc39.es/ecma262/#prod-IterationStatement), only to the do-while production.

I think enumerating the productions in which ASI can be used would be simpler to read.

**Comment by bakkot** [comment]
> Do we really need this specificity?

do-while needs to be called out explicitly because different rules apply to it: ASI applies after a do-while even without a preceding LineTerminator. That is, `do {} while (false) foo()` is syntactically valid.

@nbp:

> I think enumerating the productions in which ASI can be used would be simpler to read.

It  is not clear to me how that would help anything - you'd still need to have the "The offending token is separated from the previous token by at least one LineTerminator or the offending token is }." condition. Perhaps it's just not clear to me what you're suggesting - can you write out an example of what you'd like to see?

**Comment by nbp** [comment]
> > Do we really need this specificity?
> 
> do-while needs to be called out explicitly because different rules apply to it: ASI applies after a do-while even without a LineTerminator. That is, `do {} while (false) foo()` is syntactically valid.

Thanks for the example! I did not noticed this was a valid input.
