### ISSUE TITLE
Which ECMA version VXML 2.0 and 2.1 obey?

### ISSUE THREAD

**Issue by zhaoqilong123** [tc39/ecma262#2141]
for spidermonkey 1.7, it can handle following, but after upgraded to 52.9, fail.
If only ECMA 3 is supported but not ECMA 6 ?
```
<?xml version="1.0" encoding="UTF-8"?> 
<vxml version="2.0" xmlns="http://www.w3.org/2001/vxml" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:schemaLocation="http://www.w3.org/2001/vxml 
   http://www.w3.org/TR/voicexml20/vxml.xsd"> 
    <script> <![CDATA[ 
       function factorial(n) 
       {
         return (n <= 1)? 1 : n * factorial(n-1);
       } 
    ]]> </script> 

  <form id="form"> 
    <field name="fact"> 
      <grammar type="application/srgs+xml" src="/grammars/number.grxml"/>
      <prompt>
        Tell me a number and I'll tell you its factorial.
      </prompt> 
      <filled> 
        <prompt> 
          <value expr="fact"/> factorial is 
          <value expr="factorial(fact)"/> 
        </prompt> 
      </filled> 
    </field> 
  </form> 
</vxml>
```
I've raised same issue at the Mozilla spidermonkey github website.

**Comment by ljharb** [comment]
Anything with HTML tags is not defined by this specification, which only governs the JS language. I'm not sure what the proper place is to file this, but it'd be great if you linked to the mozilla issue you filed.

**Comment by zhaoqilong123** [comment]
> Anything with HTML tags is not defined by this specification, which only governs the JS language. I'm not sure what the proper place is to file this, but it'd be great if you linked to the mozilla issue you filed.

following are issues I raise in mozilla
https://github.com/mdn/sprints/issues/3604
https://github.com/mdn/sprints/issues/3619
https://github.com/mdn/kuma/issues/7431

**Comment by zhaoqilong123** [comment]
> Anything with HTML tags is not defined by this specification, which only governs the JS language. I'm not sure what the proper place is to file this, but it'd be great if you linked to the mozilla issue you filed.

Or I'll describe my qusetion in another way,  if ECMA standard is backward compatible in your opinion?

**Comment by ljharb** [comment]
I think it's entirely irrelevant, because only the stuff inside `<script>` tags in your OP is actually JS.

**Comment by zhaoqilong123** [comment]
> I think it's entirely irrelevant, because only the stuff inside `<script>` tags in your OP is actually JS.
OK，in your opinion，if function factorial(fact) can be called inside such VXML, or if such form break ECMA 6?

**Comment by ljharb** [comment]
EcmaScript has nothing to say about JS code being accessible from non-JS contexts; that's up to the host.

**Comment by zhaoqilong123** [comment]
> ECMAScript has nothing to say about JS code being accessible from non-JS contexts; that's up to the host.
Yes, this usage is given inside 
https://www.w3.org/TR/voicexml20
```5.3.12 script element```section

**Comment by zhaoqilong123** [comment]
> ECMAScript has nothing to say about JS code being accessible from non-JS contexts; that's up to the host.
And for ECMA 6, when handle function call, such as factorial(fact), which section about ECMA-262 6th edition June 2015 is related or used ?

**Comment by ljharb** [comment]
(Please include a newline between `>` and your reply; github can't render it properly otherwise)

I can't point you to a specific section; but as soon as you're talking about "not everything in the same script tag", there is no mention of it in this spec - only in the spec/implementation for the engine you're using.

**Comment by zhaoqilong123** [comment]
```
<?xml version="1.0" encoding="GB2312"?>
<vxml xmlns="http://www.w3.org/2001/vxml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/2001/vxml     http://www.w3.org/TR/voicexml20/vxml.xsd" version="2.1" xml:base="http://www.w3.org/2001/vxml">
	<meta name="author" content="Poornima DMS"/>
	<meta name="maintainer" content="poornimadms@huawei.com"/>
	<form id="formOne">
		<catch event="error.semantic">
			<prompt>
				pass
			</prompt>
		</catch>
		<block>
			<script>

      <![CDATA[				function callMeAnytime ( i ) 
        {
        return ( i * 2 );
        }
]]>
     			</script>
		</block>
		<block>
			<script>

      <![CDATA[				var j;
        j = callMeAnytime ( 2 );
]]>
     			</script>
		</block>
		<block>
			<prompt>
				fail:as no error was thrown
			</prompt>
		</block>
	</form>
</vxml>
```
Hello, do you think callMeAnytime ( 2 ) can be Executed successfully according to ECMA 6?
Besides, may be I should contact VXML 2.0 or 2.1 group, then do you know where's their website?

**Comment by zhaoqilong123** [comment]
> (Please include a newline between `>` and your reply; github can't render it properly otherwise)
> 
> I can't point you to a specific section; but as soon as you're talking about "not everything in the same script tag", there is no mention of it in this spec - only in the spec/implementation for the engine you're using.

Hello, my friend, do you know how to contact VXML 2.0 or 2.1 group/Community or where's their website?

**Comment by jmdyck** [comment]
See https://www.w3.org/TR/voicexml20/#Status
It tells you who develops the VoiceXML specification, and where you can comment on it.
