### ISSUE TITLE
Which behavior is correct on EnumerateObjectProperties?

### ISSUE THREAD

**Issue by Jack-Works** [tc39/ecma262#2147]
https://tc39.es/ecma262/#sec-enumerate-object-properties

**Description:**

# Test case 1
```js
const obj = { __proto__: { a: 1 }, b: 2, c: 3 }
for (const key in obj) {
    print(key)
    if (key === 'b') obj.__proto__.d = 2
}
```

**eshost Output:**

```
#### ChakraCore, Moddable XS, Engine262
b
c
a
d

#### Hermes, SpiderMonkey, V8, JavaScriptCore
b
c
a
```

## Test 2

```js
var obj = {b: 2, c: 3};
Object.setPrototypeOf(obj, {a:1});
for (const key in obj) {
  console.log(key);
  if (key === 'b') Object.setPrototypeOf(obj, {zzz:1})
}
```

ESHost output

```
#### ChakraCore, SpiderMonkey
b
c
a

#### Hermes, V8, JavaScriptCore
b
c

#### Moddable XS, Engine262
b
c
zzz
```

In the spec Note 1, there is a JS equivalent code that supports the result of Moddable XS.

> Code in the spec:

```js
function* EnumerateObjectProperties(obj) {
  const visited = new Set();
  for (const key of Reflect.ownKeys(obj)) {
    if (typeof key === "symbol") continue;
    const desc = Reflect.getOwnPropertyDescriptor(obj, key);
    if (desc) {
      visited.add(key);
      if (desc.enumerable) yield key;
    }
  }
  const proto = Reflect.getPrototypeOf(obj);
  if (proto === null) return;
  for (const protoKey of EnumerateObjectProperties(proto)) {
    if (!visited.has(protoKey)) yield protoKey;
  }
}
```

**Comment by Jack-Works** [comment]
Engine262 supports the result of ChakraCore, Moddable XS

https://engine262.js.org/#code=MYewdgzgLgBCBGArGBeGAKA3vAXDATADQzB4DMAvgJQBQA8kgKbBQB0EjUACgE4hT8AngAdGdAGboEiYpgCGeAIzUa4kDwyhIsANaNBMAJZg4SKjEw0Y1mMJ7Go6PYNo2j4jM9Qo0Acni%2B5gyIzGwA5py8%2FEKiElJmrAAmqAQ0FDRAA%3D&mode=script&features=

**Comment by Jack-Works** [comment]
Engine262 link for test case 2, only supports the result of Moddable XS

https://engine262.js.org/#code=G4QwTgBA9gRgVhAvBA3jAXBATAGggY0wGYBfAbgCgB5eAU3wBcA6AZ1oYAUwoGeBPAA60qAMwAUsOHhQh0ARhIBKSiKiQx%2BKADsWDCAGtafCAEst0eItQUIBbSygAbWk0dQA5mMN9lN0yIgvIyREZAByGDCrGjh6ZjZObl4GQWFxSWkAL2z5JQoSCiA%3D&mode=script&features=

**Comment by gibson042** [comment]
All of the above are correct. Modifications during enumeration loosen the requirements of observable behavior.

> If new properties are added to the target object during enumeration, the newly added properties are not guaranteed to be processed in the active enumeration.

> the iterator [for _O_ with a fully non-exotic prototype chain] must behave as would the iterator given by CreateForInIterator(_O_) **until one of the following occurs**:
> * the value of the [[Prototype]] internal slot of _O_ or an object in its prototype chain changes,
> * a property is removed from _O_ or an object in its prototype chain,
> * a property is added to an object in _O_'s prototype chain,
> * …
