### ISSUE TITLE
Safe regex engine against ReDos Attack

### ISSUE THREAD

**Issue by SeyyedKhandon** [tc39/ecma262#2161]
Currently, javascript regex engine suffers from lack of `atomic groups` and other features for preventing ReDos Attack, and this makes the regex very complicated to handle this kind of attacks.

It'll  be very good to handle this in js like java or other platforms to prevent redos attacks.

**Comment by ljharb** [comment]
Thanks for your thoughts. This repo isn't the appropriate place for feature requests; please see https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal

For future reference, the issue template you cleared to file this issue also says this:
> Feature requests for future versions of ECMAScript should not be made in this
repository. Instead, they are developed in separate GitHub repositories, which
are then merged into the main repository once they have received "Stage 4".
>
> Please see [CONTRIBUTING.md](/CONTRIBUTING.md) for more details.

**Comment by SeyyedKhandon** [comment]
Sorry for posting this on the wrong section. 
Thank you
