### ISSUE TITLE
GeneratorResume mistakenly links the Suspend AO

### ISSUE THREAD

**Issue by syg** [tc39/ecma262#2168]
https://tc39.es/ecma262/#sec-generatorresume shouldn't be autolinking to Suspend.

Should rename Suspend to something else.

**Comment by ljharb** [comment]
or alternatively, can add a "not dfn" wrapper around that prose?

**Comment by jmdyck** [comment]
Looks like a duplicate of #1257.

**Comment by jmdyck** [comment]
> Should rename Suspend to something else.

"SuspendAgent" maybe?

**Comment by syg** [comment]
SuspendAgent sounds to me, closing as a duplicatee of #1257.
