### ISSUE TITLE
Editoral: consider removing overloads

### ISSUE THREAD

**Issue by bakkot** [tc39/ecma262#2171]
The Date, Array, and TypedArray constructors are defined as a collection of overloaded functions, as is TypedArray.prototype.set. That's pretty unusual; normally we'd have a single definition with steps which explicitly switched on the presence or types of arguments. We should consider doing that for those four cases as well.

Overloading is also pretty weird in light of the fact that built-in functions are said to be created by CreateBuiltinFunction, whose first argument is a _single_ collection of steps, not an overloaded collection of them:

> All values that are built-in function objects are created by performing CreateBuiltinFunction(steps, slots, realmRec, prototype) where steps is the definition of that function provided by this specification, [...]

**Comment by devsnek** [comment]
+1, I've also seen this confuse people because it only links to the top one and they don't realize there are more overloads down the page.

**Comment by jmdyck** [comment]
> normally we'd have a single definition with steps which explicitly switched on the presence or types of arguments.

I'm wondering how to declare the parameter list of the unified definition. E.g., for `Date`, would you say
`Date ( [ year [ , month [ , date [ , hours [ , minutes [ , seconds [ , ms ] ] ] ] ] ] ] )`
(and then deal with the weirdness that `Date(value)` doesn't interpret `value` as a year), or
`Date ( ...args )`
(and unpack arguments as necessary)?

I think I'd vote for the latter.
