### ISSUE TITLE
convert some Number:: AOs to use algorithm steps

### ISSUE THREAD

**Issue by michaelficarra** [tc39/ecma262#2179]
In the same way we recently rewrote all of the Math built-ins to use algorithm steps (#2122), some of the Number:: AOs can be rewritten in the more typical form, as a sequence of algorithm steps. I've identified the following AOs:

* Number::exponentiate
* Number::multiply
* Number::divide
* Number::remainder
* Number::add

/cc @ryanjduffy in case he has any interest doing another one of these.

**Comment by ryanjduffy** [comment]
Sure, I'm game.
