### ISSUE TITLE
IsWordChar uses undeclared alias InputLength

### ISSUE THREAD

**Issue by michaelficarra** [tc39/ecma262#2180]
I believe we need to use an abstract closure to capture InputLength from some other context.

**Comment by claudepache** [comment]
_InputLength_ and some other symbols are declared in [subsection Notation](https://tc39.es/ecma262/#sec-notation) of Pattern Semantics.

**Comment by michaelficarra** [comment]
Yes, it seems like those should all be captured via abstract closure when needed.

**Comment by bakkot** [comment]
This was fixed by #2716.
