### ISSUE TITLE
V10 of JSON.stringify() breaks RFC 8785

### ISSUE THREAD

**Issue by cyberphone** [tc39/ecma262#2186]
It might be a non-issue for ECMA but RFC 8785 (https://www.rfc-editor.org/rfc/rfc8785.html) have got quite some traction.  RFC 8785 was based on V6 of ECMAScript.

Unfortunately (for us...) V10 changes quoted string serialization so that 😂 nowadays must be serialized as `\ud83d\ude02`.  I doubt that anybody else does that but I don't have full insight in all JSON serializers.

The V10 change doesn't seem to have yet been adopted by the browser vendors:
https://cyberphone.github.io/doc/security/browser-json-canonicalization.html

Asking ECMA to return to < V10 is probably not an option so how about adding a method `canonify()` which does the entire RFC 8785 magic?  My guess is that it would add 20 lines of code to a typical ES JSON serializer.

**Comment by ljharb** [comment]
Hi! Unfortunately, this repo isn't the appropriate place for feature requests; please see https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal

For future reference, the issue template you cleared to file this issue also says this:
> Feature requests for future versions of ECMAScript should not be made in this
repository. Instead, they are developed in separate GitHub repositories, which
are then merged into the main repository once they have received "Stage 4".
>
> Please see [CONTRIBUTING.md](/CONTRIBUTING.md) for more details.

**Comment by bakkot** [comment]
> Unfortunately (for us...) V10 changes quoted string serialization so that 😂 nowadays must be serialized as \ud83d\ude02

Does it? In [QuoteJSONString](https://tc39.es/ecma262/#sec-quotejsonstring), step 2.c should apply, so that "Set product to the string-concatenation of product and ! CodePointToUTF16CodeUnits(C)." applies, which means that the code points are output directly, rather than being escaped.

To my understanding, the recent change only affected _lone_ surrogates, as in the string `"\ud83d"`, not surrogates which are part of a pair.

**Comment by cyberphone** [comment]
@ljharb can you verify that @bakkot is correct? I surely can't digest that from the current text.

**Comment by ljharb** [comment]
@cyberphone @bakkot's reading is my reading as well - in this case, that emoji is not listed in the table, nor is an unpaired surrogate, so it should fall into https://tc39.es/ecma262/#sec-codepointtoutf16codeunits.

**Comment by cyberphone** [comment]
That's FANTASTIC!  Thanx!
I apparently missed the conversion to code-points 😌
