### ISSUE TITLE
Is Note 2 from Array.prototype.slice meaningful?

### ISSUE THREAD

**Issue by littledan** [tc39/ecma262#219]
http://tc39.github.io/ecma262/#sec-array.prototype.slice

> NOTE 2 The explicit setting of the length property of the result Array in step 11 is necessary to ensure that its value is correct in situations where the trailing elements of the result Array are not present.

The explicit setting of length is a new change vs ES5. V8 implements it, and I don't see a downside from an implementation standpoint. But I don't understand what this note means. If this happens to be creating an %Array%, then doesn't ArraySpeciesCreate already start it out at the right final length, so the trailing holes will be present already?

**Comment by anba** [comment]
The explicit Put() was erroneously removed in ES5, it is present in ES3 (ES3, 15.4.4.10 Array.prototype.slice, step 19): https://bugs.ecmascript.org/show_bug.cgi?id=417

**Comment by littledan** [comment]
I can see how that's needed in ES5, since it constructs an empty array. However, in ES2015, we start with ArraySpeciesCreate of the appropriate length.

**Comment by anba** [comment]
I just wanted to provide the history behind the Set() call, I don't think I care whether or not it's present. But if it gets removed from Array.prototype.slice, it should also get removed from Array.prototype.splice (`Set(A, "length", actualDeleteCount, true)`).

**Comment by bterlson** [comment]
Leaving aside the issue of whether the set to length is still required (which we can consider if someone wants to seriously propose that), the note is confusing in light of ES2015 semantics. I will fix it presently.
