### ISSUE TITLE
consistently note in algorithms wherever steps may be inserted/modified elsewhere

### ISSUE THREAD

**Issue by michaelficarra** [tc39/ecma262#2191]
We have step references now to ensure that algorithm modifications (mostly or wholly from Annex B) refer to the correct step number. But we're inconsistent about actually stating within the algorithm steps that this algorithm is modified elsewhere. At least one example is [B.3.7.2](https://tc39.es/ecma262/#sec-IsHTMLDDA-internal-slot-aec) changing [7.2.15, Abstract Equality Comparison](https://tc39.es/ecma262/#sec-abstract-equality-comparison) with no indication within 7.2.15. Elsewhere we have notes inline as another step. We should do that everywhere.

**Comment by daemon1024** [comment]
I would like to work on this. 

From what I understood I need to add something like 
 
> Note _Additional Equality Comparison steps related to [[IsHTMLDDA]] Internal Slot can be found in B.3.7.2_

and similar notes in for other Annex B references.

**Comment by michaelficarra** [comment]
@daemon1024 Correct. And you don't need to write out "B.3.7.2" explicitly, you should use an `<emu-xref>` tag and the section number will be generated for you. We should add these notes at every place that is modified by Annex B, whether it is algorithm steps, table entries, or anything else. Feel free to ask any additional questions you may have once you've started, it won't be a bother.

**Comment by daemon1024** [comment]
@michaelficarra I couldn't understand how to reference [B.3.3.6 Changes to BlockDeclarationInstantiation](https://tc39.es/ecma262/#sec-web-compat-blockdeclarationinstantiation). I have tried to cover all others to the best of knowledge. Can you review it?

**Comment by michaelficarra** [comment]
@daemon1024 For B.3.3.6, I would add the note at the end of the step that is replaced, saying something like "Note that this step is replaced in section `<emu-xref href="#sec-web-compat-blockdeclarationinstantiation"></emu-xref>`."
