### ISSUE TITLE
Why are there only more than 100 forms here, but there are more than 400 in my browser

### ISSUE THREAD

**Issue by JackChengGZ** [tc39/ecma262#2192]
[https://tc39.es/ecma262/#sec-well-known-intrinsic-objects](url)
`var set = new Set();
var objects = [
    eval,
    isFinite,
    isNaN,
    parseFloat,
    parseInt,
    decodeURI,
    decodeURIComponent,
    encodeURI,
    encodeURIComponent,
    Array,
    Date,
    RegExp,
    Promise,
    Proxy,
    Map,
    WeakMap,
    Set,
    WeakSet,
    Function,
    Boolean,
    String,
    Number,
    Symbol,
    Object,
    Error,
    EvalError,
    RangeError,
    ReferenceError,
    SyntaxError,
    TypeError,
    URIError,
    ArrayBuffer,
    SharedArrayBuffer,
    DataView,
    Float32Array,
    Float64Array,
    Int8Array,
    Int16Array,
    Int32Array,
    Uint8Array,
    Uint16Array,
    Uint32Array,
    Uint8ClampedArray,
    Atomics,
    JSON,
    Math,
    Reflect];
objects.forEach(o => set.add(o));

for(var i = 0; i < objects.length; i++) {
    var o = objects[i]
    for(var p of Object.getOwnPropertyNames(o)) {
        var d = Object.getOwnPropertyDescriptor(o, p)
        if( (d.value !== null && typeof d.value === "object") || (typeof d.value === "function"))
            if(!set.has(d.value))
                set.add(d.value), objects.push(d.value);
        if( d.get )
            if(!set.has(d.get))
                set.add(d.get), objects.push(d.get);
        if( d.set )
            if(!set.has(d.set))
                set.add(d.set), objects.push(d.set);
    }
}
console.log(set)`

**Comment by Jack-Works** [comment]
Cause they are defined by W3C or WHATWG as a part of Web API which doesn't belong to the ECMAScript standard.

**Comment by ljharb** [comment]
Your code looks like it's counting intrinsics - the *well-known* intrinsics are only the ones listed in the table. Additionally, there's a few examples that have multiple entries in the spec that are `===` (like `Set.prototype.values` and `Set.prototype.keys`), and additionally, individual engines are allowed to add as many properties as they like to builtin objects, so there very well could be many more in a given engine than in the spec.

**Comment by devsnek** [comment]
By my count you should see around 480 intrinsics.

**Comment by JackChengGZ** [comment]
> By my count you should see around 480 intrinsics.

No,443 intrinsics

**Comment by JackChengGZ** [comment]
> Your code looks like it's counting intrinsics - the _well-known_ intrinsics are only the ones listed in the table. Additionally, there's a few examples that have multiple entries in the spec that are `===` (like `Set.prototype.values` and `Set.prototype.keys`), and additionally, individual engines are allowed to add as many properties as they like to builtin objects, so there very well could be many more in a given engine than in the spec.

You mean there are different objects in different host environments？

**Comment by ljharb** [comment]
@JackChengGZ absolutely. Hosts are allowed to modify any object in any way they like as long as they still provide what the spec dictates.

**Comment by devsnek** [comment]
> No,443 intrinsics

Your code misses symbol-named properties :)
