### ISSUE TITLE
ValidateAndApplyPropertyDescriptor unclear meaning of "create an own data property" or "create an own accessor property"

### ISSUE THREAD

**Issue by croraf** [tc39/ecma262#2200]
In https://tc39.es/ecma262/#sec-validateandapplypropertydescriptor in bullets `2.c.i` and `2.d.ii ` it is unclear which operations should be executed when it is said:

> create an own data property 

that is

> create an own accessor property

**Comment by ljharb** [comment]
What is unclear? Both terms are clickable, and link to https://tc39.es/ecma262/#sec-object-type, which describes in the first sentence/bulleted list what the terms mean.

The mechanism an implementation uses isn't specified, but you could imagine they're using https://tc39.es/ecma262/#sec-object.defineproperty.

**Comment by croraf** [comment]
Both terms link to the general description of property types. What is needed here are the links on how to create these properties, which should not be a subject of imagination or interpretation.

For example there is https://tc39.es/ecma262/#sec-createdataproperty and https://tc39.es/ecma262/#sec-createdatapropertyorthrow , should I use one of these two, if so which one?

**Comment by ljharb** [comment]
It very much is and should be subject to interpretation :-) the spec dictates what must be observable, it doesn't dictate how an implementation must go about producing those observable results. If it's unobservable, you *can* use one of those - you can also do literally anything you want as long as JS code can't tell the difference.

**Comment by croraf** [comment]
I see what is your point. 

I also now understand that the flow goes the other way around https://tc39.es/ecma262/#sec-object.defineproperty -> https://tc39.es/ecma262/#sec-createdatapropertyorthrow -> https://tc39.es/ecma262/#sec-createdataproperty -> https://tc39.es/ecma262/#sec-ordinary-object-internal-methods-and-internal-slots-defineownproperty-p-desc -> https://tc39.es/ecma262/#sec-validateandapplypropertydescriptor -> (implementation specific "create an own data property")

With this new knowledge I think that this might boil down to https://github.com/tc39/ecma262/issues/1067

**Comment by ljharb** [comment]
In that case, do you think this can be closed in favor of #1067?
