### ISSUE TITLE
JSON.parse needs to not apply the early error rule from B.3.1

### ISSUE THREAD

**Issue by bakkot** [tc39/ecma262#2206]
[`JSON.parse`](https://tc39.es/ecma262/#sec-json.parse) says

> Let _completion_ be the result of parsing and evaluating ! StringToCodePoints(scriptString) as if it was the source text of an ECMAScript Script. The extended PropertyDefinitionEvaluation semantics defined in [B.3.1](https://tc39.es/ecma262/#sec-__proto__-property-names-in-object-initializers) must not be used during the evaluation.

B.3.1 deals with `__proto__` in object literals. But it has two parts: the extended evaluation semantics, and a new early error rule forbidding multiple occurrences of `__proto__` in a single object literal. The early error rule is also not applied in implementations (and it would be weird to do so), but the spec text doesn't mention that the rule should not be applied.

**Comment by michaelficarra** [comment]
As per today's editor call, we will mark this change as normative but make the change without asking for consensus (as a spec bugfix) since it matches with what we believe the intent of the committee to have been and with all known implementations.
