### ISSUE TITLE
Object Oriented Programming questions.

### ISSUE THREAD

**Issue by huei90** [tc39/ecma262#221]
I'm not sure am I right to ask this question in this issue.

Based on the Overview

> ECMAScript is an object-oriented programming language for performing computations and manipulating computational objects within a host environment. 

Can we expect that the current (or future) JavaScript is already **officially define as OOP language**?

For the original designed for ECMAScript, means it is not.

> ECMAScript was originally designed to be used as a scripting language but has become widely used as a general purpose programming language. 

Sorry for this stupid question but it always confuse me.

**Comment by bterlson** [comment]
I'm not sure I understand the question, but JavaScript past and present is most certainly an OOP language for every useful definition of OOP I am aware of. Going forward this will not change.
