### ISSUE TITLE
Typed Objects information in proposal table is out of date

### ISSUE THREAD

**Issue by maxogden** [tc39/ecma262#223]
I noticed that the Typed Objects link in the readme points here: https://github.com/dslomov/typed-objects-es7, which is 2.5 years old. Brendan pointed me at https://github.com/nikomatsakis/typed-objects-explainer/, which is 1 year old. He also [mentioned](https://twitter.com/BrendanEich/status/671731769440243712) there is new work that supersedes these.

It appears the "new" proposal needs a champion.

- Is there a link to new proposal?
- Is there a champion for the new proposal?
- Should the Typed Objects proposal be removed for now?

**Comment by domenic** [comment]
My impression is that the new work is floating around in the heads of @littledan, @brendaneich, @bterlson, and maybe others. Nobody has committed to champion or transfer from head to computer. So removed probably makes the most sense at this point...

**Comment by bterlson** [comment]
Agreed, will remove for now, although I am personally very hopeful with continued thinking we can get to a stage 0 proposal for this soon :)

**Comment by chicoxyzzy** [comment]
Is there any news? Nobody wants to be the Champion? 😢
