### ISSUE TITLE
(memory model) Atomics.compareExchange is specified too strongly

### ISSUE THREAD

**Issue by conrad-watt** [tc39/ecma262#2231]
Currently, [Atomics.compareExchange](https://tc39.es/ecma262/#sec-atomics.compareexchange) is specified as performing an idempotent RMW in the case that the comparison fails. This is stronger than the [analogous C++11 operation](https://en.cppreference.com/w/cpp/atomic/atomic/compare_exchange), which only performs a load if the comparison fails.

Currently, V8 appears to implement compareExchange on ARMv8 as a [pair of load-store exclusives](https://github.com/v8/v8/blob/4b9b23521e6fd42373ebbcb20ebe03bf445494f9/src/compiler/backend/arm64/code-generator-arm64.cc#L429), and only a load is performed if the comparison fails.

The difference is visible in the following program, where `b` is some integer TypedArray wrapping a zero-initialised SAB:

| Thread 1 | Thread 2 |
| ------------- | ------------- |
| b[1] = 1; | b[2] = 2; |
| Atomics.compareExchange(b, 0, 42, 42);  | Atomics.compareExchange(b, 0, 42, 42);  |
| console.log(b[2]); | console.log(b[1]);  |

If it is guaranteed that Atomics.compareExchange will always perform an RMW, then the outcome 0, 0 is forbidden by the JS memory model, as the total ordering of atomics forces one thread to synchronise with the other, even though both Atomics.compareExchange comparisons will clearly fail. Both the C++11 model, and the V8 implementation above, permit this outcome.

To model this, instead of unconditionally performing an RMW (via the spec function GetModifySetValueInBuffer), there should be two possible cases in the operational semantics. Given the provided expectedValue, either a load event with a value that is `!=` the expectedValue must be emitted, or an RMW event with a load value that is `==` the expectedValue must be emitted. The choice is non-deterministic (constrained by the axiomatic memory model).

**Comment by waldemarhorwat** [comment]
Interesting. I agree with the proposed solution.

**Comment by syg** [comment]
Nice catch. I haven't had cycles to dig too deeply, but the fix sounds pretty sensible to me. Are you up for preparing a PR, @conrad-watt? If not I'll get to it next week.

**Comment by conrad-watt** [comment]
I'm currently crunching for an already late thesis submission, so I'd be very grateful to review a PR next week rather than prepare one myself, if that's something you have the bandwidth for. Otherwise I can get to it myself in a couple of weeks.

A similar gotcha was just found while drafting the Wasm threads spec and I mainly made this issue now so that knowledge could stay in sync.
