### ISSUE TITLE
tc39.github.io should show a index of the group's work

### ISSUE THREAD

**Issue by jyasskin** [tc39/ecma262#224]
https://help.github.com/articles/user-organization-and-project-pages/ explains how to do this: basically create a https://github.com/tc39/tc39.github.io repository and put the root content in its master branch.

**Comment by bterlson** [comment]
Agreed! Help welcome :)

**Comment by jyasskin** [comment]
Could you [create](https://github.com/organizations/tc39/repositories/new) the `tc39.github.io` repository, and then I'll send you a pull request for some initial content?

**Comment by bterlson** [comment]
Done!

**Comment by jyasskin** [comment]
It turns out I can't send a pull request on an empty repository. https://github.com/jyasskin/tc39.github.io has an initial redirect to the https://github.com/tc39/ecma262#ecmascript markdown documents. You can:

```
git clone https://github.com/jyasskin/tc39.github.io.git
cd tc39.github.io
git push git@github.com:tc39/tc39.github.io.git master
```
to accept it.

It'd be possible to set up a Jekyll site and move README.md and stage0.md there, but then we'd need more links back to the repository itself, so it may not be worth it.

**Comment by bterlson** [comment]
Done! Thanks for the help :)
