### ISSUE TITLE
Clarify if parameter to EvaluateCall can be a Reference Record

### ISSUE THREAD

**Issue by lukq** [tc39/ecma262#2243]
I think it should be clarified if parameter ref to EvaluateCall can be a Reference Record.

The text says: "ref (an ECMAScript language value)". ECMAScript language value means it cannot be a Reference Record, because a Reference Record is a Specification Type.

But the very first step in EvaluateCall says:
"1. If ref is a Reference Record, then"

This would suggest that ref can be a Reference Record.

Those two pieces of text are in contradiction.

**Comment by bakkot** [comment]
Nice catch. It can indeed be either, so the preamble should read "ref (an ECMAScript language value or a Reference Record)".
