### ISSUE TITLE
Editorial Clarification: Contains definition in 5.2.4 may be misleading

### ISSUE THREAD

**Issue by codehag** [tc39/ecma262#2251]
I don't know if I am the only person who will be confused with this, but worth asking. When preparing to introduce top level await on the stream, I came across the following line:

`Let async be body Contains await.` -- Knowing what top level await does, obviously, this must be ignoring functions right? 

I double checked in the spec. The first definition, when looking it up in the spec is this one here: https://www.ecma-international.org/ecma-262/11.0/index.html#sec-static-semantic-rules

```
    For each child node child of this Parse Node, do
        If child is an instance of symbol, return true.
        If child is an instance of a nonterminal, then
            Let contained be the result of child Contains symbol.
            If contained is true, return true.
    Return false.
```

This is a bit misleading, as later on we have notes like this one:

https://www.ecma-international.org/ecma-262/11.0/index.html#sec-object-initializer-static-semantics-contains

> Static semantic rules that depend upon substructure generally do not look into function definitions.

That seems pretty important. Maybe we should add this note to the description of the algorithm above?

**Comment by michaelficarra** [comment]
I agree with @bakkot, I don't think this would've been a problem if you could see the definition of `Contains` all in one place.

**Comment by codehag** [comment]
That sounds like a much more comprehensive change, and I would be in favor of that!

**Comment by bakkot** [comment]
Contains is now defined in [a single place](https://tc39.es/ecma262/#sec-static-semantics-contains), and all usages of it link there. Hopefully it's clearer now.
