### ISSUE TITLE
Let's re-evaluate our branch protection rules

### ISSUE THREAD

**Issue by MylesBorins** [tc39/ecma262#2269]
So I accidentally pushed to master... sooorrrrrry. Was not able to force push to revert the offending commits though.

Thankfully I was able to use my admin privileges to remove branch protection rules (couldn't edit due to strange GitHub 500 error) and get the branch cleaned up... but it seems like maybe I shouldn't have been able to push directly to master in the first place.

Since we need to fix all the rules now anyways (again sorry) it might be a good time to re-evaluate our defaults

**Comment by ljharb** [comment]
As an organization owner (by virtue of being a chair), it’s impossible to prevent you from pushing anywhere, as far as I’m aware.

Our defaults are as secure as GitHub allows them to be.

**Comment by ljharb** [comment]
I can’t post a screenshot of the branch protection page where it says “organization owners will always be able to push” due to 500 errors, but i think this can be closed because of that limitation, and we can call this a Spider-Man situation.
