### ISSUE TITLE
Question about the compiler

### ISSUE THREAD

**Issue by italoacasas** [tc39/ecma262#227]
Hi Guys, I'know maybe this it is not the correct place tu put this question but I don't find a good place anywhere.

Why JavaScript is not a interpreter language?
Why JavaScript is a "compiler" language?

**Comment by getify** [comment]
This is not really a support forum, but briefly...

JS has to be processed (aka "compiled") first before execution because some of the language mechanics require *early errors* (that is, compile-time errors) if certain conditions are found in the code, such as:

```js
"use strict";
function foo( x, x ) { .. }  // duplicate param name not allowed in strict mode
```

**Comment by ljharb** [comment]
The words "compiled" and "interpreted" technically refer to implementations, and as such, every single language could be compiled or interpreted.

However, the way they're most commonly used, I would classify JS as an interpreted language (not compiled), and C++ as a compiled language.

It really just depends on how pedantic you want to be about the definitions - if you stick with the most precise definition, no language is either, only an implementation is one or the other.
