### ISSUE TITLE
Does BigInt::bitwiseNOT return one's complement?

### ISSUE THREAD

**Issue by igoradamenko** [tc39/ecma262#2278]
The spec [says](https://www-1.ecma-international.org/ecma-262/#sec-numeric-types-bigint-bitwiseNOT) that BigInt::bitwiseNOT:

> ...returns the one's complement of x; that is, -x - 1.

I'm not sure, but I always thought that one's complement includes bits inverting only, while two's complement also requires adding / subtracting 1. 

Would you mind to check it?

Also I didn't found any other mentioning of one's complement in the spec. For Number::bitwiseNOT it [says](https://www-1.ecma-international.org/ecma-262/#sec-numeric-types-number-bitwiseNOT):

> Return the result of applying bitwise complement to oldValue. The result is a signed 32-bit integer.

And it's not quite clear what kind of complement it means.

(But it's possible that I'm just luck of the computing / binary theory knowledge here. Please, feel free to show me where I'm wrong.)

**Comment by igoradamenko** [comment]
I checked the implementation in Chrome, just to be sure:

```js
function getInt32Binary(n) {
  return (n >>> 0).toString(2).padStart(32, '0');
}
```

```
> getInt32Binary(10)
"00000000000000000000000000001010"

> getInt32Binary(~10)
"11111111111111111111111111110101"

> getInt32Binary(-10)
"11111111111111111111111111110110"

> getInt32Binary(~-10)
"00000000000000000000000000001001"
```

And it looks like for Number there's definitely a one's complement. So I guess the same is right for BigInt, and `-1` there means that we convert two's complement to one's complement, or something.

Sorry for interrupting ^_^".

**Comment by khokho1986** [comment]
0x975525d5CC92D872564535d0D5E8930bAc024Ff8

**Comment by khokho1986** [comment]
0x975525d5CC92D872564535d0D5E8930bAc024Ff8 @

**Comment by khokho1986** [comment]
0x975525d5CC92D872564535d0D5E8930bAc024Ff8

**Comment by khokho1986** [comment]
> 0x975525d5CC92D872564535d0D5E8930bAc024Ff8
