### ISSUE TITLE
`ApplyStringOrNumericBinaryOperator` does not validate `opText`

### ISSUE THREAD

**Issue by ljharb** [tc39/ecma262#2281]
https://tc39.es/ecma262/#sec-applystringornumericbinaryoperator asserts that `opText` is a sequence of Unicode code points, but does not validate that it is present in the table in step 7.

I assume we want an Assert that `opText` is in the relevant table?

**Comment by jmdyck** [comment]
We don't usually. E.g., consider the ~40 algorithm steps that look up something in Table 60 (The TypedArray Constructors), none of which bother to assert that the thing is present in the table.

**Comment by ljharb** [comment]
Can you link to a few examples? The ones i can find quickly are all starting from the table, whereas this one is starting from the key.

**Comment by jmdyck** [comment]
The first two are in [10.4.5.10 IntegerIndexedElementGet](https://tc39.es/ecma262/#sec-integerindexedelementget):
```
1. Let _elementSize_ be the Element Size value specified in [Table 60] for _arrayTypeName_.
1. Let _elementType_ be the Element Type value in [Table 60] for _arrayTypeName_.
```
These are not preceded by an assertion that `_arrayTypeName_` appears in Table 60.

**Comment by ljharb** [comment]
It probably should be then :-) altho in that case, the value is extracted from an internal slot that is always set to a correct value, which is a bit different than an AO argument.
