### ISSUE TITLE
Editorial: have annotations on AOs at both def and use sites that indicate "can call user code"

### ISSUE THREAD

**Issue by syg** [tc39/ecma262#2283]
It is often a source of bugs that implementers mistakenly assume that a call to an abstract operation is unobservable, while it in fact is due to calling hooks like `valueOf` or `toString`.

An editorial improvement for implementers would be to annotate abstract operations both at definition and use sites whether or not they can call out to user code. Added bonus, as @ljharb suggested, would be enumerate all hooks that immediately callable (as opposed to transitively callable).

**Comment by jmdyck** [comment]
If you want it to appear at both def and use, you could just make it part of the name.

Or do you want to distinguish the possibility that an AO can, in general, call user code, but *this particular invocation of it* cannot. For example, ToNumber can call ToPrimitive which can call user code, but if you establish that a particular callsite will only ever pass it a primitive value (e.g., in CanonicalNumericIndexString), that invocation won't call user code.

**Comment by syg** [comment]
> Or do you want to distinguish the possibility that an AO can, in general, call user code, but this particular invocation of it cannot. 

Yep, I was planning to capture this nuance. I want it to be per-use (more precise) as well as per-def (more conservative), for the AOs where you don't have to think about it per-use.

**Comment by ljharb** [comment]
This has landed.
