### ISSUE TITLE
ReferenceIdentifier instead of IdentifierReference?

### ISSUE THREAD

**Issue by tolmasky** [tc39/ecma262#2293]
This is a small nitpick, but was curious if this alternative name had been previously considered. It seems a little strange that the three identical `Identifier` definitions don't all share one naming convention, namely `IdentifierReference`, `BindingIdentifier`, and `LabelIdentifier`.

**Comment by michaelficarra** [comment]
The editors have discussed this suggestion. We acknowledge the inconsistency, but would prefer not to make this change.
