### ISSUE TITLE
Include trailing slash in GitHub Pages site link, otherwise GitHub redirects to non-https address

### ISSUE THREAD

**Issue by UltCombo** [tc39/ecma262#231]
Currently, the [repository](https://github.com/tc39/ecma262) description reads:

> Status, process, and documents for ECMA262 https://tc39.github.io/ecma262

Clicking on the https://tc39.github.io/ecma262 link will redirect to http://tc39.github.io/ecma262/ (with a trailing slash added, and https removed :exclamation:).

Please add the trailing slash to the link so it does not perform the unsafe redirect.

**Comment by ljharb** [comment]
GitHub pages are always on HTTP, so there's no way to avoid the "unsafe" redirect.

**Comment by mathiasbynens** [comment]
@ljharb https://tc39.github.io/ecma262/ is secure and doesn’t redirect.

**Comment by ljharb** [comment]
hm, you're right - i tried curling the various URLs and must have confused myself. You're exactly right. It's very strange that github has that redirect set up.

**Comment by bterlson** [comment]
This is garbage behavior.

**Comment by bterlson** [comment]
Fixed.
