### ISSUE TITLE
Inconsistent handling of optional arguments

### ISSUE THREAD

**Issue by brabalan** [tc39/ecma262#2315]
I have found some discrepancies in the way optional (spec) arguments are specified.

The [Algorithm Conventions](https://tc39.es/ecma262/#sec-algorithm-conventions) introduce the notation for optional arguments, but do not specify what their value is if they are not present.

Some functions, such as https://tc39.es/ecma262/#sec-toprimitive, explicitly test for the presence of the optional arguments.

Others, such as https://tc39.es/ecma262/#sec-object-value or https://tc39.es/ecma262/#sec-symbol-description, do not test the presence but compare the argument to `undefined` or `null`.

Another case is when the argument is not optional, but its presence is tested (https://tc39.es/ecma262/#sec-number-constructor-number-value or https://tc39.es/ecma262/#sec-string-constructor-string-value).

Hence my questions:
- What is the value of an absent optional argument? Is it `undefined`? And should it be added to the Algorithm Conventions?
  - https://tc39.es/ecma262/#sec-resolvebinding (step 1) seems to suggest absent and undefined are two different cases.
- Should presence only be tested for optional arguments (thus `Number` and `String` should be changed)?

**Comment by bakkot** [comment]
Clause 18, [ECMAScript Standard Built-in Objects](https://tc39.es/ecma262/#sec-ecmascript-standard-built-in-objects), says:

> Unless otherwise specified in the description of a particular function, if a built-in function or constructor is given fewer arguments than the function is specified to require, the function or constructor shall behave exactly as if it had been given sufficient additional arguments, each such argument being the undefined value. Such missing arguments are considered to be “not present” and may be identified in that manner by specification algorithms.

Note however that this applies only to _built-in functions_, not abstract operations. That is why [ToPrimitive](https://tc39.es/ecma262/#sec-toprimitive), an abstract operation, is written differently from [Object](https://tc39.es/ecma262/#sec-object-value), a built-in function.

For abstract operations, it is an editorial error to refer to the value of a possibly-absent parameter without first checking for its presence, so these things do not have values. For built-in functions the value is explicitly `undefined`, per the above-quoted paragraph.

**Comment by ljharb** [comment]
Additionally, the behavior of String and Number can not be changed due to web compatibility constraints. New APIs tend to treat absent and undefined the same.

**Comment by brabalan** [comment]
Thanks a lot for these clarifications.
