### ISSUE TITLE
Words about Symbol constructor

### ISSUE THREAD

**Issue by lygstate** [tc39/ecma262#2319]
```
20.4 Symbol Objects
20.4.1 The Symbol Constructor
The Symbol constructor:

is %Symbol%.
is the initial value of the "Symbol" property of the global object.
returns a new Symbol value when called as a function.
is not intended to be used with the new operator.
is not intended to be subclassed.
may be used as the value of an extends clause of a class definition but a super call to it will cause an exception.
```

"Symbol" property of the global object.
But how the property  are defined?
Didn't have the works like this:
`This property has the attributes { [[Writable]]: false, [[Enumerable]]: false, [[Configurable]]: false }.`

**Comment by ljharb** [comment]
https://tc39.es/ecma262/#sec-property-attributes specifies the default property descriptor for all properties.

**Comment by lygstate** [comment]
> https://tc39.es/ecma262/#sec-property-attributes specifies the default property descriptor for all properties defined by the spec.

Do you means https://tc39.es/ecma262/#table-default-attribute-values ?

```

Attribute Name | Default Value
-- | --
[[Value]] | undefined
[[Get]] | undefined
[[Set]] | undefined
[[Writable]] | false
[[Enumerable]] | false
[[Configurable]] | false


```
So the writable are false?

**Comment by bakkot** [comment]
I believe the correct reference is [clause 18, ECMAScript Standard Built-in Objects](https://tc39.es/ecma262/#sec-ecmascript-standard-built-in-objects), which says

> Every other data property [except "name" and "length" for functions] described in clauses 19 through 28 and in Annex B.2 has the attributes { [[Writable]]: true, [[Enumerable]]: false, [[Configurable]]: true } unless otherwise specified.

**Comment by ljharb** [comment]
Oops, yes, thanks - I’d found the wrong defaults section.
