### ISSUE TITLE
When generating the spec, we should output an 'emca262biblio.json' for tooling consumption.

### ISSUE THREAD

**Issue by rbuckton** [tc39/ecma262#2321]
The current spec build script does not output the latest version of `ecma262biblio.json`, which would be useful for tooling consumption:

https://github.com/tc39/ecma262/blob/c328b0aded262172094e1d9a44be216fc67b0632/package.json#L13

Suggested Change:

```diff
--- "build-only": "ecmarkup --no-ecma-262-biblio --verbose spec.html out/index.html --css out/ecmarkup.css --js out/ecmarkup.js", 
+++ "build-only": "ecmarkup --no-ecma-262-biblio --verbose spec.html out/index.html --css out/ecmarkup.css --js out/ecmarkup.js --biblio out/ecma262biblio.json", 
```

This would allow tools to fetch `https://tc39.es/ecma262/ecma262biblio.json` to ensure links in proposals are generated against the latest version of the spec.

**Comment by rbuckton** [comment]
Or, as is mentioned in tc39/ecmarkup#251, an external process that updates and publishes ecma262biblio.json so that other tools can use it as well.

**Comment by bakkot** [comment]
Yeah, we should address this at some point. I prefer publishing it as an npm package so that proposals can pin the version they were using at the time, for reproducible builds.

**Comment by rbuckton** [comment]
The problem with that is the same issue I just ran into prompting me to file the issue, pinning a version doesn't work for link references unless you have a published *pinned* version of that spec to refer to as well. I just ran into this with the change to rename `FunctionCreate`. If I was using a pinned version of the biblio, I still wouldn't be up to date with the spec.

In my opinion, if we were to pin anything it would only be for published editions of the spec according to the ECMA. We'd always want to also be able to reference the *live* version of the spec so that links work correctly. The only use I might have in having a version history of ecma262biblio.json files on NPM would be to find *when* a change occurred, i.e., reporting an error like "You previously referenced `FunctionCreate`, but that doesn't exist anymore. Maybe you meant `OrdinaryFunctionCreate`?".

We don't explicitly call out algorithm names syntactically in the spec, we just use string matching. As a result, a rename like `FunctionCreate` can't easily be caught (since it goes from being a valid link to being just PascalCased text without warning).

**Comment by bakkot** [comment]
You would be out-of-date in the sense that you'd be using the wrong name, but if you were using a biblio file which had that name it would still generate a link, and that link would still work: whenever we rename things we add an `oldid` so as not to break old links (unless there isn't a sensible place to put such an id). For example, even though there is no longer an operation named `FunctionCreate`, [#sec-functioncreate](https://tc39.es/ecma262/#sec-functioncreate) still works and points you to the right place.

**Comment by bakkot** [comment]
Biblio is available on npm as  [@tc39/ecma262-biblio](https://www.npmjs.com/package/@tc39/ecma262-biblio). Proposals can add it as a dependency and use the new `--load-biblio` to link against it.
