### ISSUE TITLE
Ambiguity in DoubleStringCharacter and SingleStringCharacter definitions

### ISSUE THREAD

**Issue by lhorie** [tc39/ecma262#2322]
The [spec](https://tc39.es/ecma262/) specifies DoubleStringCharacter as:

```
DoubleStringCharacter ::
    SourceCharacter but not one of " or \ or LineTerminator
    <LS>
    <PS>
    \ EscapeSequence
    LineContinuation
```

but specifies LineTerminator as:

```
LineTerminator ::
    <LF>
    <CR>
    <LS>
    <PS>
```

In effect this says `<LS>` and `<PS>` are both allowed and disallowed inside string literals without being preceded by a baskslash.

The same issue exists in the definition for SingleStringCharacter.

Expected: there should be no ambiguity
Actual: it's not clear from reading the spec whether `<LS>` and `<PS>` characters are allowed in string literals

**Comment by mathiasbynens** [comment]
> In effect this says `<LS>` and `<PS>` are both allowed and disallowed inside string literals without being preceded by a backslash.

I don’t believe that follows from the grammar you cited.

Imagine a double-quoted string literal containing only `<LS>`. This part of the grammar then does not match:

```
    SourceCharacter but not one of " or \ or LineTerminator
```

So we continue to check the other options. We move onto the next line which says:

```
    <LS>
```

…which matches.

There is no ambiguity.

P.S. `<LS>` and `<PS>` were added here as part of https://github.com/tc39/proposal-json-superset.

**Comment by lhorie** [comment]
Hmm ok makes sense, thanks!
