### ISSUE TITLE
Implementation inconsistencies of defineProperty on Integer Indexed Exotic Objects

### ISSUE THREAD

**Issue by bmeck** [tc39/ecma262#2328]
**Description:** Per Integer Indexed Exotic Objects in the spec, setting `configurable: false` should cause the define to fail.

[10.4.5.3 [[DefineOwnProperty]] ( P, Desc )](https://tc39.es/ecma262/#sec-integer-indexed-exotic-objects-defineownproperty-p-desc)
> iii. If Desc has a [[Configurable]] field and if Desc.[[Configurable]] is false, return false.

However, the browser engines do not do this. It is possible that 

**eshost Output:**

```
$ eshost -s -x 'Object.defineProperty(new Uint8Array([1]),0, {value: 1, configurable: false});'
#### ChakraCore, Moddable XS


#### Hermes

property: undefined

#### JavaScriptCore

TypeError: Attempting to store non-configurable property on a typed array at index: 0

#### SpiderMonkey

TypeError: can't redefine non-configurable property 0

#### V8

TypeError: Cannot redefine property: 0
```

More perplexing is that `eshost` seems to disagree with the browsers and node REPLs which do not error. I'm unclear how to reproduce the errors that `eshost` shows in those REPLs or even using a `<script>` tag.

**Comment by bakkot** [comment]
I think the eshost differences you're seeing is because this is something browsers have recently fixed. When I try running that snippet on Chrome Canary or Firefox Nightly it fails.

**Comment by bakkot** [comment]
Closing per above comment, but feel free to re-open if there's something I've missed.
