### ISSUE TITLE
isConcatSpreadable set to true

### ISSUE THREAD

**Issue by nzakas** [tc39/ecma262#233]
I may be missing it, but I can't seem to find anything in the spec indicating that `@@isConcatSpreadable` should be `true` for arrays.

For `@@hasInstance`, I noted this entry explaining the default value for functions: http://tc39.github.io/ecma262/#sec-function.prototype-@@hasinstance

I was expected to see something similar for `Array.prototype`. Is this defined somewhere?

**Comment by ljharb** [comment]
By my reading, http://tc39.github.io/ecma262/#sec-isconcatspreadable indicates that if `Symbol.isConcatSpreadable` is not present, then it falls back to `IsArray` - and also that it is *not* initially present on any value.

My understanding is that the well-known symbol is provided as an opt-out mechanism for Array subclasses who do not want the spreading behavior of `concat`, to ensure that legacy code paths continue to work with Arrays.

**Comment by nzakas** [comment]
Ah! Totally missed that. Thanks.
