### ISSUE TITLE
B1.1.1 B1.2.1 B.1.4.1 id="sec-???"

### ISSUE THREAD

**Issue by huei90** [tc39/ecma262#234]
All `sec-???` refer to the page

```
http://tc39.github.io/ecma262/#sec-???
```

For the correct one

B.2.1.1 escape (string) is show as

```
href="sec-escape-string"
http://tc39.github.io/ecma262/#sec-escape-string
```

**Comment by ljharb** [comment]
It indeed looks like sections B.1.1, B.1.2.2, and B.1.4.1 link to "#sec-???" (below http://tc39.github.io/ecma262/#sec-additional-syntax-numeric-literals), and need proper section identifiers. Thanks for reporting!

**Comment by huei90** [comment]
:+1:
