### ISSUE TITLE
A GitHub tc39.es link should point to a multipage version

### ISSUE THREAD

**Issue by arhadthedev** [tc39/ecma262#2347]
Probably, after #2339 introduced a multipage version, "About/Website" section of a GitHub repository should point there.

For now, it points to a single page version:

> ![A screenshot of a section in question](https://user-images.githubusercontent.com/4881073/111226514-4ddf6d00-85f2-11eb-83c3-eb0c537b6fc1.png)

**Comment by bakkot** [comment]
Eh, I think it makes sense to treat the single-page version as canonical. Unfortunately we can't link both.

**Comment by arhadthedev** [comment]
@bakkot, is it possible to somehow take an experience of WHATWG into consideration? Both their repository and site link to https://html.spec.whatwg.org/multipage/, which is useful considering the size of HTML Living Standard.

**Comment by bakkot** [comment]
My experience with the HTML specification is that whenever I end up on the multipage version I inevitably click through to the single-page one so I can C-f for the thing I'm interested in.
