### ISSUE TITLE
GlobalDeclarationInstantiation breaks on empty Script

### ISSUE THREAD

**Issue by jmdyck** [tc39/ecma262#2354]
When [ScriptEvaluation](https://tc39.es/ecma262/#sec-runtime-semantics-scriptevaluation) ("SE") invokes GlobalDeclarationInstantiation ("GDI"), it passes the value of `_scriptRecord_.[[ECMAScriptCode]]`, which is an instance of |Script| (despite the alias `_scriptBody_` in SE, see [PR #2353](https://github.com/tc39/ecma262/pull/2353/commits/77ad0dfa8333d4301f39c8c575931ae33af0644a), and also despite GDI's preamble claiming that it receives a |ScriptBody|).

But the |ScriptBody| of a |Script| is optional, and if you pass an empty |Script| to GDI, things explode, because numerous SDOs aren't defined on an empty |Script|:
- LexicallyDeclaredNames
- VarDeclaredNames
- VarScopedDeclarations
- LexicallyScopedDeclarations

(The only 2 SDOs that are defined on an empty Script are IsStrict and Evaluation, but the breakage happens before either is invoked.)

(This problem dates back to the merge of PR #242. Before that, SE was an SDO with an explicit check for empty Script.)

There are at least 3 ways to fix this:
- In ScriptEvaluation, check for empty Script before the call to GDI (and even before building the new execution context, I imagine, so step 1?).
- In GlobalDeclarationInstantiation, check for empty Script at about step 1 (the initial Assert could actually be absorbed into the preamble).
- Define LexicallyDeclaredNames etc on empty Script.

**Comment by devsnek** [comment]
I think the third option is the way to go here.
