### ISSUE TITLE
Editorial: notes and |s

### ISSUE THREAD

**Issue by domenic** [tc39/ecma262#236]
> NOTE If there are multiple |FunctionDeclaration|s for the same name, the last declaration is used.

> NOTE If there are multiple |FunctionDeclaration|s or |GeneratorDeclaration|s for the same name, the last declaration is used.

These should probably be an emu-note with emu-note styling, in addition to fixing the pipes.

Other leftover pipes:

> Consecutive |Term|s try to simultaneously match consecutive portions of \_Input\_. If the left |Alternative|, the right

(the underscores are also left there unprocessed)

> Return the character whose code is the SV of |Hex4Digits|.

this occurs multiple times (with pipes)

> is a specification type used to define the association of |Identifier|s

>  contains two nested |FunctionDeclaration|s then the Lexical Environments

>  language syntactic elements such as |FunctionDeclaration|s, |VariableDeclaration|s, and |Catch| clauses that

> arameter |Initializer|s may contain direct eval expressions

> The following tokens are ECMAScript keywords and may not be used as |Identifier|s in ECMAScript programs.

There are a few more I missed. In general search for "|" within the document and almost all matches are bad link cases :(

**Comment by bterlson** [comment]
Submitted some fixes to emd to address this (domenic/ecmarkdown#47)

**Comment by domenic** [comment]
Verified fixed!
