### ISSUE TITLE
ClassElement production only accounts for methods

### ISSUE THREAD

**Issue by mseld2** [tc39/ecma262#2361]
The *ClassElement* production in the documentation (https://tc39.es/ecma262/#prod-ClassElement) doesn't account for code like this. 

```javascript
class MyClass {
    static propTypes = <expr>;

    state = <expr>;
}
```

![image](https://user-images.githubusercontent.com/25728622/112567843-7ebc6080-8daf-11eb-8009-97e98c7c834a.png)

**Comment by bakkot** [comment]
That's because those aren't part of the language yet. See https://github.com/tc39/ecma262/pull/1668.
