### ISSUE TITLE
A step in String.prototype.replace

### ISSUE THREAD

**Issue by rcocco** [tc39/ecma262#2370]
21.1.3.17 String.prototype.replace ( searchValue, replaceValue )
11. Let newString be the string-concatenation of the first pos code units of string, replStr, and the trailing substring of string starting at index tailPos. If pos is 0, the first element of the concatenation will be the empty String.

What does "the first pos code units of string" mean?

**Comment by bakkot** [comment]
You appear to be using an outdated version of the spec; the current version, [here](https://tc39.es/ecma262/), does not use that wording.

Anyway, here _pos_ is an index within the string _string_. So, for example, if _pos_ is 5, then it would be "the first 5 code units of _string_". Does that answer the question?

If it's the term "code unit" that is confusing you, that's more a question about [Unicode](https://unicode.org/glossary/#code_unit) than this specification.
