### ISSUE TITLE
Feature request:webbrowser support javascript  package file format 

### ISSUE THREAD

**Issue by annopnod** [tc39/ecma262#2383]
javascript  package file format  is javascript multiple file + zip
Filename extension is jszip

**Comment by Jack-Works** [comment]
Out of scope. ECMA262 does not contain anything related to the file format.

**Comment by nicolo-ribaudo** [comment]
You might be interested in this: https://github.com/littledan/proposal-module-fragments/

It allows you to put multiple modules in a single file, and then you can use gzip, brotoli, or any other compression method supported by web browsers.
