### ISSUE TITLE
ToUint8Clamp should compare limits against Number values

### ISSUE THREAD

**Issue by anba** [tc39/ecma262#2395]
[https://tc39.es/ecma262/#sec-touint8clamp](ToUint8Clamp):
> 1. Let number be ? ToNumber(argument).
> 2. If number is NaN, return +0𝔽.
> 3. If ℝ(number) ≤ 0, return +0𝔽.
> 4. If ℝ(number) ≥ 255, return 255𝔽.
> ...

Shouldn't steps 3 and 4 use Number values for the comparison? Otherwise `ToUint8Clamp(+∞𝔽)` should be undefined behaviour, because `ℝ(+∞𝔽)` isn't defined.

**Comment by jmdyck** [comment]
> `ℝ(+∞𝔽)` isn't defined

I think that's correct. ℝ is the "mathematical value", and "The mathematical value of non-finite values is not defined." (The thing that's defined on infinities is "extended mathematical value", which isn't ℝ.)

Re-checking the spec for similar cases, what about `ℝ(_m_)` (x2) in `MakeDay`? (@bakkot)

**Comment by anba** [comment]
> Re-checking the spec for similar cases, what about `ℝ(_m_)` (x2) in `MakeDay`?

I think the check in step 1 avoids this issue in `MakeDay`;
> 1. If year is not finite or month is not finite or date is not finite, return NaN.

**Comment by jmdyck** [comment]
> I think the check in step 1 avoids this issue in `MakeDay`;
> 
> > 1. If year is not finite or month is not finite or date is not finite, return NaN.

Ah right, I was distracted by the calls to `ToIntegerOrInfinity`.

**Comment by michaelficarra** [comment]
We should be able to just guard the infinite doubles or replace the conversions with conversions to [extended mathematical value](https://tc39.es/ecma262/#extended-mathematical-value), right?

**Comment by dewren99** [comment]
Would it make sense to add the new steps `2.` and `3.` like shown below and return the `infinity` values back or is it preferable to throw `TypeError` or handle it another way?
```
1. Let number be ? ToNumber(argument).

2. if number is +∞𝔽, return +∞𝔽.
3. if number is -∞𝔽, return -∞𝔽.

4. If number is NaN, return +0𝔽.
5. If ℝ(number) ≤ 0, return +0𝔽.
6. If ℝ(number) ≥ 255, return 255𝔽.
```

**Comment by michaelficarra** [comment]
@dewren99 Yes, adding a guard should work, but it should return 255<sub>𝔽</sub> for the infinities. We can do it like this

> 1. Let number be ? ToNumber(argument).
> 
> 2. if number is +∞𝔽, return +∞𝔽.
> 3. if number is -∞𝔽, return -∞𝔽.
> 
> 4. If number is NaN, return +0𝔽.
> 5. If ℝ(number) ≤ 0, return +0𝔽.
> 6. If ℝ(number) ≥ 255, return 255𝔽.
