### ISSUE TITLE
RegExp: Are quantified lookaround assertions web-reality?

### ISSUE THREAD

**Issue by iainireland** [tc39/ecma262#2396]
**Description:** The [spec grammar for a regexp term](https://262.ecma-international.org/11.0/#prod-Term) says that a term is an assertion, an atom, or an atom followed by a quantifier. This implies that an assertion cannot be followed by a quantifier.

However, quantified lookarounds are allowed by all engines except Moddable:

**eshost Output:**

```
$ eshost -s -e "/a(?=b){2}/.test('ab')"
#### ChakraCore, JavaScriptCore, SpiderMonkey, V8
true

#### Moddable XS

SyntaxError: a(?=b){2} invalid quantifier

```
In irregexp, used by both SM and V8, [there is a comment](https://searchfox.org/mozilla-central/rev/1758450798ae14492ba28b695f48143840ad6c5b/js/src/irregexp/imported/regexp-parser.cc#231-233) indicating that support for quantified lookaheads was added "for compatibility with JSC and ES3". (The comment is [almost a decade old](https://codereview.chromium.org/6499016) and predates lookbehinds, but they appear to be supported as well.) I lost track of the history at this point, but if compatibility was an issue then, it's presumably web reality now.

Should we update the spec? The implemented semantics appear to be "repeat this assertion N times from the same point", which is redundant but harmless.

(Note that this all only applies to lookaround assertions. `/^{2}/`, `/${2}/`, `/\b{2}/`, and `/\B{2}/` all produce the expected errors in every engine.)

**Comment by anba** [comment]
Annex-B's [QuantifiableAssertions](https://tc39.es/ecma262/#prod-annexB-QuantifiableAssertion) allow this mode in non-Unicode RegExps.

**Comment by iainireland** [comment]
Ah, should have known to check Annex B. Thanks!
