### ISSUE TITLE
Editorial: Notes that tell you where a `Return` step returns to

### ISSUE THREAD

**Issue by jmdyck** [tc39/ecma262#2400]
Normally, when an operation executes a `Return` step, it transfers control back to the operation that invoked it. In fact, this is so normal that the spec doesn't even bother saying it.

So it's pretty weird that when the operation [GeneratorYield](https://tc39.es/ecma262/#sec-generatoryield) executes the `Return` at step 9, it *doesn't* return to its caller.

What makes it even weirder is that the only thing in the spec that *tells* you that it doesn't return to its caller is a Note (step 10), but Notes are supposed to be non-normative. If you remove the operation's Notes, there's nothing to tell you that step 9 *isn't* a garden-variety `Return`.

(As for the `Return` at 8.a, it's harder to say what the normal interpretation would be, because it's less clear what would constitute its "caller" if/when it executes, though I'd say that the GeneratorResume that will have just resumed it would have a better claim than whatever originally called GeneratorYield. So again, the Note at 8.b is necessary to convey the intended semantics of the `Return` step.)

The spec has 2 other places where a Note tells you where a `Return` returns to:
- [`Await`](https://tc39.es/ecma262/#await)
- [`AsyncGeneratorYield`](https://tc39.es/ecma262/#sec-asyncgeneratoryield)

Given that Notes should be non-normative, what are we to make of these cases?

----

For brevity, ORT = "operation return-target", i.e. where a `Return`-step in an abstract operation will return to.

In order for the `Return` steps to behave as the Notes indicate, the assumed mental model appears to be this:

If algorithm _A_ invokes operation _B_, and _B_ has a step of the form:
```
Remove _context_ from the execution context stack
 and restore the execution context that is at the top of the execution context stack
 as the running execution context.
```
then when _B_ executes that step, this causes _B_ to modify its ORT. Specifically, _B_'s ORT changes from:
- _A_, the algorithm that invoked _B_
to:
- _R_, the operation that had "most previously" (which I read as "most recently") resumed evaluation of _context_. I believe this is also the operation that was executing when the (newly) running execution context was last "running".

(E.g., when _B_ is `GeneratorYield`, _A_ might be a definition of the `Evaluation` SDO for a _YieldExpression_, and _R_ is `GeneratorResume`.)

Roughly speaking, the assumption appears to be that the ORT is an attribute of each execution context, so when you change the running execution context, you change where the current operation will return to.

(1)
It's odd that the spec would assume this mental model, because as far as I can tell, it doesn't do anything to *give* you that mental model. I had to reverse-engineer it from Notes.

(2)
As a model, it leaves questions unanswered:
- How does an execution context's ORT attribute get set in the first place? Does it ever change?
- What does it mean for an execution context to have single ORT when lots of operations might execute during the 'lifetime' of an execution context? They can't all return to the same place.
- What about operations that execute in the absence of an execution context?
- Does an execution context have other implied attributes that affect the execution of operations?

(3)
Even if we could answer those questions, it just seems to me like a bad model, where the semantics of something as basic as a `Return` step involve the current state of the execution context stack. In my opinion, we should only use `Return` when it has garden-variety semantics. If anything else is happening, we should use different phrasing. I'm working on a PR to that effect.

**Comment by jmdyck** [comment]
In [Await](https://tc39.es/ecma262/#await) and [GeneratorYield](https://tc39.es/ecma262/#sec-generatoryield), the relevant pseudo-code is roughly of the form:

  1. Remove _contextA_ from the execution context stack and restore the execution context that is at the top of the execution context stack as the running execution context.
  1. Set the code evaluation state of _contextA_ such that when evaluation is resumed with a Completion _v_ the following steps will be performed:
    1. A-STEPS using _v_
    1. Return A-VALUE
    1. NOTE: returns to whatever called this abstract operation
  1. Return B-VALUE.
  1. NOTE: This returns to the evaluation of the operation that had most previously resumed evaluation of _contextA_.

I believe we could editorially change this to (something like):

 1. Remove _contextA_ [etc]
 1. Let _contextB_ be the running execution context.
 1. NOTE: _contextB_ is the execution context that most recently resumed the evaluation of _contextA_.
 1. Resume _contextB_ passing B-VALUE. Let _v_ be the value returned by the resumed computation.
 1. Assert: If control reaches here, _contextA_ is once again the running execution context.
 1. A-STEPS using _v_
 1. Return A-VALUE. [which returns to whatever called this abstract operation]

(So one odd `Return` has become a garden-variety `Return`, and one has become a `Resume`.)

---

However, [AsyncGeneratorYield](https://tc39.es/ecma262/#sec-asyncgeneratoryield) doesn't fit this pattern. Before the outer `Return` occurs, there's a call to `AsyncGeneratorResolve`, and there's no semantics-preserving place to put it in my suggested rewrite.

Mind you, this call to `AsyncGeneratorResolve` is somewhat concerning anyway: it occurs *after* _genContext_ has been popped from the execution context stack, but *before* control has been transferred to the underlying context. So the circumstances of its execution are a bit puzzling.

**Comment by jmdyck** [comment]
Oh, also, in the case of `Await`, I believe it could become a proper abstract operation rather than a shorthand.

**Comment by bakkot** [comment]
The "Resume ... passing ..." language could be usefully extended to [GeneratorStart](https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-generatorstart) as well. GeneratorStart currently has (roughly, skipping some cases and details)

```
1. Set the code evaluation state of _genContext_ such that when evaluation is resumed for that execution context the following steps will be performed:
  1. Let _result_ be the result of evaluating _generatorBody_.
  1. Assert: If we return here, the generator either threw an exception or performed either an implicit or explicit return.
  1. Remove _genContext_ from the execution context stack and restore the execution context that is at the top of the execution context stack as the running execution context.
  1. Return CreateIterResultObject(_result_.[[Value]], *true*).
```

That final `Return` goes to step 9 of [GeneratorResume](https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-generatorresume) (or step 10 of [GeneratorResumeAbrupt](https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-generatorresumeabrupt)), which reads

```
1. Resume the suspended evaluation of _genContext_ using NormalCompletion(_value_) as the result of the operation that suspended it. Let _result_ be the value returned by the resumed computation.
```

Modulo an unfortunately normative change to the Realm used for the IterResultObject (which is [wildly inconsistent](https://gist.github.com/bakkot/587234af192dcb86f6a76b024a416c1c) in implementations), we could rewrite GeneratorStart as

```
1. Set the code evaluation state of _genContext_ such that when evaluation is resumed for that execution context the following steps will be performed:
  1. Let _result_ be the result of evaluating _generatorBody_.
  1. Assert: If we return here, the generator either threw an exception or performed either an implicit or explicit return.
  1. Let _iterResult_ be CreateIterResultObject(_result_.[[Value]], *true*).
  1. Remove _genContext_ from the execution context stack and restore the execution context that is at the top of the execution context stack as the running execution context.
  1. Let _outerContext_ be the running execution context.
  1. Resume _outerContext_ passing _iterResult_.
  1. Assert: Control does not reach here. _genContext_ can be discarded at this point.
```

---

This also applies to AsyncFunctionStart and (I think) AsyncGeneratorStart, though in those cases the value with which the outer context is resumed will not be consumed (except in AsyncFunctionStart, to assert it is `*undefined*`). But even so, changing the `Return` to an explicit `Resume` plus an assertion that control does not pass that point would be an improvement.

**Comment by brabalan** [comment]
>     1. Remove _contextA_ [etc]
>     2. Let _contextB_ be the running execution context.
>     3. NOTE: _contextB_ is the execution context that most recently resumed the evaluation of _contextA_.

Why don’t we store a reference to `_contextB_` in `_contextA_` when resuming it? This way we could say `Let _contextA_.[[lastResumed]] be the running execution context`.

**Comment by jmdyck** [comment]
> Why don’t we store a reference to `_contextB_` in `_contextA_` when resuming it? This way we could say `Let _contextA_.[[lastResumed]] be the running execution context`.

The current text says that control "returns to the evaluation of the operation that had most previously resumed evaluation of _contextA_", which suggests that _contextA_ has to remember where that is, and your suggestion would be a way to make that more explicit.

But really, control just transfers to what is now the running execution context, i.e., the context that was "under" _contextA_ on the stack, which by design is also the context that most recently resumed _contextA_. In effect, the execution context stack does all the remembering we need.

**Comment by brabalan** [comment]
OK, I missed that "running execution context" is a synonym to "top of the stack". It makes sense now, thanks.
