### ISSUE TITLE
Promise inaccurate definition of "resolve"

### ISSUE THREAD

**Issue by vwkd** [tc39/ecma262#2402]
Trying to understand the difference of "resolve" compared to "settle" with promises.

The [spec](https://tc39.es/ecma262/#sec-promise-objects) defines "resolve" as "settle or match state of another promise"

> A promise is resolved if it is settled or if it has been “locked in” to match the state of another promise.

Where "settle" is defined as "fulfill" or "reject".

> A promise is said to be settled if it is not pending, i.e. if it is either fulfilled or rejected.

Now, looking at uses of "resolve" in code like in `Promise.resolve(..)` or `new Promise((resolve, _) => {resolve(..)})`, it only ever refers to "**fulfill** or match state of another promise" (but not "reject"). E.g. for a non-promise non-thenable value, `Promise.resolve(..)` or `new Promise((resolve, _) => {resolve(..)})` only ever creates a fulfilled promise, but never a rejected one.

It seems like either the use of "settle" in the definition of "resolve", or the use of "resolve" in code is inaccurate.

**Comment by ljharb** [comment]
`new Promise(() => { throw null; })` creates a rejected promise.

The issue is that your qualifier - a non-promise non-thenable value - isn't useful. `resolve` specifically resolves *anything*, which includes a Promise or a thenable, to a new Promise that either is settled for that value or matches the state of the resolved thenable.

**Comment by vwkd** [comment]
Thinking about it more, I think the key example is to consider a non-promise thenable. It can actually adopt either state, fulfill or reject, meaning "settle" is actually the right term used.
