### ISSUE TITLE
Array#sort is underspecified

### ISSUE THREAD

**Issue by ljharb** [tc39/ecma262#241]
Reading http://www.ecma-international.org/ecma-262/6.0/#sec-array.prototype.sort, I see that the spec says two conflicting things about the `compareFn`.

Namely, `[1, 2].sort(foo)`, for a non-undefined, non-function foo, both is implementation-defined, and throws a TypeError (the same language is in [ES5](http://www.ecma-international.org/ecma-262/5.1/#sec-15.4.4.11)).

In Safari and Chrome (and IE < 9), a non-function non-undefined argument is ignored, and the default sort is used.
In Firefox, IE >= 9, and Edge, a non-function non-undefined argument throws a `TypeError`, as I'd expect.

This seems like something we should specify, and that Safari and Chrome should shift to the non-implementation-defined behavior of throwing for a non-function non-undefined argument. Thoughts?

**Comment by ljharb** [comment]
(The TypeError in the spec is step 4a in http://www.ecma-international.org/ecma-262/6.0/#sec-sortcompare)

**Comment by bterlson** [comment]
I don't think there's a conflict here. For non-function, non-undefined comparefn's, the _sort order_ is implementation defined but the result of the sort function is normatively defined in sec-sortcompare. Safari and Chrome are wrong per spec I believe.

**Comment by ljharb** [comment]
Thanks for clarifying! I'll add a patch to es5-shim and a test to the compat-table.

**Comment by bterlson** [comment]
If this isn't covered in test262 it should be :-P /cc @goyakin
