### ISSUE TITLE
Bug or intended? ContainArguments does not cover object literal shorthands

### ISSUE THREAD

**Issue by Jack-Works** [tc39/ecma262#2423]
https://tc39.es/ecma262/multipage/ecmascript-language-functions-and-classes.html#sec-static-semantics-containsarguments

This code is invalid:

```js
function x() {
    return class T { a = arguments }
}
```

But this is not:

```js
function x() {
    return class T { a = { arguments } }
}
```

Is it a bug in the spec?

**Comment by ljharb** [comment]
if it sets `a` to an object containing the arguments object for `x`, then it seems like it isn’t supposed to be valid.

**Comment by bakkot** [comment]
It looks like it's covered to me. The `arguments` in a shorthand property [is an IdentifierReference](https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#prod-PropertyDefinition), same as [the one in a primary expression](https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#prod-PrimaryExpression). What makes you think it's not covered?

**Comment by Jack-Works** [comment]
Oh so it's a Chrome bug sorry

**Comment by Jack-Works** [comment]
I have submitted it in crbugs https://bugs.chromium.org/p/chromium/issues/detail?id=1216261
