### ISSUE TITLE
Inconsistency between specification definition of Math.hypot and engine implementations

### ISSUE THREAD

**Issue by IdanHo** [tc39/ecma262#2425]
**Description:** The psuedo code implementation provided in the latest specification https://tc39.es/ecma262/#sec-math.hypot returns `NaN` for the following evaluation: `Math.hypot(NaN, Infinity)`, while the 2020 specification (and as a result, js engines) returns `Infinity` in any call to Math.hypot that includes `Infinity` as an argument.

**Comment by bakkot** [comment]
Nice catch! This was introduced in #2122 and not quite fixed in #2172.

Opened a PR to fix at #2426.
