### ISSUE TITLE
`/(?<foo>A)\k<foo>/` is a syntax error unless using Annex B

### ISSUE THREAD

**Issue by mysticatea** [tc39/ecma262#2434]
**Description:** Adding 1 and 1 is two, but it should be...

From https://github.com/mysticatea/regexpp/issues/23.

This is about `/(?<foo>A)\k<foo>/` without `u` flag and without Annex B.

- [22.2.3.2.3 Static Semantics: ParsePattern ( patternText, u )](https://tc39.es/ecma262/#sec-parsepattern) says "if no `u` flag, parse the pattern without `N` parameter, then if no syntax errors exist and named capturing groups exist, re-parse the pattern with `N` parameter."
- `\k` is a syntax error if no `N` parameter and no Annex B.

As a result, named capturing groups without `u` flag are always a syntax error.

I think [IdentityEscape](https://tc39.es/ecma262/#prod-IdentityEscape) requires `[~N] k` or something like that in order to allow named capturing groups with no `u` flag.

**eshost Output:**

```
```

(I'm not sure about the environment without Annex B)

**Comment by bakkot** [comment]
It's a syntax error on the first pass, I agree, but that means that it will re-parse with the `N` parameter set, and when parsing with the `N` parameter we have the production `AtomEscape ::  k GroupName`, which matches `\k<foo>` as in this example. Since it parses successfully on the second pass, it's allowed.

**Comment by mysticatea** [comment]
Yes, it skips the second pass if the first pass had a syntax error, and `\k` in the first pass is a syntax error.

Maybe, should both the `N` parameter and two passes parsing move to Annex B? Those look to be for Annex B behaviors.

**Comment by devsnek** [comment]
I think this is correct as specified. The first pass will parse `\k<foo>` as the atoms `k` `<` `f` `o` `o` `>`, not a syntax error.

**Comment by mysticatea** [comment]
@devsnek That's right in Annex B. But it's a syntax error in the spec core because the sequence `\` `k` is not allowed.

**Comment by devsnek** [comment]
hm... is that the "but not UnicodeIDContinue" in the spec? i must have a bug in engine262

**Comment by bakkot** [comment]
> is that the "but not UnicodeIDContinue" in the spec?

Yes. Keep in mind that's only there for the non-Annex B grammar, i.e. the one which is not used in actual implementations. (The [Annex B variant](https://tc39.es/ecma262/multipage/additional-ecmascript-features-for-web-browsers.html#prod-annexB-IdentityEscape) does not have that restriction.)

**Comment by mysticatea** [comment]
> https://github.com/mysticatea/ecma262/commit/757927687ee99e96e9e39a88f6122716cc3088f2

That may be a candidate to patch this issue.

1. Remove two passes parsing from [22.2.3.2.3 Static Semantics: ParsePattern ( patternText, u )][22.2.3.2.3]. It parses the pattern with `[+N]` always. This should be no problem because there are no other differences than allowing named backreferences.
2. Add an Annex B section to extend [22.2.3.2.3 Static Semantics: ParsePattern ( patternText, u )][22.2.3.2.3] to introduce two passes parsing for backward compatibility about `\k`. 

[22.2.3.2.3]: https://tc39.es/ecma262/#sec-parsepattern

**Comment by scole66** [comment]
This is also #1888, sort of.
