### ISSUE TITLE
BigInt NumericValue definition missing exponent

### ISSUE THREAD

**Issue by apsillers** [tc39/ecma262#2443]
ES2020 defines the value of a parsed BigInt token in 11.8.3.2 as 

> 1. Let *n* be the mathematical integer number of code points in *DecimalDigits*.
> 2. Let *mv* be (the MV of *NonZeroDigit* × 10<sub>ℝ</sub><sup>n</sup>) plus the MV of *DecimalDigits*.

ES2021 erroneously dropped the `n` exponent in 12.8.3.2, and it is missing in the current draft:

> 1. Let *n* be the number of code points in *DecimalDigits*, excluding all occurrences of *NumericLiteralSeparator*.
> 2. Let *mv* be (the MV of *NonZeroDigit* × 10) plus the MV of *DecimalDigits*.

**Comment by jmdyck** [comment]
Change occurred in PR #2007 ([at this line](https://github.com/tc39/ecma262/commit/5c7ef7044676471fd19c2696f334b5045565e7af#diff-181371b08d71216599b0acccbaabd03c306da6de142ea6275c2135810999805aR11201)).

The point was presumably to remove just the `<sub>ℝ</sub>`, but the `<sup>_n_</sup>` also got deleted.
