### ISSUE TITLE
@@unscopables should not apply to the global environment record

### ISSUE THREAD

**Issue by rossberg-chromium** [tc39/ecma262#245]
According to the [current](http://tc39.github.io/ecma262/#sec-getidentifierreference) [spec](http://tc39.github.io/ecma262/#sec-global-environment-records-hasbinding-n), the following program should produce `undefined`:
```
this[Symbol.unscopables] = {Object: true}
Object  // undefined
```
Of all 3 browsers that implement @@unscopables (Chrome, Edge, Safari), none seems to handle that. And there is a likely reason: it would be disastrous for performance, at least unless very complicated measures are taken in VMs. That's because every access to a conventional global variable `x` would require also looking up  `window[@@unscopables].x`, i.e., two extra property look-ups. Worse, as a consequence, all existing (and essential) optimisations around global variable access are invalidated by this semantics.

I'm not sure if this semantics was intended, or where it would be useful (@@unscopables was introduced for dealing with `with` legacy). But given the implications and the noteworthy failure of all browsers to implement it correctly, I propose removing @@unscopables filtering for the global environment.

**Comment by anba** [comment]
The "If the withEnvironment flag of envRec is false, return true." handles this case. (withEnvironment is false for the object environment of the global environment.)

**Comment by rossberg-chromium** [comment]
@anba, argh, you're right, how did I miss that! Sorry for the noise.
