### ISSUE TITLE
Replacing the current editors of ECMAScript 2022

### ISSUE THREAD

**Issue by NothingIsAvailable** [tc39/ecma262#2454]
Let's contact ECMA and ask them to replace the current editors of ECMAScript 2022. The current editors worked on ECMAScript 2021 which is a total failure as it doesn't have documentation for web developers on how to use the language. These editors have no clue how to develop a product; if web developers don't have an authoritative reference for learning, then what is the point in creating a standard seeing no one will know how to use it?!

The editors of HTML know what's going on:

Documentation for browser developers: https://html.spec.whatwg.org/multipage/

Documentation for web developers: https://html.spec.whatwg.org/dev/

ECMAScript 2022 has no future with the current developers. Let ECMA know of this problem.

**Comment by ljharb** [comment]
This is a highly unproductive way to engage with anyone, and violates our code of conduct.

Separately, the editors’ job is to produce a spec; they’ve done so. There is plenty of documentation for individual implementations; you’ve linked to some - there’s nothing that needs doing here.
