### ISSUE TITLE
8 & 9 should not be legal ECMA octal constants because they don’t exist in the octal alphabet

### ISSUE THREAD

**Issue by sickcodes** [tc39/ecma262#2455]
08-09, 18-19... 78-99, etc. do not exist in the octal numbering system and should be removed in "sloppy" or "non-strict" mode.

See: https://hackerone.com/reports/1141623

And: https://bugs.chromium.org/p/chromium/issues/detail?id=1193424#c_ts1623546105

**Comment by ljharb** [comment]
They can’t be removed from sloppy mode, or websites would break.

**Comment by sickcodes** [comment]
Which websites?

8 base 8 simply does not exist, meaning octal literal bugs are being used as a feature.

**Comment by nicolo-ribaudo** [comment]
Since 8 doesn't exist in base 8, `08` is interpreted as a base 10 number.

In order to remove it, we would first have to show that no website relies on that behaviour.

**Comment by sickcodes** [comment]
CoffeeScript & Typescript have already banished inexistent octal literals from sloppy mode.

NodeJS sloppy and V8 sloppy mode both rely on flip flopping between base 8 and base 10.

ECMA should specify base 10 for all zero prefixed integers (will break things) or use base 8 only, not flip flop between them.

Having looked at this for almost 6 months straight, if anyone is using flip flopping between base 8 (expected) and then base 10 (for undefined octal literals) then they are using the bug as a feature, unfortunately.

From NodeJS: "Note that it is not possible to end up with such a case with user input unless the code is dynamically constructed and executed (such as with eval(), new Function() or the Node.js vm module."

**Comment by nicolo-ribaudo** [comment]
> then they are using the bug as a feature, unfortunately

Maybe it was a bug 25 years ago, but now it is an _explicit_ feature defined in the specification.

**Comment by sickcodes** [comment]
I understand `use strict;` disables the feature, and using `0o8` in sloppy mode works as expected. And yes it's a rule, hence why I am opening a public issue in the relevant place.

I'd like to put in a succinct question:

"Given that the octal scale is from 0-7, and prefixing `0` generally expects the octal literals to be eval'ed in base 8, should completely invalid octal literals be interpreted as base 10, when users, or most users, are unlikely to have read the ECMA rules regarding octal literal usage in sloppy mode?"

**Comment by nicolo-ribaudo** [comment]
> Given that the octal scale is from 0-7, and prefixing 0 generally expects the octal literals to be eval'ed in base 8, should completely invalid octal literals be interpreted as base 10, when users, or most users, are unlikely to have read the ECMA rules regarding octal literal usage in sloppy mode?

If we were designing a new language, then numbers starting with `0` should either be completely forbidden or be consistently parsed always using the same base.

However, we are talking about a feature that has been part of the language for 25 years and the probability that it will not break any code are zero.

I found this discussion: https://esdiscuss.org/topic/early-error-on-0-followed-by-8-or-9-in-numeric-literals-does-not-seem-to-be-web-compatible

It is about strict mode (where numbers starting with `0`) are already forbidden, and it has some real-world examples (`new Date(2014, 08, 06)`) that currently work (even if they might not produce the expected date), but that with this change would make those websites completely unusable by making then throw a syntax error before even starting to evaluate their JS code.

"sloppy mode" (the only ECMAScript mode where `08` and `09`) are allowed is "legacy" and it contains many unwanted features that cannot be removed to avoid breaking compatibility with legacy JS programs (such as the `with` statement). If you are concerned about legacy features, you can put `"use strict"` at the beginning of your program, or even better use ECMAScript modules which are strict by default.

**Comment by sickcodes** [comment]
Noted, thanks for pointing out that discussion. Many points there are the same as mine and remain the same today.

To quote Mathias Bynens (7 years ago)

https://esdiscuss.org/topic/early-error-on-0-followed-by-8-or-9-in-numeric-literals-does-not-seem-to-be-web-compatible#content-16

_The literals under discussion (e.g. 08 and 09) are not octal literals._

The discussion was accurate and the sloppy mode `new Date(2014, 01, 08)` is in fact parsing using radix/base 8, except for `08` and `09`, which are evaluated in base 10, ala decimal. Use strict code that uses new Date will fail.

Referencing the discussion with NodeJS, it's probably impossible to get to that stage without `eval` or user input.

Given this issue is nearing 10 years old, I think it would be relevant to keep it open anyway.

**Comment by nicolo-ribaudo** [comment]
> Referencing the discussion with NodeJS, it's probably impossible to get to that stage without eval or user input.

It's definitely possible, you can just write `new Date(2014, 01, 08)` and it will work. I think the mention of `eval` in the Node.js discussion is because your examples were passing a specific _syntax_ to `parseInt`, but `parseInt(08)` and `parseInt(8)`, even if they have different syntaxes, are _exactly the same thing_ at runtime.

**Comment by sickcodes** [comment]
> > Referencing the discussion with NodeJS, it's probably impossible to get to that stage without eval or user input.
> 
> 
> 
> It's definitely possible, you can just write `new Date(2014, 01, 08)` and it will work. I think the mention of `eval` in the Node.js discussion is because your examples were passing a specific _syntax_ to `parseInt`, but `parseInt(08)` and `parseInt(8)`, even if they have different syntaxes, are _exactly the same thing_ at runtime.

They should not be the same thing at runtime, in sloppy mode.

Correct, 08 is impossible to get without user input, because it is a literal. E.g. dynamically submitting new Date into runtime JS via PHP etc.

V8 + Node & SpiderMokey all follow these rules, and cracks are starting to show.

It's been 7 years since the last ECMA standard discussion so I just thought I'd bump the topic.

**Comment by ljharb** [comment]
@sickcodes `var oops = '08'; eval(oops) === 8` works fine with user input.

**Comment by sickcodes** [comment]
> Hi @sickcodes, we talked on Twitter a few weeks ago.
> 
> 
> 
> Everyone agrees that the specified behavior is very strange, but, as mentioned above and in the esdiscuss thread, it cannot be changed without breaking websites, which we are not going to do. (Yes, even though the websites are relying on behavior which should never have existed in the first place; that's not a good enough reason to break them.) So there's nothing to be done here. As such I'm going to close this issue, but feel free to continue the discussion if you're still not clear on what's happening here.

It is a good enough reason to properly deprecate them because the vulnerability is being used as a feature when everyone in the thread agrees it should be fixed.

**Comment by sickcodes** [comment]
> @sickcodes `var oops = '08'; eval(oops) === 8` works fine with user input.

It should be undefined

**Comment by sickcodes** [comment]
![image](https://user-images.githubusercontent.com/65906298/125356785-39b83c00-e356-11eb-8ace-361da515a1f6.jpeg)

**Comment by bakkot** [comment]
> It is a good enough reason to properly deprecate them because the vulnerability is being used as a feature when everyone in the thread agrees it should be fixed.

These are already as deprecated as we can make them: they are only available in non-strict contexts, they are called "legacy" in the specification, and their use is [discouraged](https://tc39.es/ecma262/multipage/additional-ecmascript-features-for-web-browsers.html#sec-additional-ecmascript-features-for-web-browsers).

**Comment by sickcodes** [comment]
> > It is a good enough reason to properly deprecate them because the vulnerability is being used as a feature when everyone in the thread agrees it should be fixed.
> 
> 
> 
> These are already as deprecated as we can make them: they are only available in non-strict contexts, they are called "legacy" in the specification, and their use is [discouraged](https://tc39.es/ecma262/multipage/additional-ecmascript-features-for-web-browsers.html#sec-additional-ecmascript-features-for-web-browsers).
> 
> 
> 
> > It should be undefined
> 
> 
> 
> That would be a more reasonable behavior, but we can't change the current behavior without breaking websites, which we are not going to do.

Thanks for that, I agree that they have been deprecated and the sloppy one is the only issue.

What about changing all 0 prefixed numbers in sloppy mode to base 10 only instead of base 8 plus base 10 of every non-existent octal?

What would that break?

That way anyone who intends to allow octal data input would eventually move to strict.

**Comment by ljharb** [comment]
@sickcodes the reality is that there's tons of code in sloppy mode that both relies on `07` being octal and `08` being decimal, whether on purpose or not. These semantics, like almost everything in JS, can't be changed without breaking websites.

**Comment by sickcodes** [comment]
07 in base 8 is the same in base 10

**Comment by bakkot** [comment]
`011` is a better example than `07`. Lots of code relies on `011 === 9`.

**Comment by sickcodes** [comment]
> `011` is a better example than `07`. Lots of code relies on `011 === 9`.

Agreed, but what about `018`...

**Comment by bakkot** [comment]
Lots of code relies on `018` being `18` too, almost certainly.

**Comment by bakkot** [comment]
> Okay but how can this be considered reliable:

No one has claimed that this behavior makes sense, just that we can't change it now without breaking a bunch of sites, which we aren't going to do.
