### ISSUE TITLE
ValidateAndApplyPropertyDescriptor description should state that P can be undefined

### ISSUE THREAD

**Issue by heycam** [tc39/ecma262#2466]
https://tc39.es/ecma262/#sec-validateandapplypropertydescriptor says:

> The abstract operation ValidateAndApplyPropertyDescriptor takes arguments O (an Object or undefined), P (a property key), ...

but IsCompatiblePropertyDescriptor calls it with P = undefined, so I think the above should say "P (a property key or undefined)".

**Comment by ljharb** [comment]
Since `ValidateAndApplyPropertyDescriptor` never actually references `P` when `O` is `undefined`, an alternative fix might be to pass an empty string instead of undefined.
