### ISSUE TITLE
Optional arguments should give an error or warning if not placed last when declaring a function

### ISSUE THREAD

**Issue by dyrich** [tc39/ecma262#2474]
If optional arguments aren't placed last when declaring a function, they will be ignored and the wrong values will be assigned to the parameters of the function.
```


function test(arg1 = 0, arg2, arg3){
}

test(2, 3); // Here arg3 will be undefined. This should give an error or warning.
```

**Comment by nicolo-ribaudo** [comment]
Adding an error to an existing feature would cause all the websites relying on it to stop working.

This should be handled by a linter, which checks your code for disallowing "bad patterns". For example, if you use ESLint you can enable the [`default-param-last`](https://eslint.org/docs/rules/default-param-last) rule.

**Comment by ljharb** [comment]
Technically this isn't an optional argument - it's just a defaulted one. `test.length` will be 3 because you must *always* pass at least 3 arguments to correctly call the function.
