### ISSUE TITLE
inline Table 57: Replacement Text Symbol Substitutions

### ISSUE THREAD

**Issue by michaelficarra** [tc39/ecma262#2479]
https://tc39.es/ecma262/#table-replacement-text-symbol-substitutions

This table is weird. It inlines algorithm steps and has some non-standard grammar matching and interpretation of parse nodes. We should get rid of this table and describe the contained behaviour within the above algorithm using typical means.

**Comment by jmdyck** [comment]
See also https://github.com/tc39/ecma262/pull/1580#discussion_r345957938

I've been thinking about this a bit. I'll volunteer to do it unless someone else wants to.

**Comment by michaelficarra** [comment]
@jmdyck Sure, feel free.
