### ISSUE TITLE
ContainsUndefinedContinueTarget needs a BlockStatement implementation

### ISSUE THREAD

**Issue by scole66** [tc39/ecma262#2481]
**Description:** The Static Semantics function `ContainsUndefinedContinueTarget` needs (at least) one more not-default implementation.

This function takes two arguments, an _iteration_set_, which contains labels a continue statement may use, and _label_set_, a list of labels which might get added to the _iteration_set_, if they apply to iteration statements.
Specified implementations except for _LabelledStatement_ and _BreakableStatement_ always reset the _label_set_ parameter to the empty list (as it's clear their productions are _not_ iteration statements).
The _default_ implementation, however, does _not_ clear the label set.

Consider: `lbl : { for ( ;; ) continue lbl ; }`

This is an undefined continue target. The _BlockStatement_ labelled by `lbl` is not an iteration statement. Web reality produces a syntax error here.

The production tree looks like

```
    LabelledStatement : LabelIdentifier : LabelledItem
    └── LabelledItem : Statement
        └── Statement : BlockStatement
            └── BlockStatement : Block
                └── Block : { StatementList }
                    └── StatementList : StatementListItem
                        └── StatementListItem : Statement
                            └── Statement : BreakableStatement
                                └── BreakableStatement : IterationStatement
```

_ContainsUndefinedContinueTarget_ for the first production adds `lbl` to the label set. 
All the remaining productions prior to the _BreakableStatement_ use the default implementation.
The _BreakableStatement_ moves the label set (containing `lbl`) into the iteration set and thus makes this label seem like a _valid_ target.

(If we actually tried to execute this code, the loop executor functions would actually treat that continue statement like a break statement, and the seemingly infinite loop would actually terminate at the first iteration.)

Fix: 
  The clearest fix would seem to be to add an implementation for the _Statement_ : _BlockStatement_ production:
  1. Return _ContainsUndefinedContinueTarget_ of _BlockStatement_ with arguments _iterationSet_ and « ».

This error seems to have been in every ECMAScript spec since the static semantics system was added in ES 6. (In particular, this issue was not due to the recent refactoring of syntax directed operations.)

**Comment by bakkot** [comment]
Huh, yup, looks like a bug. Since the current semantics are coherent, even though they don't match web reality, I think we'll need consensus to change this, but that should be easy to get.
