### ISSUE TITLE
for-await-of execution and promises as values

### ISSUE THREAD

**Issue by zloirock** [tc39/ecma262#2496]
In all modern engines
```js
for await (const value of [Promise.resolve(1), 2, Promise.resolve(3)]) {
  console.log(value); // => [ 1, 2, 3 ]
}
```
But [in the spec](https://tc39.es/ecma262/#sec-runtime-semantics-forin-div-ofbodyevaluation-lhs-stmt-iterator-lhskind-labelset) I don't see the step of resolving of the `nextValue`, `Await` applied only to the iterator step, so why the result is not
```js
for await (const value of [Promise.resolve(1), 2, Promise.resolve(3)]) {
  console.log(value); // => [Promise.resolve(1), 2, Promise.resolve(3)]
}
```
?

Sorry if I misunderstood something.

**Comment by devsnek** [comment]
It is going through the AsyncFromSyncIteratorPrototype.

**Comment by zloirock** [comment]
Yes, thanks, already found. Seems it should be solved on `AsyncFromSyncIteratorContinuation` side, sorry.
