### ISSUE TITLE
About the confusing Note section in isNaN()

### ISSUE THREAD

**Issue by jacty** [tc39/ecma262#2507]
![image](https://user-images.githubusercontent.com/4190959/132843834-85521f34-e46d-4681-9224-8fa2d287ade8.png)
In the Note section, it says for X !== X results true, the only value of X is NaN, however, [] !== [] results true as well but isNaN([]) returns false as shows below.
![image](https://user-images.githubusercontent.com/4190959/132844000-b90be237-dcc0-424c-b5f4-833ff440ea63.png)
Link of the context:
https://tc39.es/ecma262/#sec-isnan-number

**Comment by ljharb** [comment]
That example isn’t the same value. Do `const x = []; x !== x`, for any value in the x variable.

**Comment by jacty** [comment]
> That example isn’t the same value, it’s just the same source text. Do `const x = []; x !== x`, for any value in the x variable.

Oh, yes. Thanks for pointing out. But I wonder if we should change the word `value` here in `if a value X is`, since in my example, `[]` should be deemed as a value.  I wonder if we could use `if a Reference/Variable is` to make it clearer?  Or maybe we can have some examples written in the Note section?

**Comment by ljharb** [comment]
`[]` is a value. It's just that a different `[]` in the source text is a distinct value.
