### ISSUE TITLE
Wrong text in specification

### ISSUE THREAD

**Issue by PallHaraldsson** [tc39/ecma262#2516]
https://tc39.es/ecma262/
A.
"This Ecma Standard defines the ECMAScript 2022 Language. It is the twelfth edition" contradicts further down:

"ECMAScript 2021, the 12th edition". So change to "upcoming thirteenth edition"?

and:

B.
"A formal description and implementation of UTF-8 is given in RFC 3629.

In UTF-8, characters are encoded using sequences of 1 to 6 octets."

Actually RFC 3629 states "are encoded using sequences of 1 to 4 octets" (up to 6 is now outdated info, was legal before).

**Comment by ljharb** [comment]
For the first one, indeed I forgot that in 1f748a41d, and will update it shortly.

For the second one, when was that change made? Does that constitute an observable change in JavaScript that implementations may or may not have implemented?

**Comment by PallHaraldsson** [comment]
UTF-8 was changed to allow a maximum of four octets (bytes) a long time ago, to conform with UTF-16. UTF-16 strings can't map to longer (at least legal ones, I'm not sure how illegal ones are handled, but I believe no exception). Longer, illegal by now, UTF-8 sequences can't map to UTF-16.

I'm no expert on JavaScript implementations or the spec, I just noticed this in it, not sure what known JavaScript implementations actually do (also irrelevant since this is about the spec, only important what the spec says they should do, while it may track what some actual one does) with illegal UTF-8 sequences. They must do something, but the limit isn't 6 for them, since illegal sequences can be arbitrary long. It's just that 5 or 6 byte long were once legal. I very much doubt they try to support such lengths any differently.

**Comment by PallHaraldsson** [comment]
Even if I'm wrong and5 and 6 byte strings are somehow handled (in a sane or insane way), you have the power to change the spec. It would only mean implementations haven't caught up with modern UTF-8. E.g. JSON (the file format) now specifies (legal) UTF-8, independently of JavaScript.
