### ISSUE TITLE
Why is Realm always capitalized?

### ISSUE THREAD

**Issue by domenic** [tc39/ecma262#252]
It seems weird. It's not a proper noun.

**Comment by anba** [comment]
If "Realm" is used to refer to the schema of the Realm record type, it needs to be capitalized. Similar to other named schemata like PropertyDescriptor, Completion, Reference etc.

**Comment by domenic** [comment]
Agreed. But it almost never is.

**Comment by bterlson** [comment]
Hmm, I think it always is? When is it not?

**Comment by domenic** [comment]
> Before it is evaluated, all ECMAScript code must be associated with a Realm.

> well-known symbols values are shared by all Code Realms

> Well-known intrinsics are built-in objects that are explicitly referenced by the algorithms of this specification and which usually have Realm specific identities.

A few others I think...

**Comment by bterlson** [comment]
These seem like proper Realm usage (ECMAScript code must be associated with a Realm[ record]). Code Realm and Realm seem interchangeable so I'd probably say "shared by all Realms" instead, though :-P

**Comment by domenic** [comment]
I guess you could interpret things that way; seems like a stretch to me, but happy to close.

**Comment by allenwb** [comment]
"Realm" was the original name used for the concept but  the original title of subclause 8.2 was "Code Realms" . In that context "code" was just a clarifying adjective. In practice we ended up using the terms "Realm", "realm", and "Code Realm" interchangeably to refer to the abstraction.  Realm Record refers to a specific data structure.

I wsuggest that we just use "Realm" (with the cap) to refer to the abstraction. (hence "a Realm" would be an instance of the abstraction) and "Realm Record" when referring to the data structure.

**Comment by domenic** [comment]
Bikeshed: we should use lowercase "realm" for the concept, so that it is not confused with the "Realm" record type, and so as to match other concepts like "execution context". I agree with removing "code" prefix and with trying to explicitly suffix "Record" where appropriate.

**Comment by bterlson** [comment]
@domenic I'd take such a PR, I guess.
