### ISSUE TITLE
need `/$YEAR/` URLs

### ISSUE THREAD

**Issue by ljharb** [tc39/ecma262#2529]
Whenever we update https://tc39.es/ecma262/, we should also ensure that the following URLs exist and work:
 - https://tc39.es/ecma262/2021/
 - https://tc39.es/ecma262/2020/
 - https://tc39.es/ecma262/2019/
 - https://tc39.es/ecma262/2018/
 - https://tc39.es/ecma262/2017/
 - https://tc39.es/ecma262/2016/
 - https://tc39.es/ecma262/2015/ (if possible, but maybe not since this was never generated by ecmarkup)
 
 It's fine if past years are not updated once the edition is cut, since ecmarkup evolves and the spec snapshot does not.

**Comment by arhadthedev** [comment]
But public releases are already available via `https://262.ecma-international.org/$VERSION/` (see https://www.ecma-international.org/publications-and-standards/standards/ecma-262/), why clone them to tc39.es?

**Comment by ljharb** [comment]
@arhadthedev if for no other reason, because those links are created every year with the release, and [Cool URIs don't change](https://www.w3.org/Provider/Style/URI).

Additionally, we could also perhaps provide a helpful popup (like on PR previews) that warns people they're viewing an outdated snapshot of the specification, which isn't something Ecma has been interested in doing on their own site.
