### ISSUE TITLE
Grammar notation declares "token", "terminal" and "input element" as synonyms; they need to be merged

### ISSUE THREAD

**Issue by arhadthedev** [tc39/ecma262#2535]
<https://tc39.es/ecma262/#sec-grammar-notation> introduces terms in bold in the following way:

> **Input elements** other than white space and comments form the **terminal symbols** for the syntactic grammar for ECMAScript and are called ECMAScript **tokens**.

1. A part "Input elements form ... and are called tokens" directly states that *input element* and *token* are two different words for the same thing.

2. A part "Input elements ... form the terminal symbols" may imply that each input element is transformed into a terminal symbol. However, with <https://tc39.es/ecma262/#sec-lexical-and-regexp-grammars> I suspect this is not the case:

    > 1: ... sequences of such code points are translated into a sequence of **input elements**.
    >
    > 2: This grammar has as its **terminal symbols** Unicode code points that conform to ...

    Here, both *input element* and *terminal symbol* are defined as just a sequence of code points. Since terminals cannot have payload (like MV or SS/RS), they are really just synonyms too.

So I think these three terms need to be merged into "input element" (so a grammar will have nonterminals and input elements) or into "terminals" (so a lexer will take a sequence of code points and emits a sequence of terminals)  to not introduce extra entities with no need.

*P. S.: Probably, the term can also be `<def>`-ined?*

**Comment by jmdyck** [comment]
> 
> 1. A part "Input elements form ... and are called tokens" directly states that _input element_ and _token_ are two different words for the same thing.

It says "Input elements **other than white space and comments** ... are called tokens". That is, the set of input elements is partitioned into tokens and non-tokens, and white space and comments are not tokens. So "input element" and "token" are not synonyms.

> 2. A part "Input elements ... form the terminal symbols" may imply that each input element is transformed into a terminal symbol. However, with https://tc39.es/ecma262/#sec-lexical-and-regexp-grammars I suspect this is not the case:
>    > 1: ... sequences of such code points are translated into a sequence of **input elements**.
>    > 2: This grammar has as its **terminal symbols** Unicode code points that conform to ...
>        
> Here, both _input element_ and _terminal symbol_ are defined as just a sequence of code points.

Quote 2 is saying that in the *lexical* grammar, each terminal symbol is a *single* Unicode code point. Quote 1 is saying that the lexical grammar defines what sequences of Unicode code points make input elements. So "input element" and "terminal symbol" aren't synonyms either.

Each grammar defines a set of terminal symbols:
- In the syntactic grammar, each terminal symbol is a token.
- In the lexical grammar, each terminal symbol is a Unicode code point.

**Comment by arhadthedev** [comment]
Thanks for clarifications, I didn't catch these details first time. Closing since absence of a problem.
