### ISSUE TITLE
Confusing wording in String.prototype.toLowerCase()

### ISSUE THREAD

**Issue by littledan** [tc39/ecma262#254]
http://tc39.github.io/ecma262/#sec-string.prototype.tolowercase

> For each code point c in cpList, if the Unicode Character Database provides a language insensitive lower case equivalent of c then replace c in cpList with that equivalent code point(s).

A later note clarifies that this is supposed to take SpecialCasing.txt into account, which includes context-sensitive mappings (like Final_Sigma). test262 tests like built-ins/String/prototype/toLocaleLowerCase/special_casing_conditional test for the correct context-sensitive behavior. Why is this written in terms of a character-by-character mapping, rather than just deferring entirely to the Unicode Default Case Algorithms (see page 152 of http://www.unicode.org/versions/Unicode8.0.0/ch03.pdf)?

@caridy

**Comment by bterlson** [comment]
@allenwb do you know any relevant history here?

**Comment by caridy** [comment]
@bterlson this seems to be the case for 402 as well. I don't know the history, but I'm growing fond to the idea of delegating more and more to ICU Algos. I have two long debates today about this with @littledan and @srl295.

**Comment by srl295** [comment]
Character by character is wrong also. `ß` uppercases to `SS`.

**Comment by srl295** [comment]
Yes, I would support specifying the algorithms in reference to Unicode (not ICU), such as "R1 toUppercase(X)" in the PDF linked by @littledan

**Comment by anba** [comment]
Fixed in #932
