### ISSUE TITLE
BigInt ToInteger does not throw a TypeError exception

### ISSUE THREAD

**Issue by gonzobard777** [tc39/ecma262#2543]
The documentation says that converting BigInt to Number should **always** throw a TypeError exception: https://tc39.es/ecma262/multipage/abstract-operations.html#sec-tonumber

But if you apply conversion through the constructor, for example like this:
```js
Number(5n)
```
as a result, there is [no error](https://tc39.es/ecma262/multipage/numbers-and-dates.html#sec-number-constructor-number-value).

**Comment by gonzobard777** [comment]
Yes, indeed, my mistake.
Number constructor uses `ToNumeric`.
Thanks.

**Comment by bakkot** [comment]
Closing as answered, but feel free to reopen if there's a further issue here.
