### ISSUE TITLE
change iterator end sentinel in IteratorStep from false to a spec enum

### ISSUE THREAD

**Issue by michaelficarra** [tc39/ecma262#2551]
This AO currently returns an Object (typically an IteratorResult object, but I don't believe it's guaranteed) or *false*. It's weird to use *false* here. We should use a spec enum here like `~done~` or something.

**Comment by nilaygit-10721** [comment]
can you assign me this issue?

**Comment by michaelficarra** [comment]
@nilaygit-10721 We don't assign issues. If you'd like to submit a PR, go ahead.

**Comment by bakkot** [comment]
This was done in https://github.com/tc39/ecma262/pull/3311.
