### ISSUE TITLE
URL anchors of subsections inside `12.8 Literals` are inconsistent

### ISSUE THREAD

**Issue by arhadthedev** [tc39/ecma262#2558]
It seems that for the most of the subsection each anchor is a decapitalized copy of a human readable title:

- 12.1 Unicode Format-Control Characters → `#sec-unicode-format-control-characters`
- 12.2 White Space → `#sec-white-space`
- 12.3 Line Terminators → `#sec-line-terminators`
- 12.4 Comments → `#sec-comments`
- 12.5 Tokens → `#sec-tokens`
- 12.6 Names and Keywords → `#sec-names-and-keywords`
- 12.8.2 Boolean Literals → `#sec-boolean-literals`
-  etc.

However, some ones break this scheme:

- 12.8 Literals → `#sec-ecmascript-language-lexical-grammar-literals` (contains `ecmascript-language-lexical-grammar`)
- 12.8.3 Numeric Literals → `#sec-literals-numeric-literals` (first `literals` not presented for 12.8.1 and 12.8.2)
- 12.8.4, 12.8.5, 12.8.6 → `#sec-literals-string-literals`, `#sec-literals-regular-expression-literals`, `#sec-template-literal-lexical-components` (the same)

**Comment by jmdyck** [comment]
> It seems that for the most of the subsection each anchor is a decapitalized copy of a human readable title:

Yup, but there are cases where two different sections have the same human readable title, so this scheme would result in them having the same id, which would violate the uniqueness constraint for ids. So we add something different to each 'colliding' id to make them distinct. One thing to add is the parent section's id. (And if *those* are the same, then the grandparent section's id, and so on. They have to differ eventually, though it doesn't normally involve a full hierarchy path.)

To take up your example, both 12.8 and 13.2.3 are entitled "Literals". They can't both claim `sec-literals`, so neither does. Instead,
- 12.8 is in 12 "ECMAScript Language: Lexical Grammar", so it gets `sec-ecmascript-language-lexical-grammar-literals`, and
- 13.2.3 is in 13.2 "Primary Expression", so it gets `sec-primary-expression-literals`.

**Comment by arhadthedev** [comment]
@jmdyck, thank you, now I see. I didn't expect conflicting names to be prefixed equally, rather thinking about a short id for a primary section and prefixed secondary ids for accidental collisions. So after unsuccessful trials of opening short ids, I incorrectly concluded that existing counterparts are just some forgotten artifacts of previous naming scheme.
