### ISSUE TITLE
ECMA for Public Community

### ISSUE THREAD

**Issue by transdigiware** [tc39/ecma262#2563]
The ECMAScript community. There are a number of ways to contribute to the development of this specification:

GitHub Repository: https://github.com/tc39/ecma262
Issues: All Issues, File a New Issue
Pull Requests: All Pull Requests, Create a New Pull Request
Test Suite: Test262
Editors:
Shu-yu Guo (@_shu)
Michael Ficarra (@smooshMap)
Kevin Gibbons (@bakkoting)
Community:
Discourse: https://es.discourse.group
Chat: Matrix
Mailing List Archives: https://esdiscuss.org/

**Comment by ljharb** [comment]
This seems to just be text copy-pasted from the spec.
