### ISSUE TITLE
Editorial: sometimes we don't put stars around null

### ISSUE THREAD

**Issue by bakkot** [tc39/ecma262#2565]
We should probably be consistent.

E.g. [here](https://tc39.es/ecma262/multipage/ecmascript-language-scripts-and-modules.html#table-exportentry-records) we leave them out.

**Comment by jmdyck** [comment]
The only others case I can find is in [4.4.6 object](https://tc39.es/ecma262/multipage/overview.html#sec-terms-and-definitions-object). Well, there's also [4.4.15 null value](https://tc39.es/ecma262/multipage/overview.html#sec-null-value), but it's only in the section title: would adding stars make a difference in the rendering?

(Your example is the `Value Type` column of a Record Fields table. Those could probably stand some more general consistification.)
