### ISSUE TITLE
Can ASCII letter productions be consolidated?

### ISSUE THREAD

**Issue by gibson042** [tc39/ecma262#2570]
**Description:**
ECMA-262 has two distinct lexical productions with identical right-hand sides consisting of all ASCII letters:
* [_uriAlpha_](https://tc39.es/ecma262/#prod-uriAlpha), in the URI Syntax and Semantics grammar
* [_ControlLetter_](https://tc39.es/ecma262/#prod-ControlLetter), in the Regular Expression grammar

There's also a another one coming soon from Temporal, [_Alpha_](https://tc39.es/proposal-temporal/#prod-Alpha).

Would it make sense to consolidate these in e.g. the base lexical grammar, or do editors find the duplication useful?

**Comment by michaelficarra** [comment]
I think it'd be fine to consolidate them. The consolidated production name should be something general, like `AsciiLetter`.
