### ISSUE TITLE
Outdated branches without associated pull requests need to be deleted

### ISSUE THREAD

**Issue by arhadthedev** [tc39/ecma262#2579]
tc39/ecma262 repository has some unmerged branches with no associated pull requests. Their changes either cover deleted concepts or are already presented in `main`:

- `emu-see-also` - a single commit  that removes all occurences of `<emu-see-also-para>`. Not relevant after 2a18346 was merged abandoning the last occurences of this tag by the way;
- `test-travis` - a single commit that introduces Travis CI-specific build targets. Not relevant since b4e31f6;
- *`sdos` - I did not analyze these twelve commits hoping their authors know whether the relevant parts are already live*;
- *`fix-math-fix` - four commits, their changeset **looks** vaguely included into later commits*.

In addition, here are `add-zones` and `ipr-check` inside `main`. Probably, they were supposed to be removed after merging.

**Comment by ljharb** [comment]
Why do they necessarily need to be deleted? There’s nothing wrong with branches sitting around.

**Comment by arhadthedev** [comment]
I'm sorry for the delay, I waited if some branches are still in local (yet unpublished) development so someone notes it.

Pull request authors seem to delete base branches after their PR is closed without merge (for branches created right in `tc39/ecma262` examples of deletion events are https://github.com/tc39/ecma262/pull/2562#event-5543271245 and https://github.com/tc39/ecma262/pull/2366#event-4544633154). So for consistency outdated non-PR development branches also should be removed.

**Comment by ljharb** [comment]
Why? Consistency for consistency's sake has no intrinsic value.

**Comment by arhadthedev** [comment]
I agree that benefits are intangible here because feature branches are interesting for their authors only.

The only matter is that temporary branches became quite permanent for no reason, but since it creates no inconvenience outside of deliberate `git branch` browsing, I understood that it looks rather like decorative trimming of a bush.
