### ISSUE TITLE
Dead links in LICENSE.md

### ISSUE THREAD

**Issue by arhadthedev** [tc39/ecma262#2585]
LICENSE.md has two links to ecma-international.org, both are 404:

- "Ecma text copyright policy" (https://www.ecma-international.org/memento/Ecma%20copyright%20faq.htm)
- "Ecma International Policy on Submission, Inclusion and Licensing of Software" (https://www.ecma-international.org/memento/Policies/Ecma_Policy_on_Submission_Inclusion_and_Licensing_of_Software.htm)

They need to be changed to relevant ones.

**Comment by ljharb** [comment]
Thanks; instead of changing the links; I’ll report them to ecma to restore, since URLs should work forever.

**Comment by arhadthedev** [comment]
The URLs are partially fixed with redirects to the same hub page ([Ecma IPR policies](https://www.ecma-international.org/policies/by-ipr/)). However, I think the links need to give direct access as before, so they should:

- redirect https://www.ecma-international.org/memento/Ecma%20copyright%20faq.htm to https://www.ecma-international.org/policies/by-ipr/ecma-text-copyright-policy/
- redirect https://www.ecma-international.org/memento/Policies/Ecma_Policy_on_Submission_Inclusion_and_Licensing_of_Software.htm to https://www.ecma-international.org/policies/by-ipr/ecma-international-policy-on-submission-inclusion-and-licensing-of-software/

**Comment by arhadthedev** [comment]
@ljharb The "restored" URLs still continue to redirect to the same portal page of twelve links instead of the documents directly:

![image](https://user-images.githubusercontent.com/4881073/146224332-1df49ecd-5db3-4f0d-8f89-41a88942349b.png)

So it looks like a person in charge misunderstood a purpose of the report.

**Comment by ljharb** [comment]
Thanks; i reported that with your previous comment and am waiting on a response.

**Comment by arhadthedev** [comment]
Three month passed and links still redirect to the hub. Should I give up and close the issue?

**Comment by ljharb** [comment]
Nope, the passage of time doesn’t change the relevance of the issue.

**Comment by ecmageneva** [comment]
Not sure I can follow the issue. 
I get access to the following entry page to all Ecma IPR policy items: 
https://www.ecma-international.org/policies/by-ipr/
Is there anything wrong on that?
By the way if you have problems please "cut it short" and contact directly patrick@ecma-international.org who is in charge of maintaining the links on the Ecma Website, much better than to use this forum.

**Comment by patrickcharollais** [comment]
Good day,

The two redirections have been implemented as requested. The issue can therefore be closed.

Enjoy this week and all the best from a cloudy Geneva.

Patrick

**Comment by ljharb** [comment]
Thanks @patrickcharollais and @ecmageneva!
