### ISSUE TITLE
consistent wording for SDO application with argument(s)

### ISSUE THREAD

**Issue by michaelficarra** [tc39/ecma262#2616]
When applying an SDO, we sometimes use the form

> Return the result of performing RestDestructuringAssignmentEvaluation of AssignmentRestProperty with value and excludedNames as the arguments.

and sometimes use the form

> Return the result of performing RestDestructuringAssignmentEvaluation of AssignmentRestProperty with arguments value and excludedNames.

We should only use the latter. Same goes for the single argument form.

**Comment by michaelficarra** [comment]
There's also this wording:

>  Perform ? PropertyBindingInitialization of BindingPropertyList using value and environment as the arguments.

**Comment by jmdyck** [comment]
There are also a few cases where "passing" is used instead of "with" or "using".

**Comment by Rahmon** [comment]
@michaelficarra I'd like to work on this one :relaxed:

**Comment by michaelficarra** [comment]
@Rahmon Great! Let me know if you need any clarification or assistance.
