### ISSUE TITLE
Discussion about `import * as Object from 'module'`

### ISSUE THREAD

**Issue by tomma5o** [tc39/ecma262#2631]
Hey, my first time here, sorry in advance if I've made some error about the process of opening an issue.
Just want to discuss the `import * as Object from 'module'` feature in ECMAScript.

Why there is no way to import only _some_ definitions? sometimes where do we use some utility packages like **lodash** or **ramda** that exposes utility functions is a common practice to rename it or wrap it to make it recognizable at first glance from where it comes from.

Today if we want to import some methods from another module but having it "wrapped" inside an object we need to do:
```js
import { pathOr, mergeRight } from 'ramda';
const R = { pathOr, mergeRight };
```
Why we can't do:
```js
import { pathOr, mergeRight } as R from 'ramda';
```

**Comment by ljharb** [comment]
Thanks for your thoughts. This repo isn't the appropriate place for feature requests or general discussion of features; please see https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal

For future reference, the issue template you cleared to file this issue also says this:
> Feature requests for future versions of ECMAScript should not be made in this
repository. Instead, they are developed in separate GitHub repositories, which
are then merged into the main repository once they have received "Stage 4".
>
> Please see [CONTRIBUTING.md](/CONTRIBUTING.md) for more details.

This may be more relevant on https://es.discourse.group
