### ISSUE TITLE
Offline/Sandboxed Mode for web applications

### ISSUE THREAD

**Issue by EdSaleh** [tc39/ecma262#2632]
Hi,

To allow safety and data security in the web for users, I propose that we add Offline/SandBoxed mode to JavaScript and/or browser. When SandBoxed mode is on for a website when enabled, it will only allow specific configured hosts or none (e.g. CSV file) for requests. The user could force a web application to be SandBoxed by enabling a proposed 'sandboxed' checkbox + config textbox/file when installing PWA of the website as well for example.
We can also allow inter-browser communication for SandBoxed applications to allow Syncing across devices as well.

This would allow user to ensure that data and interaction with web application is secure and available locally and not sent to any server.
This would allow, for example, creating notes or word application that saves documents only on users computer and not send any user data to cloud unless specified.

Thank you,

**Comment by ljharb** [comment]
Thanks for your thoughts. This repo isn't the appropriate place for feature requests; please see https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal

However, this specific request is far out of scope for the JS language itself, and would be more appropriate for the HTML spec.

For future reference, the issue template you cleared to file this issue also says this:
> Feature requests for future versions of ECMAScript should not be made in this
repository. Instead, they are developed in separate GitHub repositories, which
are then merged into the main repository once they have received "Stage 4".
>
> Please see [CONTRIBUTING.md](/CONTRIBUTING.md) for more details.
