### ISSUE TITLE
Changes to BlockDeclarationInstantiation annex B.3.2.6

### ISSUE THREAD

**Issue by dSalieri** [tc39/ecma262#2636]
As I know [annex B.3.2.6](https://tc39.es/ecma262/#sec-web-compat-blockdeclarationinstantiation) serves for the web implementation of ECMAScript language. But I noticed that previous versions of ECMAScript either have annex or have incomplete annex or have not it at all.

Take a look on three versions of ECMAScript specs.
- [ECMAScript 7](https://262.ecma-international.org/7.0/#sec-block-level-function-declarations-web-legacy-compatibility-semantics): there is no clause of BlockDeclarationInstantiation
- [ECMAScript 8](https://262.ecma-international.org/8.0/#sec-block-level-function-declarations-web-legacy-compatibility-semantics): there is [clause](https://262.ecma-international.org/8.0/#sec-web-compat-blockdeclarationinstantiation) of BlockDeclarationInstantiation but incomplete (in comparison with current ECMAScript)
- [ECMAScript 9](https://262.ecma-international.org/9.0/#sec-block-level-function-declarations-web-legacy-compatibility-semantics): there is [clause](https://262.ecma-international.org/9.0/#sec-web-compat-blockdeclarationinstantiation) of BlockDeclarationInstantiation, it almost looks like current ECMAScript

My question is the following: Why do we have so differences for BlockDeclarationInstantiation compability among versions? Shouldn't compatibility be the same?

**Comment by bakkot** [comment]
> Why do we have so differences for BlockDeclarationInstantiation compability among versions?

The answer to this question is that block-level function declarations were added to different browsers with different semantics in the pre-ES6 days, and in ES6 and later additions we attempted to specify semantics which were shared by all browsers, but we've found places that ES6 failed to capture some part of the semantics shared by browsers and relied upon by web pages. That has of course required revisions in later additions, for example in https://github.com/tc39/ecma262/pull/453.

If you want to know details about when a particular part of the spec was introduced, for anything subsequent to ES6, you can use `git blame` or [searchfox](https://searchfox.org/ecma262/source/spec.html).

**Comment by dSalieri** [comment]
@bakkot thanks for the clarification, that was really interesting to know.
