### ISSUE TITLE
Number::lessThan returns values false instead of undefined when x or y is NaN

### ISSUE THREAD

**Issue by jacty** [tc39/ecma262#2643]
https://tc39.es/ecma262/#sec-numeric-types-number-lessThan

Hi, I checked in Node.js and Chrome, it seems when either x or y is `NaN`,  Number::lessThan returns false instead of `undefined`. I wonder if it is an `implementation-defined` feature since it is not noted in this section?

**Comment by ljharb** [comment]
This is an abstract operation that isn’t directly exposed to JavaScript, so I’m not sure what you “checked”. It’s called by IsLessThan, which is called by https://tc39.es/ecma262/#sec-evaluatestringornumericbinaryexpression via https://tc39.es/ecma262/#sec-applystringornumericbinaryoperator and https://tc39.es/ecma262/#sec-relational-operators-runtime-semantics-evaluation, which always produces false when the AO returns undefined.

**Comment by jacty** [comment]
> This is an abstract operation that isn’t directly exposed to JavaScript, so I’m not sure what you “checked”. It’s called by IsLessThan, which is called by https://tc39.es/ecma262/#sec-evaluatestringornumericbinaryexpression via https://tc39.es/ecma262/#sec-applystringornumericbinaryoperator and https://tc39.es/ecma262/#sec-relational-operators-runtime-semantics-evaluation, which always produces false when the AO returns undefined.

Ah, sorry, I thought in JS 'x < y' is equal to that AO directly since other AOs are kind of equivalent coincidently.

**Comment by ljharb** [comment]
Very, very few AOs are directly called with no other steps prior to invoking them.

**Comment by rotu** [comment]
I was confused by this too. In particular the ["Example source" column](https://tc39.es/ecma262/#table-numeric-type-ops) seems like this is the direct syntactic equivalent of the operation, given suitable operands.
