### ISSUE TITLE
Is `null[{ toString: () => { console.log('hit') } }]` supposed to hit the `console.log`?

### ISSUE THREAD

**Issue by bakkot** [tc39/ecma262#2659]
https://github.com/tc39/ecma262/pull/2267 changed the sequencing of the `RequireObjectCoercible`-on-base / `ToString`-on-property for member assignments, like `a[b] = c`.

As I read the spec, it also changed the semantics for `null[{ toString: () => { console.log('hit') } }]`, which by my reading is now supposed to print `hit` before throwing:
- the `RequireObjectCoercible` happens only during the `GetValue` call happens in [the Evaluation semantics for ExpressionStatement](https://tc39.es/ecma262/multipage/ecmascript-language-statements-and-declarations.html#sec-expression-statement-runtime-semantics-evaluation),
- which is after the `ToString` has already happened,
  - within the [`ToPropertyKey`](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-topropertykey) call
  - in step 2 of [`EvaluatePropertyAccessWithExpressionKey`](https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#sec-evaluate-property-access-with-expression-key)
  - which is called in step 4 of [the Evaluation semantics for  `MemberExpression : MemberExpression [ Expression ]`](https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#sec-property-accessors-runtime-semantics-evaluation).

Of engines I have on hand, only ChakraCore implements this behavior.

cc @codehag

**Comment by h2oche** [comment]
We can also observe this behavior with our implementation [ESMeta](https://github.com/es-meta/esmeta), which strictly follows the spec. Currently, spec and tests are diverged.

**Comment by jedel1043** [comment]
Opened a couple of PRs on the test262 repo that fixes the corresponding tests on either case: preserve the new semantics or rollback to the old behaviour. PRs will be waiting for consensus on this.

Hopefully this reactivates the discussion about the issue!

**Comment by ptomato** [comment]
Is this actually the same issue as #3295?

**Comment by bakkot** [comment]
Related, but not identical - that issue is much older than this one, which was only introduced in https://github.com/tc39/ecma262/pull/2267 (I think).

That said, I think [the same PR](https://github.com/tc39/ecma262/pull/3307) might fix this as well. I'll have to walk through it carefully to confirm.

**Comment by bakkot** [comment]
Fixed by https://github.com/tc39/ecma262/pull/3307.
