### ISSUE TITLE
B.3.2.1 - Which `FunctionDeclaration` parse nodes list does it iterate?

### ISSUE THREAD

**Issue by nicolo-ribaudo** [tc39/ecma262#2663]
**Description**:

We are trying to fix the handling of function declarations in blocks in Babel (https://github.com/babel/babel/pull/14203), and I don't understand what the spec does.

At step 29.a of [B.3.2.1](https://tc39.es/ecma262/#sec-web-compat-functiondeclarationinstantiation), it says:
```
a. For each FunctionDeclaration f that is directly contained in the StatementList of a Block, CaseClause, or DefaultClause, do
```

However, usually "For each" iterates the elements of a list. Is it iterating over the functions (deeply) contained within the function that is currently being instantiated? Or is it something like _"If the current `FunctionDeclarationInstantiation` call has been caused by evaluating a `FunctionDeclaration` parse node, let `f` be that parse node"_?

**Comment by jmdyck** [comment]
I agree that it's odd: the criterion "each FunctionDeclarationthat is directly contained in the StatementList of a Block, CaseClause, or DefaultClause"  makes it sound like we need to look at *any* Block, CaseClause, or DefaultClause, anywhere in the Script.

In ES6, that step is:
> For each _FunctionDeclaration_ f **in _varDeclarations_** that is directly contained in the _StatementList_ of a _Block_, _CaseClause_, or _DefaultClause_,

(emphasis mine), which makes it clear you don't have to go looking everywhere. But the phrase "in _varDeclarations_" was removed in efbfc88a to resolve https://tc39.es/archives/bugzilla/4427/, which links back to [an issue](https://esdiscuss.org/topic/block-level-function-declarations-web-legacy-compatibility-bug) that @bakkot raised in 2015.

However, it looks like the change that @allenwb suggested in 4427 wasn't applied correctly: in addition to dropping "in _varDeclarations_", he also appended "Contained within _code_" (where _code_ is the FunctionBody of the function that FunctionDeclarationInstantiation is being called on), but that wasn't added.

**Comment by nicolo-ribaudo** [comment]
That might still be somewhat problematic because when instantiating `f` in
```js
function f() {
  function g() {
    { function h() {} }
  }
}
```
we don't want to look at `h`.

**Comment by jmdyck** [comment]
In the phrase "Contained within _code_", I suspect the capital 'C' alludes to the 'Contains' SDO, which avoids looking inside nested functionDecls.

(To make it a proper invocation of 'Contains', I think it would need to be something like "... any _Block_, _CaseClause_, or _DefaultClause_ _x_ such that _code_ Contains _x_".)

**Comment by bathos** [comment]
I read "directly" as specifying that h (indirectly contained) is not considered.

**Comment by nicolo-ribaudo** [comment]
@bathos In my example the function _is_ directly contained in a block. I'll open a PR with "Contains".

**Comment by bathos** [comment]
Ah, got it — “directly contained” only describes the declaration relative to the block, not the block relative to the “root” statement list.
