### ISSUE TITLE
InstantiateFunctionObject (etc) annotated with [UC] (user code)?

### ISSUE THREAD

**Issue by bathos** [tc39/ecma262#2668]
[InstantiateFunctionObject](https://tc39.es/ecma262/#sec-runtime-semantics-instantiatefunctionobject) is annotated with the [UC]/user code marker seemingly due to:

- [InstantiateGeneratorFunctionObject](https://tc39.es/ecma262/#sec-runtime-semantics-instantiategeneratorfunctionobject) and
- [InstantiateAsyncGeneratorFunctionObject](https://tc39.es/ecma262/#sec-runtime-semantics-instantiateasyncgeneratorfunctionobject)

Which in turn stem from `DefinePropertyOrThrow(F, "prototype", ...)` steps in both. As far as I can tell, these are mistaken annotations and these ops are guaranteed to succeed. The [UC]s “born” here propagate into a number of other places, too, like [InitializeEnvironment](https://tc39.es/ecma262/#sec-source-text-module-record-initialize-environment) which (definitionally?) could never run user code, right?

For InstantiateAsyncGeneratorFunctionObject, however, I notice the annotation only appears in the case that the declaration is a no-identifier default export production, not an ordinary declaration, which seemed kinda random until I noticed the ordinary declaration had an explicit `!` while the default-export case didn’t. I think that’s probably the common theme (missing `!`s), though I’m not sure exactly how the [UC] annotations work yet and may be misunderstanding something.

I didn’t see any mention of these productions in #2548 and am unsure if they were already present when that was merged.

**Comment by bakkot** [comment]
This is a consequence of missing a `!` in the `Perform DefinePropertyOrThrow(...)` steps within those algorithms (which I mentioned in https://github.com/tc39/ecma262/pull/2548#issuecomment-989499264), and will be fixed by https://github.com/tc39/ecma262/pull/2547.

**Comment by bathos** [comment]
Ah, cool, I’ll close it given it’s covered elsewhere.
