### ISSUE TITLE
editorial issue causing ambiguity in typeof support for [[IsHTMLDDA]]

### ISSUE THREAD

**Issue by michaelficarra** [tc39/ecma262#2685]
Section [B.3.6.3 Changes to the typeof Operator](https://tc39.es/ecma262/#sec-IsHTMLDDA-internal-slot-typeof) adds an entry to [Table 41](https://tc39.es/ecma262/#table-typeof-operator-results) which causes the left column to be ambiguous for some objects. Every language value should fall into exactly one row of that table. Instead of modifying the table to add the row, we should modify the algorithm, adding a step that early exits for objects with an `[[IsHTMLDDA]]` slot.

**Comment by bakkot** [comment]
Or we could say that you pick the first row which matches, I guess.

**Comment by michaelficarra** [comment]
Then we'd have to insert it even earlier as well. I'd rather have the table be [MECE](https://en.wikipedia.org/wiki/MECE_principle) if possible.
