### ISSUE TITLE
Are ES6 modules in browsers going to get loaded level-by-level?

### ISSUE THREAD

**Issue by Wizek** [tc39/ecma262#27]
*Not sure if this is a good place to ask this question. If not, I'm sorry for the noise. Could you then point me elsewhere perhaps?*

I've just read this post here: http://www.2ality.com/2014/09/es6-modules-final.html
Which claims that the module system will support both sync and async loading. Which I like. But it made me wonder if/how well async loading would work for deeper dependency trees. E.g. if I had a project with 20 level deep dependency tree (at its deepest point) and my server would take on average 200ms to respond, then it would take about 4000ms minimum to execute any/all of my scripts, right? Or is there something I am missing?

If I interpret the situation correctly, what is the conceptual response to this scenario? Try to limit the tree depth? Concat everything just like it happens often with ES5? Something else?

**Comment by fkling** [comment]
https://esdiscuss.org/ might be a better place to ask this.

**Comment by domenic** [comment]
Yep, best on the mailing list :)
