### ISSUE TITLE
AsyncFunction.prototype is undefined.

### ISSUE THREAD

**Issue by jacty** [tc39/ecma262#2706]
Hi, all. 
Just found something quite confusing. 
<img width="800" alt="image" src="https://user-images.githubusercontent.com/4190959/159586515-0f3a5021-0a36-4560-b9c3-fe3a88f22e0a.png">

In the section showed above, it says async functions have an initial value for their property `prototype`  which is not undefined , however when I tried to access the initial value immediately after creating an async function, it is undefined. I am not sure if this is a future feature or something else and should we have a Note or Warning there to explain if fits?
Thanks for explaining.

**Comment by bakkot** [comment]
> it says async functions have an initial value for their property `prototype` which is not undefined

No, that's not what it says. It's talking about the builtin `AsyncFunction` object, which you can access with e.g. `(async function(){}).constructor`. That function does indeed have a `prototype` property.

**Comment by jacty** [comment]
> > it says async functions have an initial value for their property `prototype` which is not undefined
> 
> No, that's not what it says. It's talking about the builtin `AsyncFunction` object, which you can access with e.g. `(async function(){}).constructor`. That function does indeed have a `prototype` property.

Thanks for helping. May I ask how could I know if it is about `AsyncFunction` or `builtin AsyncFunction` in the spec please? I feel quite confusing when the names are more or less the same and after checked the definition under the title, I feel it is also about `AsyncFunction` (non-builtin).
<img width="789" alt="image" src="https://user-images.githubusercontent.com/4190959/159588198-244c209c-e47a-4e74-95b5-a5d89d7f42d7.png">

**Comment by bakkot** [comment]
"AsyncFunction" is the constructor. To talk about instances of the constructor, we would say "AsyncFunctions", "an AsyncFunction", "an AsyncFunction object", etc.

This is similar to how there is "[Array](https://tc39.es/ecma262/multipage/indexed-collections.html#sec-array-constructor)", which is the Array constructor, as well as "Arrays", which are instances of the Array constructor.

**Comment by jacty** [comment]
> "AsyncFunction" is the constructor. To talk about instances of the constructor (i.e., stuff like `(async function(){})`), we would say "AsyncFunctions", "an AsyncFunction", "an AsyncFunction object", etc.
> 
> This is similar to how there is "[Array](https://tc39.es/ecma262/multipage/indexed-collections.html#sec-array-constructor)", which is the Array constructor, as well as "Arrays", which are instances of the Array constructor.

Okay, I will pay more attention to the words next time though still feel a little bit confusing for me. Thanks.

**Comment by bakkot** [comment]
I sincerely apologize on behalf of the English language.

When reading the specification, another thing you can check for is the font. Except in headers, when referring to the AsyncFunction constructor the word "AsyncFunction" will generally be written in monospace or wrapped in `%`. (This convention is followed throughout the specification.)
