### ISSUE TITLE
How does super work as an object？

### ISSUE THREAD

**Issue by fltenwall** [tc39/ecma262#2725]
```javascript
class A {
  constructor() {
    this.x = 1;
  }
}

A.prototype.x = 5;

class B extends A {
  constructor() {
    super();
    this.x = 2;
    // Super refers to this when it is assigned
    super.x = 3;
   // When set, super refers to the prototype of the parent class
    console.log(super.x); // 5
    console.log(this.x); // 3
  }
}

let b = new B();
```

Super refers to different values in the same method, which I think is unreasonable and very confusing. I don't think this should be explained as a feature, it should be a bug that needs to be fixed.

**Comment by ljharb** [comment]
This isn't the place to discuss it; please see https://es.discourse.group.

Either way, if it's behavior the web depends on (which is usually the case) then it can never be "fixed" or changed, because it would break code.
