### ISSUE TITLE
Get rid of the notion of builtins "implemented as an ECMAScript function"

### ISSUE THREAD

**Issue by bakkot** [tc39/ecma262#2734]
E.g. in [Built-in Function Objects](https://tc39.es/ecma262/multipage/ordinary-and-exotic-objects-behaviours.html#sec-built-in-function-objects) we say

> If a built-in function object is not implemented as an ECMAScript function it must provide [[Call]] and [[Construct]] internal methods that conform to the following definitions:

This is silly. We should stop talking about built-ins being implemented as ECMAScript function objects, except possibly to briefly note that this option is available to an implementation as long as its observable behavior is as specified.

**Comment by linusg** [comment]
I think this is resolved by https://github.com/tc39/ecma262/pull/3145?

**Comment by jmdyck** [comment]
Yup.
