### ISSUE TITLE
Repository releases links incorrect for ES2019, ES2018, and ES2017

### ISSUE THREAD

**Issue by senocular** [tc39/ecma262#2743]
* [Release ES2019](https://github.com/tc39/ecma262/releases/tag/es2019)
  * Currently links to: https://262.ecma-international.org/9.0/
  * Should link to: https://262.ecma-international.org/10.0/
* [Release ES2018](https://github.com/tc39/ecma262/releases/tag/es2018)
  * Currently links to: https://262.ecma-international.org/8.0/
  * Should link to: https://262.ecma-international.org/9.0/
* [Release ES2017](https://github.com/tc39/ecma262/releases/tag/es2017)
  * Currently links to: https://262.ecma-international.org/7.0/
  * Should link to: https://262.ecma-international.org/8.0/

Asset PDFs are correct. Only the links in the release descriptions are incorrect (off by 1). Release links beyond 2019 are accurate.

**Comment by ljharb** [comment]
Thanks, fixed.
