### ISSUE TITLE
Invalid assumption in ValidateAndApplyPropertyDescriptor

### ISSUE THREAD

**Issue by linusg** [tc39/ecma262#2761]
Assuming `ValidateAndApplyPropertyDescriptor` is called with the following property descriptors for `Desc` and `current`:

```
Desc = { [[Configurable]]: false }
current = { [[Get]]: <some function>, [[Set]]: undefined, [[Enumerable]]: true, [[Configurable]]: false }
```

as it would happen in the second `freeze` call in this piece of code:

```js
Object.freeze(Object.freeze({ get foo() {} }));
```

It'll then perform the following steps:

```
   [...]
✅ 5. If current.[[Configurable]] is false, then
❌    a. If Desc has a [[Configurable]] field and Desc.[[Configurable]] is true, return false.
❌    b. If Desc has an [[Enumerable]] field and SameValue(Desc.[[Enumerable]], current.[[Enumerable]]) is false, return false.
❌    c. If IsGenericDescriptor(Desc) is false and SameValue(IsAccessorDescriptor(Desc), IsAccessorDescriptor(current)) is false, return false.
❌    d. If IsAccessorDescriptor(Desc) is true, then
         [...]
💥    e. Else if current.[[Writable]] is false, then
```

- `Desc` neither has `[[Configurable]]` set to true, nor has it an `[[Enumerable]]` field (steps a and b)
- `SameValue(IsAccessorDescriptor(Desc), IsAccessorDescriptor(current))` is false but `IsGenericDescriptor(Desc)` is true (step c)
- `IsAccessorDescriptor(Desc)` is false (step d)
- Step e is reached without ever confirming that `current` is a data property descriptor, and accessing the `[[Writable]]` field is invalid

This is likely a regression in https://github.com/tc39/ecma262/commit/b9efa97, it worked with the old algorithm steps. (cc @gibson042)

**Comment by gibson042** [comment]
Nice catch @linusg, would you like to submit the fix?
```patch
           1. If _current_.[[Configurable]] is *false*, then
             1. If _Desc_ has a [[Configurable]] field and _Desc_.[[Configurable]] is *true*, return *false*.
             1. If _Desc_ has an [[Enumerable]] field and SameValue(_Desc_.[[Enumerable]], _current_.[[Enumerable]]) is *false*, return *false*.
             1. If IsGenericDescriptor(_Desc_) is *false* and SameValue(IsAccessorDescriptor(_Desc_), IsAccessorDescriptor(_current_)) is *false*, return *false*.
-            1. If IsAccessorDescriptor(_Desc_) is *true*, then
+            1. If IsAccessorDescriptor(_current_) is *true*, then
               1. If _Desc_ has a [[Get]] field and SameValue(_Desc_.[[Get]], _current_.[[Get]]) is *false*, return *false*.
               1. If _Desc_ has a [[Set]] field and SameValue(_Desc_.[[Set]], _current_.[[Set]]) is *false*, return *false*.
             1. Else if _current_.[[Writable]] is *false*, then
               1. If _Desc_ has a [[Writable]] field and _Desc_.[[Writable]] is *true*, return *false*.
               1. If _Desc_ has a [[Value]] field and SameValue(_Desc_.[[Value]], _current_.[[Value]]) is *false*, return *false*.
```

**Comment by ljharb** [comment]
I'm having trouble coming up with a test case for es-abstract's upcoming ES2022 implementation that would fail this.

The example Desc/current arguments don't seem to trigger a bug, because all four of those "early return false" conditions is `false` in this case.

**Comment by IdanHo** [comment]
> because all four of those "early return false" conditions is false in this case.

Right, and since they're false we reach the 5th condition, which accesses `[[Writable]]` unconditionally, without checking if it exists.

**Comment by linusg** [comment]
> The example Desc/current arguments don't seem to trigger a bug, because all four of those "early return false" conditions is false in this case.

The bug is that *after* those four early returns that aren't triggered, in the fifth step `current.[[Writable]]` is accessed unconditionally, even though it might be an accessor descriptor that does not have a `[[Writable]]` field. Depending on the language an actual engine uses to implement these steps, this might not be observable; e.g. in es-abstract something like `current['[[Writable]]'] === false` would work without triggering a bug - it's an editorial error regardless, and might not be implementable as is in a statically typed language.

With the proposed fix, that branch is only reached with a data descriptor.

**Comment by ljharb** [comment]
Gotcha, that's the issue then, thanks - indeed in es-abstract if it doesn't exist it'll be undefined, and thus falsy.

In other words, this is purely an editorial error. Thanks!
