### ISSUE TITLE
HTML comment grammar got lost

### ISSUE THREAD

**Issue by domenic** [tc39/ecma262#277]
Compare http://www.ecma-international.org/ecma-262/6.0/#sec-html-like-comments with https://tc39.github.io/ecma262/#sec-html-like-comments. A bunch of stuff is missing from the latter.

**Comment by jmdyck** [comment]
Looks like something in the ecmarkup processor is interpreting the HTML-like comment delimiter terminals as actual comment delimiters.

**Comment by claudepache** [comment]
Maybe related: domenic/ecmarkdown#46

**Comment by bterlson** [comment]
Fixed this in Emu 2.8.6. Will be fixed once I publish the next draft!

**Comment by bterlson** [comment]
This has been fixed.
