### ISSUE TITLE
IsValidRegularExpressionLiteral does not allow 'd' flag

### ISSUE THREAD

**Issue by mroch** [tc39/ecma262#2778]
[IsValidRegularExpressionLiteral](https://tc39.es/ecma262/#sec-isvalidregularexpressionliteral) says:

> 1. If [FlagText](https://tc39.es/ecma262/#sec-static-semantics-flagtext) of literal contains any code points other than g, i, m, s, u, or y, or if it contains the same code point more than once, return false.

I think this should allow `d`

**Comment by ljharb** [comment]
cc @rbuckton

**Comment by rbuckton** [comment]
This is definitely an oversight. It should have been listed.

**Comment by rbuckton** [comment]
@ljharb I drafted a PR for this change. Should I add this as a Needs Consensus PR to the June agenda?

**Comment by ljharb** [comment]
Since it’s clearly an oversight and already has consensus, i suspect it can be landed without waiting for plenary.

**Comment by bakkot** [comment]
Yeah, editors have taken the position that "bugfix" PRs, where the intent from plenary was clear and matches implementations but the spec does not reflect that because of an oversight, can be landed without re-establishing consensus.
