### ISSUE TITLE
as keyword

### ISSUE THREAD

**Issue by aliibrahim123** [tc39/ecma262#2792]
convert any type to a specific type.
example:
```
function example(a as Number) {
    return a+a
}

example('10')      //20
```

**Comment by Jack-Works** [comment]
The ecma262 issue tracker is not the appropriate place for this discussion. See [CONTRIBUTING.md](https://github.com/tc39/ecma262/blob/main/CONTRIBUTING.md) for the best ways to contribute. This particular topic seems to belong on the [TC39 Discourse](https://es.discourse.group/).

And you might want to know about <https://github.com/tc39/proposal-type-annotations>
