### ISSUE TITLE
use consistent phrasing for comparing string values

### ISSUE THREAD

**Issue by michaelficarra** [tc39/ecma262#2794]
@gibson042 asks what our conventions should be for comparing strings in https://github.com/tc39/ecma262/pull/2721/files/#r890585298.

I think "equals" is indeed bad, but we have many options available:

* `SameValue`
* "is the same string value"
* "is the same sequence of code units"
* `SameValueNonNumeric`
* "is"

Let's pick something and make it consistent.

**Comment by bakkot** [comment]
I like "is the same string value" personally. We could `dfn` the term if we're worried it might not be clear.

**Comment by michaelficarra** [comment]
Also, "is the empty String" should remain.

**Comment by michaelficarra** [comment]
Related: https://github.com/tc39/ecma262/issues/2405

Since strings don't carry identity, "is" should be fine. Also because of this, we can do things like `if _list_ contains _string_` instead of something weird like `if _list_ contains a string with the same string value as _string_`.

**Comment by michaelficarra** [comment]
Discussed at the editor call today. "is" or "=" would be preferable as long as we've made it clear that strings do not carry identity, so I'm going to try to fix #2405 first. We could probably then use this phrasing for all values which are declared not to have identity.
