### ISSUE TITLE
Wording about inheriting data properties is misleading

### ISSUE THREAD

**Issue by syg** [tc39/ecma262#2798]
Originally came up in https://bugs.chromium.org/p/v8/issues/detail?id=12930#c3

The wording in https://tc39.es/ecma262/#sec-ordinary-object-internal-methods-and-internal-slots is misleading in that it says

"[Data properties](https://tc39.es/ecma262/#sec-object-type) of the [[Prototype]] object are inherited (and visible as properties of the child object) for the purposes of get access, but not for set access."

This, however, can be misinterpreted to mean that one can always shadow data properties on the prototype by setting a property lower on the chain. But that's false because of the override mistake. We should reword this.

**Comment by bakkot** [comment]
Maybe 

> Data properties of the [[Prototype]] object are inherited (and visible as properties of the child object) for the purposes of get access, but assignment attempts to set properties on the child object.

**Comment by syg** [comment]
@bakkot Isn't the confusion the other way around? You'd think assignments would _always_ set properties on the child, but when the prototype data property of the same name is frozen, you can't. It'd be good to capture that weirdness.

**Comment by bakkot** [comment]
Assignment _does_ attempt to set properties of the child object, it's just that the success of the attempt is conditional on the data descriptor from the parent. But yeah, probably still needs work.
