### ISSUE TITLE
Relax HostResolveImportedModule idempotency requirement when referencingScriptOrModule is null

### ISSUE THREAD

**Issue by nicolo-ribaudo** [tc39/ecma262#2803]
_HostResolveImportedModule(...) specification in ecma262: https://tc39.es/ecma262/#sec-hostresolveimportedmodule_
_HostResolveImportedModule(...) specification in HTML: https://html.spec.whatwg.org/#hostresolveimportedmodule(referencingscriptormodule,-modulerequest)_

Consider the third implementation requirement:
> - Each time this operation is called with a specific _referencingScriptOrModule_, _specifier_ pair as arguments it must return the same [Module Record](https://tc39.es/ecma262/#sec-abstract-module-records) instance if it completes normally.

Also, remember that first parameter can be `null` when, for example, the _HostResolveImportedModule_ calls comes from a dynamic import in an inline event handler on an HTML element.

Consider this example:
```html
<!-- ./index.html -->
<script>globalThis.foo = 1;</script>
<button type="button" onclick="import('./mod.js').then(console.log)">Click me</button>
<iframe src="./iframe.html"></iframe>
```
```html
<!-- ./iframe.html -->
<script>globalThis.foo = 2;</script>
<button type="button" onclick="import('./mod.js').then(console.log)">Click me</button>
```
```js
<!-- ./iframe.html -->
console.log("Hi :) I have been executed");
export const foo = globalThis.foo;
```

If you first click on the first button and then on the second one, there are two _HostResolveImportedModule(`null`, `"./mod.js"`)_ calls: according to ecma262 they should return the same module record, thus both `console.log`s will log the same namespace object and not `{ foo: 1 }`, `{ foo: 2 }`.

However, [the HTML spec](https://html.spec.whatwg.org/#hostresolveimportedmodule(referencingscriptormodule,-modulerequest)) does not respect this requirement: if _referencingScriptOrModule_ is `null`, the module resolution depends on the "[current settings object](https://html.spec.whatwg.org/multipage/webappapis.html#current-settings-object)", which is the [[HostDefined]] slot of the current Realm.

---

I think that we can fix this in two ways:
1. Change the third `HostResolveImportedModule` constraint to something like this:
    > - Each time this operation is called with a specific _referencingScriptOrModule_, _specifier_ pair as arguments, **if _referencingScriptOrModule_ is not null** it must return the same [Module Record](https://tc39.es/ecma262/#sec-abstract-module-records) instance if it completes normally.
    
    This is the easiest fix on ecma262's side, but it allows host to make `await import("./mod.js") === await import("./mod.js")` evaluate to `false` if _referencingScriptOrModule_ is `null`.

2. Change the cache key to (_referencingScriptOrModule_, _specifier_, current Realm). I believe that if _referencingScriptOrModule_ is not `null` then _referencingScriptOrModule_.[[Realm]] is the current Realm so this would only affect the `null` case, however:
    - I'm not 100% sure that the current Realm is the same when the `import(...)` call happens and when _HostResolveImportedModule_ is executed.
    - The ShadowRealm proposal might affect this (related: https://github.com/tc39/proposal-shadowrealm/issues/363)

**Comment by codehag** [comment]
I don't see a disagreement between the HTML spec and ECMA262 spec. The third bullet only applies when in the case that there _is_ a referencingScriptOrModule. That bullet point again:

> Each time this operation is **called with a specific referencingScriptOrModule**, specifier pair as arguments it must return the same [Module Record](https://tc39.es/ecma262/#sec-abstract-module-records) instance if it completes normally.

There was no guarantee of idempotency _when there isn't a referencing script_ even in the ecma script spec. This is part of why I find the reasoning behind shadowrealms not passing a referencing script a bit odd -- we aren't getting the behavior promised. 

However, if the goal is idempotency for shadow realms case, I think we can do something. Maybe we don't want to make use of the dynamic import hook?

**Comment by nicolo-ribaudo** [comment]
I read that swntencewoth a different connotation:
> Each time this operation is called with a specific **referencingScriptOrModule, specifier pair**

> However, if the goal is idempotency for shadow realms case, I think we can do something. 

Actually, I started writing this issue _before_ knowing about the shadowrealm problem. I was reviewing the spec of the Module Blocks proposal and realized that importing them does not need to go through host hooks as much as importing an external file, and so I was looking at explicitly specifying how they are cached.

If there is no referencing script or module, then the pair is `(null, "./dep.js")`.

**Comment by codehag** [comment]
Right, I am not sure that null is a "specific" referencingScriptOrModule as it explicitly is not specifying one. That said, I think this is worth a clarification! I wasn't aware of the Module Blocks case.
