### ISSUE TITLE
Commas are accidentally added

### ISSUE THREAD

**Issue by mathiasbynens** [tc39/ecma262#283]
Compare https://tc39.github.io/ecma262/#prod-LeadSurrogate with the same section in http://ecma-international.org/ecma-262/6.0/#sec-patterns.

E.g. `[match, only, if, the, SV, Hex4Digits, is, in, the, inclusive, range, xD800, to, xDBFF]` should be `[match only if the SV Hex4Digits is in the inclusive range xD800 to xDBFF]`.

**Comment by bterlson** [comment]
Yeah, the match only if and but only if annotations are not working. Looks like we need support in @rbuckton's grammarkdown. If it's something we can fix soon I'll wait, otherwise I'll rewrite these productions in emu.

**Comment by bterlson** [comment]
Fixed in 7ba2fec.
