### ISSUE TITLE
Accessing an uninitialized "let" variable outside the scope should throw an ReferenceError.

### ISSUE THREAD

**Issue by thailonlucas** [tc39/ecma262#2831]
**Description:** Accessing an uninitialized "let" variable outside the scope should throw an ReferenceError.

I tested with a normal and an arrow function, both allowed me to change the value of a variable before the declaration, on the "parent" scope, just like a "var" hoisting.

```
a = 'bar';
function setOutOfScope() {
    if(true){
        let a = 'foo'
    };
};
setOutOfScope();
console.log(a); // bar
```

**eshost Output:**

```
$  eshost -s -x "a = 'bar';function setOutOfScope() {if(true){let a = 'foo'};};setOutOfScope();console.log(a);"
#### ChakraCore, SpiderMonkey, V8, Hermes
bar
```

I'm saying this because if I try to access this variable on the same scope, before the declaration, this is the error it throws.

```
function setOutOfScope() {
    if(true){
        a = 'bar';
        let a = 'foo'
    };
};
setOutOfScope();
```

```
$ eshost -s -x "function setOutOfScope() {if(true){a = 'bar';let a = 'foo'};};setOutOfScope();"
#### ChakraCore

ReferenceError: Use before declaration

#### SpiderMonkey

ReferenceError: can't access lexical declaration 'a' before initialization

#### V8

ReferenceError: Cannot access 'a' before initialization
```

The current behavior also allows functions to change the value of another function's variable.

```
function scopeA() {
    if(true){
        let a = 'foo'
    };
};

function scopeB() {
    a = 'bar';
    console.log(a) // bar
};

scopeA();
scopeB();
```

```
$ eshost -s -x "function scopeA() {if(true){let a = 'foo'};};function scopeB() {a = 'bar';console.log(a)};scopeA();scopeB();"
#### ChakraCore, SpiderMonkey, V8, Hermes
bar
```

**Comment by ljharb** [comment]
The `a = 'bar';` creates a global variable.

Additionally, `let` declarations are hoisted to the top of the block (their initialization is not hoisted), to create the TDZ that throws that error.

**Comment by bergus** [comment]
Notice your code already does throw an error in strict mode.
The implicit creation of global variables through assignment of undeclared variables is an unfortunate behaviour that needs to be kept for backwards-compatibility.
