### ISSUE TITLE
How “implementation-defined” is %Number.prototype.toString% meant to be?

### ISSUE THREAD

**Issue by bathos** [tc39/ecma262#2847]
The final step given for [Number.prototype.toString](https://tc39.es/ecma262/#sec-number.prototype.tostring) says:

> 6. Return the String representation of this [Number value](https://tc39.es/ecma262/#number-value) using the radix specified by radixMV. Letters a-z are used for digits with values 10 through 35. The precise algorithm is [implementation-defined](https://tc39.es/ecma262/#implementation-defined), however the algorithm should be a generalization of that specified in [6.1.6.1.20](https://tc39.es/ecma262/#sec-numeric-types-number-tostring).

The “generalization of...” bit is only qualified with “should” (and I’m not certain how much “generalization of” conveys anyway). It surprised me to learn that this has been left pretty open-ended mainly because I wasn’t aware of engine differences that might have motivated it. BigInt inherited the same pattern.

Could/should the exact behavior be specified? If not, what prevented it?

**Comment by bathos** [comment]
Found a test in [test262](https://github.com/tc39/test262/pull/2613) related to this. The link in that PR goes to the Twitter thread where an implementor expressed uncertainty about the conformance requirements. The test appears more specific than the spec and seems to [pass everywhere](https://test262.report/browse/built-ins/Number/prototype/toString/a-z.js).

**Comment by michaelficarra** [comment]
Agreed, we should clarify this. In my opinion, the original author of this text was just trying to emphasize the implementation freedom around unobservable aspects of the algorithm (available everywhere), and this was not an allowance for implementation-defined *results*. I think we should remove the use of the term "implementation-defined" here, as, though it is not technically incorrect, it can easily be confusing.

We'll also need to clarify the casing requirements and the specifics of representing the number in a non-decimal base. It's easy enough to just describe an algorithm here, it's just repeated divmod.

Will discuss at editor call.

**Comment by gibson042** [comment]
My reading is that the implementation-defined aspects are shared with [Number::toString](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-numeric-types-number-tostring) step 5:

> Otherwise, let <var>n</var>, <var>k</var>, and <var>s</var> be integers such that <var>k</var> ≥ 1, 10<sup><var>k</var> - 1</sup> ≤ <var>s</var> &lt; 10<sup><var>k</var></sup>, 𝔽(<var>s</var> × 10<sup><var>n</var> - <var>k</var></sup>) is <var>x</var>, and <var>k</var> is as small as possible. Note that <var>k</var> is the number of digits in the decimal representation of <var>s</var>, that <var>s</var> is not divisible by 10, and that **the least significant digit of <var>s</var> is not necessarily uniquely determined by these criteria**.

**Comment by claudepache** [comment]
Note that an (unspecified) difference between base 10 and other bases, is that only the former makes use of the scientific notation (`1.2e+34`).

**Comment by michaelficarra** [comment]
We will solve this by adding a `radix` parameter to `Number::toString`.

**Comment by bathos** [comment]
Title update is to focus this issue on the Number case only, making it align with the work in the related PR, and a [new issue](https://github.com/tc39/ecma262/issues/2860) captures the BigInt part.
