### ISSUE TITLE
Clarification: Maximum size of an array

### ISSUE THREAD

**Issue by nzakas** [tc39/ecma262#286]
Something I noticed while reading through the spec: it appears that the maximum size of an array can now be 2^53-1 based on [ToLength](http://www.ecma-international.org/ecma-262/6.0/#sec-tolength), which is used in several places (for example, [Array.prototype.concat](http://www.ecma-international.org/ecma-262/6.0/#sec-array.prototype.concat)).

However, it looks like the [`Array` constructor ](http://www.ecma-international.org/ecma-262/6.0/#sec-array-len) still limits the length to 2^32-1.

I'm curious if this difference is intentional?

**Comment by nzakas** [comment]
(I'm guessing this is some back compat issue, just wanted to double-check.)

**Comment by allenwb** [comment]
Yes, it's intentional.  The Array.prototype methods were generally re-specified to work with collections up to ToLength size (for example, TypedArrays can in theory be that big).  But for back compact reasons Array instances are restricted to a length of 2^32-1 with Uint32 index warping.

**Comment by nzakas** [comment]
Cool, thanks!
