### ISSUE TITLE
Does ECMAScript realize [[PrimaryInterface]] and when does it do?

### ISSUE THREAD

**Issue by dSalieri** [tc39/ecma262#2873]
I came across onto `[[PrimaryInterface]]` in whatwg spec [here](https://webidl.spec.whatwg.org/#es-platform-objects), there was written following:
> An ECMAScript value value is a platform object if [Type](https://tc39.es/ecma262/#sec-ecmascript-data-types-and-values)(value) is Object and if value has a [[PrimaryInterface]] internal slot.
An ECMAScript value value implements an [interface](https://webidl.spec.whatwg.org/#dfn-interface) interface if value [is a platform object](https://webidl.spec.whatwg.org/#is-a-platform-object) and the [inclusive inherited interfaces](https://webidl.spec.whatwg.org/#interface-inclusive-inherited-interfaces) of value.[[PrimaryInterface]] [contains](https://infra.spec.whatwg.org/#list-contain) interface.

So if ECMAScript implements `[[PrimaryInterface]]` for some objects, they will be the platform objects. But I haven't seen that slot in ECMAScript. What kind of sense of this checking and when do ECMAScript objects implement the `[[PrimaryInterface]]`?

**Comment by bakkot** [comment]
`[[PrimaryInterface]]` is a slot added by the web platform to certain objects it creates, not the ES spec. Specifically it's added in [webidl](https://webidl.spec.whatwg.org/#internally-create-a-new-object-implementing-the-interface).

**Comment by dSalieri** [comment]
@bakkot so, are instances of Promises, String, etc not the platform objects, right?

**Comment by bakkot** [comment]
Correct.
