### ISSUE TITLE
TypedArraySpeciesCreate not rendering as a byperlink in algorithms

### ISSUE THREAD

**Issue by allenwb** [tc39/ecma262#288]
For example, see http://tc39.github.io/ecma262/#sec-%typedarray%.prototype.map step 6.

**Comment by anba** [comment]
Fixed in 788a2eb4c5419e116b17a4cdc8b2f345e0578261 (added missing aoids for TypedArrayCreate and TypedArraySpeciesCreate).

**Comment by bterlson** [comment]
Thanks Allen! Please keep a close eye on rendering bugs, I'm trying to fix as many as possible in the next few weeks!

**Comment by littledan** [comment]
Thanks for fixing my buggy ecmarkup!
