### ISSUE TITLE
consistently use either "nonempty" or "non-empty" spelling

### ISSUE THREAD

**Issue by michaelficarra** [tc39/ecma262#2907]
We use both spellings. We should spell them all the same. I prefer reading the hyphenated one.

**Comment by michaelficarra** [comment]
We also say "not empty" in places and may want to normalise those as well.

**Comment by bakkot** [comment]
> We also say "not empty" in places and may want to normalise those as well.

I'd prefer to stick with "If X is not empty" over "If X is non-empty", if those are the places you're thinking of.

**Comment by michaelficarra** [comment]
Yeah I kinda feel "not empty" is an ephemeral state and "non-empty" is describing an invariant.
