### ISSUE TITLE
`new ArrayBuffer()` throws per spec, but not in browsers

### ISSUE THREAD

**Issue by ljharb** [tc39/ecma262#292]
Per https://github.com/Microsoft/ChakraCore/issues/105#issuecomment-172256945 - `new ArrayBuffer` should throw a `RangeError` because `SameValueZero(ToNumber(undefined), ToLength(NaN))` is `false`.

However, Safari, Firefox, Chrome, and Edge all return an ArrayBuffer with a `byteLength` of zero (same with `new ArrayBuffer(NaN)` and `new ArrayBuffer(undefined)`.

Is it possible that step 4 of https://tc39.github.io/ecma262/#sec-arraybuffer-constructor is web-incompatible, and will need to be changed?

**Comment by zloirock** [comment]
Duplicate https://github.com/tc39/ecma262/issues/265

**Comment by ljharb** [comment]
oops, thanks
