### ISSUE TITLE
Unicode code point mnemonics don't support collections of characters

### ISSUE THREAD

**Issue by gibson042** [tc39/ecma262#2927]
[Grammar Notation](https://tc39.es/ecma262/multipage/notational-conventions.html#sec-terminal-symbols) documents a convention for references to Unicode code points without a conventional printed representation: «_shown in the form "\<ABBREV>" where "ABBREV" is a mnemonic for the code point_». This singular characterization does not support the definition of \<USP> as «_Any Unicode “Space_Separator” code point_» in [White Space](https://tc39.es/ecma262/multipage/ecmascript-language-lexical-grammar.html#sec-white-space).

**Comment by michaelficarra** [comment]
See related: https://github.com/tc39/ecma262/issues/2930
