### ISSUE TITLE
why undefined is not literals? 

### ISSUE THREAD

**Issue by ChoDragon9** [tc39/ecma262#2932]
I have some question about `undefined` and `null` history.

`undefined` is defined in global object since es3.
`null` and `undefined` are similar. so, i think `undefined` can be literals.

why `undefined` is defined in global object?
why `undefined` is not defined in literals?

please let me know (_ _)

**Comment by ljharb** [comment]
This was already asked on discourse: https://es.discourse.group/t/why-undefined-is-not-literals/1489/3 and that's the only proper place to ask.

**Comment by ChoDragon9** [comment]
@ljharb thank you :)
