### ISSUE TITLE
result of "return" method in IteratorClose

### ISSUE THREAD

**Issue by GeorgNeis** [tc39/ecma262#294]
[7.4.6 IteratorClose](http://tc39.github.io/ecma262/#sec-iteratorclose) enforces that the result of the return method is an object:

> `8. If Type(innerResult.[[value]]) is not Object, throw a TypeError exception.`
> `9. Return Completion(completion).`

This seems strange as the result is not used.  What's the reason for this check?

**Comment by ljharb** [comment]
It's defined by user code, so it might return a primitive - and given that it's an iterator result, its return value must conform with the contract. See step 3 in http://tc39.github.io/ecma262/#sec-iteratornext and step 1 in http://tc39.github.io/ecma262/#sec-iteratorcomplete and http://tc39.github.io/ecma262/#sec-iteratorvalue.
