### ISSUE TITLE
Assignment operators are not atomic

### ISSUE THREAD

**Issue by jsalvata** [tc39/ecma262#2940]
**Description:**

Execution semantics for assignment operators interacts badly with asynchronous code.

Example:
```
const f = async (x) => Promise.resolve(x);
let sum = 0;
void await Promise.all([1, 2].map(async (i) => {
    sum += await f(i);
}));
sum; // 2
```
Which is a shocking result.

This seemingly equivalent code gives the result anyone would expect:
```
const f = async (x) => Promise.resolve(x);
let sum = 0;
void await Promise.all([1, 2].map(async (i) => {
    term = await f(i);
    sum += term;
}));
sum; // 3
```

**eshost Output:**

This is not an issue with the engines, but with the spec itself.

**Relevant spec and proposed solution**
*13.15.2 Runtime Semantics: Evaluation* gives the following semantics:

<img width="925" alt="image" src="https://user-images.githubusercontent.com/1059994/197235913-eb9ae50a-823b-48b3-a012-e2fa0b22c6f9.png">

Swapping steps 2 and 3 would solve this issue.

Of course this is, strictu sensu, a breaking change.
If this were done, a similar fix would be needed for each of the boolean assignment operators.

**Comment by bakkot** [comment]
There is very little chance such a change would be web-compatible, not least because it would affect the semantics of non-async, pre-ES6 code such as

```js
var obj = {
  get x() {
    console.log('get');
  },
  set x(y) {
    console.log('set');
  },
};
obj.x += console.log('RHS');
```
which prints in the order "get", "RHS", "set".

Moreover it would break left-to-right evaluation order, which is generally held to be important.

This is how `await` works in other languages, like Python:

```py
import asyncio

async def slow_three():
  await asyncio.sleep(0)
  return 3

async def main():
  global x
  x += await slow_three()
  print(x) # prints 4, not 5

x = 1
asyncio.run(main())
x = 2
```

**Comment by nicolo-ribaudo** [comment]
Also, this is exactly the behavior if you replace `sum +=` with `sum = sum +`, which is how most developers think about the `...=` operators.
