### ISSUE TITLE
Missing PrepareForTailCall in Function.prototype.apply

### ISSUE THREAD

**Issue by raulsebastianmihaila** [tc39/ecma262#295]
If Function.prototype.apply (www.ecma-international.org/ecma-262/6.0/#sec-function.prototype.apply) is called with no argArray, PrepareForTailCall is not performed, unlike in Function.prototype.call, where PrepareForTailCall is always performed.

**Comment by zloirock** [comment]
https://github.com/tc39/ecma262/pull/119
