### ISSUE TITLE
"A resolved promise may be pending, fulfilled or rejected."

### ISSUE THREAD

**Issue by amn** [tc39/ecma262#2954]
In [section 27.2 titled "Promise Objects"](https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-promise-objects), the following sentence ends the last paragraph of the section:

> A resolved promise may be pending, fulfilled or rejected.

This seems confusing to me, especially in light of the preceding clarifications in same section, like the one that mentions that "any Promise is in one of three _mutually exclusive states_ (emphasis mine): fulfilled, rejected, and pending".

Is this a linguistic kind of blunder or is the sentence quoted first above, really supposed to read like it does? In that case I, for one, can't understand what information it is attempting to convey exactly, granted I am not a native English speaker.

**Comment by nicolo-ribaudo** [comment]
The full paragraph:
> A promise is resolved if it is settled or if it has been “locked in” to match the state of another promise. Attempting to resolve or reject a resolved promise has no effect. A promise is unresolved if it is not resolved. An unresolved promise is always in the pending state. A resolved promise may be pending, fulfilled or rejected.

`Promise.resolve(1)`, `Promise.reject(1)` and `Promise.resolve(otherPromise)` all give you resolved promises:
- the first one is fulfilled, and its value is 1
- the second one is rejected, and its value is 1
- the third one is pending, and its status/value are "locked in" and guaranteed to reflect the status of `otherPromise` and its future value.

**Comment by amn** [comment]
Hi Nicolo,

I don't see how any of your clarification explains how a _resolved_ promise may be "pending", specifically, from the sentence I quoted.

The full paragraph doesn't explain or support the sentence in question -- all of the sentences are valid except the problematic last one.

Maybe we misunderstood each other? The crux of the issue I take with the last sentence in the paragraph, is in that I believe it's self-contradictory -- a _resolved_ promise cannot be any of "pending" or "rejected", although I understand it can be "fulfilled". Or I don't understand the difference between "resolved" and "fulfilled", although one'd think the former follows what `resolve` implies.

**Comment by mhofman** [comment]
Resolved means the promise (A) is locked to a provided resolution value. If that resolution value is another promise(B), it will adopt the state of that other promise(B), which may be pending, fulfilled or rejected. Only if the resolution value is not a promise, or if it's a fulfilled promise(B), will the promise(A) be fulfilled.

**Comment by amn** [comment]
Ok, I understand now what the spec was trying to specify here.

**Comment by devsnek** [comment]
There is a misconception that resolved means fulfilled, because `Promise.resolve(5)` and new `Promise((resolve) => resolve(5))` are somewhat common patterns that result in resolved and fulfilled promises. This is not the case though. Resolved promises are ones which have either been fulfilled, rejected, or set to track the state of another promise (in which case they are pending) In addition to the examples nicolo provided, I would consider these:

- `new Promise(() => {}) -> this creates and unresolved promise.
- `Promise.resolve(Promise.reject(1))` -> this creates a resolved rejected promise
-> `Promise.resolve(new Promise(() = {}))` -> this creates a resolved pending promise.

**Comment by amn** [comment]
Indeed, I can totally expect this to trip and confuse people, I have been using promises in what I have considered being fairly advanced patterns, but seeing how also I wasn't aware of the distinction made apparent here, surely means people that struggle with more basic promise-related logic, most likely aren't aware of this. Grant d, I haven't neede to ever do `Promise.resolve(another_promise)` -- I'd probably then just use the  `another_promise` expression instead.

Anyway, appreciate you fellows chipping in with elaborate and succinct commentary that settled (no pun intended) this issue for me.

**Comment by Josh-Cena** [comment]
> Granted, I haven't needed to ever do `Promise.resolve(another_promise)` -- I'd probably then just use the `another_promise` expression instead.

Consider this:

```js
function handleValue(maybePromise) {
  const realPromise = Promise.resolve(maybePromise);
  realPromise.then(console.log, console.error);
}

handleValue(1);
handleValue(new Promise((res) => setTimeout(res, 1000)));
```

`realPromise` is a _resolved_ promise, but whether it's pending, fulfilled, or rejected depends on the identity of `maybePromise`. Here's how you may get a rejected promise from `Promise.resolve()`:

```js
handleValue({
  get then() {
    throw new Error("Nope");
  },
});
```
