### ISSUE TITLE
Appendix C Strict Mode

### ISSUE THREAD

**Issue by GarrettS** [tc39/ecma262#2986]
### "C The Strict Mode of ECMAScript"

The fourth bullet point has two different points. Break that up into two bullet points and review each for clarity.

There is no need to repeatedly remind the reader that these rules apply to strict mode code. That is asinine. This section is about strict mode. Be concise, be precise, mean what you say, and convey meaning to the reader. Proofread. Use a grammar checker if necessary.

The first point has to do with ReferenceError. the second, with TypeErrors. The second point can further be broken up into sub-points.

The full bullet point in the spec is as follows:

- Assignment to an undeclared identifier or otherwise unresolvable reference does not create a property in the [global object](https://tc39.es/ecma262/#sec-global-object). When a simple assignment occurs within [strict mode code](https://tc39.es/ecma262/#sec-strict-mode-code), its [LeftHandSideExpression](https://tc39.es/ecma262/#prod-LeftHandSideExpression) must not evaluate to an unresolvable Reference. If it does a ReferenceError exception is thrown ([6.2.5.6](https://tc39.es/ecma262/#sec-putvalue)). The [LeftHandSideExpression](https://tc39.es/ecma262/#prod-LeftHandSideExpression) also may not be a reference to a [data property](https://tc39.es/ecma262/#sec-object-type) with the attribute value { [[Writable]]: false }, to an [accessor property](https://tc39.es/ecma262/#sec-object-type) with the attribute value { [[Set]]: undefined }, nor to a non-existent property of an object whose [[Extensible]] internal slot is false. In these cases a TypeError exception is thrown ([13.15](https://tc39.es/ecma262/#sec-assignment-operators)).

Break this up as such:

- Assignment to an[y] undeclared identifier or otherwise unresolvable reference does not create a property in the [global object](https://tc39.es/ecma262/#sec-global-object). Simple assignment must not evaluate to an unresolvable Reference. If it does**,** a ReferenceError exception is thrown ([6.2.5.6](https://tc39.es/ecma262/#sec-putvalue)). 
- The [LeftHandSideExpression](https://tc39.es/ecma262/#prod-LeftHandSideExpression) can be neither a reference to a [data property](https://tc39.es/ecma262/#sec-object-type) with the attribute value { [[Writable]]: false }, to an [accessor property](https://tc39.es/ecma262/#sec-object-type) with the attribute value { [[Set]]: undefined }, nor to a non-existent property of an[y] object whose [[Extensible]] internal slot is false. In these cases**,** a TypeError exception is thrown ([13.15](https://tc39.es/ecma262/#sec-assignment-operators)).

**Comment by GarrettS** [comment]
> @GarrettS a reminder that all TC39 spaces are governed by our [Code of Conduct](https://tc39.es/code-of-conduct/), and comments like "asinine" aren't appropriate.

It is imperative programming language specifications be clear, concise, precise. To do otherwise defies the definition of "specification".

The ECMAScript spec has long had the problem of being hard for developers to understand. Attitudes resistant to edification may help to explain why that is the case. 

Facts don't care about your feelings. 

I believe "Community standards" are mostly used to weaponize discussion and disparaged and deflect comments. Furthermore, I find such behavior deserving of derision and contempt.  Net nanny comments belong in the waste bin. Please see also: https://youtu.be/V4HuAW4G9Uw (For those not too easily offended.)

Also, I filed this under ECMA 262.

Thank you.

**Comment by ljharb** [comment]
@GarrettS in that case, i'll close and lock this.
