### ISSUE TITLE
Possibly-unreachable specification text

### ISSUE THREAD

**Issue by jugglinmike** [tc39/ecma262#299]
I'm having trouble verifying step 4.a.ii.1 in section 13.12.9 ("Runtime Semantics: CaseBlockEvaluation"):

>     CaseBlock : { CaseClauses }
>
>     1. Let V = undefined.
>     2. Let A be the List of CaseClause items in CaseClauses, in source text order.
>     3. Let found be false.
>     4. Repeat for each CaseClause C in A,
>        a. If found is false, then
>           i. Let clauseSelector be the result of CaseSelectorEvaluation of C.
>           ii. If clauseSelector is an abrupt completion, then
>               1. If clauseSelector.[[value]] is empty, return
>                  Completion{[[type]]: clauseSelector.[[type]], [[value]]:
>                  undefined, [[target]]: clauseSelector.[[target]]}.

source: http://www.ecma-international.org/ecma-262/6.0/#sec-runtime-semantics-caseblockevaluation

(The algorithm for blocks containing the `default` case have an equivalent step.)

Because CaseSelectorEvaluation is defined as follows:

>     CaseClause : case Expression : StatementListopt
>
>     1. Let exprRef be the result of evaluating Expression.
>     2. Return GetValue(exprRef).

...the question I'm having trouble answering is: which Expression will return an empty abrupt completion?

**Comment by anba** [comment]
These steps were initially added to support do-expressions, but currently they aren't needed (and got removed in 748ec83c5c36414b9455b87ddba3ba2eba686edc).

**Comment by jugglinmike** [comment]
@anba Thank you!

**Comment by anba** [comment]
(BTW there is a similar issue in CreatePerIterationEnvironment: ` lastIterationEnvRec.GetBindingValue` can never return an abrupt completion in ES2015/2016. The call to ReturnIfAbrupt was only added to handle this case: `for (let x = do { continue; }; ;) {}`. )
