### ISSUE TITLE
Standard proposal format?

### ISSUE THREAD

**Issue by mathiasbynens** [tc39/ecma262#3]
What should it look like?

See http://yehudakatz.com/2011/09/13/a-proposal-for-es-next-proposals/ by @wycats for some inspiration.

**Comment by rauschma** [comment]
It’d be nice if every proposal did have some kind of repository, with a structure like the one proposed by domenic. SIMD (currently stage 3) doesn’t, but seems to have the necessary material for setting one up. Its proposal URL is currently: https://docs.google.com/presentation/d/1MY9NHrHmL7ma7C8dyNXvmYNNGgVmmxXk8ZIiQtPlfH4/edit

**Comment by ljharb** [comment]
@rauschma the SIMD proposal is here: https://github.com/tc39/ecmascript_simd

**Comment by leobalter** [comment]
I believe this is already resolved.

As a bonus, it should be very fun to close the last issue with less than 3 digits here.

**Comment by michaelficarra** [comment]
Agreed, we have [tc39/template-for-proposals](https://github.com/tc39/template-for-proposals) now. :tada: We can track further improvements in that repo's issue tracker.
