### ISSUE TITLE
Array.forEach not chainable

### ISSUE THREAD

**Issue by killemov** [tc39/ecma262#3003]
**Description:** Return value of forEach is undefined, but it should be the array itself.

**Comment by ljharb** [comment]
Whether it "should" be or not - which is debatable - that ship sailed long ago, in 2009, and this repo isn't the place to discuss changes to the language. I'd suggest visiting one of the places mentioned in https://github.com/tc39/ecma262/blob/main/CONTRIBUTING.md#creating-a-new-proposal if you have further questions.
