### ISSUE TITLE
Rename `RS: Evaluation` of `SwitchStatement : switch ( Expression ) CaseBlock` to `RS: SwitchEvaluation`

### ISSUE THREAD

**Issue by oruborus** [tc39/ecma262#3005]
If one implements the productions for `BreakableStatement` and `SwitchStatement` through inheritance, the implementation of [RS: Evaluation (`BreakableStatement`)](https://tc39.es/ecma262/#sec-statement-semantics-runtime-semantics-evaluation) would be overwritten by [RS: Evaluation (SwitchStatment)](https://tc39.es/ecma262/#sec-switch-statement-runtime-semantics-evaluation).

A psossible remedy would be to rename [RS: Evaluation (SwitchStatment)](https://tc39.es/ecma262/#sec-switch-statement-runtime-semantics-evaluation) to [RS: SwitchEvaluation (SwitchStatment)](https://tc39.es/ecma262/#sec-switch-statement-runtime-semantics-evaluation):
![image](https://user-images.githubusercontent.com/17663/215337518-ba0e01d0-2a83-41a8-9136-8bbbff2bb006.png)

This operation would be solely used in [RS: LabelledEvaluation (SwitchStatement)](https://tc39.es/ecma262/#sec-runtime-semantics-labelledevaluation):
![image](https://user-images.githubusercontent.com/17663/215336414-bc75f6ef-0306-48ba-a7f5-29c46c2c8a9e.png)

This would be easier to understand and be thus more error-resistant (like [RS: LoopEvaluation](https://tc39.es/ecma262/#sec-runtime-semantics-loopevaluation)).

**Comment by bakkot** [comment]
I'm not sure what it would mean to implement productions "through inheritance". Nonterminals in a context-free grammar aren't meant to be interpreted as having a subclass relation; they're all distinct things.

The specially-named variants of Evaluation, like LoopEvaluation, are only used for operations which take arguments, unlike the primary Evaluation operation. Evaluation of SwitchStatement is not such an operation. Giving it a different name would imply there's something different about evaluating SwitchStatement vs evaluating any other production, and that's not true, so I would be opposed to that.

**Comment by oruborus** [comment]
Thank you for your quick response.

I was not aware of the specific conventions which lead to the naming of certain operations.

Of course are the nonterminals `BreakableStatement` and `SwitchStatement` clearly distinct, but they share a rather obvious relation as a `SwitchStatement` _is_ a `BreakableStatement` which in turn lends itself to inheritance rather well (even if it is not meant to interpreted like that).

**Comment by jmdyck** [comment]
> a `SwitchStatement` _is_ a `BreakableStatement`

The spec doesn't say that a _SwitchStatement_ Parse Node 'is a' _BreakableStatement_ Parse Node, so you might be better off not thinking that it is.

**Comment by oruborus** [comment]
After reading both of your comments I agree with you.
I'm better off thinking that the `BreakableStatement` parse node might contain a `SwitchStatement` parse node. In that case the change I proposed is not needed.

But it did _feel_ a lot cleaner.

Thank you both for the clarification.
