### ISSUE TITLE
InitializeInstanceElements is invoked twice for base classes with no explicit constructor

### ISSUE THREAD

**Issue by StefanOctavian** [tc39/ecma262#3020]
**Description:** 
According to section `15.7.14 RS: ClassDefinitionEvaluation`, step `14.a.vi`, when a class is defined without an explicit `constructor` method, the abstract closure that is used as the constructor function for this class invokes `InitializeInstanceElements`, regardless of whether it is a base class or a derived class. This is necessary for derived classes, because, as there is no explicit `constructor` method, there is no explicit `super` call, which would call `InitializeInstanceElements` for the derived class. However, for base classes, according to `10.2.2`, step `6.b`, `[[Construct]]` will call `InitializeInstanceElements` for base classes. This means that, per the spec, an instance of a base class without an explicit constructor should have its fields initialized twice, once due to the `new` operator calling `[[Construct]]` and then due to the call to the implicit constructor.

However, this is not the case in major implementations of the language. For the following example:
```javascript
let obj = {
    get prop() {
        print('Initializer');
        return 1;
    }
}

class A {
    field = obj.prop
}

let a = new A();
```` 

 **eshost output**:
 ```bash
 #### engine262, GraalJS, JavaScriptCore, Moddable XS, QuickJS, SpiderMonkey, V8
Initializer
````

I believe this is either just a specification error as it would be pointless initializing the fields twice, as all major implementations have figured, but there's also a chance that I misunderstood something in the specification. In the case of the former, the solution would simply be to move step `14.a.vi` in `ClassDefinitionEvaluation` to `14.a.iv.5`

**Comment by ljharb** [comment]
https://tc39.es/ecma262/#sec-runtime-semantics-classdefinitionevaluation

I believe `InitializeInstanceElements` here is passing *the constructor itself* as the instance, which would initialize static fields but not instance fields.

**Comment by StefanOctavian** [comment]
@ljharb if you take a look at https://tc39.es/ecma262/#sec-initializeinstanceelements, the order of the arguments is first the object whose fields are being initialized (and this is passed "result" in the algorithm we both referenced, which is the instance) and then the constructor (and this is passed "F" which is the class / constructor function itself )

**Comment by ljharb** [comment]
ah! that's inside an Abstract Closure - which is like a closed-over function. It's not actually evaluating that at class definition time.

**Comment by StefanOctavian** [comment]
@ljharb yes. It's initializing the created **instance**, it couldn't be called at class definition time. The issue here is that [[Construct]] is also initializing the same fields.

**Comment by michaelficarra** [comment]
@StefanOctavian I agree with your conclusion and I agree with your proposed solution to move the step to the derived path. Do you want to submit a PR?

**Comment by StefanOctavian** [comment]
@michaelficarra Yes. I just submitted a PR.

**Comment by ljharb** [comment]
Closing, per https://github.com/tc39/ecma262/pull/3023#issuecomment-1498211451
