### ISSUE TITLE
Description of the UNary - Operator

### ISSUE THREAD

**Issue by fangniyima** [tc39/ecma262#3024]
Description:
In the Note part of 13.5.5 Unary -Operator：
![1](https://user-images.githubusercontent.com/76503086/222901009-5f664d69-26cc-4c4d-b3c4-ca1a16608567.png)

However, it is explicitly stated in its runtime semantics that BigInt type will not be converted to Number type. Whether the description here should improve？

**Comment by jmdyck** [comment]
Yeah, that Note should probably say "... converts its operand to a numeric value ..."

**Comment by fangniyima** [comment]
@jmdyck Can I submit a PR?

**Comment by jmdyck** [comment]
Yes, for editorial corrections like this, anyone can submit a PR.
