### ISSUE TITLE
Claimed equivalence between `RegExp(…)` and `new RegExp(…)` doesn’t hold

### ISSUE THREAD

**Issue by andersk** [tc39/ecma262#3028]
According to [§22.2.4 The RegExp Constructor](https://tc39.es/ecma262/multipage/text-processing.html#sec-regexp-constructor):

> Thus the function call `RegExp(…)` is equivalent to the object creation expression `new RegExp(…)` with the same arguments.

But empirically (in at least JavaScriptCore, SpiderMonkey, and V8), these calls are not equivalent:

```js
> r = /a/;
/a/
> RegExp(r) === r
true
> new RegExp(r) === r
false
```

and looking at the steps in §22.2.4.1, it should only be possible for the `RegExp` constructor to return its argument unchanged (2.b.ii) when NewTarget is **undefined**, i.e. it was called as `RegExp(…)` rather than `new RegExp(…)`.

Does the equivalence claim need to be corrected? It seems to have motivated an incorrect optimization in the SWC minifier:

- swc-project/swc#6941

[Previously posted [to the ES Discourse](https://es.discourse.group/t/is-regexp-really-equivalent-to-new-regexp/1637).]

**Comment by ljharb** [comment]
I'm not sure `equivalent` implies `===` - both of those expressions produce a regex with the same source and flags as `r`, whether it's got the same object identity or not.

**Comment by andersk** [comment]
Equivalent doesn’t imply `===` (e.g. `0/0 !== 0/0`). But what I’m saying is that an equivalence between `RegExp(…)` and `new RegExp(…)` should imply an equivalence between an expression that uses `RegExp(…)` and an expression that uses `new RegExp(…)`—whether or not that expression happens to involve the `===` operator.

Another example without the `===` operator is

```js
> r = /a/g, r.exec("a"), RegExp(r).exec("a")
null
> r = /a/g, r.exec("a"), new RegExp(r).exec("a")
[ 'a', index: 0, input: 'a', groups: undefined ]
```

Of all the constructors that make the same equivalence claim (`Function`, `Error`, `NativeError`, `AggregateError`, `RegExp`, `Array`, `GeneratorFunction`, `AsyncGeneratorFunction`, `AsyncFunction`), `Error` is the only one that breaks this equivalence by passing through the original object when used without `new`.

**Comment by bakkot** [comment]
Agreed, the note should be updated or just removed. It's wrong.

@ljharb The note is about two _behaviors_ being equivalent - here they're observably different.

I'd lean towards removing the note entirely, I think. Rewording it to be correct is a bit tricky.

**Comment by tabatkins** [comment]
I think it's important to note the preceding sentence, which is what the quoted sentence in the OP is referring to in its claim of equivalence:

> creates and initializes a new RegExp object when called as a function rather than as a constructor.

*Sometimes* `RegExp()` returns a fresh RegExp object, other times it doesn't. (While `new RegExp()` always does, obviously.) So yeah the sentence is straight-up wrong.
