### ISSUE TITLE
Explicit setting "length" in splice/slice is always necessary

### ISSUE THREAD

**Issue by Josh-Cena** [tc39/ecma262#3036]
[`Array.p.slice()`](https://tc39.es/ecma262/#sec-array.prototype.slice) and [`Array.p.splice()`](https://tc39.es/ecma262/#sec-array.prototype.splice) has a note that reads:

> Setting "length" became unnecessary starting in ES2015

This is still necessary, because the constructor used in `ArraySpeciesCreate` may not actually use the parameter to set its `length` property.

```js
const arr = [1, 2, 3];
arr.constructor = { [Symbol.species]: function () {} };

print(Array.prototype.slice.call(arr, 0, 3).length);
```

```
#### engine262, GraalJS, JavaScriptCore, SpiderMonkey, V8
3
```

If the step that sets the length is removed, the `Array.prototype.slice.call(arr, 0, 3)` step would not have the `length` property.

**Comment by jmdyck** [comment]
See also PR #1277.

**Comment by Josh-Cena** [comment]
So #1277 discusses whether the note is about whether setting length of `this` or return value is unnecessary. But in fact, either one may be a non-array (although at least one is). Not sure if the note should be kept at all.
