### ISSUE TITLE
Web reality with for...in mid-iteration modification

### ISSUE THREAD

**Issue by Josh-Cena** [tc39/ecma262#3037]
**Description:** I'm writing MDN docs for some corner cases of `for...in` loops when I realized that sometimes all major engines deviate from the spec. I'm not sure if this should be changed in all engines or simply changed in spec.

1. Property added to prototype should be visited.

```js
const proto = {};
const obj = { __proto__: proto, a: 1, b: 2 };

for (const prop in obj) {
  console.log(`obj.${prop} = ${obj[prop]}`);
  proto.c = 3;
}
```

```
$ eshost -s test.js
#### engine262, GraalJS
obj.a = 1
obj.b = 2
obj.c = 3

#### JavaScriptCore, SpiderMonkey, V8
obj.a = 1
obj.b = 2
```

2. Property turned to non-enumerable should not be visited.

(Because JSC performs correctly for this case, I've submitted bugs to both V8 and SM instead.)

```js
const obj = { a: 1, b: 2, c: 3 };

for (const prop in obj) {
  console.log(`obj.${prop} = ${obj[prop]}`);
  Object.defineProperty(obj, "c", { enumerable: false });
}
```

```
$ eshost -s test.js
#### engine262, GraalJS, JavaScriptCore
obj.a = 1
obj.b = 2

#### SpiderMonkey, V8
obj.a = 1
obj.b = 2
obj.c = 3
```

3. Changed prototype should be visited.

```js
const obj = { a: 1, b: 2 };

for (const prop in obj) {
  console.log(`obj.${prop} = ${obj[prop]}`);
  Object.setPrototypeOf(obj, { c: 3 });
}
```

```
$ eshost -s test.js
#### engine262, GraalJS
obj.a = 1
obj.b = 2
obj.c = 3

#### JavaScriptCore, SpiderMonkey, V8
obj.a = 1
obj.b = 2
```

If we decided these are bugs in implementations, there should be tests for these. (It seems there aren't?)

**Comment by bakkot** [comment]
Iteration order is [explicitly unspecified](https://tc39.es/ecma262/multipage/ecmascript-language-statements-and-declarations.html#sec-enumerate-object-properties) in the following circumstances:

- the value of the [[Prototype]] internal slot of O [the object in question] or an object in its prototype chain changes,
- a property is removed from O or an object in its prototype chain,
- a property is added to an object in O's prototype chain, or
- the value of the [[Enumerable]] attribute of a property of O or an object in its prototype chain changes.

I think that covers all of these examples, so I don't think any engines are in violation of the spec.

**Comment by Josh-Cena** [comment]
Thanks @bakkot that makes sense.
