### ISSUE TITLE
Math.random() possible problem

### ISSUE THREAD

**Issue by fimorio** [tc39/ecma262#3042]
`Math.random()` creates a floating point number between 0 and 1, exclusive 1.
https://tc39.es/ecma262/multipage/numbers-and-dates.html#sec-math.random

The Mozilla Firefox Browser Console generates a floating point number with 17 positions after decimal points.
```
Math.random();
// 0.45065673763833813
// 0.12345678901234567
```

With a random number of `0.99999999999999999` the published examples have a problem. The result is possible greater than `max`.
```
var min = 0;
var max = 100;
// returns a random number between min and max (both included).
Math.floor(Math.random() * (max - min + 1) + min);
// ...
var random_n1 = 0.12345678901234567;
var random_94 = 0.99999999999999994;
Math.floor(random_94 * (max - min + 1) + min); 
// 100
var random_n2 = 0.12345678901234567;
var random_95 = 0.99999999999999995;
Math.floor(random_95 * (max - min + 1) + min); 
// 101
```
https://www.w3schools.com/js/js_random.asp
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random?retiredLocale=de

But, the Mozilla Firefox Browser Console generates not in all situations a number with 17 positions after decimal points. Sometime only a number with 16 positions after decimal points.
```
for (var i = 0; i < 1000000000; i++) {
  var random = Math.random();
  if (random > 0.999999999) {
  console.log(random);
}
}
// 0.9999999990514166
// 0.9999999994690799
// 0.1234567890123456
```
I haven't the equipment to make more test. A random number greater than `0.99999999999999994` is very rarely, but maybe possible.

**Comment by ljharb** [comment]
What published examples? TC39 doesn't manage MDN, and certainly not w3schools, and the spec doesn't have any relevant examples that I can find.

**Comment by bakkot** [comment]
This is a misunderstanding of floating point numbers and/or `Math.random`. `Math.random` doesn't make numbers by picking random decimal digits; rather it generates a floating point number in the appropriate range directly. And the decimal number `0.99999999999999999` is represented by the floating point number `1` - that is, `0.99999999999999999 === 1` - so `Math.random` _cannot_ generate `0.99999999999999999`.

**Comment by fimorio** [comment]
Hello bakkot, thanks for the info.
`0.99999999999999999 === 1` , and what is with `0.99999999999999995`?
```
var min = 0;
var max = 100;
var random_n2 = 0.12345678901234567;
var random_95 = 0.99999999999999995;
Math.floor(random_95 * (max - min + 1) + min); 
// 101
```

**Comment by nicolo-ribaudo** [comment]
It's still 1:
```js
> 0.99999999999999995 === 1 
true
```

**Comment by fimorio** [comment]
OK. Thats not so easy to understand it. Here is a website with a float to IEEE 754 calculator:
http://weitz.de/ieee/
```
0.99999999999999994
0x3FEFFFFFFFFFFFFF
0b0011111111101111111111111111111111111111111111111111111111111111
0.99999999999999994 = 0.9999999999999999

0.99999999999999995
0x3FF0000000000000
0b0011111111110000000000000000000000000000000000000000000000000000
0.99999999999999995 = 1

0.99999999999999999
0x3FF0000000000000
0b0011111111110000000000000000000000000000000000000000000000000000
0.99999999999999999 = 1
```
I haven't found the transformation in the code.     
In another websites, there was different results, because it wasn't calculated wit JavaScript.     
Have you a code example to convert a float into a IEEE?

**Comment by nicolo-ribaudo** [comment]
You can use one of these functions:
```js
function floatToBytesBin(num) {
  let buf = new ArrayBuffer(8);
  new DataView(buf).setFloat64(0, num);
  return new DataView(buf).getBigUint64(0).toString(2).padStart(64, "0")
}
function floatToBytesHex(num) {
  let buf = new ArrayBuffer(8);
  new DataView(buf).setFloat64(0, num);
  return new DataView(buf).getBigUint64(0).toString(16).padStart(16, "0")
}
```

**Comment by fimorio** [comment]
Thanks @nicolo-ribaudo , but sorry, I described it too unclearly. The result should be the value that `Math.random` returns, so again a float. Like:
```
function floatToBytesBinToFloat(num) {
  let buf = new ArrayBuffer(8);
  new DataView(buf).setFloat64(0, num);
  let iee754 = new DataView(buf).getBigUint64(0).toString(2).padStart(64, "0");
  let iee754float = ? // convert iee754 to float
  return iee754float;
}
// so also for BytesHex

var num = 0.99999999999999994;
floatToBytesBinToFloat(num); // 0.99999999999999999

var num = 0.99999999999999995;
floatToBytesBinToFloat(num); // 1
```

**Comment by bathos** [comment]
@fimorio An ES Number value already is a 64-bit float, so `floatToBytesBinToFloat` is equal to `number => number`. The functions @nicolo-ribaudo gave are for introspecting the underlying binary representation of such values, which can help one understand how they work “under the hood”.

**Comment by fimorio** [comment]
@bathos , yes, OK, i had a misleading. The `Math.random()` don't pass a `float`, but a `IEE 754`, and this is "visible" not `0.99999999999999994`, but `0.99999999999999999`. But when a `float` instead the (`Math.random()`) `IEE 754` is used, the result is different. Thanks.
