### ISSUE TITLE
Conversion of Infinity in ToUint32

### ISSUE THREAD

**Issue by sunkai9064** [tc39/ecma262#3047]
Hello, I am learning about arrays. In 10.4.2.1 [[DefineOwnProperty]] ( P, Desc ), ToUint32(P) is called to convert the property key, but there is such a description in it:

>2. If number is not finite or number is either +0<sub>𝔽</sub> or -0<sub>𝔽</sub>, return +0<sub>𝔽</sub>.

However, this is not the case in actual operation, as follows

```
let arr = [];
arr[1/0]= 1;
//arr   [Infinity: 1]
```

Is this a bug, or am I misunderstanding something?

**Comment by jmdyck** [comment]
10.4.2.1 `[[DefineOwnProperty]]` invokes `ToUint32` at step 2.f, which is guarded by step 2: "Else if _P_ is an array index". In your example, _P_ is the String value "Infinity", but that doesn't qualify as an 'array index', so execution proceeds to step 3, where a non-array-index property (with property key "Infinity") is created.

**Comment by sunkai9064** [comment]
@jmdyck Thank you, I missed the branch condition above
