### ISSUE TITLE
%TypedArray% constructor calling super

### ISSUE THREAD

**Issue by leobalter** [tc39/ecma262#305]
Previously on the ES2015, we got each of the _TypedArray_ constructors calling the %TypedArray% super class:

```
22.2.4.1 TypedArray( ... argumentsList)

...
3. Let super be here.[[GetPrototypeOf]]().
... 
7. Return Construct(super, argumentsList, NewTarget).
```

Now (on the ES2016 draft/master branch) the _TypedArray_ constructors are not calling the %TypedArray% superclass anymore. See https://github.com/tc39/ecma262/issues/163#issuecomment-158116899

```
22.2.4.1 TypedArray ( )

This description applies only if the TypedArray function is called with no arguments.

1. If NewTarget is undefined, throw a TypeError exception.
2. Let constructorName be the String value of the Constructor Name value specified in Table 50 for this TypedArray constructor.
3. Return ? AllocateTypedArray(constructorName, NewTarget, %TypedArrayPrototype%, 0).
```

And a super call is now seen at the %TypedArray% constructor:

```
22.2.1.1 %TypedArray%()


4. Let super be ? here.[[GetPrototypeOf]]().
5. If IsConstructor (super) is false, throw a TypeError exception.
...
7. Return ? Construct(super, argumentsList, NewTarget). 
```

It seems the the steps 4 and 5 are misplaced. They came from https://github.com/tc39/ecma262/pull/247, it seems they might be removed or doesn't need to be placed there.

Checking %TypedArray% static methods as `from` and `of`, both call TypedArrayCreate which is safe when called from the _TypedArray_ objects and won't need no further call on super as well.

It seems safe to say %TypedArray% might throw a TypeError on any way it's called. It does not help creating internals neither it seems necessary on the static methods.

**Comment by littledan** [comment]
Seems like a typo in my PR that the _TypedArray_ constructors don't call the super constructor. As for the %TypedArray% constructor, calling the super constructor was a suggestion by @allenwb , but I think you're right--this isn't needed, as %TypedArray% is a base class, and base classes don't tend to call their super constructor (even if one is dynamically added through proto chain manipulation).

**Comment by allenwb** [comment]
See what I said in https://github.com/tc39/ecma262/issues/163#issuecomment-158125718  and https://github.com/tc39/ecma262/issues/163#issuecomment-158125718 .

%TypedArray% should throw if directly newed, super called, or called. It should just throw a TypeError

**Comment by littledan** [comment]
@allenwb I really like this idea. Wrote a PR to implement it. What do you think?

**Comment by leobalter** [comment]
@littledan I came in 5 minutes late: 9c10da5 :)
