### ISSUE TITLE
consider improving the body font

### ISSUE THREAD

**Issue by michaelficarra** [tc39/ecma262#3090]
Our body font list is not great. The highest priority fonts are Windows-exclusive, meaning that readers will get different renderings on different platforms. We should address this using a web font. Also, our current choices are not very legible. I would appreciate a font that uses dotted or slashed zero, for one, to more easily distinguish it from `O`, a commonly-used alias.

If we're okay considering a sans-serif font, I am *extremely* partial to [Atkinson Hyperlegible](https://fonts.google.com/specimen/Atkinson+Hyperlegible/about). It's designed to be very accessible for low-vision readers, but it is also great for people with no vision impairment. I use it as the default sans-serif font in my browser.

If we'd prefer to stick with a serifed font, there's plenty of great free choices on Google Fonts (though a quick skim doesn't show any with dotted or slashed zero).

**Comment by devsnek** [comment]
That looks pretty good.  https://b612-font.com/ might also be an option.

**Comment by michaelficarra** [comment]
Comparison:

<details>
<summary>Palatino (18px)</summary>
<img src="https://github.com/tc39/ecma262/assets/218840/efc2a2a5-7a34-4132-8e4e-d5a070e1dd88" />
</details>

<details>
<summary>Atkinson Hyperlegible (17px)</summary>
<img src="https://github.com/tc39/ecma262/assets/218840/72f19a34-de87-4669-8229-b351ad7bc6f3" />
</details>

<details>
<summary> Allerta (17px)</summary>
<img src="https://github.com/tc39/ecma262/assets/218840/9efbc117-4404-4f49-ba46-cfeadda714e3" />
</details>

<details>
<summary>B612 (17px)</summary>
<img src="https://github.com/tc39/ecma262/assets/218840/3d636fd0-cad7-46e1-89c4-699b1edaf819" />
</details>

**Comment by ljharb** [comment]
fwiw the order you put them seems to match my order of which looks the best - i like palatino.

**Comment by ctcpip** [comment]
strong preference for atkinson.  generally serif fonts are at a disadvantage for a11y.

@michaelficarra could you provide comparison of the fonts with the following text?  `qp db 0O nu il1I 69 a8 a6 6g rnm`

**Comment by bakkot** [comment]
Of those options, Palatino  is the only one I do not find painful to read.

**Comment by ljharb** [comment]
Same; Atkinson (and the other two) is too bold for me.

For a11y, font choice is usually something a user can override in their own browser, i think?

**Comment by ctcpip** [comment]
## palatino:

![Screenshot 2023-06-20 at 1 48 26 PM](https://github.com/tc39/ecma262/assets/15326526/089c4685-9451-429c-9f6a-12059f881d7e)

<hr>

## atkinson

![Screenshot 2023-06-20 at 1 49 55 PM](https://github.com/tc39/ecma262/assets/15326526/7cb4dd66-b9e9-481b-8da6-e71e07666aeb)

**Comment by michaelficarra** [comment]
@ctcpip

> really don't like the zeroes in palatino...

Same. That was the majority of the original motivation for opening this investigation.

**Comment by ctcpip** [comment]
I missed that palatino was the font that many of us see the current spec text rendered in.  the preference some have for palatino may be, at least in part, due to cognitive momentum / status quo bias, as it's what folks are accustomed to looking at (perhaps extensively and over a period of years) and therefore perceive it to be more readable because they are accustomed to reading it.

**Comment by michaelficarra** [comment]
I've added Google's Noto fonts as a "neutral" point of comparison.

**Comment by michaelficarra** [comment]
@devsnek Of the fonts in my comparison above, only the Noto family gains slashed zeroes when that rule is applied.

**Comment by michaelficarra** [comment]
I'm starting to think that the generally looser letter spacing of the fonts designed for legibility is the issue here. For those that don't like Atkinson Hyperlegible, do you like it more with tighter letter spacing?

<details>
<summary>Atkinson Hyperlegible, 17px, standard spacing</summary>
<img src="https://github.com/tc39/ecma262/assets/218840/ee9756b7-3bb4-4437-8c0e-3f4fbe51d301" />
</details>

<details>
<summary>Atkinson Hyperlegible, 17px, -0.01em spacing</summary>
<img src="https://github.com/tc39/ecma262/assets/218840/650e4ae9-5faf-44e0-94ad-3a3cebe6390f" />
</details>

<details>
<summary>Atkinson Hyperlegible, 17px, -0.02em spacing</summary>
<img src="https://github.com/tc39/ecma262/assets/218840/bc026a36-37e0-40a9-ade7-97e8c72679b2" />
</details>

<details>
<summary>Atkinson Hyperlegible, 17px, -0.03em spacing</summary>
<img src="https://github.com/tc39/ecma262/assets/218840/04d9ee3e-4798-46b1-b7eb-b5e183688159" />
</details>

<details>
<summary>Atkinson Hyperlegible, 17px, -0.04em spacing</summary>
<img src="https://github.com/tc39/ecma262/assets/218840/efd303bf-9037-44a6-b7e0-2078d23a580d" />
</details>

**Comment by devsnek** [comment]
what if we have all of these with a dropdown?

**Comment by ctcpip** [comment]
the reduced letter spacing results in... `the keming`

![Screenshot 2023-06-20 at 4 25 47 PM](https://github.com/tc39/ecma262/assets/15326526/5bb601d4-c34d-482c-be9e-c5d1fb77cf9f)

**Comment by ljharb** [comment]
I don't think the letter spacing at 0 is a problem at all; everything tighter than that looks claustrophobic to me.

**Comment by syg** [comment]
> @devsnek Of the fonts in my comparison above, only the Noto family gains slashed zeroes when that rule is applied.

Including Noto Serif? I think Noto Serif also looks acceptable.

**Comment by ctcpip** [comment]
> Including Noto Serif? I think Noto Serif also looks acceptable.

sadly no

**Comment by michaelficarra** [comment]
@ctcpip Both Noto Sans and Noto Serif gain a slashed zero for me when using that CSS rule. How did you test?

**Comment by ctcpip** [comment]
@michaelficarra

![Screenshot 2023-06-22 at 1 03 20 PM](https://github.com/tc39/ecma262/assets/15326526/a5c43af9-3a70-4067-9943-7ecca9781d99)

**Comment by michaelficarra** [comment]
![image](https://github.com/tc39/ecma262/assets/218840/b309ac49-8915-4a93-9585-3abd05a24bab)

![image](https://github.com/tc39/ecma262/assets/218840/58beae16-e56d-49e4-90fc-6fd06ccb0929)

**Comment by ctcpip** [comment]
@michaelficarra are you sure `noto serif` is the rendered font there?  your screenshot doesn't include the computed rendered fonts info

**Comment by devsnek** [comment]
noto serif from the repo appears to contain slashed zeros: https://github.com/notofonts/noto-fonts/tree/main/hinted/ttf/NotoSansMono

**Comment by ctcpip** [comment]
@devsnek that's not noto serif

**Comment by devsnek** [comment]
oh sorry wrong link: https://github.com/notofonts/noto-fonts/tree/main/hinted/ttf/NotoSerif

now that i look more though, looks like the official downloads are here now: https://notofonts.github.io/

**Comment by michaelficarra** [comment]
@ctcpip Yes, I am sure.

![image](https://github.com/tc39/ecma262/assets/218840/a492aa9d-2b7c-4820-92c5-360b2f9a08dc)

**Comment by ctcpip** [comment]
@michaelficarra sorry, not saying it's wrong font, but your screenshot is still not showing the rendered font.  for example, here is the font-family `woot`, but it's rendering Atkinson:

![Screenshot 2023-06-22 at 7 11 47 PM](https://github.com/tc39/ecma262/assets/15326526/ad35f891-a7ea-4867-b735-9f719174f6a3)

**Comment by ctcpip** [comment]
it's entirely possible googly is just not loading all the font variants and there is indeed slashed zero support for noto.  I'm not intending to be incredulous :)

**Comment by michaelficarra** [comment]
This was fixed by https://github.com/tc39/ecmarkup/pull/539.
