### ISSUE TITLE
Set `Object.prototype.toJSON` a non-configurable, non-writable `null`

### ISSUE THREAD

**Issue by petamoriken** [tc39/ecma262#3095]
The current spec allows to define `Object.prototype.toJSON` as desired, which can affect `JSON.stringify`.

```js
Object.prototype.toJSON = () => "foo";
JSON.stringify({ bar: "baz" }); // '"foo"'
```

To avoid this, I propose to define a non-configurable, non-writeable property of null for `Object.prototype.toJSON`. This is similar to the discussion of `Function.prototype[Symbol.metadata]` for Decorator Metadata proposal.

> There’s a constraint from implementers that it be syntactically determinable whether a class should be given a Symbol.metadata property. This means it can be conditional based on the presence of decorators, but not by the actual usage of metadata by decorators. Additionally, we all agree that we don’t want it to be possible to add metadata to everything by modifying Function.prototype. The only way it turns out to be practical to do that is to add a non-configurable, non-writeable property of null to Function.prototype, to avoid injecting metadata on everyone. Given those constraints, there’s only one design that makes sense, and that’s the design everyone likes.

https://github.com/tc39/notes/blob/main/meetings/2023-05/may-16.md#summary-of-key-points

**Comment by ljharb** [comment]
This repo isn’t the place to suggest language changes; see https://github.com/tc39/ecma262/blob/main/CONTRIBUTING.md#new-feature-proposals

**Comment by petamoriken** [comment]
@ljharb This is not a proposal for a new feature, but a discussion forum for normative change.

**Comment by ljharb** [comment]
This isn’t a forum for that either; you could try https://es.discourse.group.

Making any changes to Object.prototype is highly likely to break the web, and there’d need to be a really compelling argument to do so, and it’d need to go through the proposal process or find a delegate to champion it in committee - which is done on the discourse.

**Comment by petamoriken** [comment]
OK

**Comment by mhofman** [comment]
Discourse is definitely the right place to raise this kind of suggestions.

That said I will answer here that specifically such a change would trigger the "override mistake" for existing code which uses assignment to add a `toJSON` to their custom objects (or prototype objects), and as such is a non starter without a mitigation in place for the override mistake.

**Comment by petamoriken** [comment]
Move to https://es.discourse.group/t/set-object-prototype-tojson-a-non-configurable-non-writable-null/1732
