### ISSUE TITLE
drop "this Date object" from the Date section

### ISSUE THREAD

**Issue by michaelficarra** [tc39/ecma262#3118]
As defined in https://tc39.es/ecma262/#sec-properties-of-the-date-prototype-object. It is unnecessary indirection and obscures a possible abrupt completion. I would much rather use normal spec steps.

Possibly also consider dropping "this time value".

**Comment by bakkot** [comment]
@michaelficarra https://github.com/tc39/ecma262/pull/3063

**Comment by michaelficarra** [comment]
@bakkot That PR doesn't resolve either of my proposed changes.

**Comment by jmdyck** [comment]
I've done some analysis on this, will see what I can come up with.
