### ISSUE TITLE
Cannot create proxy for class constructor

### ISSUE THREAD

**Issue by raulsebastianmihaila** [tc39/ecma262#312]
ProxyCreate (http://www.ecma-international.org/ecma-262/6.0/#sec-proxycreate) doesn't set the [[Construct]] method if the target isn't callable (doesn't have [[Call]]). AFAIK, class constructors don't have [[Call]]. Is this a bug?

**Comment by ljharb** [comment]
Class constructors do have `[[Call]]`, it's just specified to throw a TypeError. See http://tc39.github.io/ecma262/#sec-makeclassconstructor, and step 2 of http://tc39.github.io/ecma262/#sec-ecmascript-function-objects-call-thisargument-argumentslist.

**Comment by raulsebastianmihaila** [comment]
I see, thanks!
