### ISSUE TITLE
Rendering issue ("_numYearsN_") in DayFromYear

### ISSUE THREAD

**Issue by linusg** [tc39/ecma262#3180]
This is tricky as it tries to refer to multiple similarly named variables, but the result of mixing inline code and variable syntax looks rather odd:

```
`_numYearsN_`
```

I think this should use plain code without the underscores, or the variable syntax (which would emit `warning: could not find a preceding declaration for "numYearsN" (use-before-def)`)

![image](https://github.com/tc39/ecma262/assets/19366641/b8a7883d-e2cc-451c-9795-6c03643e4503)

**Comment by jmdyck** [comment]
That's my fault, back in PR #3092. (Didn't look close enough at the rendering.) I'll submit a fix.
