### ISSUE TITLE
There seems to be a fundamental contradiction between the specification of escape sequences between JSON and raw strings.

### ISSUE THREAD

**Issue by aeschylus** [tc39/ecma262#3186]
I did some analysis with Bourne.parse and JSON.parse. The issue is unrelated to request size and is only related to JSON string formatting. Consider the following examples:
```js
try {
  JSON.parse(`{"foo":"bar\""}`)
} catch (e) {
  console.error(e)
}
// SyntaxError: Expected ',' or '}' after property value in JSON at position 12

try {
  JSON.parse(String.raw`{"foo":"bar\""}`)
} catch (e) {
  console.error(e)
}
// No error
```

https://github.com/hapijs/hapi/issues/4461#issuecomment-1741188420

**Comment by ljharb** [comment]
Actually, closing, since this is just the content of another person’s issue comment.

**Comment by aeschylus** [comment]
I would expect the JSON as JSON to be parsable.

**Comment by aeschylus** [comment]
The consequence of this is that I can't receive some input to an API endpoint and parse it without causing an error. This is a fundamental need. In this case the client is trying to represent inches ( and in: 'This board is 2" x 4"'). I don't have control over the format of this input, and currently we are having to write the stream directly to the file system and then translate it back in, instead of merely parsing it in the API endpoint.

**Comment by bakkot** [comment]
> Am I wrong to expect the escaped quote to be escaped, and therefore for the JSON to be parsable?

Yes.

This isn't an issue with ECMAScript, and this isn't a support forum. I recommend trying StackOverflow.

**Comment by bathos** [comment]
In case you haven’t figured this out yet: the string `'{"foo":"bar\""}'` is an ES string with an _ES escape sequence_ for escape a double quote. Its string value is `{"foo":"bar""}`, which is not valid JSON source text. JSON is _another language_ with _its own_ escape sequences, so the corrected ES string is `'{"foo":"bar\\""}'`, i.e. you need to escape (ES) the escape (JSON).
