### ISSUE TITLE
Small change feature request.

### ISSUE THREAD

**Issue by dkfdkdodkms** [tc39/ecma262#3218]
I'm not sure if this is the correct place to file this, but here is the request:

The debugger statement is currently very limited. Ideally one could specify a negative stack position.

//current: pause at stack position x
debugger;

 //propose an optional n argument: pause at stack position x - n;
debugger n; 

example:
```
const fail = (message) => 
{
    if (window.debug) debugger 1;  //debugger would pause at the fail call rather than here
 
    const error = new Error(message); 
    if (Error.captureStackTrace !== undefined) Error.captureStackTrace(error, fail);
   
    throw error;
}

let foo = b ?? fail('invalid value given');
```

**Comment by ljharb** [comment]
It's not; see https://github.com/tc39/ecma262/blob/main/CONTRIBUTING.md#creating-a-new-proposal

However, note that stacks aren't specified in the language at all yet; see https://github.com/tc39/proposal-error-stacks

**Comment by dkfdkdodkms** [comment]
Hm, then why does the readme say this? "For small changes to ECMAScript, you can contribute by filing an issue or a pull request against the current text of ECMA-262 standard in this repository."

Also, this isn't about the stack, specifically. This is about extending the debugger statement. Given my example includes some error code, I can see why it might have looked like that.

"

**Comment by ljharb** [comment]
Anything observable to users is not a small change.

**Comment by dkfdkdodkms** [comment]
Observable to devs? Users shouldn't see this, as it's only applicable when the debug console is open.

**Comment by ljharb** [comment]
Yes, developers are users.

**Comment by dkfdkdodkms** [comment]
Ah, yes, that makes sense in this context. Okay, thanks.

**Comment by Jack-Works** [comment]
and also, you may interested in https://github.com/tc39/proposal-standardized-debug
