### ISSUE TITLE
"but not one of" is rendered as "one of" in RegExp patterns

### ISSUE THREAD

**Issue by goyakin** [tc39/ecma262#325]
For example, the checked-in version of the `ClassAtomNoDash` RegExp grammar in Section 21.2.1 says:

    ClassAtomNoDash[U] ::
      SourceCharacter but not one of `\` or `]` or `-`
      `\` ClassEscape[?U]

However, the [rendered version](https://tc39.github.io/ecma262/#prod-ClassAtomNoDash) removes `but not` after `SourceCharacter` and shows it as:

    ClassAtomNoDash[U] ::
      SourceCharacter one of `\` or `]` or `-`
      `\` ClassEscape[?U]

**Comment by bterlson** [comment]
Fixed in 7ba2fec.
