### ISSUE TITLE
Clicking on a RegExp pattern in Annex B brings the default one in Section 21.2.1 into view

### ISSUE THREAD

**Issue by goyakin** [tc39/ecma262#326]
For example, given that `CharacterEscape` is overridden in Annex B.1.4, one would expect to see that version when `CharacterEscape` under `ClassEscape` is clicked. However, the [default one](https://tc39.github.io/ecma262/#prod-CharacterEscape) in Section 21.2.1 is brought into view instead.

**Comment by bterlson** [comment]
Duping in favor of #365.
