### ISSUE TITLE
Proxy [[SetPrototypeOf]] improvement

### ISSUE THREAD

**Issue by raulsebastianmihaila** [tc39/ecma262#329]
AFAICT, most of the proxy internal methods that are meant to change some state (preventExtensions, defineProperty, set and delete) check the state of the target only if the trap returns a truthy value. Wouldn't it be better for setPrototypeOf to behave the same?

By that I mean that in step 11 of [[SetPrototypeOf]] (http://www.ecma-international.org/ecma-262/6.0/#sec-proxy-object-internal-methods-and-internal-slots-setprototypeof-v) there should be a check like If booleanTrapResult is false, return false.

I think this would make it easier to reason about proxies.

**Comment by claudepache** [comment]
[Link to the spec section](https://tc39.github.io/ecma262/#sec-proxy-object-internal-methods-and-internal-slots-setprototypeof-v).

I think indeed that the current steps 9-12 should be run only if _booleanTrapResult_ is **true**.

**Comment by bterlson** [comment]
This is fixed in master.
