### ISSUE TITLE
GetPrototypeFromConstructor has unused parameter

### ISSUE THREAD

**Issue by raulsebastianmihaila** [tc39/ecma262#330]
It seems to me that [GetPrototypeFormConstructor] (https://tc39.github.io/ecma262/#sec-getprototypefromconstructor) doesn't use the second argument, intrinsicDefaultProto. The introduction to this operation and the assertion in step 1 seem to contradict step 4 and the note at the end of the operation.

**Comment by zenparsing** [comment]
What about step 4.b?

**Comment by raulsebastianmihaila** [comment]
Oh, sorry, I misread. Thanks!
