### ISSUE TITLE
Undefined `%GeneratorFunction.prototype.prototype.next%` intrinsic in CreateListIteratorRecord

### ISSUE THREAD

**Issue by aapoalas** [tc39/ecma262#3304]
In [CreateListIteratorRecord](https://tc39.es/ecma262/#sec-createlistiteratorRecord) step 3 refers to a `%GeneratorFunction.prototype.prototype.next%` intrinsic object which is not mentioned anywhere else in the specification text.

This of course refers to [%GeneratorPrototype%.next ( value )](https://tc39.es/ecma262/#sec-generator.prototype.next) and seems to suggest that changing the `next` property of `Generator.prototype.prototype` will not affect this abstract operation's function but the lack of any other mentions to this intrinsic leaves this a little ambiguous.

**Comment by aapoalas** [comment]
Actually no it doesn't. Nevermind, apologies.

**Comment by ljharb** [comment]
It's not ambiguous, and is defined in the second paragraph of https://tc39.es/ecma262/#sec-well-known-intrinsic-objects.
