### ISSUE TITLE
rephrase `JSON.parse` more generally in terms of `String`-convertible value parameter

### ISSUE THREAD

**Issue by ltcmelo** [tc39/ecma262#3319]
As of the 2025 edition, [25.5.1 `JSON.parse ( text [ , reviver ] )`](https://tc39.es/ecma262/#sec-json.parse) reads as:

_"This function parses a JSON text (a JSON-formatted String) and..."_

Yet, based on a few implementations and official tests cases (e.g. [text-non-string-primitive](https://github.com/tc39/test262/blob/main/test/built-ins/JSON/parse/text-non-string-primitive.js) and [text-object](https://github.com/tc39/test262/blob/main/test/built-ins/JSON/parse/text-object.js)), the `text` parameter of `JSON.parse` doesn't need to be a `String`; even though, it's expect the `text` is convertible to an `String` — in fact, step 1 of this abstract operations is:

_"1. Let jsonString be ? [ToString](https://tc39.es/ecma262/#sec-tostring)(text)."_

Perhaps the description of function `JSON.parse` should be rephrased more generally in terms of an ECMAScript language value that can be converted to an `String`?

**Comment by michaelficarra** [comment]
I don't think we need that kind of precision in the summary. This text is meant to be less complete than the algorithm steps, while not being incorrect. This function *does* parse a JSON-formatted String, and it also converts its input to String before doing that.

**Comment by ltcmelo** [comment]
I think that specifications should be as precise as possible. Also, since the summary indicates the parameter's types, I'd consider it to be incorrect (not just imprecise): This function does parse a JSON-formatted `String`, which is an ECMA value, but it parses values of other ECMA types as well; for instance, when formalizing an ECMA implementation/verifier, this function won't always "type check".

I create PR https://github.com/tc39/ecma262/pull/3322 with a suggested change, in case if you find it useful.
