### ISSUE TITLE
Array and Object naming 

### ISSUE THREAD

**Issue by msselwyn** [tc39/ecma262#3329]
I found this bug in javascript.. 

while declaring array or object using 'name' as array name or object name with keyword 'var', that array and object converted into string, other keywords like 'let' and 'const' working normally

<img width="959" alt="Screenshot 2024-04-28 210157" src="https://github.com/tc39/ecma262/assets/168815506/51805e3a-2426-448f-9718-017c004b3355">
<img width="959" alt="Screenshot 2024-04-28 205455" src="https://github.com/tc39/ecma262/assets/168815506/3c1a9c3b-c706-436a-835f-ce8e201783e1">
<img width="959" alt="Screenshot 2024-04-28 205343" src="https://github.com/tc39/ecma262/assets/168815506/45ce1c4d-f29b-48cf-87a2-335af6bf8156">

find the attachment for your reference

**Comment by ljharb** [comment]
This isn't a bug; it's because in a browser, assigning to `name` sets the `window.name` property, and the HTML spec coerces your array into a string.
