### ISSUE TITLE
ECMAScript 2024 intro mentions transferring ArrayBuffers, but that is still Stage 3

### ISSUE THREAD

**Issue by JohnRiv** [tc39/ecma262#3358]
This part that was added to the Introduction as part of ECMAScript 2024 starts with:

> ECMAScript 2024, the 15th edition, added facilities for resizing and transferring ArrayBuffers and SharedArrayBuffers;

However, it appears that [resizable ArrayBuffer and growable SharedArrayBuffer was added](https://github.com/tc39/ecma262/pull/3116), but the ability to transfer them was [pulled out into its own proposal that is currently in stage 3](https://github.com/tc39/proposal-arraybuffer-transfer), so I think "and transferring" should be removed from that sentence.

**Comment by Josh-Cena** [comment]
ArrayBuffer transfer became stage 4 in Feb 2024: https://github.com/tc39/notes/tree/main/meetings/2024-02 It's even already in the spec: https://tc39.es/ecma262/multipage/structured-data.html#sec-arraybuffer.prototype.transfer
