### ISSUE TITLE
Typo on the tc39.es/ecma262/ web site? - says it is the 2025 Language Specification, but highest tag and branch are for 2024

### ISSUE THREAD

**Issue by intltechventures** [tc39/ecma262#3360]
It apepars that the tc39.es/ecma262/ states that the "2025 Language Specification" is the latest - but the news today was "the Ecma General Assembly approved the latest ECMAScript / JavaScript language spec" - but the git repo only shows a tag/branch for 2024.

**Comment by bakkot** [comment]
tc39.es/ecma262 is the current draft of what will become the 2025 Language Specification when it is published next year. It is continually updated and therefore contains more things than the 2024 specification or any previous yearly edition, which are a point-in-time snapshot. See the first paragraph of the document:

> The document at https://tc39.es/ecma262/ is the most accurate and up-to-date ECMAScript specification. It contains the content of the most recent yearly snapshot plus any finished proposals (those that have reached Stage 4 in the proposal process and thus are implemented in several implementations and will be in the next practical revision) since that snapshot was taken.
