### ISSUE TITLE
Unclear whether Iterator/AsyncIterator `next` can have multiple parameters

### ISSUE THREAD

**Issue by rotu** [tc39/ecma262#3372]
It is unclear how many parameters the _Iterator_ and _AsyncIterator_ interface is supposed to have. There is a [note](https://tc39.es/ecma262/#sec-iteratornext) that implies any number of parameters is permitted (provided that it should be callable with no arguments)

> Arguments may be passed to the **next** function but their interpretation and validity is dependent upon the target _Iterator_. The for-of statement and other common users of _Iterators_ do not pass any arguments, so _Iterator_ objects that expect to be used in such a manner must be prepared to deal with being called with no arguments.

But the [IteratorNext](https://tc39.es/ecma262/#sec-iteratornext) operation takes only zero or one value and the [%AsyncFromSyncIteratorPrototype%.next] operation only forwards zero or one arguments.

**Comment by ljharb** [comment]
That's what those iterators do - you can make your own iterator that takes any number of values, it's just that all the builtin mechanics only take 0 or 1.

**Comment by bakkot** [comment]
When the language calls `.next`, it passes either 1 argument (in the case of `yield *`, in which case it forwards the argument from the outer call to `.next`) or 0 arguments (in the case of any other built-in iteration). `AsyncFromSyncIteratorPrototype` is used internally to wrap sync iterators into async iterators; it's just forwarding the behavior from other callsites and is not really a callsite itself.

But you can of course define a `.next` method which takes as many arguments as you'd like. It's just that if you're going to be using it with `yield *` or built-in iteration, you should be prepared to handle 1 or 0 arguments (respectively).

**Comment by rotu** [comment]
> That's what those iterators do - you can make your own iterator that takes any number of values, it's just that all the builtin mechanics only take 0 or 1.

Okay, that's what I thought. But the [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_iterator_protocol) are confused on this point too, specifically claiming that the iterator protocol only allows for 0 or 1 argument:

> An object is an iterator when it implements a next() method with the following semantics:
> 
> [`next()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#next)
> 
>     A function that accepts zero or one argument ...

Similarly, the Iterator Helpers proposal and Async Iterator Helpers proposal both seem to discard *all* arguments. I can see this mentioned here: https://github.com/tc39/proposal-iterator-helpers/pull/194

It could definitely use some clarifying language - it's super unintuitive that you can have an object `x` that implements the "_Iterator_ protocol" and *only* that protocol, but where nevertheless `Iterator.from(x)` does not preserve its behavior.

**Comment by bakkot** [comment]
> But the [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_iterator_protocol) are confused on this point too, specifically claiming that the iterator protocol only allows for 0 or 1 argument:

I'd regard that as being correct. You can define a `next` method which does whatever it wants, of course, but the spec machinery is never going to give it more than 1 argument. But, it's not clear what it would even mean to forbid taking 2 arguments. This is talking about what's useful, not what's formally permissible.

Part of the trick here is that the _iterator_ protocol works with 0-arity `next`, and the _generator_ protocol works with 1-arity `next` (as evidenced by the fact that syntactic generators use the argument to give the value of `yield` expressions), but also syntactic generator functions are used to implement iterators. If you just say "iterator `next` accepts 0 arguments" then generators aren't strictly speaking iterators, which seems misleading. ([TypeScript](https://github.com/microsoft/TypeScript/pull/58243) has been struggling with just this issue.)

Incidentally I have written this up in a bit more detail [here](https://github.com/tc39/how-we-work/blob/iterator-protocol/iterator-protocol.md), though I haven't gotten around to linking it anywhere.

> Similarly, the Iterator Helpers proposal and Async Iterator Helpers proposal both seem to discard all arguments. I can see this mentioned here: https://github.com/tc39/proposal-iterator-helpers/pull/194
>
> It could definitely use some clarifying language - it's super unintuitive that you can have an object `x` that implements the "Iterator protocol" and only that protocol, but where nevertheless `Iterator.from(x)` does not preserve its behavior.

The spec does not use the phrase "Iterator protocol". The ["Iterator interface" section](https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-iterator-interface) is pretty explicit that iterators should be prepared to be called with no arguments.

If you mean that MDN could use clarification, certainly you can raise the issue with them.
