### ISSUE TITLE
Broken external link in Number::toString

### ISSUE THREAD

**Issue by nicolo-ribaudo** [tc39/ecma262#3389]
This was originally reported by @annevk on Matrix, I'm opening an issue to make sure we don't forget about it since there are already a bunch of other messages.

The link to http://ampl.com/REFS/abstracts.html#rounding in Note 3 of https://tc39.es/ecma262/#sec-numeric-types-number-tostring returns a 404.

It can now be found at https://ampl.com/_archive/first-website/REFS/rounding.pdf, but I guess linking to web archive would be better.

**Comment by ishon19** [comment]
Hi @nicolo-ribaudo, I'd love to do this change! 

I found the most recent working web archive [snapshot](https://web.archive.org/web/20230727101558/https://portal.ampl.com/docs/archive/first-website/REFS/abstracts.html) from July 27, 2023. Updating the link in the docs to this, as you suggested. Should we still link the most recent one?

**Comment by nicolo-ribaudo** [comment]
The latest seems to be fine :)
