### ISSUE TITLE
Duplicate entry

### ISSUE THREAD

**Issue by cstruct** [tc39/ecma262#339]
`Object.getOwnPropertyDescriptors` seems to be duplicated in stage 2 and stage 0.

**Comment by asphp** [comment]
`2c4834a0` removed the proposal from stage 0 and added an updated version with new champion to stage 2. `8d7995d6` later readded the same proposal that was removed.

**Comment by ljharb** [comment]
Thanks, I'll update #338 to fix that.

**Comment by cstruct** [comment]
Fixed by #338.
