### ISSUE TITLE
Implementations and test262 do not fully comply with AO ApplyStringOrNumericBinaryOperator when opText is +

### ISSUE THREAD

**Issue by tonygermano** [tc39/ecma262#3413]
There may have been an unintentional change made in https://github.com/tc39/ecma262/pull/1961, which implemented AO `ApplyStringOrNumericBinaryOperator`, when `opText` is `+`.

Both before and after this change, the `lprim` value is the result of `ToPrimitive(lval)` (no type hint.)

However, prior to the change `lnum` is the result of `ToNumeric(lprim)`, whereas after the change `lnum` is the result of `ToNumeric(lval)`. This results in `ToPrimitive` being called on `lval` a second time, this time with a NUMBER type hint.

I noticed this when working to bring https://github.com/mozilla/rhino up to spec, and I could not figure out why test(https://github.com/tc39/test262/blob/fc49c9ce163dcf501bb0457f0521900cd744cbda/test/language/expressions/addition/coerce-symbol-to-prim-invocation.js) kept failing on the first assertion. My `log` variable contained "leftrightleftright".

After doing some testing in browsers, I finally determined that everyone else is still using the prior behavior of `lnum = ToNumeric(lprim)` rather than following the current specification.

Additional examples that produce different output depending on whether the old or current behavior is being followed:
```javascript
var left = {counter: 0, valueOf() {return this.counter += 1}}
var right = {counter: 0, valueOf() {return this.counter += 10}}
var result = left+right
```
Old spec result: 11
Current spec result: 22

```javascript
var left = {[Symbol.toPrimitive]: hint => hint === "default" ? 1 : 2}
var right = {[Symbol.toPrimitive]: hint => hint === "default" ? 10 : 20}
var result = left+right
```
Old spec result: 11
Current spec result: 22

**Comment by bakkot** [comment]
[ApplyStringOrNumericBinaryOperator](https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#sec-applystringornumericbinaryoperator) step 1d/e looks like addresses precisely this, to me, unless I'm misreading it somehow.

**Comment by tonygermano** [comment]
I don't know how I overlooked that, but you are correct. Thank you for the quick response.
