### ISSUE TITLE
Editorial: String.prototype.matchAll iterators won't return null

### ISSUE THREAD

**Issue by susisu** [tc39/ecma262#3421]
**Description:**

The description of `String.prototype.matchAll` says:

> Each iteration result's value is an Array containing the results of the match, or *null* if the String did not match.

However, if the string did not match, the iterator returns `undefined`, not `null`, as far as you don't use an object with a custom `@@matchAll` property instead of the standard `RegExp`.

(Possibly this is because [the old reivision of the proposal stated it returns `null`](https://github.com/tc39/proposal-string-matchall/commit/f368659e372b37afe241496db3425209d24f14ec) but the description remains unchanged?)

**eshost Output:**

```
$ eshost -s -x "const it = 'A'.matchAll(/B/g); const r = it.next(); print(r.done); print(r.value)"
#### JavaScriptCore, SpiderMonkey, V8, V8 --harmony, XS
true
undefined
```

**Comment by ljharb** [comment]
In the case where done is true, the value should be ignored, so i think we just need to tweak the description and remove the last clause.
