### ISSUE TITLE
<dfn> IteratorResult object

### ISSUE THREAD

**Issue by michaelficarra** [tc39/ecma262#3426]
We use IteratorResult object as if it's a defined term but I was surprised to learn that it doesn't actually have a `<dfn>`. We also have some references to it as "the IteratorResult interface", including [the place where I think it should be defined](https://tc39.es/ecma262/#sec-iteratorresult-interface). We should add the `<dfn>` and replace the "interface" references.

**Comment by jmdyck** [comment]
I agree to linking back to the definition, but why replace the "interface" references? Are you saying it shouldn't be an interface?

What about the other iteration interfaces? Note that most of them also have corresponding occurrences of "a /Foo/ object". Should the spec drop the idea of interfaces altogether?

**Comment by michaelficarra** [comment]
I think any definition of an "X object" is a description of its interface. I don't see a reason to use the term "X interface" instead of just saying "X objects".

**Comment by bakkot** [comment]
Saying something is a Proxy object does not just describe its interface.

**Comment by michaelficarra** [comment]
When it's defined by its interface (as with IteratorResult), yes it does.

**Comment by jmdyck** [comment]
When describing exotic objects, "an X object" means an object whose *internal methods* conform to the requirements specified for X objects. But when Y is an interface name, "a Y object" means an object that has *properties* that conform to the interface definition.

While you can define things that way, I wonder if it's confusing for readers (and if leaning into the latter usage would make things more confusing).
