### ISSUE TITLE
dynamic import does not allow internal module naming in the ECMAScript module system as importmap does

### ISSUE THREAD

**Issue by andrewhodel** [tc39/ecma262#3430]
It is possible to assign module names that other modules can use with `importmap`, however `importmap` cannot provide certainty of loading.

```js
<script type="importmap">
  {
    "imports": {
      "three": "https://cdn.jsdelivr.net/npm/three@<version>/build/three.module.js",
      "three/addons/": "https://cdn.jsdelivr.net/npm/three@<version>/examples/jsm/"
    }
  }
</script>
```

`import()` as dynamic importing does not.

```js
import('/three.module.js').then(function(fulfillment) {

	// set the name in the global namespace
	window['THREE'] = fulfillment;

        // there is no way to access the ECMAScript name three (this fails with 'three' not available in ECMAScript module system)
        // the module in OrbitControls.js has `import three` in it's source code.  (hear declare here often)
        import { OrbitControls } from 'three/addons/controls/OrbitControls.js';

}, function(rejection) {

	// this is a load error
	console.log('import() rejection', rejection);

});
```

# Summary
ECMAScript dynamic module import() does not allow internal naming of the module.

**Comment by andrewhodel** [comment]
@bakkot I disagree with the proposal process because it is similar to implementing floating point numbers in a library and submitting a report that explains the problem is that floating point numbers in a library are supposed to have support of basic mathematics.

There's no reason that the dynamic import function should lack internal module naming.  It should always be a part of it because it's required by the module system (ECMAScript module).

**Comment by bakkot** [comment]
I appreciate your frustration, but this is not in fact a fundamental part of a module system. Indeed few if any common programming languages expose such a mechanism, and they, like the module system in JavaScript, enjoy widespread use among and utility for programmers. This need for this kind of virtualization is fairly niche. However, it is being explored; I encourage you to take a look at the proposal I linked above, which would let you evaluate a module in a context where you can hook its imports and fulfill them yourself, just as you seem to want.
