### ISSUE TITLE
importmap should have extra events

### ISSUE THREAD

**Issue by andrewhodel** [tc39/ecma262#3431]
# dynamic import

If you use dynamic importing, there is no way to use the `importmap` and most importantly there is no way to set the ECMAScript module's special name that is only accessible inside the module system (lowercase three in this example).

# non dynamic import

1. If you use non dynamic importing, for example `import * as THREE from 'three';` there is no way to attach an error or a load event.

2. You cannot attach the events to the module name (THREE in this example) that is created with `import * as THREE from 'three';` because the load process happens without a call to `send()` that would allow you to attach event listeners (similar to `XHR`).

**You need to use non dynamic importing to be able to set the ECMAScript module's special name because other modules use that name internally, that (1 & 2) is why the `importmap` needs to provide these events.**

# how

Each resource that the `importmap` requests needs an `error` event and a `load` event.

That means that there needs to be a `importmapResourceError` and a `importmapResourceLoad` event that is specific to `script` elements that are `importmap`.

Those events should have:

1. The ECMAScript module system special name of the module that the `importmap` imported or attempted to import.
2. The path of the script that the `importmap` imported or attempted to import.

The `importmapResourceError` event should block next attempt requests until a return happens within the event to preserve existing `importmap` functionality and allow a `cancel` return value that prevents automatic retries that are currently undocumented.  The `object` passed as the first argument to the event must have a retry function that can be used after `cancel` is returned.

```js
<script id="myimportmap" type="importmap">
  {
    "imports": {
      "square": "./module/shapes/square.js",
      "circle": "https://example.com/shapes/circle.js"
    }
  }
</script>
<script type="text/javascript">
var myimportmap = document.getElementById('myimportmap');

// you can easily use an object here to track the number of retries of each module
var retry_count = 0;
myimportmap.addEventListener('importmapResourceError', function(e) {

  console.log(e.module, e.src, 'had an error loading', e);

  // try 10 times
  if (retry_count < 10) {
    // try again in 5 seconds
    setTimeout(function() {
      this.importmapResourceErrorObject.retry();
    }.bind({importmapResourceErrorObject: e}), 5000);
    retry_count++;
  }

  // return true to cancel
  return true;

});
</script>
```

As it stands now with no documented number of retries or time between each retry is unacceptable.

**Comment by bakkot** [comment]
Import maps are not part of ECMAScript. You want HTML, either [the spec itself](https://github.com/whatwg/html/) or [the import maps community group](https://github.com/WICG/import-maps).
