### ISSUE TITLE
dynamic import with import() lacks subresource integrity

### ISSUE THREAD

**Issue by andrewhodel** [tc39/ecma262#3432]
Dynamic import with `import()` lacks subresource integrity.

**Comment by bakkot** [comment]
Subresource integrity is not a part of ECMAScript at all. The relevant specification is [here](https://github.com/w3c/webappsec-subresource-integrity) although it is also partially defined in HTML, and in fact HTML [did recently add support for SRI for modules](https://github.com/whatwg/html/pull/10269), including dynamically imported modules, via import maps.
