### ISSUE TITLE
Too sparse production-rules for AssignmentExpression?

### ISSUE THREAD

**Issue by 1UnitedPower** [tc39/ecma262#344]
Hi everybody,
i just tried to derive the simple expression `(x => x)` from EcmaScript2015/16 syntax rules, what i thought should be an easy excercise. There is also a [test case](https://github.com/tc39/test262/blob/master/test/language/expressions/arrow-function/syntax/arrowparameters-bindingidentifier-concisebody-assignmentexpression.js#L13) that covers a similar construct. However, if i'm not overseeing something crucial, then i must conclude that these expressions cannot be derieved from the official production rules. So, here is my naive approach:

```
PrimaryExpression →
CoverParenthesizedExpressionAndArrowParameterList →
(Expression) →
(AssignmentExpression) →
(ArrowFunction) →
(ArrowParameters => ConciseBody) →
(ArrowParameters => AssignmentExpression) → ???
```

The problem here is that i cannot derive an *IdentifierReference* from an *AssignmentExpression*. The only production rules i could take from here, are:

```
AssignmentExpression[In, Yield]:
  ConditionalExpression[?In, ?Yield]
  [+Yield]YieldExpression[?In]
  ArrowFunction[?In, ?Yield]
  LeftHandSideExpression[?Yield] = AssignmentExpression[?In, ?Yield]
  LeftHandSideExpression[?Yield] AssignmentOperator AssignmentExpression[?In, ?Yield]
```

I'm filing this here, becuase i think that this dilemma has even more implications. For example, even `x = 42` is not a valid *AssignmentExpression*, which does'nt seem to capture the correct idea.

**Comment by zenparsing** [comment]
Looks like the rule `PostfixExpression : LeftHandSideExpression` is missing from the grammar summary section.  Is this a problem with emu-prodref?

**Comment by zenparsing** [comment]
Same issue for YieldExpression in the grammar summary.  It's linking to the first occurrence of YieldExpression which happens to be in the "restricted grammar rules" section (and where it's only showing the NLTH rules).

**Comment by 1UnitedPower** [comment]
Indeed, with `PostfixExpression : LeftHandSideExpression` it becomes possible to derive `(x => x)` with the following sequence:

```
PrimaryExpression →
CoverParenthesizedExpressionAndArrowParameterList →
(Expression) →
(AssignmentExpression) →
(ArrowFunction) →
(ArrowParameters => ConciseBody) →
(ArrowParameters => AssignmentExpression)  →
(ArrowParameters => ConditionalExpression)  →
(ArrowParameters => LogicalORExpression)  →
(ArrowParameters => LogicalANDExpression) →
(ArrowParameters => BitwiseORExpression) →
(ArrowParameters => BitwiseXORExpression) →
(ArrowParameters => BitwiseANDExpression) →
(ArrowParameters => EqualityExpression) →
(ArrowParameters => RelationalExpression) →
(ArrowParameters => ShiftExpression) →
(ArrowParameters => AdditiveExpression) →
(ArrowParameters => MultiplicativeExpression) →
(ArrowParameters => UnaryExpression) →
(ArrowParameters => PostfixExpression) →
(ArrowParameters => LeftHandSideExpression) →
(ArrowParameters => NewExpression) →
(ArrowParameters => MemberExpression) →
(ArrowParameters => PrimaryExpression) →
(ArrowParameters => IdentifierReference) →
(ArrowParameters => Identifier) →
(ArrowParameters => IdentifierName) →
(ArrowParameters => IdentifierStart) →
(ArrowParameters => UnicodeIDStart) →
(ArrowParameters => x) →
(BindingIdentifier => x) →
(Identifier => x) →
(IdentifierName => x) →
(IdentifierStart => x) →
(UnicodeIDStart => x) →
(x => x)
```

Awkwardly verbose, but it works.
Thanks @zenparsing
