### ISSUE TITLE
RS: CompileAtom for Atom :: `.` should not call the AllCharacters AO

### ISSUE THREAD

**Issue by JLHwung** [tc39/ecma262#3442]
Here is the current `CompileAtom` algorithm for the `Atom:: .` production:

[Atom](https://tc39.es/ecma262/#prod-Atom) :: .
1. Let A be [AllCharacters](https://tc39.es/ecma262/#sec-allcharacters)(rer).
2. If rer.[[DotAll]] is not true, then
   a. Remove from A all characters corresponding to a code point on the right-hand side of the [LineTerminator](https://tc39.es/ecma262/#prod-LineTerminator) production.
3. Return [CharacterSetMatcher](https://tc39.es/ecma262/#sec-runtime-semantics-charactersetmatcher-abstract-operation)(rer, A, false, direction).

Here is the current [`AllCharacters` algorithm](https://tc39.es/ecma262/#sec-allcharacters):

1. If rer.[[UnicodeSets]] is true and rer.[[IgnoreCase]] is true, then
   a. Return the [CharSet](https://tc39.es/ecma262/#pattern-charset) containing all Unicode code points c that do not have a [Simple Case Folding](https://www.unicode.org/reports/tr44/#Simple_Case_Folding) mapping (that is, [scf](https://tc39.es/ecma262/#eqn-scf)(c)=c).
2. Else if [HasEitherUnicodeFlag](https://tc39.es/ecma262/#sec-runtime-semantics-haseitherunicodeflag-abstract-operation)(rer) is true, then
   a. Return the [CharSet](https://tc39.es/ecma262/#pattern-charset) containing all code point values.
3. Else,
   a. Return the [CharSet](https://tc39.es/ecma262/#pattern-charset) containing all code unit values.

According to this AO, the regex `/./iv` should not match (a U+0061 LATIN SMALL LETTER A) which has a simple case folding mapping to (A U+0041 LATIN CAPITAL LETTER A) . I believe this change is not intended, and none of popular browsers actually follows that.

```js
// Safari 18: true
// Firefox 131: true
// Chrome 126: true
/./iv.test("a")
```

This change was introduced in https://github.com/tc39/ecma262/pull/2418/files#diff-181371b08d71216599b0acccbaabd03c306da6de142ea6275c2135810999805aR36349, to fix this we can revert "Let _A_ be AllCharacters(_rer_)." to "Let _A_ be the CharSet of all characters."

**Comment by bakkot** [comment]
Thanks for the report. However, I don't think there's an issue here: `CharacterSetMatcher` step 2.k. will call [Canonicalize](https://tc39.es/ecma262/multipage/text-processing.html#sec-runtime-semantics-canonicalize-ch), which will map the input character `"a"` to `"A"` in step 1.a, which will then be in the `CharSet` returned by `AllCharacters`. Right?

**Comment by JLHwung** [comment]
In step 1 of AllCharacters AO:

> If rer.[[UnicodeSets]] is true and rer.[[IgnoreCase]] is true, then
a. Return the [CharSet](https://tc39.es/ecma262/#pattern-charset) containing all Unicode code points c that do not have a [Simple Case Folding](https://www.unicode.org/reports/tr44/#Simple_Case_Folding) mapping (that is, [scf](https://tc39.es/ecma262/#eqn-scf)(c)=c).

IIRC this effectively excludes both `a` and `A` from the `AllCharacters` results when both UnicodeSets and IgnoreCase is true, because they _have_ simple case folding. The intention of the `AllCharacters` AO is to generate a universal set for computing the complement of a given class set, but I don't think it is correct to interpret the dot here.

**Comment by JLHwung** [comment]
Oh I see. So the simple case folding here actually means those characters in https://www.unicode.org/Public/UCD/latest/ucd/CaseFolding.txt with the status `S` right? I was confused by the usage note "A. To do a simple case folding, use the mappings with status C + S." in that file.

As of Unicode 16 there are only 31 characters with the `S` status in `CaseFolding.txt`, and the current spec should be correct as long as the `S` mapping does not map one character to another character that also has the `S` mapping.

**Comment by JLHwung** [comment]
Closing this issue as apparently I misread the format of CaseFolding.txt, which maps capital letters to lowercase letters but not the otherwise. In the `/iv` mode, the AllCharacter AO returns all lowercase letters and other stuffs, it is okay because the [Canonicalize](https://tc39.es/ecma262/multipage/text-processing.html#sec-runtime-semantics-canonicalize-ch) step will map input `A` to `a`, which will match the `a` in the CharSet.
