### ISSUE TITLE
[quesion] Strange PerformanceObserver API Judgment of LCP Elements

### ISSUE THREAD

**Issue by electroluxcode** [tc39/ecma262#3449]
refer: https://codepen.io/yilaikesi/pen/VwobPJV

There are two elements on my interface.

One is logo.svg, and the parsing time is 300ms.
The other is a 4K image, and the parsing time is 1000ms.

As expected, when both are on the page, the largest contentful paint (LCP) should always be that 4K image.

However, in reality,

when I place the 4K image before the logo image, then the LCP is the 4K image.

When I place the 4K image after the logo image, then the LCP is the logo image.

This is not expectations

![Image](https://github.com/user-attachments/assets/3cdfa2dc-da60-45bf-84d8-2b4ea5e31cc3)
![Image](https://github.com/user-attachments/assets/3b25751b-09fc-4bc5-b830-640ccb3bdcd7)

**Comment by ljharb** [comment]
All of these things are part of the web, not part of the JS language.

**Comment by nicolo-ribaudo** [comment]
PerformanceObserver is defined by W3C at https://github.com/w3c/performance-timeline. You can try reaching out to them.
