### ISSUE TITLE
Missing second parameter in Object.getOwnPropertyDescriptor

### ISSUE THREAD

**Issue by sunkai9064** [tc39/ecma262#3465]
**Description:** The current specification converts the missing second parameter to "undefined" via ToPropertyKey.This also includes Objct.hasOwn and Reflect.getOwnPropertyDescriptor.I think the second parameter in these APIs has a clear meaning and should not be considered optional and have a default value of "undefined".
I don't understand why this is not an Early Error，And I believe that no code in the real world relies on this behavior.If anyone knows the reason for this design, please explain it, thank you!

**example:**
```
let target = {undefined:  "get it"}
let proxy = new Proxy(target, {
    getOwnPropertyDescriptor(target, key){
        console.log(key)                        // "undefined"
        return Reflect.getOwnPropertyDescriptor(target, key)
    }
})

Object.getOwnPropertyDescriptor(proxy)
// {value: 'get it', writable: true, enumerable: true, configurable: true}
```

**Comment by bakkot** [comment]
Almost everything in the language works like this. Historically the justification was that it was better to do _something_ rather than erroring out, because an error necessarily means the whole application stops working. The committee considers that to be a mistake and has decided to [stop coercing arguments](https://docs.google.com/presentation/d/1aumShXqYgQV38Bg_L3FfJvGKIupJVCxs_C-Iz3r_tRE/edit#slide=id.g106f4536d9_0_109) in the future, but we generally can't change existing APIs without breaking webpages, which we will not do.

> And I believe that no code in the real world relies on this behavior

Alas, this is far too optimistic. I am almost certain real code relies on this behavior. Consider, for example

```js
let keys = ['foo', 'bar'];
let obj = {};
for (let i = 0; i <= keys.length; ++i) { // note the accidental `<=` instead of `<`.
  if (Object.getOwnPropertyDescriptor(obj, keys[i])) console.log('found a key');
}
```

We have generally found [people will come to rely on almost any behavior](https://www.hyrumslaw.com/).

> why this is not an Early Error

Incidentally, you just mean "an error". Early Errors are specifically for illegal syntax which cannot be easily ruled out by the grammar.

**Comment by sunkai9064** [comment]
> Alas, this is far too optimistic. I am almost certain real code relies on this behavior. Consider, for example
> 
> let keys = ['foo', 'bar'];
> let obj = {};
> for (let i = 0; i <= keys.length; ++i) { // note the accidental `<=` instead of `<`.
>   if (Object.getOwnPropertyDescriptor(obj, keys[i])) console.log('found a key');
> }
> We have generally found [people will come to rely on almost any behavior](https://www.hyrumslaw.com/).
> 
Thanks for your answer. I understand what you mean by "better to do something rather than erroring out" and "implicit conversion is a feature of the language". But I think explicitly providing undefined is different from missing parameters. People may rely on operations like String() to get a value, but I don't think anyone would rely on Object.getOwnPropertyDescriptor with missing parameters to get undefined. If it is necessary for the two to be consistent, can the relevant instructions in the specification be improved? The current situation is that you have to go deeper to know clearly what is optional.

**Comment by sunkai9064** [comment]
> Alas, this is far too optimistic. I am almost certain real code relies on this behavior. Consider, for example
> 
> let keys = ['foo', 'bar'];
> let obj = {};
> for (let i = 0; i <= keys.length; ++i) { // note the accidental `<=` instead of `<`.
>   if (Object.getOwnPropertyDescriptor(obj, keys[i])) console.log('found a key');
> }
>

@bakkot Thanks for your answer. I understand what you mean by "better to do something rather than erroring out" and "implicit conversion is a feature of the language". But I think explicitly providing undefined is different from missing parameters. People may rely on operations like String() to get a value, but I don't think anyone would rely on Object.getOwnPropertyDescriptor with missing parameters to get undefined. If it is necessary for the two to be consistent, can the relevant instructions in the specification be improved? The current situation is that you have to go deeper to know clearly what is optional.

**Comment by bakkot** [comment]
> If it is necessary for the two to be consistent

There are a very few methods which distinguish between `undefined` and "not passed", but as a rule we avoid distinguishing between the two, yes.

> The current situation is that you have to go deeper to know clearly what is optional.

Optional parameters are denoted in the specification by `[` brackets `]` around the parameter. (See for example [`Array.from`](https://tc39.es/ecma262/multipage/indexed-collections.html#sec-array.from).) Not all methods throw when you omit an optional parameter, but there's no reason developers should be aware of that.

**Comment by michaelficarra** [comment]
@sunkai9064 Next time, please use [the discourse](https://es.discourse.group/) for these kinds of questions.

**Comment by sunkai9064** [comment]
> [@sunkai9064](https://github.com/sunkai9064) Next time, please use [the discourse](https://es.discourse.group/) for these kinds of questions.

OK, thanks
