### ISSUE TITLE
Why can the Linking stage be called several times without any problems?

### ISSUE THREAD

**Issue by dSalieri** [tc39/ecma262#3472]
[There is a paragraph in the specification](https://tc39.es/ecma262/multipage/ecmascript-language-scripts-and-modules.html#sec-example-cyclic-module-record-graphs), it is quite new, it appeared in ECMAScript 2023:

> The difference here between loading, linking and evaluation errors is due to the following characteristic:
>
> - [Evaluation](https://tc39.es/ecma262/multipage/syntax-directed-operations.html#sec-evaluation) must be only performed once, as it can cause side effects; it is thus important to remember whether evaluation has already been performed, even if unsuccessfully. (In the error case, it makes sense to also remember the exception because otherwise subsequent Evaluate() calls would have to synthesize a new one.)
> - Linking, on the other hand, is side-effect-free, and thus even if it fails, it can be retried at a later time with no issues.
> - Loading closely interacts with the [host](https://tc39.es/ecma262/multipage/overview.html#host), and it may be desirable for some of them to allow users to retry failed loads (for example, if the failure is caused by temporarily bad network conditions). 

I speak about the [Linking](https://tc39.es/ecma262/multipage/ecmascript-language-scripts-and-modules.html#sec-moduledeclarationlinking) stage, it says "side-effect-free" and that "it can be retried at a later time with no issues". 

And here the question arises: What will change from the first unsuccessful [Linking](https://tc39.es/ecma262/multipage/ecmascript-language-scripts-and-modules.html#sec-moduledeclarationlinking) attempt to the second?

As far as I know, these are binding resolution errors. If, say, there is no binding from the imported module, an error will be thrown. 

> i. Let resolution be importedModule.ResolveExport(in.[[ImportName]]).
> ii. If resolution is either null or ambiguous, throw a SyntaxError exception.

What is the point of retrying if the first time we got an error regarding binding resolution? The imported file does not change.

Is there something I don't understand? Please clarify this point because it is confusing.

P.S. Regarding the [Evaluation](https://tc39.es/ecma262/multipage/ecmascript-language-scripts-and-modules.html#sec-moduleevaluation) stage, everything is clear, it is allowed to be executed only once due to side-effects.

@guybedford could you help?

**Comment by nicolo-ribaudo** [comment]
That paragraph is about the internal behavior of those methods, rather than about how hosts are expected to interact with them.

Specifically, Evaluate() needs to cache it's result because evaluating twice would be observable since it runs user code. Link() on the other hand can run the full algorithm multiple times, since it will always return the same result with no side effects.

**Comment by dSalieri** [comment]
@nicolo-ribaudo Isn't it better to also cache the result as in the case of Evaluate() for Link()?

If we use a module that has an error at the Link() stage. It will be evaluated as many times as Link() is called. Does it make sense to make its result cacheable like Evaluate()?

Why waste resources and calculate an expectedly erroneous result many times?
