### ISSUE TITLE
Atomics.add / Atomics.sub does not check TypedArray

### ISSUE THREAD

**Issue by kimjg1119** [tc39/ecma262#3493]
In step 1 of the [Atomics.add](https://tc39.es/ecma262/multipage/structured-data.html#sec-atomics.add), `typedArray` seems to be an `ESValue` since there is no check such as `ValidateTypedArray` or something. Atomics.sub does the same. 

Unfortunately, typedArray is related to the memory model, and it is complex, and I cannot understand the details. However, it looks like a spec bug, and it is also related to #3486.

**Comment by anba** [comment]
This is a known spec bug -> #3117.

**Comment by kimjg1119** [comment]
> This is a known spec bug -> [#3117](https://github.com/tc39/ecma262/issues/3117).

Thanks!
