### ISSUE TITLE
[Discourse] Thoughts on JS0 and JSSugar

### ISSUE THREAD

**Issue by antonmak1** [tc39/ecma262#3510]
I feel a bit uneasy about the current trends that can be applied to JavaScript. Working on the benchmark, I see that the vector of ECMAScript development can go the way of lodash or jQuery. I don't like this at all, because it is clear how this "optimization" hits performance. Imagine if a lot of people just started using `forEach` instead of `for`, and then people would be given more functions like that, and then the applications would be even slower.

**Comment by ljharb** [comment]
This isn't the venue to discuss it - please see our actual [discourse](https://es.discourse.group) instead.

**Comment by antonmak1** [comment]
@ljharb Hello! Ok. It's just that when I clicked on the "Discourse" link, it said that the site was not found or something like that in the domain

**Comment by ljharb** [comment]
odd, it seems to work for me from the readme, the issue template popup, and the link i commented above.

**Comment by ljharb** [comment]
Makes sense, no worries :-)
