### ISSUE TITLE
NewPromiseCapability section has to be clear about GetCapabilitiesExecutor call

### ISSUE THREAD

**Issue by thefourtheye** [tc39/ecma262#355]
As it is, `NewPromiseCapability` section says

> Let _executor_ be a new built-in function object as defined in GetCapabilitiesExecutor Functions 

but the `GetCapabilitiesExecutor Functions` is defined as

> When a GetCapabilitiesExecutor function _F_ is called with arguments _resolve_ and _reject_ the following steps are taken:

So, it is not very clear what the functions passed to `GetCapabilitiesExecutor` from `NewPromiseCapability`.

Can someone please explain?

**Comment by zenparsing** [comment]
The purpose of GetCapabilitiesExecutor is to extract the resolve and reject functions from constructing a new promise and pack them into a PromiseCapability record.  Think of it like this:

```js
function makeGetCapabilitiesExecutor() {
    return function F(resolve, reject) {
        F._Capabilities.resolve = resolve;
        F._Capabilities.reject = reject;
    };
}
```
