### ISSUE TITLE
More Ordinary* abstract operations

### ISSUE THREAD

**Issue by annevk** [tc39/ecma262#357]
I created #356 which refactors some existing text in a way that seems more consistent with the OrdinaryHasProperty etc. precedent that was already set. However, I would also appreciate it if we could introduce OrdinaryGetPrototypeOf, OrdinaryDelete, and OrdinaryEnumerate for use in https://github.com/annevk/html-cross-origin-objects (which will be merged into the HTML standard in due course).

Would such a PR be accepted even though the restructuring is only for an external document?

**Comment by bterlson** [comment]
Mirroring my comment on #356, yep, this seems great! We should do it for all the slots!

**Comment by annevk** [comment]
Closing in favor of that PR.
