### ISSUE TITLE
Transcription issue in 12.1 identifier definition

### ISSUE THREAD

**Issue by littledan** [tc39/ecma262#358]
We seem to have lost the words "but not" in the ecmarkup for Identifier

http://tc39.github.io/ecma262/#sec-identifiers
http://www.ecma-international.org/ecma-262/6.0/#sec-identifiers

In the 2015 version, there's "IdentifierName but not ReservedWord", but in 2016, "IdentifierName ReservedWord". Thanks to @nickie for pointing this out

@bterlson

**Comment by michaelficarra** [comment]
Related to https://github.com/tc39/ecma262/issues/325?

**Comment by bterlson** [comment]
Yes very likely related. Will investigate. Have a few grammarkdown updates that need to get pushed through, this is either one of those or another one :-P Great find!

**Comment by bterlson** [comment]
Duping against #325.
