### ISSUE TITLE
What happened to the default operator and existential operator strawmans?

### ISSUE THREAD

**Issue by flying-sheep** [tc39/ecma262#359]
seen [here](http://wiki.ecmascript.org/doku.php?id=strawman:default_operator) and [here](http://wiki.ecmascript.org/doku.php?id=strawman:existential_operator), those are features many people switching from coffeescript are missing.

**Comment by zenparsing** [comment]
@flying-sheep es-discuss is the appropriate place for these kinds of questions.  See https://esdiscuss.org/topic/optional-chaining-aka-existential-operator-null-propagation for a recent proposal.

**Comment by flying-sheep** [comment]
ah, OK, so @claudepache will champion [es-optional-chaining](https://github.com/claudepache/es-optional-chaining) soon anyway

**Comment by claudepache** [comment]
> ah, OK, so @claudepache will champion es-optional-chaining soon anyway

Rather, I'm waiting for someone from TC39 to champion it.

**Comment by flying-sheep** [comment]
oh, then i didn’t read properly. in any case, this is an important proposal.

I’d also like to see `x ?= y`, but understand that this would be a different proposal
