### ISSUE TITLE
As-patterns

### ISSUE THREAD

**Issue by luciferous** [tc39/ecma262#375]
This has been discussed previously on es-discuss.[1] But that was some years ago, and from what I gathered, the consensus was that it's clearly useful, but not useful enough to be included at that point in time. I'm wondering if it's worth revisiting its usefulness again now.

The basic idea is to allow binding a name to the whole value being destructured, .e.g:

```javascript
var z@{x,y} = {x: 1, y: 2};
assertEquals(1, x);
assertEquals(2, y);
assertDeepEquals({x:1, y:2}, z);
```

We can refer to specifications of other languages (e.g. [Haskell Report 2010](https://www.haskell.org/definition/haskell2010.pdf)) for more formal semantics if that is useful in guiding the discussion.

[1]: https://mail.mozilla.org/pipermail/es-discuss/2012-April/022395.html

**Comment by domenic** [comment]
Closing per https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#feature-requests

**Comment by luciferous** [comment]
Not the friendliest way to have communicated that, but ok.

**Comment by michaelficarra** [comment]
@luciferous It's pretty rude to open an issue without reading the contribution guide and then complain that a contributor telling you that you've violated the contribution guidelines was not friendly enough. If you're so sensitive that every comment must be guarded with pleasantries in order to avoid hurting your feelings, you might not want to participate in professional discourse.

**Comment by luciferous** [comment]
@michaelficarra Sorry, I had to ask around to even get to this project. I didn't know about TC39. And, I opened an issue that was soliciting discussion. Yes, obviously I don't know what the process is and I was asking assistance so that I could contribute.

Right now your process makes this really difficult, and if you're simply closing issues from potential contributors asking for assistance, then maybe that's not the best way to welcome them.

**Comment by luciferous** [comment]
@michaelficarra I think you're missing my point if you think I'm asking for pleasantries. I thought we as a community had moved on from saying essentially RTFM to others in the community.

**Comment by domenic** [comment]
@luciferous please read ttps://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#feature-requests. Submitting a pull request is not an acceptable way to propose a feature.

**Comment by luciferous** [comment]
@domenic Thanks. It was previously discussed on es-discuss, I linked to this up top. Should I just create a new post on that mailing list, with essentially the same message?

**Comment by domenic** [comment]
@luciferous generally if no TC39 member on the mailing list has decided the original message was compelling enough to take it on as a proposal, that means the idea has no support and will not become a proposal. Bumping the message does not really increase your chances.

A pull request to the spec is the _last_ stage of the process, after you have a champion and they have turned it into a proposal and advanced it to stage 4 of the TC39 process. But if you can't get to stage 0, there's no point.

**Comment by domenic** [comment]
That said, I now realize the message you linked is several years old. Maybe bumping it is OK to see if new committee members who have joined since then have different opinions.

**Comment by bterlson** [comment]
Given that the last post on es-discuss was from 2012, it seems reasonable to bump it again I think.

**Comment by luciferous** [comment]
Yep, I can see how my creating an issue can be interpreted as subverting the process. But that assumes this process is clear to newcomers. Now, it's clear and I'll jump back to es-discuss and start form there. Thanks for clarifying, @domenic @bterlson.

**Comment by ljharb** [comment]
https://github.com/zkat/proposal-as-patterns may be relevant.
