### ISSUE TITLE
PropertyName doesn't inherit Yield in AssignmentProperty

### ISSUE THREAD

**Issue by jmdyck** [tc39/ecma262#388]
(Following up on https://github.com/tc39/ecma262/issues/374#issue-131910337 ...)

In the production
```
    AssignmentProperty[Yield] : PropertyName `:` AssignmentElement[?Yield]
```
I'm wondering why `PropertyName` isn't `PropertyName[?Yield]`. Everywhere else that PropertyName appears, it inherits the setting of the Yield parameter.

I've looked at other places in the grammar where a nonterminal could inherit a parameter-setting but doesn't, and I could generally see why, but not in this case.

And I looked in test262 and didn't find a test that would distinguish the two possibilities.

So I'm thinking it's maybe a bug.

**Comment by littledan** [comment]
Generally properties can have any keyword name (e.g., return, throw, to take a couple examples used in primordials) so I think this is fine.

**Comment by michaelficarra** [comment]
@littledan `PropertyName` only has the `Yield` flag so it can pass it on to `ComputedPropertyName`. As you said, it doesn't matter for `LiteralPropertyName`, which doesn't even accept the flag.

I believe the grammar says

```js
function *g() {
  ({[yield]: x} = y);
}
```

would not be a valid program, but will become valid if this flag is added. :+1: This change sounds good.

**Comment by allenwb** [comment]
yup

looks likes like an oversight in the ES6 grammar.

**Comment by littledan** [comment]
Oh I see, my mistake.
