### ISSUE TITLE
Typo: "must be true so, let" should be "must be true, so let"

### ISSUE THREAD

**Issue by domenic** [tc39/ecma262#389]
> Otherwise, IsAccessorDescriptor(desc) must be true so, let getter be desc.[[Get]].

**Comment by ljharb** [comment]
I'd go with "must be true, so, let" since the "let …" is a separately emphasized clause ¯\_(ツ)_/¯ :bike::house:

**Comment by zenparsing** [comment]
Or use assert. So many choices!

**Comment by annevk** [comment]
In HTML we went with "must be true, so let". Happy to provide a PR for ECMAScript if someone wants to call it.

**Comment by bterlson** [comment]
Let's just use assert rather than normalizing another convention.
