### ISSUE TITLE
NewPromiseCapability & GetCapabilitiesExecutor Functions

### ISSUE THREAD

**Issue by raulsebastianmihaila** [tc39/ecma262#392]
The way [GetCapabilitiesExecutor] (https://tc39.github.io/ecma262/#sec-getcapabilitiesexecutor-functions) is used in [NewPromiseCapability] (https://tc39.github.io/ecma262/#sec-newpromisecapability) doesn't make sense to me.

First, there are some resolve and reject functions that are set as properties of the [[Capability]] slot of the executor that results from the operation. However, these resolve and reject functions are not passed as arguments in NewPromiseCapability. And, even if they were, in step 5 of NewPromiseCapability, the value of the [[Capability]] slot of the executor is replaced with the promise capability that was created in NewPromiseCapability, whose resolve and reject functions are undefined.

On the readability side, I think it would be an improvement to make GetCapabilitiesExecutor look more like other abstract operations: GetCapabilitiesExecutor(resolve, reject). And make it return F (the executor) instead of undefined. And explicitly pass resolve and reject from NewPormiseCapability.

**Comment by thefourtheye** [comment]
Closely related to #355

**Comment by domenic** [comment]
And as before, people just seem confused. GetCapabilitiesExecutor is not an abstract operation.

**Comment by thefourtheye** [comment]
@domenic I believe that, it should be explained better in the spec. Every time I go through the spec I get confused at that point and looks like I am not the only one.

**Comment by raulsebastianmihaila** [comment]
I see now. I think the most confusing part is that the... section... is called GetCapabilitiesExecutor Functions. My mind was telling me that it was a getter that was supposed to create an executor. But it's not. The executor is never created, it just is.

**Comment by domenic** [comment]
It's created in step 4 of NewPromiseCapability.

**Comment by raulsebastianmihaila** [comment]
Yep, but not in GetCapabilitiesExecutor, as the name suggests.

**Comment by domenic** [comment]
Maybe it would be clearer if you thought of it as "ExecutorThatGetsCapabilities"

**Comment by raulsebastianmihaila** [comment]
:+1:  Yep, it would be even clearer if it was named that way. :)

**Comment by bterlson** [comment]
I think it's fine as-is naming wise but would accept a PR for a informative note regarding the purpose of this function.

**Comment by rauschma** [comment]
A class diagram would also be helpful, to get an overview of the entities that are involved in this part of the spec (PromiseReaction Record, PromiseCapability Record, Promise Reject Function, Promise Resolve Function, CapabilitiesExecutor Function, PromiseReactionJob,  PromiseResolveThenableJob, Promise).
