### ISSUE TITLE
Make Realm's field records start with an uppercase code point

### ISSUE THREAD

**Issue by annevk** [tc39/ecma262#393]
It seems in general field records start with an uppercase code point. Therefore it should probably be [[GlobalObject]] and such.

**Comment by jmdyck** [comment]
The spec is split on this matter.

In the following record-types, each field name starts with a lowercase letter:
    Completion (type, value, target)
    Iterator (iterator, done)
    Realm (intrinsics, globalObject, globalEnv, templateMap)
    TemplateMap entry (strings, array)
    Method definition (key, closure)
    GlobalSymbolRegistry (key, symbol)

And in these, it's uppercase:
    PropertyDescriptor
    PendingJob
    Script
    Module
    Source Text Module
    ImportEntry
    ExportEntry
    PromiseCapability
    PromiseReaction

In Function Environment Record, it's mixed.

If we're going for consistency, I think I'd prefer lowercase, because then field names would be lexically distinct from internal slot names (modulo [[name]] and [[env]] of ArgGetter and ArgSetter).

**Comment by annevk** [comment]
Can we change [[name]] and [[env]] to become [[Name]] and [[Env]] then? I would be okay with such a convention. @bterlson?

The reason I'm raising this by the way is https://github.com/whatwg/html/pull/638 where HTML introduces its own set of internal slots and fields. I suspect that eventually we'll revamp IDL and it'll become relevant there too.

**Comment by bterlson** [comment]
I'm not sure there's much value in having a lexical distinction between fields and slots. I'd be ok saying that anything inside double-brackets should start with uppercase, personally.

**Comment by littledan** [comment]
Another place this comes up is Intl, which uses lower-case.

**Comment by annevk** [comment]
@bterlson do you want a PR for starting all fields and slots with an uppercase code point?

**Comment by bterlson** [comment]
@annevk Yeah sure, if you'd like to put one together I'd take it! If we want a lexical distinction between slots and fields then we should come up with something other than [[ ]] for one or the other.
