### ISSUE TITLE
ArgumentList grammar production missing [Yield] parameter in grammar annex

### ISSUE THREAD

**Issue by ianwjhalliday** [tc39/ecma262#396]
The ArgumentList production in the grammar annex is missing the [Yield] parameter
https://tc39.github.io/ecma262/#sec-expressions

**Comment by jmdyck** [comment]
Yeah, it's using the "definition" in 5.1.5, so this is probably a side-effect of issue #365.

**Comment by jmdyck** [comment]
(So the annex A productions for VariableDeclaration, IterationStatement, StatementList, and ThrowStatement are similarly affected.)

**Comment by bterlson** [comment]
Duping in favor of #365.
