### ISSUE TITLE
Should arrow functions allow `yield` as identifier name in StrictFormalParameters?

### ISSUE THREAD

**Issue by ianwjhalliday** [tc39/ecma262#397]
Currently arrow functions pass along the Yield parameter to their parameter list grammar production, making yield a reserved word in that context.

However, function expressions do not pass the Yield parameter along to their FormalParameters production.

Corner case but seems an odd asymmetry.

**Comment by michaelficarra** [comment]
Currently, 14.2.1 defines an early error that disallows *YieldExpression*s in *ArrowParameters*.

> It is a Syntax Error if *ArrowParameters* Contains *YieldExpression* is **true**.

So the only difference this grammar change would make would be allowing `yield` used as an identifier in *ArrowParameters* (or conversely disallowing `yield` used as an identifier in *FormalParameters*, but that would be web incompatible). :+1: let's drop the flag from *ArrowParameters*.

**Comment by anba** [comment]
Even when [Yield] gets removed, `yield` still cannot be used as the name of an arrow function default parameter in a generator function context.
```js
function* g() {
  // Default parameters cannot be named "yield", because `yield = 0`
  // is initially parsed as an assignment expression.
  var f = (yield = 0) => {};
}
```

And removing [Yield] probably also complicates correctly reinterpreting CoverParenthesizedExpressionAndArrowParameterList as ArrowFormalParameters:
```js
function* g() {
  // Lexical token sequence for `yield/a/i` is `YIELD REGEXP`.
  // When CoverParenthesizedExpressionAndArrowParameterList is reinterpreted/reparsed
  // as ArrowFormalParameters, the lexer/parser is not allowed to change this to the
  // token sequence `YIELD DIV IDENT DIV IDENT`.
  var f = (p = yield/a/i) => {};
}
```

**Comment by ianwjhalliday** [comment]
@anba ah, there's the gotcha with arrow functions! Thanks for pointing that out.  I see the need for the asymmetry now.
