### ISSUE TITLE
Allow non-HTML-encoded entities

### ISSUE THREAD

**Issue by ljharb** [tc39/ecma262#404]
Things like `&lt;` would be much nicer to work with as `<` in `spec.html` - is this something ecmarkup/ecmarkdown could handle for us?

**Comment by bterlson** [comment]
Spec.html should be utf-8 encoded and html entities should only be used when needed. Eg. a < b should be fine, although I could be wrong about that. I plan on doing this work along with the big Ecmarkdown 3.0 conversion post-snapshot.

**Comment by ljharb** [comment]
awesome - we might want to set up a travis task to specifically lint for all the things we don't want included in spec.html - like html entities, or internal slots with non-uppercase code points, etc?

**Comment by bterlson** [comment]
Sure, I would love for npm test to actually do something useful ;)

**Comment by musgravejw** [comment]
Trying to follow up on this thread, would this issue require tests and/or a feature in ecmarkdown?

**Comment by ljharb** [comment]
Sure, but ecmarkup input isn’t valid html already :-)

**Comment by mathiasbynens** [comment]
Right. I was pointing out that the case for which ecmarkup doesn’t have to do anything special is `a > b` rather than `a < b`. (re: @bterlson’s comment)

**Comment by bakkot** [comment]
Per editor call today, now that we have an [auto-formatter](https://github.com/tc39/ecmarkup#formatter), we'll have the formatter translate from HTML entity style (which some people prefer to write) to actual code points (which most people prefer to read).

So the editorial convention will be that spec.html has actual code points (except for `&lt;` and `&amp;`), but people won't need to remember the rules (as long as they remember to `npm run format`).
