### ISSUE TITLE
Proposal: Symbol.breakLoop for exit from forEach loops

### ISSUE THREAD

**Issue by xlaywan** [tc39/ecma262#41]
Now there is no way to exit from forEach loops.
``` js
iterable.forEach(item => {
  if (item == 'what we need')
    return Symbol.breakLoop // loop breaks here
})
```
Traditional equivalent
``` js
for (let item of iterable) {
  if (item == 'what we need')
    break
}
```
Or just `Symbol.break`.

**Comment by herby** [comment]
What's wrong with using `.some` / `.every` and returning `return true` / `return false` to break out?

**Comment by xlaywan** [comment]
Oh, sure, forgot them) Issue can be closed.

**Comment by ljharb** [comment]
Also ES6's `Array#find` will return the item you're looking for, or `undefined`, stopping the iteration as soon as the predicate returns true.
