### ISSUE TITLE
Proposal: Array.prototype.feed

### ISSUE THREAD

**Issue by Youmoo** [tc39/ecma262#42]
Array has some methods which supports functional coding ,such as map,reduce..
Say I wanna do some transforming with an array and log the result :
```js
var result=[1,2,3].map(function(v){
	return v+1;
});
console.log(result);
```
It'll be better if we can log the result without declaring variable *result*
First I think about this:
```js
[1, 2, 3].map(function(v) {
	return v + 1;
}).some(function(v, i, a) {
	console.log(a);
	return true;
});
```
But this is aginst the purpose of `some`.
I need something like this:
```js
Array.prototype.feed = function(callback) {
	callback(this);
};
[1, 2, 3].map(function(v) {
	return v + 1;
}).feed(function(a) {
	console.log(a);
});
```
In practice, we often need map / filter / reduce arrays and deal with the result. So it'will be a pleasure if array has a *feed* method (more than a pleasure if Object.prototype also has *that*:) to support more functional programming

Sorry for my poor English, Hope I can be understood:)

**Comment by herby** [comment]
Very cryptically written. As I understand you want something like `in:` in Pharo Smalltalk. AFAICT this construct is not Array-specific, it is useful in any object, if it would be added. What complicates it, is if result is `null` or `undefined` (which is not a problem in "everything is an object" Smalltalk). BTW what's wrong with plain

```js
console.log([1,2,3].map(function(v){
    return v+1;
}));
```

except it is a bit awkward? In ES6, a more awkward

```js
((_=[1,2,3].map(function(v){
    return v+1;
})) => console.log(_))()
```

is probably possible as well.

**Comment by Youmoo** [comment]
@herby Thank you , your description is more clear :+1: 
Let everything in js has a `feed` method is all I want .

**Comment by michaelficarra** [comment]
```js
// with the proposed Object.prototype.feed
[1,2,3].map(function(v){ return v+1; }).feed(console.log.bind(console));
// or:
[1,2,3].map(function(v){ return v+1; }).feed(_ => console.log(_));
// without it:
console.log([1,2,3].map(function(v){ return v+1; }));
```

I can't see any justification for this.

**Comment by Youmoo** [comment]
@michaelficarra It will make a more fluent and chain-able (like jQuery method chaining)  programming experience.

**Comment by michaelficarra** [comment]
@Youmoo Libraries like underscore do this without extending `Object.prototype`:

```js
_([1,2,3]).map(function(v){ return v+1; }).feed(_ => console.log(_)).done();
```

**Comment by bterlson** [comment]
Closing this now. Proposals should have an identified champion and repository set up where work happens. This is not the place to brainstorm about proposals.
