### ISSUE TITLE
CloneArrayBuffer copies the underlying ArrayBuffer until the end, which callers don't need

### ISSUE THREAD

**Issue by littledan** [tc39/ecma262#447]
The TypedArray constructor includes a fast path for a TypedArray input (as opposed to treating it as an iterable), which has a fast path for the case of the same-type input and output. This calls CloneArrayBuffer. CloneArrayBuffer takes an argument for the start offset, but not for the end, so it copies the underlying ArrayBuffer until the end. Then, the caller sets the \[\[ArrayLength]] appropriately so that it gets the right length array. However, the underlying ArrayBuffer is still accessible through `get %TypedArray%.prototype.buffer`, so the extra unnecessary allocation is observable. Would it make sense to change the TypedArray constructor definition to not allocate and keep around this extra memory?

**Comment by littledan** [comment]
@allenwb @kmiller68 @leobalter  What do you think about this issue?

**Comment by leobalter** [comment]
> Would it make sense to change the TypedArray constructor definition to not allocate and keep around this extra memory?

Your commit (8a60672) seems interesting and helps looking through this issue.

Currently, it seems the new clone is limited to the expected src buffer bytelength as in steps 8 and 11 on CloneArrayBuffer, eliminating the excess from the offset.

```
8. Let targetBuffer be ? AllocateArrayBuffer(cloneConstructor, cloneLength).
```

On your changes, you also limit these changes to the bytelength of the typedArray, eliminating the remaining unused buffer bytelength after the typedArray bytelength is considered.

That seems reasonable and indeed might avoid extra memory use, especially in case you have a subarray sample.

**Comment by littledan** [comment]
@leobalter Exactly. To clarify from the spec text, see the way that cloneLength is calculated:

> 6 . Let _cloneLength_ be _srcLength_ - _srcByteOffset_.

The early end is not taken into account, only the offset.

**Comment by allenwb** [comment]
I agree, this is a bug.  The fast path should not produce a buffer with extra space.

Personally, I'd fix it by adding a cloneLength parameter to CloneArrayBuffer

**Comment by littledan** [comment]
@allenwb Good suggestion, especially seeing how @annevk pointed out HTML uses this operation in a way which would be unusable with the new definition. I wish we had multiple named optional arguments in ECMASpeak! I'll modify this patch for both of these concerns.

**Comment by littledan** [comment]
The new version is intended to address these concerns. Any thoughts? Thanks for the feedback.
