### ISSUE TITLE
Proposal request: ignored arguments

### ISSUE THREAD

**Issue by dbkaplun** [tc39/ecma262#454]
I'd like to gauge the feasibility of a new feature, akin to [ignored values in array destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Ignoring_some_returned_values):
```js
function ignoredArgument (foo,,baz) {
  return foo+baz;
}
console.log(ignoredArgument(1,2,3) === 4);
```

Which could replace this common idiom, alleviating the need for an unused variable:
```js
function ignoredArgument (foo,_,baz) {
  return foo+baz;
}
console.log(ignoredArgument(1,2,3) === 4);
```
Does this feature make sense? Am I missing anything?

See also: https://esdiscuss.org/topic/proposal-ignored-arguments

**Comment by UltCombo** [comment]
Please post these to the [ES Discuss mailing list](https://esdiscuss.org/). It is the proper place for this kind of discussion, and you will get a far broader audience.
