### ISSUE TITLE
Request: Basic lazy evaluation.

### ISSUE THREAD

**Issue by thomasfoster96** [tc39/ecma262#46]
*Sorry if this is the wrong place to post this (or if someone has already proposed it).*

Lately I've been writing quite a bit of code which needs some things to be lazily evaluated. So far I've just been using functions with empty parameters, but having lots of empty function parameters all over the place makes things unnecessarily verbose and hard to read. Some examples of where this might happen:

```javascript
// Logging a value after a specified amount of time.
setTimeout(function(){console.log("Ten seconds have passed")},10000);
setTimeout(()=>console.log("Ten seconds have passed"),10000);

// Generic library that lazily evaluates chained methods.
bigArray.map(x=x*2).filter(x=>x>10).sort((a,b)=>a-b).exec()
```

As you can see, a `function` expression with empty parameters has 10 unnecessary characters, while an arrow function with empty parameters has 4 unnecessary characters. 

My first thought was to wrap expressions to be lazily evaluated in backticks, but they are now used for template strings. Perhaps putting a `@` or a `#` before an expression wrapped in parentheses or statement wrapped in curly braces would be acceptable?

As for evaluating the expression/statement, I'd think that `expression()` would make sense. This would mean that if the chained methods example above was used, then the `.exec()` or `.done()` method could just be `()`. The examples above might then become:

```javascript
setTimeout(@(console.log("Ten seconds have passed"), 10000);

bigArray.map(x=x*2).filter(x=>x>10).sort((a,b)=>a-b)()
```

**Comment by bterlson** [comment]
Headless arrows, eg. `=> console.log("foo")`, might be good enough? They were considered for ES6 but were somewhat contentious.

**Comment by thomasfoster96** [comment]
They could work quite well. 

The `@` is probably a no go because of decorators.

**Comment by thejameskyle** [comment]
I spoke to @wycats awhile back about something along the lines of this:

```js
let arr = [1...10];
let result = arr.entries()->filter(isEven)->drop(2)->take(2);

console.log(result); 
```

> Note: The `->` is really just a placeholder for whatever the syntax might be.

Desugared:
```js
let arr = [1...10];
let iter = take(drop(filter(arr.entries(), isEven), 2), 2);
let result = [];

for (let entry of iter) {
  result.push(entry[1]);
}

console.log(result);
```

The methods would look like this:

```js
function* filter(iterator, callbackFn, thisArg) {
  let index = 0;
  for (let entry of iterator) {
    if (callbackFn.call(thisArg, entry[1], entry[0])) {
      yield [index++, entry[1]];
    }
  }
}
 
function* reject(iterator, callbackFn, thisArg) {
  let index = 0;
  for (let entry of iterator) {
    if (callbackFn.call(thisArg, entry[1], entry[0])) {
      yield [index++, entry[1]];
    }
  }
}
 
function* drop(iterator, n=1) {
  let index = 0;
  for (let entry of iterator) {
    if (entry[0] >= n) {
      yield [index++, entry[1]];
    }
  }
}
 
function* take(iterator, n=1) {
  let index = 0;
  for (let entry of iterator) {
    if (entry[0] < n) {
      yield [index++, entry[1]];
    }
  }
}
```

[Demo](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=function*%20filter(iterator%2C%20callbackFn%2C%20thisArg)%20%7B%0A%20%20let%20index%20%3D%200%3B%0A%20%20for%20(let%20entry%20of%20iterator)%20%7B%0A%20%20%20%20if%20(callbackFn.call(thisArg%2C%20entry%5B1%5D%2C%20entry%5B0%5D))%20%7B%0A%20%20%20%20%20%20yield%20%5Bindex%2B%2B%2C%20entry%5B1%5D%5D%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%20%0Afunction*%20reject(iterator%2C%20callbackFn%2C%20thisArg)%20%7B%0A%20%20let%20index%20%3D%200%3B%0A%20%20for%20(let%20entry%20of%20iterator)%20%7B%0A%20%20%20%20if%20(callbackFn.call(thisArg%2C%20entry%5B1%5D%2C%20entry%5B0%5D))%20%7B%0A%20%20%20%20%20%20yield%20%5Bindex%2B%2B%2C%20entry%5B1%5D%5D%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%20%0Afunction*%20drop(iterator%2C%20n%3D1)%20%7B%0A%20%20let%20index%20%3D%200%3B%0A%20%20for%20(let%20entry%20of%20iterator)%20%7B%0A%20%20%20%20if%20(entry%5B0%5D%20%3E%3D%20n)%20%7B%0A%20%20%20%20%20%20yield%20%5Bindex%2B%2B%2C%20entry%5B1%5D%5D%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%20%0Afunction*%20take(iterator%2C%20n%3D1)%20%7B%0A%20%20let%20index%20%3D%200%3B%0A%20%20for%20(let%20entry%20of%20iterator)%20%7B%0A%20%20%20%20if%20(entry%5B0%5D%20%3C%20n)%20%7B%0A%20%20%20%20%20%20yield%20%5Bindex%2B%2B%2C%20entry%5B1%5D%5D%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%0Alet%20arr%20%3D%20_.range(1%2C%2011)%3B%0Alet%20isEven%20%3D%20n%20%3D%3E%20n%20%25%202%20%3D%3D%3D%200%3B%0Alet%20iter%20%3D%20take(drop(filter(arr.entries()%2C%20isEven)%2C%202)%2C%202)%3B%0Alet%20result%20%3D%20%5B%5D%3B%0A%0Afor%20(let%20entry%20of%20iter)%20%7B%0A%20%20result.push(entry%5B1%5D)%3B%0A%7D%0A%0Aconsole.log(result)%3B%0A&playground=false)

**Comment by thomasfoster96** [comment]
@thejameskyle Yeah I don't think `->` would work as final syntax because AFAIK that's also the (unofficially?) proposed syntax for another type of arrow functions.

Though your example does cover something I hadn't thought about - adding lazy evaluation to existing methods.

**Comment by thejameskyle** [comment]
>  Yeah I don't think -> would work as final syntax because AFAIK that's also the (unofficially?) proposed syntax for another type of arrow functions.

Yeah like I said, just a placeholder instead of a `.`. I haven't seen any other proposals though, link?

>  Though your example does cover something I hadn't thought about - adding lazy evaluation to existing methods.

Yeah, and how to extend that, at first I was think of property lookups, however that's not really extensible without overriding prototypes.

```js
arr.entries()->filter() // Array.prototype.filter
// vs
function* filter() {}
arr.entries()->filter(isEven);
```

---

I was also thinking about the new [function bind](https://github.com/zenparsing/es-function-bind) proposal and wondering if lazy evaluation could be implemented for generators. /cc @zenparsing

```js
let arr = [1, 2];

arr.entries()::filter(a)::forEach(b)
// a(1), a(2), b(1), b(2)

arr.entries()::filterGenerator(a)::forEachGenerator(b)
// a(1), b(1), a(2), b(2)

arr.entries()::filterGenerator(a)::forEach(b)
// a(1), a(2), b(1), b(2)
```

**Comment by benjamingr** [comment]
@thejameskyle yes, lazy iteration over iterables is something that will probably be adopted, there are already libraries like lazy.js and kris kowal wrote a library that does this (with the iteration protocol) over 2 years ago (I think?) - nothing new about lazy sequences :)

**Comment by zloirock** [comment]
@thejameskyle https://github.com/rwaldron/tc39-notes/blob/master/es6/2014-11/nov-19.md#58-mapprototypemap-and-mapprototypefilter-spec--set

**Comment by thomasfoster96** [comment]
@thejameskyle Having had a second look at your use case, wouldn't it just be better to add `.filter`, `.map` and `.forEach` to generators? I think something similar is proposed for [Observable](https://github.com/zenparsing/es-observable#observable).

**Comment by bterlson** [comment]
Closing this issue now. Feature requests should be made on es-discuss.
