### ISSUE TITLE
Question: Intended semantics for setting lastIndex?

### ISSUE THREAD

**Issue by littledan** [tc39/ecma262#477]
In https://tc39.github.io/ecma262/#sec-regexpbuiltinexec step 12.a.iii, `lastIndex` is set to 0 regardless of whether _sticky_ or _global_ is true. However, in all other cases, `lastIndex` is only set when those flags are present. These semantics were a little surprising to me--were they intentional? I'm curious about the history. This came up for me in code review for implementing part of ES2017 semantics for RegExps https://codereview.chromium.org/1776883005 @allenwb @hashseed

**Comment by allenwb** [comment]
That's what ES3 and ES 5 did.  See:
[ES3](http://ecma-international.org/publications/files/ECMA-ST-ARCH/ECMA-262,%203rd%20edition,%20December%201999.pdf) 15.10.6.2 step 6 and [ES5.1 15.10.6.2](http://ecma-international.org/ecma-262/5.1/#sec-15.10.6) step 9.a.i

**Comment by domenic** [comment]
Duping to #625.
