### ISSUE TITLE
Spread operator within ternary operator

### ISSUE THREAD

**Issue by tresdin** [tc39/ecma262#478]
I think it would be nice to be able to use spread operator like this:
```
var x = [1,2];
var y = [];
y.push(x instanceof Array ? ...x : x);
```

**Comment by getify** [comment]
Feature proposal discussions belong on [es-discuss](https://mail.mozilla.org/listinfo/es-discuss).

**Comment by leobalter** [comment]
```js
var x = [1,2];
var y = [];
y.concat(x);
```

**Comment by topaxi** [comment]
See leobalters version, if your usecase needs `push` you can use:

```javascript
var x = [1,2];
var y = [];
y.push(...Array.isArray(x) ? x : [ x ]);
```

**Comment by tresdin** [comment]
@leobalter Very nice suggestion if I don't mind creating a new array.

**Comment by tresdin** [comment]
@topaxi It looks like a workaround rather than an official method for the case. Also, I personally think it's a bit less readable.

**Comment by bterlson** [comment]
Not the appropriate venue for this discussion.

**Comment by arielgee** [comment]
Excuse my necrophilia, but wouldn't that do the trick?:

`y.push(...(x instanceof Array ? x : [x]));`

**Comment by ljharb** [comment]
@arielgee that’s just a less robust, not-cross-realm form of https://github.com/tc39/ecma262/issues/478#issuecomment-197373487.

**Comment by KaKi87** [comment]
Hello there,

> Feature proposal discussions belong on [es-discuss](https://mail.mozilla.org/listinfo/es-discuss).

Did someone did it ?

Thanks

**Comment by SrBrahma** [comment]
Any updates?

**Comment by Glamurio** [comment]
I'll also ask again for this feature.

**Comment by getjiggy** [comment]
I am once again asking for this feature.
