### ISSUE TITLE
es 2017, the seventh edition

### ISSUE THREAD

**Issue by raulsebastianmihaila** [tc39/ecma262#483]
I see than the title in the draft was changed to Ecmascript 2017. Now the draft says that 'It is the eighth edition'. It should be the seventh, because es6 was the sixth, right? Also the scope of the document should be updated (https://tc39.github.io/ecma262/#sec-scope). It still has 2016 instead of 2017. 

Does this mean that there will be no standard released this year?

**Comment by rossberg-chromium** [comment]
es6 = es2015
es7 = es2016
es8 = es2017

The first has been released, the second is feature-frozen, we are now working on the third. So everything seems correct (except the year in the scope, as you point out).

**Comment by bterlson** [comment]
Edition numbers are confusing but they continue to exist along side the years. Sadly they are off by one from what you might expect.

I fixed sec-scope.

@raulsebastianmihaila you can see the rendering of the ES2016 draft here: https://tc39.github.io/ecma262/2016. It's built from the es-2016 branch.
