### ISSUE TITLE
Do expressions absent from proposals

### ISSUE THREAD

**Issue by matthewrobb** [tc39/ecma262#49]
Hey all, I was just doing some digging on `do expressions` and found: https://github.com/rwaldron/tc39-notes/blob/master/es6/2014-01/jan-29.md#conclusionresolution-2

> Conclusion/resolution
> * do-expressions as generailsation of block statements
> * Progresses do-expressions to the next state in the new process.

However I don't see them mentioned in the proposals table.

**Comment by sebmck** [comment]
They aren't an active proposal.

**Comment by arv** [comment]
@rossberg-chromium is planning to present this at TC39 in September.

**Comment by sebmck** [comment]
Fixed via 034d11ce5fab89d4f99376e6d40d5ceb63514386.
