### ISSUE TITLE
favicon gone missing

### ISSUE THREAD

**Issue by allenwb** [tc39/ecma262#491]
http://tc39.github.io/ecma262/ seems to have lost it's Ecma favicon.

(It actually might be wise to not use the official Ecma  favicon on drafts like this, but something to make it standout in a roll of tabs would be nice.)

**Comment by mathiasbynens** [comment]
<https://tc39.github.io/ecma262/> has `<link rel="icon" href="favicon.ico">` in its source but <https://tc39.github.io/ecma262/favicon.ico> seems to be missing, indeed.

**Comment by alrra** [comment]
> https://tc39.github.io/ecma262/ has <link rel="icon" href="favicon.ico"> in its source but https://tc39.github.io/ecma262/favicon.ico seems to be missing, indeed.

That's because the `favicon.ico` is now in the `img/` directory.

**Comment by alrra** [comment]
> The reference should be updated.

I've opened #493.
