### ISSUE TITLE
Unsure about ES6-super-construct=proposal.md

### ISSUE THREAD

**Issue by silkentrance** [tc39/ecma262#499]
@allenwb 

In https://github.com/tc39/ecma262/blob/master/workingdocs/ES6-super-construct%3Dproposal.md

it reads

> 12. If a class definition does not include an explicit constructor definition, it defaults to: 
> constructor(...args) {super(...args)}; if the class has a non-null extends clause. Otherwise it defaults > to: constructor() {};.

> - If you define a constructor body then you inherit both the constructor argument signature and body 
> from your superclass.

Should this not rather read

> - If a class definition does not include an explicit constructor definition, then it will inherit both the constructor definition's argument signature and body
> from its superclass.

instead?

**Comment by bterlson** [comment]
Working docs are super old. This should be correct in the main spec.
