### ISSUE TITLE
Throwing TypeErrors on access of RegExp.prototype flag properties breaks some websites

### ISSUE THREAD

**Issue by AnnotationMark** [tc39/ecma262#500]
The spec on the RegExp.prototype object states that it "is not a RegExp instance and does not have a [[RegExpMatcher]] internal slot or any of the other internal slots of RegExp instance objects" (see https://tc39.github.io/ecma262/2016/#sec-properties-of-the-regexp-prototype-object).

As a result, accessing flag properties (like "sticky") on an object should result in a TypeError being thrown according to the spec (see https://tc39.github.io/ecma262/2016/#sec-get-regexp.prototype.sticky).

This breaks websites that do feature testing by checking if the property is undefined.  For example, there is a JS library XRegExp (see http://xregexp.com) that extends the regexp implementation, and XRegExp does this form of feature testing (see https://github.com/slevithan/xregexp/blob/d0e665d4068cec4d15919215b098b2373f1f12e9/tests/perf/versions/xregexp-all-v2.0.0.js and https://github.com/slevithan/xregexp/blob/28a2b033c5951477bed8c7c867ddf7e89c431cd4/tests/perf/index.html).  As a result, websites that uses XRegExp can break (e.g. some Atlassian tools).

Checking for an undefined property is a common web idiom for feature testing.  In light of that, does it make sense for the spec to require that we throw a TypeError doing an undefined check on a RegExp.prototype flag property?

**Comment by AnnotationMark** [comment]
Oops.  Looks like this issue was already reported in https://github.com/tc39/ecma262/issues/262.  Sorry for the noise.

**Comment by littledan** [comment]
@AnnotationMark Are you seeing this error in any shipping browser? Maybe it'd be useful to forward the bug report to them. In #262 I explained the compatibility workarounds that I have put into Chrome.

**Comment by AnnotationMark** [comment]
@littledan I did not observe this in a shipping browser, but only while implementing the RegExp.prototype spec requirements in WebKit.

**Comment by domenic** [comment]
Looks like this was fixed by https://github.com/tc39/ecma262/pull/511.
