### ISSUE TITLE
String.prototype.trimStart/trimEnd (or trimLeft/trimRight)

### ISSUE THREAD

**Issue by evilpie** [tc39/ecma262#514]
I refreshed @sebmarkbage's trimLeft/trimRight proposal: https://evilpie.github.io/ecmascript-string-left-right-trim/. trimStart/trimEnd are now the canonical function objects, which matches the newly introduced padStart/padEnd functions. The old non-standard trimLeft/trimRight functions simply alias those. For posterity sake there is a tiny backwards compatibility issue, String.prototype.trimLeft.name would be "trimStart" instead of "trimLeft" as it is now. I don't expect this to cause any issues.

I wrote up two different proposal, one where trim/trimStart/trimEnd duplicate all of the (albeit very short) code and one where those functions call an abstract operation `TrimString`. I can't actually decide, which one I like more, but the later certainly follows DRY as noted by @ljharb.

This is stage 1 proposal at the moment, so I assume I need somebody to champion this?

**Comment by ljharb** [comment]
I think @sebmarkbage is still championing this proposal - if you can make a pull request into his proposal repository, that would be the best place to discuss it.

**Comment by evilpie** [comment]
This is now a pull request sebmarkbage/ecmascript-string-left-right-trim#6. We also settled on option 2.
