### ISSUE TITLE
new Promise without first argument

### ISSUE THREAD

**Issue by xlaywan** [tc39/ecma262#515]
Instead of:
``` js
let promise = new Promise((resolve, reject) => {
	if (true)
		resolve()
	else
		reject()
})
```
This
``` js
let promise = new Promise
if (true)
	promise.resolve()
else
	promise.reject()
```

Less nesting. What do you think?

**Comment by UltCombo** [comment]
That's called a deferred, and is a rather different concept. Any code that has access to the deferred object has full control over it and can resolve or reject it with any value, which is often considered insecure or undesirable.

In any case, this repository is not a place for such discussions. Please see the [CONTRIBUTING doc](https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#proposals) and post proposals to the [ES Discuss](https://esdiscuss.org/) mailing list.

**Comment by bterlson** [comment]
Yeah, it's a deferred. Oft-discussed possible addition, but not an alternative to what is presently spec'd.
