### ISSUE TITLE
Is there any proposes for better Symbol() syntax?

### ISSUE THREAD

**Issue by yisk** [tc39/ecma262#523]
Maybe we need some sugar for getting built-in symbols from Symbol? As the new methods added via symbols this can be useful.
```javascript
// now
new Array()[Symbol.iterator]
/foo/g[Symbol.match]

// sugar
new Array()::iterator
/foo/g::match

```

**Comment by claudepache** [comment]
The right place to have such a discussion is the es-discuss mailing list, not this repository. See [CONTRIBUTING.md#feature-requests](/tc39/ecma262/blob/master/CONTRIBUTING.md#feature-requests).
