### ISSUE TITLE
14.1.12 Static Semantics: IsFunctionDefinition

### ISSUE THREAD

**Issue by CountOrlok** [tc39/ecma262#536]
I think there is something missing in [IsFunctionDefinition](https://tc39.github.io/ecma262/#sec-function-definitions-static-semantics-isfunctiondefinition) at 14.1.12. The operation as described here will only return true if the given production is a _named_ function definition, but false for _anonymous_ function definitions.

Therefore when calling [IsAnonymousFunctionDefinition](https://tc39.github.io/ecma262/#sec-isanonymousfunctiondefinition) with argument _production_, the first algorithm step would always return false for anonymous function expressions and the operation [HasName](https://tc39.github.io/ecma262/#sec-function-definitions-static-semantics-hasname) would be unreachable.

So it rather should be:

**14.1.12 Static Semantics: IsFunctionDefinition**

FunctionExpression: function (FormalParameters) {FunctionBody}

FunctionExpression: function BindingIdentifier (FormalParameters) {FunctionBody}

Return true. 

[as in ES2015: [IsFunctionDefiniton](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-function-definitions-static-semantics-isfunctiondefinition)]

Or is there a reason for changing this?

**Comment by GeorgNeis** [comment]
I agree. (This also applies to classes and generator functions.)

**Comment by allenwb** [comment]
Right, as noted in the original issue,  this appears to be a regress from the original ES6. The bug also occurs in  [14.4.9](https://tc39.github.io/ecma262/#sec-generator-function-definitions-static-semantics-isfunctiondefinition) and [14.5.8](https://tc39.github.io/ecma262/#sec-class-definitions-static-semantics-isfunctiondefinition)
