### ISSUE TITLE
Proposal: Adjacent string literal concatenation

### ISSUE THREAD

**Issue by kentor** [tc39/ecma262#55]
This would be great when breaking up strings into multiple lines in the source code. It would save us from writing a `+` for every line break. This is a feature present in C, Python, and Ruby. It's most useful when your style guide enforces max characters per line and you want to keep a level of indentation.

Example:
```javascript
// gettext is used for translations
gettext('This is a string literal '
        'written in multiple lines');
```
should be transpiled to a single string.
```javascript
// gettext is used for translations
gettext('This is a string literal written in multiple lines');
```
Other thoughts:
- An indented template string introduces multiple spaces in between words and line feed characters.
- Stripping line feeds and multiple spaces is not entirely the point. Yes we can create a function that does that, but having the interpreter/compiler handle the concatenation should be more performant and the strings can be statically analyzed by tools (linting, makemessages)

**Comment by getify** [comment]
We already have that:

```js
gettext(`This is a string literal 
        written in multiple lines`);
```

See: [https://github.com/lukehoban/es6features#template-strings](Template Strings)

**Comment by michaelficarra** [comment]
Those are not the same thing, @getify. @kentor's proposal would be the same as

```js
// gettext is used for translations
gettext('This is a string literal ' +
        'written in multiple lines');
```

**Comment by shovon** [comment]
@getify also relevant: http://programmers.stackexchange.com/a/255021/17183

**Comment by kentor** [comment]
@getify @michaelficarra Right, if I were to indent the block containing the template string, I would add spaces in between `literal` and `written`.

I'm running my javascript through django's `makemessages` for translations, and it looks for strings in between `gettext`. If the spaces are introduced it will think the source string has changed. I'm concatenating using `+` for now to avoid the problem, but it would just be a nice feature not to have to do that.

Also this could perhaps be a performance boost depending on the environment/VM. I definitely see it being transpiled to a single string without using `+`.

**Comment by allenwb** [comment]
see https://esdiscuss.org/topic/multiline-template-strings-that-don-t-break-indentation

**Comment by shovon** [comment]
> Also this could perhaps be a performance boost depending on the environment/VM. I definitely see it being transpiled to a single string without using `+`.

Yeah, that's definitely a big win.

**Comment by pluma** [comment]
Here's the relevant part of the official Python reference: https://docs.python.org/3.4/reference/lexical_analysis.html#string-and-bytes-literals

Ditto for Ruby: http://ruby-doc.org/core-2.2.0/doc/syntax/literals_rdoc.html#label-Strings

**Comment by bterlson** [comment]
Closing this now. Proposals should have an identified champion and repository set up where work happens. This is not the place to brainstorm about proposals.
