### ISSUE TITLE
Provide an abstract operation for the latter part of OrdinarySet

### ISSUE THREAD

**Issue by Ms2ger** [tc39/ecma262#566]
WebIDL uses

>  Perform steps 3-11 of the default [[Set]] internal method ([ECMA-262], section 9.1.9). 

because it wants to replace the definition of *ownDesc*. It would be better to have an explicit operation for it to call.

**Comment by domenic** [comment]
I think it'd be best if Web IDL just copied the appropriate steps, actually. There's no clear factoring here. (Also, that is outdated, as there are only 9 steps in what is now called OrdinarySet.)

**Comment by annevk** [comment]
IDL should probably also be rewritten for this since it seems the complexity is only warranted for objects supporting indexed properties. Better to isolate those from the ordinary objects.

**Comment by bterlson** [comment]
Going to go with Domenic's recommendation :-P Feel free to re-open though!
