### ISSUE TITLE
Add property "original" to RegExp since property "source" is not clearly specified

### ISSUE THREAD

**Issue by matthewadams** [tc39/ecma262#577]
The output of `RegExp.source` changed on us.

When node@0.12.14 with v8@3.28.71.19 upgraded to node@4.0.0 with v8@4.5.103.30, the output of `RegExp.source` changed.  The data below from my tests show it clearly, which uses `new RegExp('/test').source`.
```
node        v8             new RegExp('/test').source
----------- -------------- -----------------------------------
v0.12.14    3.28.71.19     /test
v4.0.0      4.5.103.30     \/test
```
Beginning with node@4.0.0/v8@4.5.103.30, `RegExp.source` now escapes forward slashes, which broke one of our scripts.  With this change, there is no way to get the original string `s` given in `new RegExp(s)`.  This strikes me as a deficiency, for which I have two suggestions.

(1) ECMAScript to specify a new property `original` that would return the original string given to `new RegExp()`.  That way, `source` can keep returning whatever it wants to, which, currently, is an arbitrarily formatted string, provided that it behaves the same way as the original string when given to `new RegExp()`, and `original` would return the string originally given to `new RegExp()`.

(2) `source` could revert to the older v8 behavior, be specified to return the original string as given to `new RegExp()`, and a new `canonical` property could be added that clearly specifies how a `RegExp` should be formatted in a standard way.

I imagine it might be too late for (2), but, in either case, it would be nice if ECMAScript at least standardized `source` to return predictable values across implementations, as [discussed](https://mail.mozilla.org/pipermail/es-discuss/2013-March/029281.html) [previously](https://bugs.ecmascript.org/show_bug.cgi?id=1470).

**Comment by claudepache** [comment]
> (1) ECMAScript to specify a new property `original` that would return the original string given to `new RegExp()`. That way, `source` can keep returning whatever it wants to, which, currently, is an arbitrarily formatted string, provided that it behaves the same way as the original string when given to `new RegExp()`, and `original` would return the string originally given to `new RegExp()`.

See https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#feature-requests

> (2) `source` could revert to the older v8 behavior, be specified to return the original string as given o `new RegExp()`, and a new `canonical` property could be added that clearly specifies how a `RegExp` should be formatted in a standard way.

The change of behaviour of `RegExp('/test').source` in v8 was needed in order to conform to the spec since ES6. In previous versions, it was less tightly specified. See [RegExp.prototype.source](https://tc39.github.io/ecma262/#sec-get-regexp.prototype.source) last step and [EscapeRegExpPattern](https://tc39.github.io/ecma262/#sec-escaperegexppattern) step 2.

**Comment by claudepache** [comment]
> in order to conform to the spec since ES6

In fact, that behaviour (escaping `/`) [was already required in ES5.1](http://www.ecma-international.org/ecma-262/5.1/#sec-15.10.4.1).

**Comment by bterlson** [comment]
Closing this. If there's still an issue here please see CONTRIBUTING.md.
