### ISSUE TITLE
Ignoring arguments

### ISSUE THREAD

**Issue by caub** [tc39/ecma262#585]
Similarly to:

`var [,x,,y] = [1,2,3,4,5,6];`

I think it could be interesting to let a field empty in function arguments

`[1,2,3,4].map( (,i) => i )`, `Array.from({length:10}, (,i) => i )`

`function test(a,,b) { }`

(but that would alter the current parsing, that doesn't allow it)

Currently I often use `_` as a way to mark ignored fields, but when there are more than 1 you need another identifier. A standard way would be interesting rather

**Comment by domenic** [comment]
Closing per https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#feature-requests

**Comment by caub** [comment]
ok, thanks
