### ISSUE TITLE
Typo in Script Evaluation?

### ISSUE THREAD

**Issue by GeorgNeis** [tc39/ecma262#587]
In 15.1.10 (https://tc39.github.io/ecma262/#sec-runtime-semantics-scriptevaluation), 
the identifier `ScriptBody` comes out of nowhere. I suppose it should be replaced with `scriptRecord.[[ECMAScriptCode]]`.

**Comment by jmdyck** [comment]
ScriptEvaluation used to be a syntax-discriminated operation, whose only definition was attached to the production `Script : ScriptBody?`, so the reference to `|ScriptBody|` was well-defined. It looks like it became a dangling reference when ScriptEvaluation became an abstract operation (in 698819cb).
