### ISSUE TITLE
Semantics of ResolveExport for default exports

### ISSUE THREAD

**Issue by GeorgNeis** [tc39/ecma262#601]
If a module M does not provide a default export, then M.ResolveExport("default") throws a SyntaxError (see step 6 in [15.2.1.16.3](https://tc39.github.io/ecma262/#sec-resolveexport)).  For any other name that cannot be found, ResolveExport returns null instead.

Throwing a SyntaxError seems wrong, also because ResolveExport is being described as side-effect free elsewhere in the spec.

**Comment by allenwb** [comment]
Agreed,
Step 6.b should be `Return null`
