### ISSUE TITLE
Superfluous check in [[Get]] for Module Namespace Exotic Object?

### ISSUE THREAD

**Issue by GeorgNeis** [tc39/ecma262#602]
In [9.4.6.8](https://tc39.github.io/ecma262/#sec-module-namespace-exotic-objects-get-p-receiver), step 11 throws an exception if the module's environment is undefined.  How can this ever happen?  The environment is set in [15.2.1.16.4 ModuleDeclarationInstantiation](https://tc39.github.io/ecma262/#sec-moduledeclarationinstantiation) and never unset as far as I can tell.  I don't see how a namespace object's [[Get]] can be invoked without ModuleDeclarationInstantiation having happened before.

**Comment by allenwb** [comment]
The spec. allows an implementation to extend the language with additional kinds of modules. 15.2.1.16.4 only applies to Source Text Modules.  9.4.6.8 must work will all kinds of modules, including implementation provided kinds. Step 11 is there just in case the environment of such an extension module has not been set.
