### ISSUE TITLE
pdf export on the gh-pages branch?

### ISSUE THREAD

**Issue by Pomax** [tc39/ecma262#608]
I'd love to pour through the docs during train rides, flights etc. but wifi is most definitely not avaliable everywhere, and getting a git repo cloned onto an android device -while doable- is not the most useful. Would it be possible to have a pdf/epub/other formate single file download available in the gh-pages branch that makes the entire document available for offline consumption?

**Comment by UltCombo** [comment]
Or maybe add a service worker to make the site available offline. While at it, may as well comply with the remaining PWA requirements so Android users can add it to the home screen.

**Comment by littledan** [comment]
You can generate a PDF in your browser by using the "print to PDF" functionality.

**Comment by bterlson** [comment]
Yes, print to PDF works fine for these cases (it's exactly how the official PDF is produced). I imagine you could also just load the page in a tab and leave it open (since it's just one big static HTML file).

**Comment by Pomax** [comment]
Not every browser comes with the ability to print to pdf (From what I can tell, on Chrome offers that ability out of the box), but if that's how the official PDF is generated then that'll work fine.

As for leaving a tab open, that won't work quite as well as pdf exports, as mobile devices (certain Android devices) may try to reload webviews have been suspended, leading to a "no network" error page view instead of the page the user was originally viewing.

**Comment by michaelficarra** [comment]
@Pomax There shouldn't be anything stopping you from saving the web page and opening that in your mobile browser.

**Comment by Pomax** [comment]
of course not, but that's not exactly a nice reading experience compared to a pdf in a decent ebook reader on mobile. Anyway, "export to PDF" works, so I'll go with that.

**Comment by bterlson** [comment]
@Pomax FWIW, any browser (or other application) can print to PDF w/ Windows 10. I bring this up because it reminds me that the official PDF is produced this way because Chrome on other platforms doesn't seem to make the links work within the document.

**Comment by Pomax** [comment]
Kind of staying away from that until I literally have no other choice, but good to know, thanks!
