### ISSUE TITLE
`each` instead of `forEach`

### ISSUE THREAD

**Issue by zwhitchcox** [tc39/ecma262#613]
I'm not sure what the exact process is, but I hereby propose we create an alias, `each` for `forEach`.

This falls in line with the nomenclature of iterative Array prototype functions in javascript, e.g., `every`, `some`, `filter`, `reduce`, etc., of having one word to describe the loop. It creates cleaner code, is more precise, and just looks better. It's also a pain to have to write `forEach` rather than `each`, and, frankly, the other languages are laughing at us about this.

So, let's write some cleaner code with with `each` instead of `forEach`!

**Comment by domenic** [comment]
See https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md, which was linked in a big yellow warning at the top when you created this issue.

**Comment by zwhitchcox** [comment]
Umm, no it wasn't, but ok

**Comment by domenic** [comment]
![screenshot from 2016-06-17 12 57 06](https://cloud.githubusercontent.com/assets/617481/16148616/0d605c5c-348b-11e6-948d-2268e54a27ff.png)

**Comment by zwhitchcox** [comment]
Well, I didn't see it. And anyway, there's no link to submit a new proposal on that site.

**Comment by Lysande** [comment]
@zwhitchcox yes, there is: 
"Feature requests for future versions of ECMAScript should not be made in this repository. To make a feature request, post to the [es-discuss mailing list](https://esdiscuss.org/)."

"If you have a new proposal you want to get into the language, you first need a TC39 champion. Head to es-discuss to find one."

**Comment by zwhitchcox** [comment]
Ok, thank you, I have initiated the process to get that done.
