### ISSUE TITLE
Add clarification that StrictFormalParameters does not imply strict mode code

### ISSUE THREAD

**Issue by tcare** [tc39/ecma262#618]
I've seen a number of people confused that StrictFormalParameters does not imply strict mode code. I have definitely seen bugs introduced due to this confusion too, especially around non-simple parameter lists with opt-in behavior.

A while back on #jslang we spoke about perhaps renaming StrictFormalParameters to something more reflective of the nature of preventing duplicates. I would instead propose that we add a note to 14.1.1 (https://tc39.github.io/ecma262/#sec-directive-prologues-and-the-use-strict-directive) or 14.1.2 (https://tc39.github.io/ecma262/#sec-function-definitions-static-semantics-early-errors) that a StrictFormalParameters production in a non-strict context does not imply strict mode code rules.

**Comment by jmdyck** [comment]
See also https://bugs.ecmascript.org/show_bug.cgi?id=4152
