### ISSUE TITLE
add a colophon

### ISSUE THREAD

**Issue by michaelficarra** [tc39/ecma262#62]
A colophon describes the tools and resources used in the creation of a published work. Additionally, it may contain the authorship information such as who created the work, and when and where the work was created.

As an example, see [the colophon from Stephen Wolfram's _A New Kind of Science_](http://www.wolframscience.com/nksonline/page-1264?firstview=1).

**Comment by bterlson** [comment]
2 months later, I have proposed copy for a sub-intro clause:

<h1>About This Edition</h1>
<p>This edition is authored on <a href="https://github.com/tc39/ecma262">GitHub</a> with the help of many members of the ECMAScript community. The source format is an HTML dialect called <a href="https://github.com/bterlson/ecmarkup">Ecmarkup</a>. Ecmarkup provides a framework and toolset for authoring ECMAScript specifications that follow the <emu-xref href="#notational-conventions">established notational conventions</emu-xref> for this document. Ecmarkup builds on and integrates a number of other formats and technologies including <a href="https://github.com/rbuckton/grammarkdown">Grammarkdown</a> for defining syntax and <a href="https://github.com/domenic/ecmarkdown">Ecmarkdown</a> for authoring algorithm steps. Prior editions of this specification were authored using Word&emdash;the Ecmarkup source text that formed the basis of this edition was produced by converting the ECMAScript 2015 Word document to Ecmarkup using an <a href="https://github.com/jmdyck/es-spec-emu/">automated conversion tool</a>.</p>

<p>This rendering is produced by using the Ecmarkup toolchain to build the source Ecmarkup format into standard HTML, CSS, and ECMAScript for display in web browsers and printing to PDF or other mediums.</p>

**Comment by michaelficarra** [comment]
:+1: I like it, other than the sentence

>  Prior editions of this specification [...] an automated conversion tool.

The colophon should be about this particular instance of the work, not a history lesson.

**Comment by domenic** [comment]
In that case I think whatever you want to call what was added is strictly more interesting and useful than a colophon, so I would not change anything.
