### ISSUE TITLE
12.10.4 Runtime Semantics: InstanceofOperator

### ISSUE THREAD

**Issue by CountOrlok** [tc39/ecma262#622]
The note in [12.10.4](https://tc39.github.io/ecma262/#sec-instanceofoperator) begins with *Steps 5 and 6 provide compatibility...*, but there is no *Step 6* in the algorithm above, so I think it should better start with *Step 5 provides compatibility...*

**Comment by claudepache** [comment]
Fixed by https://github.com/tc39/ecma262/commit/9746dbf8092e34313a9fb1b5d304b0fd412238e7
