### ISSUE TITLE
spec.html: <title> is undefined

### ISSUE THREAD

**Issue by azu** [tc39/ecma262#63]
[spec.html](https://github.com/tc39/ecma262/blob/master/spec.html "spec.html") has not `<title>`.

![firefox developer edition 2015-09-23 13-18-26](https://cloud.githubusercontent.com/assets/19714/10037763/9c0de5d2-61f5-11e5-9827-b8209771659d.png)

- http://tc39.github.io/ecma262/

**Comment by domenic** [comment]
This seems fixed.

**Comment by azu** [comment]
Thanks.
