### ISSUE TITLE
Native classes inheritance

### ISSUE THREAD

**Issue by iliakan** [tc39/ecma262#631]
The class semantic assumes that for `class B extends A`:
```js
B.prototype.__proto__ === A.prototype // true (for method inheritance)
B.__proto__ === A // true (for static inheritance)
```

But for built-in classes only the 1st is true:
```js
Array.prototype.__proto__ === Object.prototype // true
```

The second is wrong: `Array.__proto__ !== Object`.

Was that discussed and left "as is" for backwards compatibility? That's inconsistent.

**Comment by domenic** [comment]
`class A` is different from `class A extends Object`.

**Comment by getify** [comment]
Yeah, isn't Array.__proto__ (and A.__proto__ by default) gonna be Function instead of Object?

**Comment by iliakan** [comment]
@domenic do I get it right that `Array` is meant to inherit from `Object`? Aren't they supposed to be native classes with inheritance?

**Comment by iliakan** [comment]
@domenic I mean, what you say is correct now, right, that's also what I write, but from OOP standpoint that looks strange, usually classes inherit from base Object.

**Comment by ljharb** [comment]
@iliakan a "class" produces a constructor function. Functions inherit from `Function`.

**Comment by domenic** [comment]
Array is not meant to inherit from Object. It is a built-in class without inheritance, just like `class A` is a non-built-in class without inheritance.
