### ISSUE TITLE
Is /l{   12 ,    }/ just as valid as /l{12,}/?

### ISSUE THREAD

**Issue by icefapper** [tc39/ecma262#639]
Hello
From what I understand from the spec, whitespace is significant in literals; which, to me, means
`QuantifierPrefix :: { DecimalDigits , DecimalDigits }` in RE's should accept `/l{12,}/` but not `/l{  12  ,  }/`; but that is not the behavior of Firefox, for example; it accepts either of the above. 

Has the insignificance of whitespace in an RE quantifier been mentioned in the spec? Or is Firefox actually wrong?

**Comment by claudepache** [comment]
Just tested in Firefox and Safari:

```js
/^a{1, }$/.exec('a') // null
/^a{1, }$/.exec('a{1, }') // ["a{1, }"]
```

I.e., `/^a{1, }$/` is treated the same way `/a\{1, \}/`. That semantics is already specced in Annex B (hint: [ExtendedPatternCharacter](https://tc39.github.io/ecma262/#prod-annexB-ExtendedPatternCharacter) does not exclude `{` nor `}`).

**Comment by icefapper** [comment]
@claudepache 
Thanks for the hint! Looks like it is as you say.

**Comment by icefapper** [comment]
@claudepache
Please correct me if I'm actually wrong: `/a{1, }/` is treated like `/a\{1, \}/` because `{1, }` fails to get parsed as an RE quantifier?

**Comment by claudepache** [comment]
@icefapper You're correct. Under the annex-B semantics, when parsing a RegExp pattern, the order under which the production alternatives are tried is significant.

**Comment by icefapper** [comment]
@claudepache Thanks!
I will leave this issue at your disposal; please close it whenver you find it appropriate.

**Comment by icefapper** [comment]
Also for the record, Chrome accepts `/[\w-e]/` even though I've not come across any matching production in the spec.
