### ISSUE TITLE
Add metadata block

### ISSUE THREAD

**Issue by bterlson** [tc39/ecma262#645]
Should have information on:
- Test262
- Where to report bugs
- Where to request features
- How to contact the editor
- Link to changelog?

**Comment by michaelficarra** [comment]
@bterlson This was the perfect opportunity to add a colophon (https://github.com/tc39/ecma262/issues/62).

**Comment by bterlson** [comment]
@michaelficarra incidentally, that one is next on my list! I was thinking another intro clause, but do you think the colophon content should go inside the metadata block?

**Comment by michaelficarra** [comment]
@bterlson In printed works, I believe the colophon is usually on the page which lists publisher and version information. I think the metadata block is our spec's analogue, so it probably belongs in there.

**Comment by littledan** [comment]
Excellent improvement!
