### ISSUE TITLE
Can we create a "web reality" label or similar?

### ISSUE THREAD

**Issue by domenic** [tc39/ecma262#648]
I spent some time today looking into obsoleting https://javascript.spec.whatwg.org/. At this point that document is empty, and I was proposing (in https://github.com/whatwg/javascript/issues/29#issuecomment-235800151) replacing it with a quick readme pointing to existing web reality-related proposals and open bugs. As part of that, it might be nice to have a dedicated "web reality" tag on this repo that we could link to. So far the bugs that have come up as an important part of web reality are #289 and #562. https://github.com/whatwg/javascript/issues/12 may deserve porting to this repo and lumping under that tag as well.

**Comment by bterlson** [comment]
https://github.com/tc39/ecma262/labels/web%20reality

**Comment by domenic** [comment]
Awesome, I went through and tagged everything open I could find.

**Comment by bterlson** [comment]
@Domenic very nice thank you!

**Comment by mathiasbynens** [comment]
Please tag these as well:

https://github.com/tc39/ecma262/issues/663
https://github.com/tc39/ecma262/issues/664
https://github.com/tc39/ecma262/issues/665

Thanks!
