### ISSUE TITLE
Terser arrow function + destructuring syntax - thoughts?

### ISSUE THREAD

**Issue by bcherny** [tc39/ecma262#653]
This is my first time posting here, and I'm not sure this is the right place to do it, but I was wondering what you guys think of making parens around destructured arrow function parameters optional. If this gets positive feedback, I can write up a proposal:

```js
// Today
let fn1 = _ => _ + 1
let fn2 = ({_}) => _ + 1
let fn3 = ([_]) => _ + 1

// Proposed (more uniform syntax)
let fn1 = _ => _ + 1
let fn2 = {_} => _ + 1
let fn3 = [_] => _ + 1
```

**Comment by ljharb** [comment]
How can a parser/engine know that those aren't an object literal, a block, or an array literal, without having to backtrack when it finds the "=>"?

**Comment by bcherny** [comment]
How does it know with the current syntax?

**Comment by michaelficarra** [comment]
> and I'm not sure this is the right place to do it

It is not the right place. From [CONTRIBUTING.md](https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md):

> #### Feature Requests
> 
> Feature requests for future versions of ECMAScript should not be made in this repository. To make a feature request, post to the [es-discuss mailing list](http://esdiscuss.org). Your goal will be to convince others that your proposal is a useful addition to the language and recruit TC39 members to help turn your request into a proposal and shepherd it into the language.

**Comment by bcherny** [comment]
@michaelficarra - Got it, will post on es-discuss instead.
