### ISSUE TITLE
https://tc39.github.io/ecma262/ is a broken link

### ISSUE THREAD

**Issue by jyasskin** [tc39/ecma262#655]
Something's wrong with the gh-pages branch: it only contains `img/` directories.

**Comment by bterlson** [comment]
looking into it... something broken with travis.

**Comment by bterlson** [comment]
It has been resurected. Actually a bug due to latest ecmarkup change. I did test with ecma262 so I'm not sure how this happened (possibly missteps during npm link?). Regardless, will be more careful in the future.

**Comment by caridy** [comment]
@bterlson I'm having the same issue in 402, for some reason the auto-deploy.sh is not generating the pages. Can you provide more details?

**Comment by bterlson** [comment]
@caridy what do the travis logs say? All I did was deploy a fix to ecmarkup (it was an issue with the emu-grammar change which presumably intl doesn't care about).
