### ISSUE TITLE
`String.prototype.trim{Start,Left}` & `String.prototype.trim{End,Right}`

### ISSUE THREAD

**Issue by mathiasbynens** [tc39/ecma262#663]
Proposal: https://github.com/sebmarkbage/ecmascript-string-left-right-trim by @sebmarkbage

Please tag this issue with the “web reality” label (because of `String.prototype.trimLeft` and `String.prototype.trimRight`). Thanks!

**Comment by domenic** [comment]
Let's leave this open until the proposal has been merged into the main spec, so that people looking at https://github.com/tc39/ecma262/labels/web%20reality can get a better view.

**Comment by ljharb** [comment]
Closed by #1275.
