### ISSUE TITLE
Remove arguments.caller from the spec

### ISSUE THREAD

**Issue by claudepache** [tc39/ecma262#670]
_**Note.** Not to be confused with `Function#caller`._

---

The spec acknowledges that `arguments.caller` “has historically been provided as an implementation-defined extension by some ECMAScript implementations”.

However, nowadays this historical wart is not found in any browser since long ago, e.g.:
* [removed from Mozilla before Firefox was born] (https://bugzilla.mozilla.org/show_bug.cgi?id=7224) ;
* [removed from IE9 Standards mode] (https://msdn.microsoft.com/en-US/library/gg622933(v=vs.85).aspx).

I think one can clean the spec by removing all special cases around `arguments.caller`. As far as I can see, the modifications would be:

* [9.4.4. Arguments Exotic Objects] (https://tc39.github.io/ecma262/#sec-arguments-exotic-objects), Note 3: remove the mention of "caller".

* [9.4.4.1 [[GetOwnProperty]] of Arguments objects] (https://tc39.github.io/ecma262/#sec-arguments-exotic-objects-getownproperty-p): remove step 7, that special-cases `"caller"`, together with the remark _”If an implementation does not provide a built-in caller property for argument exotic objects then step 7 of this algorithm must be skipped.”_

* [9.4.4.5 [[HasProperty]] of Arguments objects] (https://tc39.github.io/ecma262/#sec-arguments-exotic-objects-hasproperty), use the same implementation as ordinary objects, removing the `"caller"` special case and the remark ”_If an implementation does not provide a built-in caller property for argument exotic objects then step 2 of this algorithm must be skipped._”

* [9.4.4.7. CreateUnmappedArgumentsObject] (https://tc39.github.io/ecma262/#sec-createunmappedargumentsobject), remove step 9, that adds a "caller" poison-pill to unmapped arguments objects.

* [16.2 Forbidden Extensions] (https://tc39.github.io/ecma262/#sec-forbidden-extensions), add: _“Arguments objects, both mapped and unmapped, must not be created with an own property named `"caller"`.”_

* [Annex C The Strict Mode of ECMAScript] (https://tc39.github.io/ecma262/#sec-strict-mode-of-ecmascript), modify item: _“Arguments objects for strict functions define <del>non-configurable accessor properties named "caller" and "callee"</del> <ins>a non-configurable accessor property named "callee"</ins> which throw<ins>s</ins> a TypeError exception on access”_ — (Also, at the time of writing, backreference to section 9.2.7 is incorrect, it should be 9.4.4.7; was already reported in #572.)

Concretely, for the implementations not supporting the arguments.caller extension, the changes resume to removing the "caller" poison-pill from their unmapped Arguments objects.

**Comment by erights** [comment]
I just tested and am surprised to see that this is correct. Good riddance! Now that arguments.caller is totally and permanently dead, I agree we no longer need to guard against it. I support this removal.

**Comment by leobalter** [comment]
I'll add this to the agenda for the next meeting for the consensus formalities.

@claudepache do you want to prepare a PR for this? Otherwise I can do it, also checking test262.
