### ISSUE TITLE
Object.prototype.toString()

### ISSUE THREAD

**Issue by timurtu** [tc39/ecma262#671]
The toString function on objects should return a JSON.stringify of the object. 

const myObj = {a: 2}

console.log(myObj.toString()) // "[Object object]" // waste of time and energy ^

console.log(myObj.toString()) // "{ 'a': '2' }"
// useful information ^

**Comment by mathiasbynens** [comment]
This would break backwards compatibility.

**Comment by timurtu** [comment]
How?

**Comment by mathiasbynens** [comment]
Lots of existing code relies on `Object.prototype.toString.call(someObject)` returning `'[object Object]'`. It’s commonly used to detect whether a given value is an object.

https://github.com/search?l=javascript&q=toString.call+"%5Bobject+Object%5D"&ref=searchresults&type=Code

**Comment by timurtu** [comment]
Okay I see your point but look how much more common [this usage](https://github.com/search?utf8=%E2%9C%93&q=typeof+%22object%22&type=Code&ref=searchresults) is. Doesn't it make more sense to return a string of the object with the toString method rather than a constant string saying what type of thing it is?

**Comment by mathiasbynens** [comment]
It doesn’t matter if that makes more sense or not. We cannot break the web.

Anyway, this is not the place for such proposals. See <https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#proposals>.
