### ISSUE TITLE
Internal method invariants vague about exceptions

### ISSUE THREAD

**Issue by annevk** [tc39/ecma262#680]
A number of internal methods can throw per HTML, but https://tc39.github.io/ecma262/#sec-invariants-of-the-essential-internal-methods is not clear on whether that is allowed. (Despite it already being implicitly allowed, e.g., OrdinaryDelete invoking [[GetOwnProperty]] with a ? in front of it.)

This came up in https://github.com/whatwg/html/issues/1726 as cross-origin [[Delete]] always throws in implementations, even outside "strict mode", and therefore cannot simply return false.

**Comment by claudepache** [comment]
All internal methods may throw: that can happen notably, but not exclusively, when user-defined code is triggered and throws (Proxies, user-defined accessors, etc.). And https://tc39.github.io/ecma262/#sec-invariants-of-the-essential-internal-methods applies only when the internal method returns nonabruptly: maybe that should be said explicitly?

**Comment by annevk** [comment]
It would help me, I think I got myself confused a few times now reading that section.

**Comment by jmdyck** [comment]
(Just noticed this issue.) See #1537 for related discussion, and #1539 which should resolve @annevk's original concern.

**Comment by allenwb** [comment]
Note that [6.1.7.2](https://tc39.es/ecma262/#sec-object-internal-methods-and-internal-slots) says:

> An internal method implicitly returns a Completion Record, either a normal completion that wraps a value of the return type shown in its invocation pattern, or a throw completion.

**Comment by jmdyck** [comment]
(Yes, but also note that it didn't say that when @annevk opened this issue.)

**Comment by allenwb** [comment]
We ES6, at approximately the same place said:

> An internal method implicitly returns a Completion Record as described in 6.2.2. 

The explicit case would have been covered by being explicit.

**Comment by jmdyck** [comment]
Yup, and saying that it returns a Completion Record wasn't enough to answer the original question.

**Comment by annevk** [comment]
Thanks for fixing this @jmdyck!
