### ISSUE TITLE
"do{;}while(false)false" prohibited in spec but allowed in consensus reality

### ISSUE THREAD

**Issue by littledan** [tc39/ecma262#684]
This bug is following up on [an earlier bug in the old tracker](https://bugs.ecmascript.org/show_bug.cgi?id=8). I just checked, and the syntax is still allowed in Chrome and Firefox. Any thoughts on whether this should be standardized? I don't have any data on how often it's used, but it seems useful for minimizers. in V8, the syntax has been allowed since inception, with the following comment in the code from 2008:

>   // Allow do-statements to be terminated with and without
>   // semi-colons. This allows code such as 'do;while(0)return' to
>   // parse, which would not be the case if we had used the
>   // ExpectSemicolon() functionality here.

I think the grammar change would be as simple as leaving off the semicolon at the end of [IterationStatement](https://tc39.github.io/ecma262/#prod-IterationStatement). Thoughts? cc @erights who filed the original bug.

**Comment by bterlson** [comment]
FWIW it also parses in Chakra and JSC. But isn't this just ASI semantics? ASI calls out this case specifically in bullet 1.3 (https://tc39.github.io/ecma262/#sec-rules-of-automatic-semicolon-insertion).

**Comment by littledan** [comment]
Oh, my mistake, it's right there.

**Comment by erights** [comment]
Yup. I just checked https://es5.github.io/#x7.9.1 and this third bullet is new; presumably to close exactly this bug.

**Comment by allenwb** [comment]
Also see [Annex E](https://tc39.github.io/ecma262/#sec-additions-and-changes-that-introduce-incompatibilities-with-prior-editions) entry for 11.9.1.
