### ISSUE TITLE
Symbols on Module Namespace Exotic Objects

### ISSUE THREAD

**Issue by GeorgNeis** [tc39/ecma262#693]
Module Namespace Exotic Objects have [two (own) symbol properties](https://tc39.github.io/ecma262/#sec-module-namespace-objects).

[[[Get]]](https://tc39.github.io/ecma262/#sec-module-namespace-exotic-objects-get-p-receiver), [[GetOwnProperty]], and [[HasProperty]] for these have the ordinary semantics, but [[Delete]], [[Set]] and [[DefineProperty]] don't (e.g. [[DefineProperty]] always fails).  This seems inconsistent and I'm wondering if it is a bug.  (Also note that these symbols are set up as configurable).

**Comment by ajklein** [comment]
@bterlson Would love your input, it's hard to tell if this is a simple spec bug or if there's some deep intention in this inconsistency.

**Comment by bterlson** [comment]
Seems like an oversight to me. I could see the current design making sense if the symbols were non-configurable, but instead they are configurable but impossible to change given the implementations of [[Delete]], [[Set]], and [[DefineProperty]]. These should learn to delegate symbol keys to the ordinary variants.

**Comment by domenic** [comment]
I don't really have an opinion either way, but it seems like a plausible path is to just make the symbols non-configurable? It's a little strange that there would be two configurable properties on an object that otherwise acts somewhat "frozen".

**Comment by ajklein** [comment]
I was thinking that non-configurable would make more sense, too. Though if we do that I think we'd have to freeze the @@iterator method as well.
