### ISSUE TITLE
Array.prototype.values is not fully web compatible

### ISSUE THREAD

**Issue by evilpie** [tc39/ecma262#695]
Apparently "Microsoft Dynamics CRM 2011" breaks when Array.prototype.values exists. From what I understand Chrome landed Array#values at two different times and removed it again. Current Chrome versions don't have Array#values anymore ([issue 615873](https://bugs.chromium.org/p/chromium/issues/detail?id=615873)). This bug has been known since 2014 and there apparently is an update to that CRM software (http://www.crmanswers.net/2014/10/lookup-errors-with-google-chrome-38.html). I am looking into removing Array.prototype.values from Firefox stable again ([bug 1299593](https://bugzilla.mozilla.org/show_bug.cgi?id=1299593)). The Chrome issue claims Safari is shipping this feature already. To my knowledge we haven't heard from any other breakage, so I am still optimistic we can land this at some point.

**Comment by chicoxyzzy** [comment]
According to [compat-table's test](http://localhost:63342/compat-table/es6/#test-Array.prototype_methods_Array.prototype.values) Edge does have `Array.prototype.values` so seems like MS doesn't care about Dynamics CRM 2011. So I don't see any reason to remove this feature from Firefox stable

**Comment by bterlson** [comment]
@chicoxyzzy we have it shipped, yes. However it's possible we are somewhat saved by a GP setting that allows corps to direct users to IE11 for certain old intranet applications.

**Comment by claudepache** [comment]
@chicoxyzzy According to your compat-table, Edge has supported  Array#values() since its first release; so it's not as if it supported Dynamics CRM 2011 once, and later break it in an update like Firefox and Chrome.

**Comment by ljharb** [comment]
Chrome 66 in April, and [Firefox 60](https://www.fxsitecompat.com/en-CA/docs/2018/array-prototype-values-is-now-enabled-again/) in May, will both re-enable `Array.prototype.values`, at which point this can be closed.

**Comment by evilpie** [comment]
I guess we can close this now.  Discussing this with @gsathya he mentioned that they saw some minor breakage in Chrome, but don't plan on disabling it again. I didn't see any breakage with Firefox, so we don't have any plans for removing this either.
