### ISSUE TITLE
`arguments` ordinary vs exotic difference

### ISSUE THREAD

**Issue by isiahmeadows** [tc39/ecma262#696]
I'm guessing the builtin methods for `arguments` exotic objects [described here](https://tc39.github.io/ecma262/#sec-arguments-exotic-objects) don't apply to `arguments` ordinary objects, but it didn't seem very clear to me that the distinction was between strict `arguments` objects that were otherwise array-like ordinary objects and sloppy `arguments` exotic objects which have those builtin methods.

**Comment by allenwb** [comment]
> On Sep 23, 2016, at 2:46 PM, Isiah Meadows <notifications@github.com> wrote:
> 
> I'm guessing the builtin methods for arguments exotic objects described here <https://tc39.github.io/ecma262/#sec-arguments-exotic-objects> don't apply to arguments ordinary objects, but it didn't seem very clear to me that the distinction was between strict arguments objects that were otherwise array-like ordinary objects and sloppy arguments exotic objects which have those builtin methods.
> 
> 
You shouldn’t have to guess. The first paragraph of 9.4.4 says: “Depending upon the characteristics of the function definition, its arguments object is either an ordinary object or an arguments exotic object. “

9.4.4.7 and 9.4.4.8 respectively create the ordinary and exotic variants of argument objects.

**Comment by ljharb** [comment]
This seems answered; happy to reopen if not.
