### ISSUE TITLE
super in class extending null should disallow super call in constructor

### ISSUE THREAD

**Issue by bterlson** [tc39/ecma262#698]
It presently keys off of ClassHeritage being present but if it's present but null it should also be an early error. /cc @bmeck

**Comment by bterlson** [comment]
I'm also not entirely sure why we didn't make super in base class methods an early error (rather than a TypeError by way of MakeSuperPropertyReference). @allenwb thoughts?

**Comment by bakkot** [comment]
@bterlson, given that it works in object literals, it would be at least a little surprising if didn't work in base classes.

e.g.
```js
''+(new class {
  toString(){
    return 'my ' + super.toString();
  }
}); // "my [object Object]"
```

**Comment by bterlson** [comment]
@bakkot right, thanks!

So presumably we could make super in methods for `class extends null` an early error?

**Comment by bterlson** [comment]
@ajklein points out that [[HomeObject]]'s prototype is determined dynamically, so the prototype could change.

**Comment by bakkot** [comment]
Are we talking about the literal `null`, vs e.g. `class extends (()=>null)() {}`? Because as I understood it `ClassHeritage` could evaluate to `null` at runtime - but we can't have early errors for that.

**Comment by ljharb** [comment]
Thanks to @ajklein my understanding is now that if `[[HomeObject]]` ever became changeable, which was previously possible, that `extends X` could always change from `null` to non-null, so `super` access can't be an early error.

**Comment by bterlson** [comment]
@bakkot yeah you're right, early error is only possible with the `null` literal (unless we throw early-ish during CDE, but I wouldn't argue for that I guess).
