### ISSUE TITLE
Immutable Prototype Exotic Objects is underspecified

### ISSUE THREAD

**Issue by allenwb** [tc39/ecma262#705]
The [specification](https://tc39.github.io/ecma262/#sec-immutable-prototype-exotic-objects) for Immutable Prototype Exotic Objects is incomplete and does not fully follow the pattern used to specify other standard exotic objects.  Other than for [[GetPrototypeOf]], an implementer would have to guess at the intended definition of the essential internal methods.

This can be corrected by replacing the single paragraph of 9.4.7 with something like the following :

> _Immutable prototype exotic objects_ have the same internal slots as ordinary objects however  the  [[Prototype]] internal slot is immutable. Once the [[Prototype]] internal slot has been initialized its value must not  change.
> 
> Immutable prototype exotic objects provide alternative definitions for the following internal methods. All of the other Immutable prototype exotic object essential internal methods that are not defined below are as specified in 9.1.

**Comment by domenic** [comment]
+1. Nit: I'd replace "must not change" with "can not change" since otherwise the normative not-changing requirement is being duplicated in two places.

**Comment by littledan** [comment]
Thanks for pointing this out; I'll prepare a spec match to make it match the other parts soon.
