### ISSUE TITLE
explanation of ** precedence?

### ISSUE THREAD

**Issue by johnsdean** [tc39/ecma262#709]
I think the specification says that ** and / are at the same level of precedence, / has left-to-right associativity, and ** has right-to-left associativity. Testing shows that 4 / 2 ** 2 evaluates to 1. That leads me to believe that ** has higher precedence or somehow the ** associativity overrides the / associativity. 1. Can you verify that ** really has the same precedence as / ? 2. Can you explain how the associativity works on the example I gave?

**Comment by rwaldron** [comment]
I believe you've misread or misunderstood the grammar (which defines the precedence): https://tc39.github.io/ecma262/#sec-exp-operator

Take a look at the tests for practical examples: https://github.com/tc39/test262/blob/master/test/language/expressions/exponentiation/exp-operator.js
