### ISSUE TITLE
Module namespace @@iterator seems strange

### ISSUE THREAD

**Issue by domenic** [tc39/ecma262#710]
There is no other object in JS whose iterableness expresses a list of its keys. It seems strange that for module namespace objects, we are expecting people to write

``` js
for (const x of moduleNamespace) {
  console.log(moduleNamespace[x]);
}
```

whereas for other JS objects, we are expecting people to write

``` js
for (const x of Object.keys(obj)) {
  console.log(obj[x]);
}
```

It makes more sense to me to require the latter pattern for all objects.

Is it appropriate to suggest removing the iterator at this stage?

**Comment by caridy** [comment]
I totally agree! I remember we touched on this a while ago, and it is just weird. Maybe @allenwb knows better, but maybe this was just a leaking definition from the time of the loader.

**Comment by littledan** [comment]
cc @GeorgNeis @ajklein

**Comment by ajklein** [comment]
This should be closed, as `@@iterator` has been removed from the spec.
