### ISSUE TITLE
Why Number(symbol) crashes?

### ISSUE THREAD

**Issue by medikoo** [tc39/ecma262#712]
I was searching available resources but wasn't able to find the answer.

What's the reasoning behind having `Number(symbol)` crash instead of returning `NaN` (as it's in the case all other non-coercible values that expose some primitive representation)? It feels not consistent.

If someone can point me to some discussion that provided the reasoning I'd be grateful.

_I originally posted this question at Mozilla discussion group, but it feels a bit abandoned. If this repository is not right place for such questions, I'll be glad if you direct me to the right one. Thanks!_

**Comment by leobalter** [comment]
[Number(value)](https://tc39.github.io/ecma262/#sec-number-constructor-number-value) calls the abstract operation [ToNumber(value)](https://tc39.github.io/ecma262/#sec-tonumber), which throws a TypeError when value is a Symbol.

Why do you want to cast a symbol value to a Number?

We have this mailing list for this kind of discussion: http://esdiscuss.org/

**Comment by domenic** [comment]
This doesn't appear to be an issue with the current specification, and as such is not appropriate for this repo. es-discuss or StackOverflow are good ways to get clarification on specification and language usage questions.

**Comment by medikoo** [comment]
> Why do you want to cast a symbol value to a Number?

I didn't say I want to do that. I said that specification seems inconsistent in handling non-number coercible values, and I'm wondering what's the reasoning.

**Comment by medikoo** [comment]
@domenic I thought http://esdiscuss.org/ is not longer a place where TC39 is involved. Anyway thanks for redirection
