### ISSUE TITLE
Bug: Template Literals

### ISSUE THREAD

**Issue by ev1stensberg** [tc39/ecma262#718]
Using regexp to transform some string containing template literals fails. Removes a slash. Any reason why this happens? 

![skjermbilde 2016-10-22 kl 22 44 06](https://cloud.githubusercontent.com/assets/16735925/19622398/3caf396a-98a9-11e6-893b-488d3f75932a.png)
![skjermbilde 2016-10-22 kl 22 45 36](https://cloud.githubusercontent.com/assets/16735925/19622402/44fd6ba0-98a9-11e6-9710-ad0f6de36c3a.png)
![skjermbilde 2016-10-22 kl 22 48 03](https://cloud.githubusercontent.com/assets/16735925/19622430/b6daf3e6-98a9-11e6-8f15-70135bc7e016.png)
![skjermbilde 2016-10-22 kl 22 48 41](https://cloud.githubusercontent.com/assets/16735925/19622431/b6f99a4e-98a9-11e6-80f4-1178cfef0d94.png)

**Comment by domenic** [comment]
This doesn't appear to be a bug report with the spec, but instead a support question. Those are best posted to other locations like StackOverflow.

**Comment by ev1stensberg** [comment]
Aight @domenic , sorry for the disturbance. Furthermore, have a great weekend!
