### ISSUE TITLE
Redundancy in the `ToLength`?

### ISSUE THREAD

**Issue by zerkms** [tc39/ecma262#721]
http://www.ecma-international.org/ecma-262/7.0/#sec-tolength

The step 3 there is an explicit comparison with the `+Infinity`.

What is the point to have it there, as long as it will be handled by the last step `Return min(len, 2^53-1).` anyway.

**Comment by chozzz** [comment]
+1

**Comment by allenwb** [comment]
I think this is a case where the redundancy does no harm and is actually helpful to readers of the spec. 

Readers look at the ToX abstract operations when they need verify, for themselves, how specific cases are handled. In such situations it is easier to see an explicit statement of how `+Infinity` is handled than to have to remember or lookup that max() is defined to work with `+Infinity`.

**Comment by leobalter** [comment]
This step was an useful reference when I wrote tests for TypedArrays, I imagined the same applies to runtime implementors.

**Comment by zerkms** [comment]
@allenwb @leobalter then for consistency it should be another step that checks for `-Infinity`.

**Comment by chozzz** [comment]
@zerkms They already did that on step 2.

`If len ≤ +0, return +0.`

**Comment by zerkms** [comment]
@chozzz sure.

That's my exact point: if it is fine to expect `-Infinity` less than zero, then it would be equally fine to expect `+Infinite` greater than `2^53-1`.

**Comment by bterlson** [comment]
Editorially I am fine with the current spec text in this regard.

**Comment by bterlson** [comment]
There is now evidence of three people being confused by this. Since the min part is fairly straight forward I guess we'll remove the redundant check and rely on implementers to understand how max/min work with +/-Infinity.
