### ISSUE TITLE
Separate subsections for mathematical functions in Algorithm Conventions

### ISSUE THREAD

**Issue by siriniok** [tc39/ecma262#723]
There is a lot of references to mathematical functions like `min`, `max`, `abs`, etc. in the specification. All of them now described in the end of section [5.2 Algorithm Conventions](http://www.ecma-international.org/ecma-262/7.0/#sec-algorithm-conventions). And it's impossible to reference any of these functions directly, so links to them currently lead to the section 5.2. It's enough confusing.
I think we need to create a separate subsection for each mathematical function. It will make much simpler to find them and understand what they do.

**Comment by domenic** [comment]
I think instead of creating artificial sections we should just make the links go directly to the definitions.

**Comment by bterlson** [comment]
There are now direct links to the various mathematical operations (and the date ops too). which should make it much easier to find them. Thanks for the feedback @siriniok and sorry for the long delay :)
