### ISSUE TITLE
await appears at two places in the expression grammer

### ISSUE THREAD

**Issue by allenwb** [tc39/ecma262#727]
(based upon Nov. 11, 2016 revision)

Both [_AssignmentExpression_](https://tc39.github.io/ecma262/#sec-assignment-operators) and [_UnaryExpression_](https://tc39.github.io/ecma262/#sec-unary-operators) list _AwaitExpression_) as an alternative. It can't be both. I believe that _UnaryExpression_ is the correct placement.

Note, this problem also exists in Annex A.2

**Comment by bterlson** [comment]
Indeed, its placement in AssignmentExpression is a mistake.
