### ISSUE TITLE
Spec's markup is hostile to sane anchor use

### ISSUE THREAD

**Issue by bzbarsky** [tc39/ecma262#732]
STEPS TO REPRODUCE:

1)  Load https://tc39.github.io/ecma262/#sec-json.stringify
2)  Click the "List" link in step 1 to go to https://tc39.github.io/ecma262/#sec-list-and-record-specification-type
3)  Hit the browser's back button

EXPECTED RESULTS: Browser scrolls back to JSON.stringify algorithm.

ACTUAL RESULTS: Nothing happens.

ADDITIONAL INFORMATION: The entire body of the spec is inside the `<div id="spec-container">` thing which has "overflow-y: auto".  So when scrolling in step 2 above, that div is what gets scrolled, not the main viewport.  But session history in browsers only stores the scroll position of the viewport.  As a result, when traversing back in history there is no scrolling happening in this case.  The upshot is that you can't get back to where you came from, which is really annoying.

Ideally the spec would use the viewport scrollbars as its main mechanism, not the scrollbars of some random div in the page.

**Comment by bterlson** [comment]
I'm attempting a fix this weekend. Unfortunately the container was added to work around crazy perf issues, but fortunately I think I can simply apply the same fix to body, and also if that doesn't work I got some additional workarounds from helpful folks on twitter that I can try.

**Comment by bterlson** [comment]
I worked on this some but there is no easy fix - fixes either introduce new layout bugs in various browsers, or regress experience in other ways (eg. scrolling toc to top/bottom starts scrolling main spec body). Still working on it.

**Comment by bterlson** [comment]
Fixed in emu 3.7.2 (rendered spec updated as well).
