### ISSUE TITLE
what's new things of ES2017(ES8) ?

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [tc39/ecma262#743]
**what's new things of ES2017(ES8) ?**
https://esdiscuss.org/topic/es6-es7-es8-and-beyond-a-proposed-roadmap
https://esdiscuss.org/topic/es8-proposal-optional-static-typing
http://www.2ality.com/2016/02/ecmascript-2017.html  
https://developer.mozilla.org/en-US/docs/Web/JavaScript/New_in_JavaScript/ECMAScript_Next_support_in_Mozilla   
https://github.com/sirisian/ecmascript-types  
https://gist.github.com/sirisian/dbc628dde19771b54dec  
https://www.quora.com/What-features-will-be-in-ES7-and-ES8

**Comment by UltCombo** [comment]
See the [TC39 Process](https://tc39.github.io/process-document/) document and the [active proposals](https://github.com/tc39/proposals) list. The proposals that reach "finished" status in time will be included.
