### ISSUE TITLE
is `export default function l() {}` syntactically valid?

### ISSUE THREAD

**Issue by icefapper** [tc39/ecma262#750]
Hello
judging from the spec, function declarations following an `export default` can not have names. At least I was unable to derive `export default function l() {}` from the relevant rules outlined in ES2015 and ES2017 specs.
I am also rather confused by the fact that Table 43 in ES2017 actually uses such construct.

is it a spec bug? or am I only missing something?

**Comment by loganfsmyth** [comment]
As mentioned on Babel's Slack, the `[+Default]` in the `FunctionDeclaration` rule is additional syntax for that specific case, but it does not replace the normal function declaration syntax with a name, which still applies when `export default` is in use.

**Comment by icefapper** [comment]
looks like I've missed the fact that the `+` next to a rule means 'also', 'not' only
