### ISSUE TITLE
CreateDynamicFunction is not correct for async function prototypes

### ISSUE THREAD

**Issue by domenic** [tc39/ecma262#751]
That is, the issue mentioned in https://github.com/tc39/ecma262/pull/692#issuecomment-247479834 was never fixed.

**Comment by domenic** [comment]
You also need to fix the note:

> A prototype property is automatically created for every function created using CreateDynamicFunction, to provide for the possibility that the function will be used as a constructor.

**Comment by bterlson** [comment]
It's a weird note, but I'll update it.
