### ISSUE TITLE
Adding support for camel casing

### ISSUE THREAD

**Issue by zspitzer** [tc39/ecma262#761]
Both HTML5 data attributes and css properties use camel casing, however, there
aren't native functions to perform these, thus libraries like jQuery have their own implementations

The camel casing is documented here
https://html.spec.whatwg.org/multipage/dom.html#dom-dataset

Discussion started here https://twitter.com/zackster/status/814697677661184000

**Comment by bterlson** [comment]
Es-discuss is the proper venue for feature requests. See [contributing.md](https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#feature-requests).
