### ISSUE TITLE
Are the changes from #637 LR(1) compatible?

### ISSUE THREAD

**Issue by anba** [tc39/ecma262#776]
Has anyone checked if the grammar is still LR(1) with the changes from #637? When I use the following toy grammar to model the modifications from #637, I get shift/reduce and reduce/reduce conflicts.

```yacc
%start module

%error-verbose

%token ID
%token EXPORT "export"
%token FROM "from"
%token AS "as"

%%

module : moduleItemList ;
moduleItemList : exportDeclaration | moduleItemList exportDeclaration ;

exportDeclaration : exportClause FROM ID | exportClause_local ;

exportClause : '{' exportSpecifier '}' ;
exportClause_local : '{' exportSpecifier_local '}' ;

exportSpecifier : ID | ID AS ID ;
exportSpecifier_local : identifierReference | identifierReference AS ID ;

identifierReference : ID ;

%%
```

**Comment by jmdyck** [comment]
(I tried to generate an LR automaton, but couldn't figure out how to incorporate lookahead-restrictions into the algorithm.)

**Comment by jmdyck** [comment]
Yeah, it seems to me that after seeing `export { IdentifierName`, the parser has a couple of reduce actions available (reduce to `Identifier` or to `ExportSpecifier[~Local]`), but the only basis for deciding between them is the presence or absence of a `FromClause`, which is arbitrarily far away.

**Comment by anba** [comment]
Thanks for confirming @jmdyck!
