### ISSUE TITLE
Which prototype to use when extending an object from another realm and my constructor prototype is not an object?

### ISSUE THREAD

**Issue by AnnotationMark** [tc39/ecma262#786]
Let's say we have a script that looks like this:
```
<script>
let iframe = document.createElement('iframe');
document.body.appendChild(iframe);
let w = iframe.contentWindow;

function MySet() { }
MySet.prototype = undefined;

var o = Reflect.construct(w.Set, [], MySet);
alert(Object.getPrototypeOf(o) == window.Set.prototype); // Case 1
alert(Object.getPrototypeOf(o) == w.Set.prototype); // Case 2
alert(Object.getPrototypeOf(o) == window.Object.prototype); // Case 3
alert(Object.getPrototypeOf(o) == w.Object.prototype); // Case 4
</script>
```

According to http://w3c-test.org/custom-elements/htmlconstructor/newtarget.html, Case 1 should be true and the others false.

Based on my reading of the ES spec (9.2.2 ECMAScript Function Objects [[Construct]] - https://tc39.github.io/ecma262/#sec-ecmascript-function-objects-construct-argumentslist-newtarget, 9.1.13 OrdinaryCreateFromConstructor - https://tc39.github.io/ecma262/#sec-ordinarycreatefromconstructor, and 9.1.14 GetPrototypeFromConstructor - https://tc39.github.io/ecma262/#sec-getprototypefromconstructor), it appears that Case 3 should be true, and the others false.

Currently, Chrome implements Case 1, while Safari and Firefox implements Case 2.

Which one of these is actually the correct behavior?  Thanks.

**Comment by claudepache** [comment]
The base constructor is `w.Set`, which uses `OrdinaryCreateFromConstructor(NewTarget, "%SetPrototype%", « [[SetData]] »)` and not `OrdinaryCreateFromConstructor(newTarget, "%ObjectPrototype%")`, see https://tc39.github.io/ecma262/#sec-set-iterable. I think it should be Case 2.

**Comment by AnnotationMark** [comment]
Thanks for the clarification.
