### ISSUE TITLE
CoveredAsyncFunctionHead doesn't exist

### ISSUE THREAD

**Issue by jmdyck** [tc39/ecma262#789]
Each of 14.7.3 and 14.7.4 has a reference to CoveredAsyncFunctionHead, which does not exist. Should that be CoveredAsyncArrowHead?

**Comment by bterlson** [comment]
Yes, fixed in bd432b9b8b07a93ef1234756336b33a57f511e17.

**Comment by ljharb** [comment]
Is that pushed up yet?

**Comment by bterlson** [comment]
Sorry it wasn't. And of course I had another rebase to do. Actual commit: e5b0f7a11f226e6afa8c5f7836e0132581ae0ddd.
