### ISSUE TITLE
Classes seems to be too strict

### ISSUE THREAD

**Issue by sr229** [tc39/ecma262#803]
the ECMAScript 6 Harmony Specification for Classes require at least a Constructor/Super/Static to define a method/function/etc. 
```js
class moveWhere extends Movement{
  constructor () {
      move(left);
   }
};
```

Making classes on Javascript always explicitly defining a constructor or such optionally, makes the classes encapsulation more dynamic.
```js
class moveWhere extends Movement {
  move(left);
};
```
If this is too vague or invalid, you may simply ignore this and close this issue.

*Note: This idea is based on [CoffeeScript's Classes](http://coffeescript.org/#classes)*

**Comment by bakkot** [comment]
I'm not entirely sure what you're asking for, but per [CONTRIBUTING.md](https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#feature-requests) you should send feature requests to [esdiscuss](https://esdiscuss.org/).

It'll help if you can be a bit more clear about what it is you're asking for, also.
