### ISSUE TITLE
Misordered comments for section identification in spec.html

### ISSUE THREAD

**Issue by HangPark** [tc39/ecma262#805]
There is a comment right above each of section (including subsection, subsubsection, etc.) of the form `<!-- es6num="#.#.#" -->` to indicate the section number.

But I found several misordered comments:
- ... - 13.7.5.14 - **9.1.11** - 13.8 - ...
- ... - 12.4.5.1 - **12.5.7** - **12.5.7.1** - **12.5.8** - **12.5.8.1** - 12.5 - ...
- etc.

I think some of those are comment errors and others are misorderings, but I can not decide which is of which case since I'm new in ECMA-262. Perhaps these errors are not the errors but my mistake or already discussed in the community.

Please check. Thanks.

**Comment by ljharb** [comment]
`es6num` is to denote legacy numbering links from ES6/ES2015 - all new sections lack them, and reorderings are intentional. The purpose is to preserve old anchor links to the closest possible relevant content in the updated spec.
