### ISSUE TITLE
21.2.1 erroneous production?

### ISSUE THREAD

**Issue by isiahmeadows** [tc39/ecma262#819]
Based on the definition for [*Quantifier*](https://tc39.github.io/ecma262/#prod-Quantifier), a valid *Quantifier* would include `??`, making things like `a??` a valid regular expression body, even though it's redundant. Is that an oversight?

I'll note that `a???` is not a valid production, though, so it's only limited to 1 or 2 `?`s.

**Comment by ljharb** [comment]
`/a??/` parses just fine in browsers, so even if it's a mistake, it's probably not web-compatible to change it.

**Comment by claudepache** [comment]
At first sight, `/a??/` is just the non-greedy version of`/a?/`, i.e., the latter is equivalent to `/a|/` and the former to `/|a/`.

**Comment by claudepache** [comment]
That is to say, the two `?`s have two completely different meanings: the first one modifies an Atom and means “optional”, and the second one modifies a Quantifier and means “non-greedy”.

**Comment by littledan** [comment]
Thanks for the answer, looks like the case is closed.
