### ISSUE TITLE
Show current (super) section title

### ISSUE THREAD

**Issue by camillobruni** [tc39/ecma262#82]
While browsing the spec I typically end up looking for something like "[[Call]]" which exists in multiple places (Functions, Proxies...). In this case it is not always immediately clear in which section you are.

It would be nice to highlight the current super-section somehow. One option would be to show it in the expanded TOC, another one might be using fixed Breadcrumps at the top of the specs.

**Comment by michaelficarra** [comment]
You should open this issue against [ecmarkup](https://github.com/bterlson/ecmarkup) instead.

**Comment by camillobruni** [comment]
perfect, thanks.
