### ISSUE TITLE
editorial: definition of strict total order

### ISSUE THREAD

**Issue by jmdyck** [tc39/ecma262#823]
The definition of 'strict total order' includes the condition `_a_ _R_ _b_ or _b_ _R_ _a_`, but this can't be true when `_a_ = _b_`. Possible fixes:
- Start that line with `If _a_ ≠ _b_,`
- Insert the word `distinct` into the `For all` line.

**Comment by syg** [comment]
I prefer inserting the word "distinct"

**Comment by jmdyck** [comment]
PR #946 resolved this.
