### ISSUE TITLE
Partial matching a string against a regex

### ISSUE THREAD

**Issue by sassanh** [tc39/ecma262#836]
Suppose that I have this regular expression: /abcd/ Suppose that I want to check the user input against that regex and disallow entering invalid characters in the input. When user inputs "ab", it fails as an match for the regex, but I can't disallow entering "a" and then "b" as user can't enter all 4 characters at once (except for copy/paste). So what I need here is a partial match which checks if an incomplete string can be potentially a match for a regex.

Java has something for this purpose: .hitEnd() (described here http://glaforge.appspot.com/article/incomplete-string-regex-matching) python doesn't do it natively but has this package that does the job: https://pypi.python.org/pypi/regex.

I didn't find any solution for it in js. It's been asked years ago: http://stackoverflow.com/questions/9060979/javascript-regex-partial-match and even before that: http://stackoverflow.com/questions/416425/check-if-string-is-a-prefix-of-a-javascript-regexp
And I asked it here again: https://stackoverflow.com/questions/42461651/partial-matching-a-string-against-a-regex and still no answer.

I don't know where should I suggest this feature request. Please let me know if this is wrong place to ask for it and tell me where should I ask it instead.

**Comment by bakkot** [comment]
See [CONTRIBUTING.md](https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#feature-requests). Feature requests should be made to [esdiscuss](https://esdiscuss.org/).

**Comment by bakkot** [comment]
That said, on second glance it looks like this might be a better feature request for a library like [XRegExp](http://xregexp.com/).

**Comment by sassanh** [comment]
Thanks for info.
