### ISSUE TITLE
Editorial: _NcapturingParens_ renders poorly in Annex B 1.4 grammar

### ISSUE THREAD

**Issue by littledan** [tc39/ecma262#859]
In [AtomEscape](https://tc39.github.io/ecma262/#prod-annexB-AtomEscape), the second DecimalEscape clause has literal `_` characters instead of a proper reference to a variable. I can't find a simple fix in playing around with it; I wonder if this is a limitation of grammardown. Thanks to @schuay for pointing this out from the named capture groups spec.

**Comment by anba** [comment]
Dup of #570
