### ISSUE TITLE
Waiter removed twice when waking suspended agent?

### ISSUE THREAD

**Issue by binji** [tc39/ecma262#861]
@AndrewScheidecker pointed out what seems to be a bug in the spec here:
https://github.com/WebAssembly/design/pull/1019#issuecomment-291288082

> Incidentally, I believe I found an erroneous assertion in the SAB spec. In Atomics.wait, step 18 performs RemoveWaiter after Suspend completes. RemoveWaiter asserts that the agent being removed is in the WaiterList. However, if Suspend returned because a call to Atomics.wake called WakeWaiter, the agent will have been removed from the WaiterList already by step 11 of Atomics.wake.

I took a look and this seems right to me. Are we missing something?

cc: @lars-t-hansen @syg

**Comment by syg** [comment]
@lars-t-hansen wrote that part but I concur with @AndrewScheidecker's reading here that there's double removal in the case of non-spurious wakeup in `Atomics.wake`. I'd imagine the fix here is to perform RemoveWaiter from `Atomics.wake` only in the case of spurious wakeup, and in the intentional wakeup case, assert that W is not in WL.

**Comment by lars-t-hansen** [comment]
@syg, I assume by "spurious wakeup" you mean "the agent was explicitly woken, it did not time out".  If so, I agree with your suggestions.  (If you actually mean "spurious wakeup" then we have bigger problems, because there shouldn't be any spurious wakeups.)

**Comment by lars-t-hansen** [comment]
Opened a PR here: https://github.com/tc39/ecma262/pull/865

**Comment by syg** [comment]
@lars-t-hansen Err, I'm not sure what I meant as I typed that while leaving work yesterday -- but timeout is the right thing here.

**Comment by bakkot** [comment]
I get the impression this was addressed by #865 and hence should be closed, yes?
