### ISSUE TITLE
The mozilla page for this links back to a non existant page

### ISSUE THREAD

**Issue by OmgImAlexis** [tc39/ecma262#872]
Not sure what can be done about this but this [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Language_Resources) page links back to the github pages repo this for yet it currently goes to a 404 page.

Hopefully someone from here can resolve this issue.

**Comment by ljharb** [comment]
It's a wiki; anyone can update it.

**Comment by OmgImAlexis** [comment]
I have no clue where the links are meant to go though, I figured someone that actually works on this repo may have a better idea.

**Comment by ljharb** [comment]
@OmgImAlexis which links specifically 404? The top two pairs all work fine.

**Comment by annevk** [comment]
At the bottom it has https://tc39.github.io/ecma262/2016/  and http://tc39.github.io/ecma402/2016/. Links should probably also be changed to HTTPS.

**Comment by annevk** [comment]
(Go to edit, hit source, then search for "github". I'll fix the lack of HTTPS, not sure about those two links though.)

**Comment by ljharb** [comment]
Thanks, will fix

**Comment by ljharb** [comment]
k, corrected to point to the ecma-international site instead. Closing.

@bterlson, it'd be really nice if we kept the older years in subdirectories in gh-pages, so we can point people there instead for a snapshot.

**Comment by bterlson** [comment]
@ljharb I am not interested in maintaining old snapshots. That is what the ECMA website is for. I will do a better job this year deleting the /2017 branch immediately after ratification which will hopefully cut down on inbound links.

**Comment by ljharb** [comment]
Fair enough; they wouldn't need maintenance tho, they'd just sit untouched forever.

**Comment by bterlson** [comment]
In theory. In practice it will be non-zero amounts of work to maintain :)

**Comment by leobalter** [comment]
do we have any easy way to set redirects?

**Comment by ljharb** [comment]
Not on github pages; it'd have to be an `index.html` with an HTML meta redirect.
