### ISSUE TITLE
Editorial: contradiction re Function instances

### ISSUE THREAD

**Issue by jmdyck** [tc39/ecma262#876]
[Function Instances](https://tc39.github.io/ecma262/#sec-function-instances) says:
> Every function instance is an ECMAScript function object and has the internal slots listed in Table 27. Function instances created using the Function.prototype.bind method (19.2.3.2) have the internal slots listed in Table 28.

But Function.prototype.bind creates bound function exotic objects, which are not ECMAScript function objects, so there is a contradiction.

(In passing, "function instance" in the first sentence should presumably be "Function instance".)

Here are a couple possibilities (there may be others):
- The first sentence is incorrect: not every Function instance is an ECMAScript function object. (Could fix by deleting "ECMAScript".)
- The second sentence is incorrect: functions created by Function.prototype.bind are not Function instances. (Could fix by changing "Function instances" to "Function objects", and maybe adding that they're not Function instances.)

This is complicated by the fact that the spec doesn't clearly say was it means by "X instance" where X is some constructor. I'm guessing it means 'instance' in more or less the sense of the 'instanceof' operator. But I'm still not sure how to resolve the contradiction.

**Comment by anba** [comment]
I went with the second option in #866 (3e02a57f85d5718f481cad28e1de019d37dd5167).

**Comment by jmdyck** [comment]
> I went with the second option in #866.

Ah, so you did.

@bterlson, you can close this as a duplicate unless you think it warrants discussion.
