### ISSUE TITLE
Obscure description in the Conformance section

### ISSUE THREAD

**Issue by NE-SmallTown** [tc39/ecma262#880]
The [doc](https://tc39.github.io/ecma262/#sec-conformance) says:

> In particular, a conforming implementation of ECMAScript may provide properties not described in this specification, and values for those properties, for objects that are described in this specification.

Sorry for that I can't understand it very well.Does the means"a conforming implementation of ECMAScript may provide properties and values for these properties,though they don't be described in this specification,but for objects that are described in this specification."?

Much appreciated if anyone could explain this.

**Comment by allenwb** [comment]
Try reading it as if  ", and values for those properties," was not there.

**Comment by NE-SmallTown** [comment]
@allenwb Thanks!

If I get you,you mean:

There is some objects that are described in this specification,but the spec may provide properties(and values for those properties) which are not described in this specification of **these** objects.
