### ISSUE TITLE
Agent Clusters note 4 seems broken

### ISSUE THREAD

**Issue by annevk** [tc39/ecma262#897]
Found by @foolip at https://github.com/whatwg/html/pull/2521#discussion_r111905976.

1. It's not a DOM SharedWorker. If you want to be vague, just say "shared worker" as defined in the HTML Standard.
2. Don't say "regular worker"; it's dedicated worker.
3. Per your own advice, a shared worker cannot share memory with a dedicated worker whose owner is a document. A shared worker can only share memory with a dedicated worker "descendant".

cc @lars-t-hansen

**Comment by lars-t-hansen** [comment]
I agree that note could be rephrased to be much clearer.  Points (1) and (2) are terminology and easily rephrased, though I think we might take the opportunity to do better, I'll put something up for review.  Re your point (3), the note is expressing a hypothetical and should at least be rewritten with appropriate grammar.  I'll look into that as well.

**Comment by annevk** [comment]
Fixed by 0719f44aab93215ed9a626b2f45bd34f36916834.
