### ISSUE TITLE
Suggest adding method " format" to Date.prototype.

### ISSUE THREAD

**Issue by wendux** [tc39/ecma262#898]
Since we often need a custom time display format, I suggest adding method " format" to Date.prototype , so we can use the time format symbol like other programming language, such as java.  
 For example, we can write code like this:
 `(new Date()).format("yyyy-MM-dd hh:mm:ss")`

**Comment by annevk** [comment]
I recommend reading https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md. This is not the right place for proposals.

**Comment by domenic** [comment]
You may also enjoy https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat.

**Comment by littledan** [comment]
FWIW In the context of the DateTimeFormat, we've discussed the pattern [here](https://github.com/tc39/ecma402/issues/21). cc @zbraniecki @caridy
