### ISSUE TITLE
Reversed order of `import` and `from`

### ISSUE THREAD

**Issue by n-sviridenko** [tc39/ecma262#906]
Why not to be able to write `from` and just after `import`, like in python? It will allow to implement an autocompletion for exported members of specified package.

**Comment by leobalter** [comment]
To get a complete answer for your question you will need to catch up with years of discussions on the syntax. You can check it in the meeting notes https://github.com/rwaldron/tc39-notes and esdiscuss.org as well..

Based on your question, it seems like autocompletion is the only argument for a different order, but a lot of other syntactical reasonings are in game to match this current way. 

In any other way, this is already specified and released 2 years ago, I don't think it's worth changing that neither this would have any consensus from the parties involved.

esdiscuss should be the right channel to keep this conversation, so I'm closing this one here.
