### ISSUE TITLE
Why allow BindingPattern for BindingRestParameter

### ISSUE THREAD

**Issue by saambarati** [tc39/ecma262#915]
I'm looking at this spec text:
https://tc39.github.io/proposal-object-rest-spread/#Rest
and
https://tc39.github.io/proposal-object-rest-spread/#Rest-RuntimeSemantics-RestBindingInitialization

Why not only allow an identifier for rest?

For example, I think this code is too difficult to understand (and has little real world value):
```
let {[a]: b, ...[c]} = expr;
```

What does this even do? Not what I would've expected it to.

I think I finally understand that it's something like this (with a lot of hand waiving):
```
let tmp1 = a.toString();
let b = expr[tmp1];
let tmp2= { ... expr - tmp1 properties }  ;
let [c] = tmp2;
```

**Comment by saambarati** [comment]
An example of JS that expresses why I think this is crazy:

```
Object.prototype[Symbol.iterator] = function() { console.log('foo'); return {next: function() { console.log('baz'); return {done:true}}}}
let {...[baz]} = {foo:20}
```

**Comment by syg** [comment]
@anba has raised a similar point here: https://github.com/tc39/proposal-object-rest-spread/issues/43

**Comment by littledan** [comment]
Cc @gsathya @caiolima

**Comment by caiolima** [comment]
I don't think it's a good idea since we will not be consistent with Array Rest spec that allows recursively rest operations. IMHO it could bring confusion against intuitive usage of rest operations.

BTW, I think it's a good idea discuss this topic into [tc39/proposal-object-rest-spread#43](https://github.com/tc39/proposal-object-rest-spread/issues/43) since it is not part of spec yet.

**Comment by peey** [comment]
Do note the functional differences between `let {...{a}} = expr` and `let {a} = expr`

The first example would only set a only if a is expr's own property, but the second example is equivalent to `a = expr.a`. 

Though it does get redundant after one level of nesting, I don't see much point in `let {...{...{a}}} = expr`

**Comment by Josh-Cena** [comment]
I think this can be closed now? The final spec does not allow this syntax.
