### ISSUE TITLE
Await: FutureReservedWord?

### ISSUE THREAD

**Issue by bathos** [tc39/ecma262#922]
In the ES2018 spec, the A.1 Lexical Grammar summary includes the following:

> `await` is only treated as a _FutureReservedWord_ when _Module_ is the goal symbol of the syntactic grammar.

In the primary section on future reserved words, 11.6.2.2, `await` isn’t mentioned. In both sections, `await` is listed as a keyword proper rather than a future reserved word. Other notes in the text clarify that some contexts permit `await` as an identifier but I don’t think this is related to its classification as "keyword" vs "future reserved word". If I’m understanding right, the bit about _FutureReservedWord_ in the grammar summary seems likely to be a vestige from an earlier version of the spec.

**Comment by chicoxyzzy** [comment]
Hmmm... should be fixed already aec498db94dedbf31a930c6b09c2ae939d21890f

**Comment by chicoxyzzy** [comment]
@bathos I think you are right. It seems like A.1 part about `await` should be removed. I Filed #926
