### ISSUE TITLE
Missing semi-colon in for grammar

### ISSUE THREAD

**Issue by qfox** [tc39/ecma262#924]
The `IterationStatement` ([link](https://tc39.github.io/ecma262/#sec-iteration-statements)) has this rule:

```
for(Lexical Declaration[~In, ?Yield, ?Await] Expression[+In, ?Yield, ?Await]opt; Expression[+In, ?Yield, ?Await]opt) Statement[?Yield, ?Await, ?Return]
```

While that initially got me excited I've since then recovered and am fairly certain it's just missing the first semi-colon in the grammar.

This bug is present in every appearance of this rule (about 13x, search for `LexicalDeclaration Expression`) and was at least present [since ES6](https://www.ecma-international.org/ecma-262/6.0/).

Trivial fix.

**Comment by qfox** [comment]
I would like to point out that there's a unique opportunity here to define a "simple" loop where you define the start and finish of a var without, technically, introducing new syntax. `for (let i 80; 100) stmt`

**Comment by littledan** [comment]
@qfox Where do you think the missing semicolon is? [LexicalDeclaration](https://tc39.github.io/ecma262/#prod-LexicalDeclaration)'s grammar has a semicolon in it.

It's true that this is a possibility for a new language feature, but such a new feature will have to be proposed separately.

**Comment by qfox** [comment]
(That last bit was a joke)

The grammar is

```
for(LexicalDeclaration Expression; Expression) Statement
```

I'm pretty sure that should be

```
for(LexicalDeclaration; Expression; Expression) Statement
```

**Comment by qfox** [comment]
Oh, I see now. Okay.

**Comment by littledan** [comment]
@qfox I'm glad to have you carefully reviewing the ECMAScript spec, even if this ended up being OK already. I hope you keep on the lookout for anything that we could fix or make more clear!
