### ISSUE TITLE
Inconsistent spacing around binary operators

### ISSUE THREAD

**Issue by domenic** [tc39/ecma262#925]
Mostly there seems to be space between binary operators and their operands, e.g. `Repeat, while q ≠ s`, `If e = p`, etc. But sometimes there is no spacing, e.g. the latter half of `If e = p, let q be q+1`, or the former half of `If q+r > s`.

Obviously very minor, but I think cleaning this up to add spaces everywhere would be good.

**Comment by dantesolis** [comment]
hey guys, could I work on this issue, is this a good issue for a `first-time contributor` or should I take something else?  Thanks

**Comment by littledan** [comment]
@dantesolis Go for it! I think an editorial patch like this would be great for a first-time contributor. You can do this by editing the spec.html file in this repository and making a PR on GitHub. Feel free to ask questions here or on the #tc39 channel on Freenode IRC.

**Comment by ljharb** [comment]
@dantesolis are you still hoping to take this on?

**Comment by jmdyck** [comment]
If not, I'll do it.

**Comment by littledan** [comment]
@jmdyck Go for it. I also ran into this in the mathematical values change.
