### ISSUE TITLE
Better closures, or promise-handling, in the spec

### ISSUE THREAD

**Issue by domenic** [tc39/ecma262#933]
Over in the async iteration spec, we're having to write up more and more annoying "closures" as sections. Examples, from the current spec and from async iteration:

- https://tc39.github.io/ecma262/#sec-async-functions-abstract-operations-awaited-fulfilled
- https://tc39.github.io/ecma262/#sec-async-functions-abstract-operations-awaited-rejected
- https://tc39.github.io/ecma262/#sec-promise-reject-functions
- https://tc39.github.io/ecma262/#sec-promise-resolve-functions
- https://tc39.github.io/ecma262/#sec-proxy-revocation-functions
- https://tc39.github.io/ecma262/#sec-promise.all-resolve-element-functions
- https://tc39.github.io/proposal-async-iteration/#await-fulfilled
- https://tc39.github.io/proposal-async-iteration/#await-rejected
- https://tc39.github.io/proposal-async-iteration/#sec-async-iterator-value-unwrap-functions
- Another two upcoming ones as part of https://github.com/tc39/proposal-async-iteration/pull/102

The vast majority of these are basically trying to respond to promises, running some spec steps in reaction to their fulfillment or rejection. (Those that are not: promise-rejection-functions, promise-resolve-functions, and proxy-revocation-functions.)

I would love to explore one or both of the following paths:

1. A way of writing these closures inline, in the algorithms that need to create them, as you would do in ECMAScript.
   - Probably we would want to preserve the current spec's explicit listing of "closed over" values, unlike ECMAScript code.
2. Algorithmic conventions for operating on promises that allow us to generally react to promises. [Web specs are already using some](https://www.w3.org/2001/tag/doc/promises-guide#shorthand-phrases); of those I think the most important are, in order from most- to less-important:
   - Upon fulfillment / upon rejection
   - Transforming
   - A promise resolved with x / a promise rejected with x

<details>
<summary>Example of (1)</summary>

CreateResolvingFunctions(promise)

When CreateResolvingFunctions is performed with argument _promise_, the following steps are taken:

1. Let _alreadyResolved_ be a **false**.
1. Let _resolve_ be the built-in function object defined by the following steps, [closing over] _promise_ and _alreadyResolved_, and taking the argument _resolution_:
    1. If _alreadyResolved_ is **true**, return **undefined**.
    1. Set _alreadyResolved_ to **true**.
    1. If SameValue(_resolution_, _promise_) is **true**, then...
    1. ...
1. Let _reject_ be the built-in function object defined by the following steps, [closing over] _promise_ and _alreadyResolved_, and taking the argument _reason_:
    1. If _alreadyResolved_ is **true**, return **undefined**.
    1. Set _alreadyResolved_ to **true**.
    1. Return RejectPromise(_promise_, _reason_).
1. Return a new Record { [[Resolve]]: resolve, [[Reject]]: reject }.
</details>

<details>
<summary>Example of (2)</summary>

AsyncFunctionAwait ( value )

1. Let _asyncContext_ be the running execution context.
1. Let _valueAsPromise_ be [a promise resolved with] _value_.
1. Upon fulfillment of _valueAsPromise_ with _fulfillmentValue_, perform the following steps, [closing over] _asyncContext_:
    1. Let _prevContext_ be the running execution context.
    1. Suspend _prevContext_.
    1. Push _asyncContext_ onto the execution context stack; _asyncContext_ is now the running execution context.
    1. Resume the suspended evaluation of _asyncContext_ using NormalCompletion(_fulfillmentValue_) as the result of the operation that suspended it. Let _result_ be the value returned by the resumed computation.
    1. Assert: When we reach this step, _asyncContext_ has already been removed from the execution context stack and _prevContext_ is the currently running execution context.
    1. Return Completion(_result_).
1. Upon rejection of _valueAsPromise_ with _rejectionReason_, perform the following steps, [closing over] _asyncContext_:
    1. Let _prevContext_ be the running execution context.
    1. Suspend _prevContext_.
    1. Push _asyncContext_ onto the execution context stack; _asyncContext_ is now the running execution context.
    1. Resume the suspended evaluation of _asyncContext_ using Completion{[[Type]]: throw, [[Value]]: _rejectionReason_, [[Target]]: empty} as the result of the operation that suspended it. Let _result_ be the value returned by the resumed computation.
    1. Assert: When we reach this step, _asyncContext_ has already been removed from the execution context stack and _prevContext_ is the currently running execution context.
    1. Return Completion(_result_).
1. Remove _asyncContext_ from the execution context stack and restore the execution context that is at the top of the execution context stack as the running execution context.
1. Set the code evaluation state of _asyncContext_ such that when evaluation is resumed with a Completion _resumptionValue_ the following steps will be performed:
    1. Return _resumptionValue_.
1. Return.
</details>

I am willing to spend significant time refactoring the current spec if I can get the go-ahead, for either (1) or (2) or both.

**Comment by bterlson** [comment]
I like upon-fulfillment and upon-rejection a lot (with "closures"). How frequently are the others coming up in Async Iteration work?

What is the concern with omitting the "closing over" clause? The default assumption of "indented steps see outer named aliases" seems fine.

**Comment by domenic** [comment]
> How frequently are the others coming up in Async Iteration work?

"a promise resolved with" is very frequent. The others less so... I was thinking "transforming" would be used by Promise.prototype.finally or Promise.all, but I see those call the public API methods, so that doesn't quite work. And I guess it shouldn't; we should use proper closure machinery, possibly made simpler by (1), for closures that are actually exposed to author code.

> What is the concern with omitting the "closing over" clause? The default assumption of "indented steps see outer named aliases" seems fine.

I can't be sure, but I vaguely imagine it's to make you aware of the "cost" of the closure, and to make it easier to translate into languages (like C++) which don't have auto-capturing closures? I'd be OK omitting it.

**Comment by jmdyck** [comment]
The spec uses the term "internal closure" for (roughly) an anonymous abstract op with access to 'outer' metavariables. Path #1 is proposing (roughly) an anonymous built-in function object whose call-semantics are given by steps with access to 'outer' metavariables. The spec should make it clear (via naming and description) that the two things are similar but distinct.

**Comment by domenic** [comment]
Goodness, I had no idea that the spec had a notion of "internal closure" already. I see it is only used inside the notation of RegExp pattern semantics; strange.

**Comment by jmdyck** [comment]
Yeah, there's a lot of strange stuff in RegExp semantics!

**Comment by littledan** [comment]
Yeah, I was a bit confused at first by how the data passing in the RegExp spec works, though I imagine it's done that way because things would be very wordy if it were all explicit.

Anyway, the RegExp usage of closures is pretty different from the Promise usage; it seems like they should be addressed separately.
