### ISSUE TITLE
inadequate .[[Value]] after ReturnIfAbrupt in 15.2.1.20

### ISSUE THREAD

**Issue by kotarondo** [tc39/ecma262#936]
In the following Evaluation algorithm, *sl.[[Value]]* in the last line should be *sl* because *sl* is already a completion's [[Value]] after ReturnIfAbrupt(sl).
```
15.2.1.20 Runtime Semantics: Evaluation
ModuleItemList: ModuleItemList ModuleItem
 1. Let sl be the result of evaluating ModuleItemList.
 2. ReturnIfAbrupt(sl).
 3. Let s be the result of evaluating ModuleItem.
 4. Return Completion(UpdateEmpty(s, sl.[[Value]])).
```

**Comment by ljharb** [comment]
Doesn't ReturnIfAbrupt(sl) *become* the value? I don't think it mutates the fictional `sl` binding.

**Comment by kotarondo** [comment]
The Definition of ReturnIfAbrupt:
```
5.2.3.3 ReturnIfAbrupt
Algorithms steps that say or are otherwise equivalent to:

ReturnIfAbrupt(argument).
mean the same thing as:

If argument is an abrupt completion, return argument.
Else if argument is a Completion Record, let argument be argument.[[Value]].
```

In above case,  step 2 means:
```
If sl is an abrupt completion, return sl.
Else if sl is a Completion Record, let sl be sl.[[Value]].
```

**Comment by ljharb** [comment]
Ah, fair point. That seems like a confusing way for the spec to be worded,  but given that, I think you are correct.

**Comment by jmdyck** [comment]
> That seems like a confusing way for the spec to be worded

(I think it would be less confusing with the proposal of Issue #497.)
