### ISSUE TITLE
What about proper String, Date and Number formatting?

### ISSUE THREAD

**Issue by devlato** [tc39/ecma262#939]
Hello guys and ladies,

what do you think about adding some common String and Date formatting APIs finally? Currently if you need to format a date, you have to use third party library or write tons of code, and formatting of dates is required in almost any project. Why don't add some APIs similar to moment.js API to the standard library?

I.e.
```
const now = new Date();
const formatted = now.format('DD.MM.YYYY HH:mm:ss');
assert(formatted, '22.06.2017 15:48:18');
```

Or for strings:
```
const formatted = 'Hello, number ${value}'.format({
  value: 12,
});
assert(formatted, 'Hello, number 12');
```

Or for numbers:
```
const formatted = 12.format('%4${value}');
assert(formatted, '    12');
```

I mean, it's 2017, and there is still no formatting API in standard library

**Comment by IgnoredAmbience** [comment]
Template literals cover your second request. https://hacks.mozilla.org/2015/05/es6-in-depth-template-strings-2/
I believe an updated Date API is in progress.

**Comment by devlato** [comment]
@IgnoredAmbience yes, but I guess I cannot use a template string as a template? I mean, is it possible to store the template in a variable and interpolate on demand? I.e.:

```
const template = 'Hello, Mr ${lastName}';
// ...
// And somewhere there we use template variable from above to format the result.
```

I'm asking because all the languages typically have this feature and because this approach is serializable.

**Comment by domenic** [comment]
Closing per https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#feature-requests

**Comment by littledan** [comment]
ECMA 402 is a good place to discuss this further as well; see https://github.com/tc39/ecma402/issues/21 . Generally, for now, you can use moment.js for this sort of thing.

**Comment by jungshik** [comment]
Ecma 402 certainly is. There's a better bug for this than tc39/ecma402#21. I can't find it now, but will add a reference to that later.
