### ISSUE TITLE
HTML comment-like productions in module code

### ISSUE THREAD

**Issue by isiahmeadows** [tc39/ecma262#949]
**Edit:** Add link.

Is my [read of the spec](https://tc39.github.io/ecma262/#sec-html-like-comments) correct in that in module code, these two are functionally equivalent?

```js
// 1.
a <!-- b

// 2.
a < !(--b)
```

**Comment by michaelficarra** [comment]
Yep.

**Comment by isiahmeadows** [comment]
Thanks!

**Comment by isiahmeadows** [comment]
Basically means a lot of parsers are wrong, including Acorn, Babylon, and Esprima.

**Comment by michaelficarra** [comment]
Notably not mine https://github.com/shapesecurity/shift-parser-js :grin:
