### ISSUE TITLE
add a favicon

### ISSUE THREAD

**Issue by michaelficarra** [tc39/ecma262#95]
Now that the spec is distributed as a web page, it should have a favicon.

**Comment by michaelficarra** [comment]
How about this? ![ecma262-favicon](https://cloud.githubusercontent.com/assets/218840/10600142/2bccf39e-76bd-11e5-9822-5b9ce227af47.png)

**Comment by domenic** [comment]
What is that? A gas station?

**Comment by michaelficarra** [comment]
A mini version of the ECMA-262 title page:

<img width="594" alt="ecma-262 title page" src="https://cloud.githubusercontent.com/assets/218840/10600280/57f3eba2-76be-11e5-9619-38f364eb91f0.png">

**Comment by domenic** [comment]
But that title page is not part of the spec anymore. Seems bad.

Just the usual ES logo makes sense to me.

**Comment by michaelficarra** [comment]
You mean like this? ![262](https://cloud.githubusercontent.com/assets/218840/10600688/4f675a84-76c1-11e5-8c2d-223db1957aea.png) Boring.

**Comment by thejameskyle** [comment]
@michaelficarra Do you like this one any better? ![](https://avatars2.githubusercontent.com/u/218840?v=3&s=20)

**Comment by allenwb** [comment]
Ecma owns the graphic design of Ecma publications and they already provide a favicon.  You see it if you browser the official Ecma HTML distribution: http://ecma-international.org/ecma-262/6.0/ 

That favcon is available at https://github.com/tc39/ecma262-6-src/blob/master/es-spec-html/favicon.ico

**Comment by michaelficarra** [comment]
Copying ES6 (ECMA) favicon here for posterity/convenience: <img width=16 alt="ecma" src="https://cloud.githubusercontent.com/assets/218840/10612067/175c6650-7704-11e5-9da8-6392305678dd.png" />

**Comment by bterlson** [comment]
ahahahaha it is taking ALL my willpower not to install the favicon proposed by @thejameskyle. Will hopefully copy the one from es-spec-html, though.

**Comment by bterlson** [comment]
Added the favicon to the gh-pages branch.

**Comment by michaelficarra** [comment]
@bterlson Just adding the file to `gh-pages` isn't sufficient, as those files aren't served from the root. You'll have to add a `<link>` to the `<head>` that points to it. I'll submit a PR.

**Comment by allenwb** [comment]
Well, since it is just a draft and not the actual standard you could use a different favicon.  That might even be preferable if it helps people  distinguish drafts from the standard.
