### ISSUE TITLE
Contradiction concerning Execution Contexts?

### ISSUE THREAD

**Issue by tmerr** [tc39/ecma262#980]
Section `8.3 Execution Contexts` claims:

> The LexicalEnvironment and VariableEnvironment components of an execution context are always Lexical Environments. When an execution context is created its LexicalEnvironment and VariableEnvironment components initially have the same value.

Is this always the case?
```
18.2.1.1 Runtime Semantics: PerformEval
...

11. Let ctx be the running execution context.
12. NOTE: If direct is true, ctx will be the execution context that performed the direct eval. If direct is false, ctx will be the execution context for the invocation of the eval function.
13. If direct is true, then
    a. Let lexEnv be NewDeclarativeEnvironment(ctx's LexicalEnvironment).
    b. Let varEnv be ctx's VariableEnvironment.
14. Else,
    a. Let lexEnv be NewDeclarativeEnvironment(evalRealm.[[GlobalEnv]]).
    b. Let varEnv be evalRealm.[[GlobalEnv]].
15. If strictEval is true, set varEnv to lexEnv.
...
17. Let evalCxt be a new ECMAScript code execution context.
...
21. Set the evalCxt's VariableEnvironment to varEnv.
22. Set the evalCxt's LexicalEnvironment to lexEnv.
23. Push evalCxt on to the execution context stack; evalCxt is now the running execution context.
...
```

With the program `var x = 3; eval("let y = 4");`, `direct` would be true, and `strict` would be false. So upon entering the eval we would create an Execution Context with an empty LexicalEnvironmnent (aside from its `outer`), and reuse the old VariableEnvironment. Doesn't this contradict the claim that "When an execution context is created its LexicalEnvironment and VariableEnvironment components initially have the same value"?

**Comment by bterlson** [comment]
Yeah I think that statement is misleading. I'll probably just remove it.

**Comment by tmerr** [comment]
As far as I can tell [the statement was accurate back in 5.1]( https://www.ecma-international.org/ecma-262/5.1/#sec-10.4.2) then broke in 6.0. Kill it with fire 👍

**Comment by bterlson** [comment]
@tmerr want to send a PR?
