### ISSUE TITLE
`await` as a default parameter's name/value within a normal function nested inside an async function - what's the behavior?

### ISSUE THREAD

**Issue by isiahmeadows** [tc39/ecma262#987]
Two separate examples, and I can't tell if it's a spec bug or V8 bug...

```js
// Note: this should be considered a script
"use strict"
async function foo() {
  function bar({await}) { return await }
  return bar({await: 1})
}
```

My intuition is that this is valid, and `foo()` should return a same-tick promise to `1`.

```js
"use strict"
var await = 1
async function foo() {
  function bar({baz = await}) { return baz }
  return bar({})
}
```

My intuition is that this (and the sloppy mode equivalent) should have one of two behaviors:

1. It should be an early error, since `await` is used outside the function, inside the scope of `foo()`.
2. It should be valid, and `foo()` should return a same-tick promise to `1`.

-----

Note that I expect sloppy mode to be similar in both cases.

**Comment by isiahmeadows** [comment]
Note that I expect sloppy mode to be similar in this case.

**Comment by isiahmeadows** [comment]
From testing in V8, I did find that both cases returned a same-tick promise to `1`.

**Comment by littledan** [comment]
V8 follows the JavaScript spec here and treats `await` as a simple identifier. See [the definition of FunctionDeclaration](https://tc39.github.io/ecma262/#prod-FunctionDeclaration), which parses parameters with the `~Await` flag. As a property key, object literals generally allow any sort of keyword before the colon.

**Comment by isiahmeadows** [comment]
Okay, thanks! I knew there was something subtle I was probably missing.
